#+title: Dasrael
* Identification
** Aliases
** Background
*** Childhood
** Appearance
*** Ethnicity
*** Build
*** Face
** Social Status
*** Class/Allegiances
*** Wealth
*** Clothing
* Character
** Personality
** Goals
** Needs
** Fears
** Ideals
* Abilities
** Heraldry
Dark - Mind. One aspect of their Mind Heraldry is so strong that they get "premonitions" of the future, specifically, human-oriented future, like prophecies, as they are able to synthesize and read other's desires so well, and what they are likely to do, that other's dreams, factored in with the strength of their will, enter their mind. However this ability makes him somewhat schizophrenic and insane, and can actually inhibit him, as he has trouble staying in the present.
** Profession
** Stats
** Skills
* Relationships
** Family
** Romantic
Married to Hatheni
** Friendships
** Enemies
Revictus-- sees him as totalitarian after he killed Rentar and other dissenters who were oppossed to his vision for a One-world government and the Gods working as a government to stop the return of Tregale and make a stronger civilization.
