* Guidelines for this doc format
- For **, this means that this key beat occurs, and then
  everything grouped after it is all the beats/scenes that occur after it until the next beat begins. e.g: ** Midpoint will start with the first crucial beat (the midpoint itself), which are additionally marked with ! as a prefix, and then scenes which follow after. This is why Break into X is in Act X.

* ACT I :apathasaw:metheno:citadel:
** Opening Image 
*** ! Billy doesn't have enough money for Wreathward, but he can make enough in a duel
- [x] Billy complains he doesn't have enough money for the duel and is alcoholic.
- [x] Damin steals gun for Billy for the duel
- [x] Billy joins the duel
*** - Billy wins the duel
- [x] Billy faces off. It's close, but the revolver is potent.
*** - Billy and Damin go to Metheno
- [x] Billy on the boat. It's cheap and uncomfortable. The crew members take advantage of Damin and steal his food, and we see Damin's nihilism and roll-overness here, as well as Billy's anger and determination for justice.
** Goal Stated
*** ! Billy visits his father's grave [goal: taking revenge]
- [x] Billy and Damin arrive in Metheno and reflect on its changes. Billy deals with negative emotions regarding the place, Damin doesn't remember much.
- [x] Billy and Damin visit the grave. Billy reflects in private. Brief flashbacks to the day, we learn why they left. Billy swears revenge.
*** - Billy gets info of Aldwin and Okin's whereabouts [+]
- [0] Billy goes to Aldwin's old house, but someone else lives there.
- [x] Billy goes to the chapel, and learns from the fill-in Ather that Aldwin is now an Impalias at The Citadel, and Okin is the Ather for this town, but is fighting on the Farsunni front.
*** - Billy travels to the Citadel with Damin [+]
- [x] Billy and Damin enter the Citadel
- [0] Billy fakes being a wide-eyed Versalist who wants Aldwin to hear his testimony to get his first Point.
- [0] Billy and Damin find Aldwin in a Cathedral.
** Inciting Incident
*** ! Billy shoots Aldwin, but sees Okin [+]
- [x] Billy shoots Aldwin, but sees Okin
*** - Billy is hunted by Rothars and he escapes the Citadel [-]
- [x] Billy and Damin chase sequence from Rothars.
- [x] Billy and Damin escape the Citadel.
*** - Billy goes back in to try to kill Okin [+] REDACTED
- [0] Damin doesn't want to do it. Damin says that Okin wasn't responsible. Billy convinces Damin as Damin fears being alone.
- [0] Billy gets him and Damin disguised as an armored Rothar and a squire.
- [0] Damin uses his summons to find Okin in the middle of the night.
- [0] Billy and Damin sneak into Okin's quarters, but Gendro catches them.
- [0] Another fight commences between Gendro, the awoken Rothars, and Billy and Damin. Billy and Damin lose and are cornered.
* ACT II :monastery:
** Break into Two
*** ! Allia eliminates the Rothars and rescue Billy and Damin [+]
- [x] Allia fights off the Rothars, and then her Space ally teleports them of them out of the Citadel (into the airship).
*** - Allia takes Billy to the Monastery [-]
- [x] Allia takes Billy and Damin to her airship.
- [x] Billy questions who Allia's party are and what they are doing. Allia and the party are conflicted to
- [x] Billy tries to negotiate to leave, but the party won't let him, and Billy realizes that they are doomed if they don't receive help.
*** - Billy and Damin train in the Monastery [+]
- [ ] Billy and Damin meet the Council. Allia has to justify their rescue, the Council heavily dissaproves of outsiders. Billy respects Allia a bit for defending him. some of the council members even imply killing Damin and Billy, which further raises Billy's suspicion.
- [ ] Billy is staying in the Monastery but is too suspicious to participate. Damin meets people his age.
- [ ] Billy agrees to train so he can better fight off Devinars when he encounters Okin again, and they have no other option.
- [ ] Billy's instincts are good in training but he struggles with being too impulsive and vindictive, especially in team battles, putting himself and others at risk.
- [ ] Billy is looked down upon by his peers for being not born into the Monastery, which fuels his anger and vindictiveness.
- [ ] However Billy learns to trust in his teammates a little bit, but again that makes him lock down, because he knows he needs to cultivate the negative emotions to fuel his power, so he artificially tries to raise it again.
- [ ] Damin really creatively uses modules and Avador is impressed and takes him as a personal tutee.
*** - Avador discovers Damin's nightmares {b-plot goal: find the Dark Weapon}
- [ ] Though his skills are great, Damin still has a seizure during training, and it's hurting him severely. The other trainees look down on him more.
- [ ] Billy learns that the Monastery sees Billy and Damin staying as permanent. He doesn't like this, and starts to plan an escape.
- [ ] Avador witnesses Damin having a nightmare. Damin recognizes Intillia from his nightmare, and Avador interprets this as a prophecy.
*** - Billy tries to escape with Damin [+]
- [ ] Billy informs Damin that the Monastery sees their arrangement as permanent and makes him leave by going to hijack a jellyship.
- [ ] Damin pauses mid-escape, he thinks their life now is better than it was before, and he believes Avador about his dreams being important and that this is what they were leading to.
 - [ ] Damin pauses mid-escape, he thinks their life now is better than it was before, and he believes Avador about his dreams being important and that this is what they were leading to.
- [ ] Billy says "it's me or them", and Damin and him try to board a jellyship.
** First Pinch Point
*** ! Billy and Damin are caught [-] {+}
- [ ] Billy and Damin are caught by Allia. They fight, but are outnumbered and surrender to the Monastery after Damin is disconnected from the jellyship. Allia convinces her friends not to tell the council, but they the rumor spreads
- [ ] Upon this development and the unsuccessful hunt for Intillia's killer, the Monastery Council makes leaving the Tneranatos prohibited, infuriating the minority factions, especially the Revenants, within the Monastery. Allia is furious at Billy and Damin.
- [ ] Billy is harrassed during a training exercise by his peers for attempting to escape the Monastery. Both him and Damin are teamed up_uring exercises.
- [ ] Billy narrowly escapes and tries to stop the same from happening to Damin, but it's too late. However Damin has a huge Tregale freakout, scaring the bullies away. Billy swears revenge on Damin and his' bully.
*** - Billy meets the Revenants, Damin meets the Sentinels [+] {+}
- [ ] Billy is introduced to the Revenants when Calkesh, a radical Mind Herald, defends him against his bully. Calkesh is very anti-Citadel and seeks Intillia's killer [+]
  - [ ] Billy quickly understands the Revenant's motives and charms them into believing he just has the same problem with the Citadel as they do.
- [ ] Avador and Allia introduce Damin to their faction, the Sentinels, who have the same goals as Intillia had later in life, to reintroduce the Monastery into society as a correct version of the gods. {+}
*** - Billy tricks Revenants into planning a secret mission to track and kill Okin [+]
- [ ] After Damin tells him about the Sentinels and Intillia, Billy sneakily gets information from Allia and Voshri about Intillia.
- [ ] Billy crafts some lies to make Calkesh believe that Okin was Intillia's murderer.
- [ ] Billy refuses Calkesh' request to get Damin to join the Revenants, as Billy thinks its too dangerous for him. Still, Calkesh gives Billy a Dark Crystal that Damin can use to contact him if necessary.
*** - Damin discovers a map to the Forge {+}
- [ ] In the Sentinel hideout, Damin's visions, with Avador's help, lead him to Intillia's secret records where finds Intillia's journal which gives him thne location of the forge in krinosas, as well as Tregale's first journal, which gives him new visions.
- [ ] Billy and Calkesh finalize their plan to infiltrate the Citadel and kill Okin, with the help of many including Calkesh' submissive sister, Voshri, a quiet and kind Elements Herald. Billy is put in charge of the "home team" which includes a Dark Herald and Voshri who will meet up with Calkesh when the mark is found. Calkesh leaves the Monastery. [+]
* ACT III :leviathiStrait:
** Midpoint
*** ! Billy's rebel scheme is found out and he faces execution. [-] {-}
- [ ] Billy is ready to leave, but just before he does, he goes to take revenge on his bully by crippling  [-]
  - [ ] Billy successfully cripples the bully, but is caught by the bullies' friends. Billy is knocked out in the fight and arrested.
- [ ] Voshri finds that Billy has been arrested, and tells Damin and Allia. [+]
  - [ ] They figure out how they will break out Billy.
*** - The Party escapes the Monastery. [+] {+}
- [ ] Allia, Voshri and Damin surprise attack Billy's hearing and free Billy. [+]
- [ ] A grand escape sequence with the party fighting off other Heralds. Avador comes to the party's aid.
*** - Calkesh has found Okin, the Party squabbles [+] {+}
- [ ] Billy convinces Damin to connect him with Calkesh, who has found Okin. Damin is a bit mad that Billy is hiding the Revenants from him. [+]
  - [ ] Calkesh wants to kill Okin himself, but Billy wants the kill for himself. Billy convinces Calkesh that Okin is a dangerous Herald and Calkesh will need backup. [-]
- [ ] Billy is desperate and tries to convince Voshri to vote with him to change the ship's course, who is unsure about leaving the ship now that they are wanted by the Monastery. {-}
  - [ ] Allia overhears and Voshri tells Allia what their plan was, unknowingly ousting Billy's lie. Billy tries to lie again but Damin has had enough and tells Billy to give it up. Allia is furious at Billy and Damin. [-] {-}
- [ ] Now Voshri is worried about Calkesh, and tries to get Damin and Billy to let her tell Calkesh that Okin isn't Intillia's killer, but Billy won't give her the Crystal. Allia, Voshri, and Billy fight over what to do.  Allia tries to subdue Billy, and the three fight, disrupting the ship. [-] {-}
** Second Pinch Point
*** ! Nexon's Pirates capture the Party [-] {-}
- [ ] The Party fighting makes the Ship nearly fall out of the sky and come within Nexon's view. Nexon shoots it down, and they are captured. 
*** - Billy befriends Nexon, The Party plan their escape [+] {+}
- [ ] Nexon befriends Billy, and returns him the Dark Crystal [+]
  - [ ] A pirate insults Billy, and he let's it slide off his back
- [ ] Nexon tells Billy that he is hunting the Leviathi. He tells the group his plan that the ship fleet will use airship balloons that will dock from the land ships to release decoys  filled with anti-Heraldry crystals for the Leviathi to eat, and then when it eats enough of them Nexon will kill it. Nexon says they shot down the airship to get another jellyfish.
  - [ ] Billy is subconsciously ashamed that he lied to Voshri.
  - [ ] Damin refuses to contact Calkesh for Billy. [-]
  - [ ] Allia and the other three plan to escape, and get the Crystal back from Billy. Allia's plan is to teleport to a ship in the back of the fleet, take control of it, and get close enough to the coast to portal, when Nexon is distracted and fighting the Leviathi.  [-] {+}
- [ ] Billy convinces Nexon to help him go kill Okin if Billy comes with him to hunt the Leviathi and celebrate afterward. [+]
- [ ] Allia and the other three advance their plan to escape. {+} [-]
*** - Billy ruins their escape plan [+] {-}
- [ ] Damin wants to go with Allia, and Billy and Damin argue. Billy thinks Damin will go if he doesn't do something drastic, and will die in Krinosas, and then he won't get his revenge.
- [ ] Damin betrays Billy and steals the Dark Crystal when Billy is sleeping so Voshri can tell Calkesh that Billy lied. {+} [-]
- [ ] In fear of losing his brother to Krinosas, and to get back at them for Damin's betrayal, Billy tells Nexon about their escape plan. Nexon stops their plan and locks up Allia and Voshri. [+]
- [ ] Damin is more distant then ever from Billy, even though Damin is not punished by Nexon.
*** ! The Leviathi destroys the fleet and Billy loses contact with Calkesh [-] {-}
- [ ] The Leviathi appears, and Nexon's plan begins. It goes smoothly at first. [+]
- [ ] Billy finds out that Damin betrayed him and that Allia and Voshri are enacting their plan, with Damin's help, and explodes in indignation, destroying the ship (or maybe just an item he throws into the sea), and alerting the Leviathi. [-]
- [ ] The Leviathi is disturbed and attacks. Billy is knocked unconscious. He loses his Dark Crystal, and with it, his connection to Calkesh.  [-] {-}
** All is Lost
*** - Billy and Damin crash on Krinosas [-] {+}
- Billy wakes up, surprised he is alive. However, Damin is very injured.
  - Billy nurses Damin. He tries to use Light power Forgiveness, but he can't do it because . He just does Indignation again, because he can't do it.
  - Damin's visions grow stronger, which enhances his pain, and he summons his main to track the strong feeling he has, despite Billy's wishes.
- However, Damin is furious at Billy when Billy blames Allia for their situation, and finally snaps when Billy is swearing that he will get his comeuppance on Allia and whining about Nexon falling through.
  - Damin tells Billy how he knows the full extent of Billy's lies to the Revenants, and how Voshri, the other Revenants, and Allia are unfairly punished, but they didn't seek revenge, unlike Billy who lets revenge consume his life.
- Damin's nihilistic attitude is revealed and he says he will let himself die.
*** - Billy brings Damin to the Forge [+] {+}
- [ ] Billy, in tears, confesses he would give up his revenge to save Damin and he regrets bringing them here to the unconscious Damin. [-]
- [ ] Billy swears he will get Damin help, and carries the unconscious Damin through the jungle in the direction the summon guides, but he is dying. {+}[+]
* ACT IV :krinosas:forge:
** Break into Four
*** ! Billy and Damin find the Forge, Voshri forgives Billy and Allia helps Damin [+] {+}
- [ ] Billy collapses, but his screams of desperation are heard by Allia and Voshri.
- [ ] Voshri forgives Billy, and Billy apologizes and reconciles with them. Allia uses Liquid Heraldry to stop Damin's blood loss and heal him.
*** - Billy bonds with the Dark Children and Architor, Damin asks for the Dark Weapon [+]
- [ ] The Dark Children help to further patch up Damin.
- [ ] Damin ask Architor about the weapon. Architor considers but denies.
*** - Revictus' calls Architor using a Dark Crystal [+]
- [ ] Architor projects Revictus surroundings using Dark Crystal tech and then Billy sees Okin in the background, which makes him want to go in. Arhitor agrees and they go in. [+]
- [ ] Architor and the Children use the weapon to open a portal into Deionis' mind, a Child is given the weapon. The party joins.
- [ ] Billy sees Okin, and tries to kill him, which pulls out more Deionis personalities. [+]
- [ ] The Children and the party have to fight off the Deionis personalities, until the other group of children can get to Okin and Revictus' body, and defend Okin from Billy.
- [ ] The Dark Children start uploading the mass of Crystals into a sleeped Architor-Revictus.
** Final Confrontation
*** ! Architor-Revictus challenges Billy for the weapon [concluded] {concluded}
- [ ] Billy denies Architor-Revictus' offer for the weapon in exchange for Okin's life.
- [ ] Architor-Revictus final battle in the Forge Lava pit. A few Dark Children disable him and join the Party.
** Closing Image
*** ! The Party escapes with Dark Children from the Forge, Billy is excited and determined to help save the world
