* Tregale convinces Damin that things are more complicated then Tregale just purely being a 'bad guy'
* Tregale/Revictus/someone mentions Nietzsche
"There was a man who got very close," Tregale's eyelids launched upwards till his scleras and foreign documnents from the highest intellectual centers in the world, that the man took to reading. As the man grew up, he understood how the religion was formed, what its purpose was. He ruthlessly tore down its contradictions, and from what he knew about foreign nations and their cultures he tore them down too. He was a master at that-- even I would be afraid to face him, in case he tore me down in a sentence. He wrote that man invented the Gods because he knew in his heart even his loved ones would forget his works, that one day his the vases and gardens he injected his soul into would be crushed or wither away, but he needed that work to be acknowledged so desperately that he invented one who would never forget. Quite ironic, that the only one who looks upon his work to this day-- has been made a God of sorts."
"But Revictus invented the Gods too--"
"He wrote of that, too. He had many justifications for the Gods," Tregale smiled. "And he did not just tear down-- he saw their necessity. In fact, he feared that soon enough all would come to the realization that he did, and the Gods would crumble, and there would be catastrophe in the heart of man." 
"So now that the Citadel will be revealed-- do you think what he said will come true?"  (Damin has been told by Tregale that Deionis has taken over the Citadel, and the truth will likely be revealed soon (perhaps by one of the Tregale Five focused on TRUTH))
Tregale's lips pursed. "Perhaps. But I do not think that man, or really, the universe, can or will let himself stay still in that black pit. Waking up from the lie of the Citadel-- it will be painful for men. But really it is analagous to waking up and having--" Tregale looked down and furrowed his eyebrow. "What do you call it now-- oh yes, a hangover."
"And what happened to that man?" Damin said.
"Oh, I assummed he lived out a rather normal life," Tregale shook his head. "I never met him. But do know that even he, with his biting assaults that tried to get one to face reality-- in the end, even he could not."
Damin leaned closer. Tregale smiled like a proud old teacher meeting an adorable pupil after a lesson.
"Even he could not just live his own life and do his own work, knowing it would fade soon after he was gone. He had to convince himself that really the stakes were as high as though everyone would repeat their lives for all eternity, instead dissappearing like a blip," Tregale looked downwards and his fingers moved like the legs of a bug. A layer of water filled his eyes. "Even he, as all finite beings, sought for permanence, and like the rest, he failed."
"But isn't he permanent in a way? He is in your mind even now-- and you have affected history in a way that can never be undone. Not to mention that you and the rest of the gods cannot die by aging."
Tregale chuckled and shook his head. "Even us so-called gods will still be transformed. There is no eternal reccurence, only eternal... evolution."
Damin shakes his head. "How do you know? You have lived long and seen a lot more then me... but how can you say such a thing with certainty?"
Tregale smiled. "If it was any other way-- there would have only been *gas* for all eternity."
