#+title: Okin Monologue
Even if it was a lie, it was what the lie I was given. It was the foundation of everything, that cannot be proven, that can never be proven. It was the context in which I was born into, and thus, who I am as a being. I cannot be without it. I am of it. It is what made my skin, my flesh, my bones, my mind. Even now, as I understand the Citadel was built on lies, I am of the Citadel. The men born today, whether they think it all to be true, whether they suspect it is a lie but repress it, whether they suspect it is a lie and conspire, or whether they downright know it is a lie but do not know why, or whether, like me or even Revictus himself, they know how it is a lie, they are beings of the Citadel. But in uncovering the lie, and the result of that being something made anew, if they make something anew, then they will not be born men of the Citadel, even if they are still called men of the Citadel, they will be beings of another. They are beings-in-Space, and that Space is the Citadel.
