add Okin visit to synodontis

Concerns:
-Considering:
  - Add more beats between Okin and the Mouth of the Gods (main antagonist)
  - Backuh uses more mental influence powers

Additions:
- Okin just temporarily replaces Aldwin

* ACT I
** Opening Image
*** ! Okin will not lie, even to help his men on the Farsunni front.
- [0] Okin's men torture rebel prisoners to find information (rebels are tribals in Wreathward, who have aligned with the Farsunni, raiding Wreathward). The Krusadar is away.
- [X] Previa sees a chance for a glorious raid of the enemy. Okin thinks it's a good idea but wants to wait on the Krusadars' orders. Previa decides to do it anyway.
- [0] Okin follows Previa and gets a backup squad because he is worried for Previa's safety.
- [0] Previa's squad is threatened but Okin is there to save the day.
- [X] They are tried, and Okin tells the truth despite Previa's insistence otherwise which gets them sent back to the Citadel.
** Inciting Incident
*** ! Billy puts Aldwin into a coma, and Okin is his impromptu replacement
- [X] Okin and Previa try to meet Aldwin again in the Citadel
- [X] Okin witnesses the Dark Herald execution led by Aldwin
- [X] Okin sees the assasination and is traumatized, the doctors are unsure whether Aldwin is alive. Previa tries to hide his feelings but later breaks down.
- [X] Okin interrogates the guards about Billy's wherabouts and tells them that he suspects it's Billy.
*** - (Ch 3 + 4) Okin becomes an Impalias
- [X] Okin is named as Aldwin's replacement.
- [ ] Okin leads the hunt for Billy, and commands the guards to search for the escaped Dark Herald.
- [ ] Okin meets the other Impaliases.
- [ ] They debate the war in Farsun and Surkusch. They are debating how much resources to put into ships, so that they can maybe do a naval invasion of Farsun. The landlocked Impaliases think its unfair.
- [ ] Timeskip: Okin has done some Impalias duties, like naming a new Council member.
* ACT II
** Break Into 2
*** ! The Synodontis debate begins
- [ ] Synodontis arrives in the city
- [ ] Okin is introduced to the Synodontis debate. The consensus needs to be unanimous. Right now it is (7/10).
- [ ] Another Impalias tries to subtly buy off Okin to pass the vote, Okin is astonished by this. He brings it to the Mouth of the Gods, who gives Okin an empty promise that he will do something.
- [ ] Okin brings up the other Impaliases' corruption before the Council and the Council pretends to be flabbergasted.
** B-Plot
*** ! Previa investigates Aldwin's assassination
- [ ] Okin tells Previa he is surprised the Synodontis vote is so one-sided. Previa tells Okin he suspects this all ties together in the assasination as an attempt to silence Aldwin for speaking out that Synodontis is the antichrist. Okin tells Previa that is crazy and he thought it was actually Billy. Previa says that's crazy and that Billy is probably dead.
- [ ] Okin is surprised that by the second debate everyone has shifted (except him) to the pro-Synodontis side. (9/10)
- [ ] The guards have found the escaped Dark Herald. Okin, to surpress his feelings over it, personally oversees his execution.
*** Okin goes to the opposition meeting
- [ ] Previa prompts Okin to say that the other Impalias' are corrupt. Okin doesn't have the balls to speak about that and tries to pass the spotlight.
- [ ] Deionis introduces himself to Okin after Okin's failure and gives him a confidence boost and tells him they should pray together.
* ACT III
** Midpoint
*** ! The Mouth is upset Okin is not voting for Synodontis and calls for an election in Whenran
- [ ] Okin confronts the Mouth, the Mouth justifies that this is the way it was supposed to be.
- [ ] Okin does a campaign with Previa and the opposition to vote for him.
*** Okin runs against the other Impalias
- [ ] Soldiers from Farsun are brought to slander Okin.
- [ ] Deionis talks to Okin about rumors that many Impalias elections have been rigged. Okin doesn't believe him.
** Second Pinch Point
*** !  Okin's allies are found and murdered. Okin's life is barely saved by his own accidental activation of Illusion Heraldry.
- [ ] The meeting is attacked.
- [ ] Okin is in denial about himself being an Illusion Herald.
- [ ] Okin is insecure and still in denial about whether he should tell the truth about being an Illusion Herald and gets guidance from Gendro at a Dark Herald execution without getting into details. Gendro stands by his Versalist values.
  - This time, Okin looks away.
- [ ] Having given up, Okin attends the council, and agrees to vote for Synodontis, which moves the vote to the "next stage".
- [ ] Okin finally can't take it and tests his Illusion Heraldry.
- [ ] Okin is about to kill himself, but Backuh presents Okin with someone who has testimonies of Synodontis' non-godliness (who knows him from Marthia.) Okin is somewhat convinced by Backuh's "greater truth" narrative.
- [ ] Okin confronts the most cowardly Impalias directly about why all the other Impaliases are so gung-ho about Synodontis, and also about who attacked the meet. The cowardly Impalias reveals that this was all planned out ahead of time.
** Third Act Turn
*** ! Okin meets Synodontis
- [ ] Since Okin agreed, the Impalias' all travel to see Synodontis. Okin and Deionis discuss that Okin will test Synodontis based on passages in the Onorun.
- [ ] Synodontis is frustrated by Okin's games and
* ACT IV
** Break Into 4
*** ! Okin chooses to ambush Revictus at their second meeting
** Final Confrontation
- Revictus knows Aldwin's been murdered and in desperation meets Okin. Okin meets Revictus, then you hear information in Billy's plot from Architor, then cut back to Okin from high-tension information.
- Deionis frames
- Okin lies in court about Previa's testimony that Okin is a Dark Herald, and that it was Okin that killed Aldwin. Previa is sentenced to death. (B plot close).
** Denouement
- Previa is broken out of prison by Deionis
- Okin acts as a McCarthy-esque demagogue, making false promises to the people to gain power, saying that he has been ordained by Aredal/Olitheon to fight against the modern Citadel.
