add Okin visit to synodontis

Concerns:
-Considering:
  - Add more beats between Okin and the Mouth of the Gods (main antagonist)
  - Backuh uses more mental influence powers

Additions:
- Okin just temporarily replaces Aldwin
- *Okin tells his crew to spy on Vovwaq.*
- "Double mentor decision motif" w/ Henard, Deionis

* ACT I
** Opening Image
*** ! Okin will not lie, even to help his men on the Farsunni front.
- [0] Okin's men torture rebel prisoners to find information (rebels are tribals in Wreathward, who have aligned with the Farsunni, raiding Wreathward). The Krusadar is away.
- [X] Previa sees a chance for a glorious raid of the enemy. Okin thinks it's a good idea but wants to wait on the Krusadars' orders. Previa decides to do it anyway.
- [0] Okin follows Previa and gets a backup squad because he is worried for Previa's safety.
- [0] Previa's squad is threatened but Okin is there to save the day.
- [X] They are tried, and Okin tells the truth despite Previa's insistence otherwise which gets them sent back to the Citadel.
** Inciting Incident
*** ! Billy puts Aldwin into a coma, and Okin is his impromptu replacement
- [X] Okin and Previa try to meet Aldwin again in the Citadel
- [X] Okin witnesses the Dark Herald execution led by Aldwin
- [X] Okin sees the assasination and is traumatized, the doctors are unsure whether Aldwin is alive. Previa tries to hide his feelings but later breaks down.
- [X] Okin interrogates the guards about Billy's wherabouts and tells them that he suspects it's Billy.
*** - (Ch 3 + 4) Okin becomes an Impalias
- [X] Okin is named as Aldwin's replacement.
- [X] Okin leads the hunt for Billy, and commands the guards to search for the escaped Dark Herald.
- [X] Okin meets the other Impaliases.
- [X] They debate the war in Farsun and Surkusch. They are debating how much resources to put into ships, so that they can maybe do a naval invasion of Farsun. The landlocked Impaliases think its unfair.
- [0] Timeskip: Okin has done some Impalias duties, like naming a new Council member.
* ACT II
** Break Into 2
*** ! The Synodontis debate begins
- [X] Synodontis arrives in the city
- [X] Okin is introduced to the Synodontis debate. The consensus needs to be unanimous. Right now it is (6/10).
** B-Plot
*** ! Previa investigates Aldwin's assassination
- [X] Okin tells Previa he is surprised the Synodontis vote has more people voting for Synodontis. Previa tells Okin he suspects this all ties together in the assasination as an attempt to silence Aldwin for speaking out that Synodontis is the antichrist. Okin tells Previa that is crazy and that that conclusion is hasty and he thought it was actually Billy. Previa says that's crazy and that Billy is probably dead.
- [0] Okin and Previa's argument escalates when Okin tells Previa he is always just mad about Aldwin
- [X] Impalias Vovaq tries to subtly buy off Okin to pass the vote, Okin is astonished by this. He brings it to the Mouth of the Gods, who gives Okin an empty promise that he will do something.
- [X] Okin is surprised that by the second debate that Mikeol has shifted to the pro-Synodontis side. (7/10). Okin starts to suspect that some Impalises are corrupt and working together, namely Vovaq and Ricartotten. Henard advises the other Impalises to think about this more carefully.
*** Okin goes on a date with Liejuett
- [ ] Liejuett is a a very popular Othar known for her genius scientific mind, beauty, and advancements in Whenran, who was childhood friends with Okin. She visits him and they go on a date in Metheno to help relieve Okin's stress
*** Okin goes to the opposition meeting and meets Deionis
- [X] Previa prompts Okin to say that the other Impalias' are corrupt. Okin doesn't have the balls to speak about that and tries to pass the spotlight.
- [ ] Deionis introduces himself to Okin after Okin's failure and gives him a confidence boost and tells him they should pray together. Deionis and Okin agree that Previa is too unstable and impulsive to be a leader of True Light and they need to work together tbehind the scenes.
- [ ] The guards have found the escaped Dark Herald. Okin, to surpress his feelings over it, personally oversees his execution.
*** Okin tells Henard about his concerns
- [ ] Okin asks Henard to join him after the meeting
- [ ] Okin tells Henard about what Vovwaq did, and in an extreme case he's worried this is part of the 'deciever's prophecy
- [ ] Henard is surprised but says he'll look into it, but says to Okin that there is no way that Vovwaq is part of the deciever's prophecy, and it was probably just normal Vice.
- [ ] Henard tells Okin that even though they see eye to eye it is unwise to join the True Lights, as dogmatism about anything beside the Onorun, and division in the Citadel is unwise
- [ ] Okin tells Henard that especially after the Vovwaq thing he is firm that Syno is wrong, and he won't stand down, and even if the True Lights might be too divisive he is on their side and will support them.
- [ ] Henard tells Okin that from his Olitheon mentor he learned that Truth and Curiosity go together, and that being that stubborn he might not be open to the Truth. Okin questions himself more.
** First Pinch Point
*** Okin avoids lying and Mikeol is attacked and killed by a Follower of the Return
- [ ] When leaving the building, Okin and Mikeol are attacked by Followers of the Return who believe that the Citadel has been taken over by the Decievers. The attacker asks Okin if Mikeol is a supporter of Syno. Despite Mikeol's wishes, Okin tells the Truth, and the attacker kills Mikeol.
- [ ] The guards come in. Okin helps to kill the atttacker.
- [ ] Ovolo blames Okin for Mikeol's death. A lot of the Impaliases distrust Okin now, but some support his supreme dedication to the Virtues
- [ ] Okin uses it to convince his replacement and Mathelin, bringing it to (6/10)
* ACT III
** Midpoint
*** ! The Mouth is upset Okin is pushing the vote for Synodontis in the opposite direction and calls for an election in Whenran
- [ ] In reality, the Mouth was told by Henard, but Okin thinks it's Vovwaq, who mocks him.
- [ ] Okin confronts the Mouth, the Mouth justifies that this is the way it was supposed to be as Aldwin is not reported to be recovering.
- [ ] Okin looks to the other Impaliases, but they say it is the Mouth's decision as leader of the Impaliases. Henard admits it is a bit wrong with this crucial issue, but relents.
*** Okin starts his campaign
- [ ] Okin does a campaign with Previa and the True Lights to vote for him.
- [ ] Deionis talks to Okin about rumors that many Impalias elections have been rigged and is afraid this one will be rigged against him. Even thogh Okin suspects Vovaq and Ricartotten, he doesn't believe the corruption goes that deep.
*** Okin's opponent makes some moves
- [ ] Soldiers from Farsun are brought to slander Okin as a coward. Despite being advised not to, Okin tells the truth about his cowardice. His popularity takes a dive.
- [ ] Volmunst says that admitting cowardice is actually brave, and says he believes in him and will tell all his Whenrani Krusadar contacts to drum up support and his own people.
  - [ ] Okin brings up the Vovaq's corruption before the Council and the Council pretends to be flabbergasted. Vovaq tries to gaslight Okin into believing the phrasing wasn't so corrupt. Okin accusses some members of being in cahoots with Vovaq.
- [ ] Okin's opponent receives a huge campaign boost from Vovwaq, promising more cooperation between the two territories. Vovwaq tries to buy off Okin again, promising to switch his support to him, Okin doesn't give him the time of day.
- [ ] One of Okin's staff is accused of being a Dark Herald. Though it's an obvious lie, it catches on, and Okin's popularity tanks more. Amesa recommends cutting the staff, but Okin says its against Compassion and Truth.
*** Okin works hard to convince the others
- [ ] Okin and his entire team have stayed up countless nights and brought a huge annotated copy of the Onorun, with every verse that contradicts Ty-Shou being Aredal, and every verse for it.
- [ ] Henard engages with every verse, and debates a few with Okin. Ricartotten takes the lead to debate with Okin angrily. Vovwaq, Mikeol and Ricartotten begin to drone out, and Ricartotten calls for it to end. The Mouth sustains Ricartotten's request, to Okin's surprise.
- [ ] Volmunst applauds Okin's dedication, comparing it to a 'war of text', but still disagrees. It's still (6/10).
*** Okin fights back
- [ ] Okin spends time visiting local towns. He profusely denies the allegations about his staff.
- [ ] Okin talks to Deionis about the campaign. Deionis says that he has to admit the election is rigged against him, and come out in support of True Light, the only base that will support him. He also points out Vovwaq's corruption and says the Impaliases are not to be trusted, they are the Deceivers. Okin is sure Vovwaq might be sinful but still doesn't believe.
- [ ] Liejuett makes an offer to help Okin's campaign with the Istars. Okin talks about marrying her
*** Okin's support for True Light backfires
- [ ] Okin comes out in support of True Light. Okin says he'll be making deals with Xohl'a to increase Whenran's economy. His popularity rises.
- [ ] There is a large brawl between True Light and the Followers of the Return at one of Okin's rallies. His popularity plummets.
** Second Pinch Point
*** ! Okin breaks up with Liejuett
- [ ] Liejuett says Okin and her should get married and he should drop out of the race. Okin realizes he is lusting after Liejuett, and she is a tempation for him to stop following his mission. and breaks up with her.
- [ ] Liejuett sees this as a betrayal and tells the public that Okin led her on, told her to help his campaign, asked her to marry him and then told her its over, which is all technically true. Okin's approval rating plummets to near 0
*** Okin and Deionis break into the opponent's house
- [ ] Desperate, Okin goes to Deionis for help. Deionis claims that the opponent is housing a Dark Herald. It's a long shot and risky but Okin thinks he needs it to win
- [ ] They break in and find the DH with crystals
- [ ] Small brawl between Okin and opponent.
- [ ] Deionis calls authorities to see DH and Crystals
*** Okin oversees the Dark Herald and opponent's execution
- [ ] Okin interrogates the DH
- [ ] Okin oversees execution but feels guilty (could put this after Okin discovers he's a DH. If so, Deionis should physically stop Okin)
*** Okin tells Deionis he doesn't want to work with True Light anymore
*** Okin wins the election
- [ ] By a thin margin, Okin wins the election against the unknown opponent. (Backuh did some anti-meddling)
*** Okin winning the election convinces Volmunst and Levinor
- [ ] Volmunst says that everything was against Okin, and he knew Okin went through several hurdles and still stood by his Virtues, so he knows the Four are on his side. He changes and it becomes (4/10).
** All is Lost
*** ! Okin winning makes Revictus sends assassins, Okin discovers he's a Dark Herald
- [ ] Deionis warns Okin assassins are coming but Okin doesn't believe him
- [ ] Deionis warns Okin that assassins are coming, but Okin doesn't heed his warning
- [ ] During the attack, everyone is killed. Okin instinctively uses Dark Heraldry to defend himself
- [ ] Okin is in denial about himself being an Illusion Herald.
- [ ] Okin is insecure and still in denial about whether he should tell the truth about being an Illusion Herald and gets guidance from Gendro. Gendro stands by his Versalist values.
*** Okin gives up
- [ ] Okin finally can't take it and tests his Illusion Heraldry. It works and he is suicidal.
- [ ] Having given up, Okin attends the council, and agrees to vote for Synodontis. Everyone else gives up in the same meeting (10/10).
- [ ] Okin is about to kill himself, but Backuh knows something is wrong and has come to meet him. Backuh presents Okin with someone who has testimonies of Synodontis' non-godliness (who knows him from Marthia.) Okin is somewhat convinced by Backuh's "greater truth" narrative, and that there is all this Corruption in the Citadel. (Maybe Backuh references the line /Darkness will destroy itself/)
*** Okin meets Synodontis
- [ ] Since Okin agreed, the Impalias' all travel to see Synodontis. Okin and Deionis discuss that Okin will test Synodontis based on passages in the Onorun.
- [ ] Synodontis is frustrated by Okin's games and shows anger that Aredal wouldn't.
- [ ] Okin asks Syno to display his power. It is not the same as the one shown in the Onorun.
- [ ] Okin is still unsure, until he hears Wosa say something that matches the voice on the other end of his opponent's Dark Herald's line. (could either be played when they were spying-- this would make sense why no one else will believe him)
* ACT IV
** Break Into 4
*** ! Synodontis is declared Aredal -- until Okin interrupts it
- [ ] The rest of the Impaliases speak at the Citadel in affirmation that Synodontis is Aredal, except Okin who yells 'Nay'
*** Henard introduces Okin to Revictus. Okin learns that the religion is a construct
- [ ] After the Nay, the other Impaliases are furious and call Okin a liar. They strip Okin of his Truth. Henard requests Okin to meet with him later.
- [ ] Okin, though a bit suspicious, accepts. Henard takes him to meet Revictus
- [ ] Revictus looks like Olitheon, but explains he's Revictus but needs to fulfill the prophecy of Olitheon because Olitheon is dead.
- [ ] Okin is shocked. Revictus explains that Tregale is real and coming and Synodontis needs to be declared as Aredal, and Okin must agree to undo the nay-nay
- [ ] Revictus offers Okin to be his right hand if he undoes the nay-nay
- [ ] Okin promises he will, but now he is having a full existential crises about his morals and everything he ever believed
*** Okin tells Deionis about Revictus
- [ ] Okin tells Deionis he met Revictus, but Deionis tells him that who he calls Revictus is really the deciever, Deionis himself
- [ ] Okin mets Henard and asks how he can trust Revictus. Henard says that Revictus is the God he knows, and thats how he's been able to control the Citadel for so long and write the Onorun
- [ ] Okin does not trust the Citadel any more. He plans with Deionis to kidnap (kill)? Revictus
** Final Confrontation
*** ! Okin meets with Revictus again, but this time with a plan to ambush him
- [ ]
*** Deionis reveals his identity and traps Okin in the dark dimension
** Denouement
- [ ] Okin is held hostage by Architor-Revictus. Billy spares him, so he reluctantly joins Architor-Revictus
