* Guidelines for this doc format
- For **, this means that this key beat occurs, and then
  everything grouped after it is all the beats/scenes that occur
  after it until the next beat begins. e.g: ** Midpoint will start
  with the first crucial beat (the midpoint itself), which are
  additionally marked with ! as a prefix, and then scenes which
  follow after. This is why Break into X is in Act X. The ! points
  of the last beat of the act are duplicated as the first beat of
  the next act to show continuity.

Ty-shou's main power comes from his genuine love for humanity. Wosa tries to force it but it doesn't work because it is not d genuine love. Aredal's version of the power was to amplify the aspects of a person, but Ty-Shou has a twisted version based on his own ego and self image that makes everyone a reflection of himself and super soldiers.

Ty-Shou's struggle with divinity and leadership. Who's god/prophet should he be and which people should he lead

* PART I :centralMarthia:
** Act I (Opening Image)
*** Chapter 1
**** All the leaders are in Cong Lang for the start of king making, Dragon Lord crosses the mountains
- [X] There is a large formal gathering of high level officals
- [0] Ty-Shou does not see the point in attending, Wosa has to remind him of the importance
- [0] Ty-Shou sees Kitsai and her brother and Anut
- [0] Messenger arrives delivering news of the Dragon Lord crossing into Vang Do
- [0] Coalition head commits to protecting all central Marthians
*** Chapter 2
**** Festival in the streets
- [0] See Anut, Kitsai, and her brother
**** Ty-Shou meets with Maalesh
- [0] Maalesh meets him there, Wosa introduces the two, she flirts with him
- [0] Wosa does much of the talking with Malesh, Ty-Shou is more interested in the army than economics
- [0] Maalesh calls Ty-Shou out direcetly
- [0] Wosa comments that Maalesh is out of line, attributes it to lack of order and civility in Vaareshi
- [0] Wosa leaves to prepare Bei-San ahead of his arrival, reminds Ty-Shou to ensure he is back in Bei-San before King Making begins
*** Chapter 3
**** The brother hosts a formal banquet to welcome the start of king making
- [X] Ty-Shou observes the differing fashion of the multiple nations
- [X] Meets Kitsai, she asks if he is a god like his people say he is
- [0] Taleito introduces himself, he asks how Ty-Shou intends to govern Bei-san
 Inciting Incident
**** ! The banquet is interrupted by the King's death
- [X] Anut arrives late and rushes to the brother, and everyone eventually comes to the conclusion the king is dead
- [X] The two begin to leave the room, when the brother collapses and so do other members of his train and those around the hall
- [X] Ji-Xing wants to leave, Ty-Shou and Kazon push through to try and help the brother. He is unable to heal the poison because he can't feel the emotion
- [X] Ji-Xing has to drag Ty-Shou out
*** Chapter 4
**** Bei-sanian party arrives back at the compound
- [M] fighting down the palace, which will be synced with fighting into the palace to kill anut later
- [] Streets are chaotic as the Bei-Sanian carriage train arrives at their political compound. The of Cong Lang lock down the city.
- [] An Jin-Gu (messenger) delivers news from Anut that the city is in lock down.
- [] Ty-Shou speculates about who attacked, and if Anut is allowed to do that. Ji-Xing tells Ty-Shou that Anut wants them in the city by King making
- [] Qi-An asks if they should leave anyways, reminding them that they must be back in Bei-San before King Making begins
- [] Ty-Shou thinks it is unbefitting of a hero to run from danger, and that he thinks things will clear up soon enough for them to be home safe (make up a distance)
**** Kitsai arrives with a small honour guard
- [] A carriage arrives with Kitsai, she is injured, !!Ty-Shou is able to heal her!!
- [] She informs them of the death of her father, and that Anut has seized support in the city and attempted to kill her. She tells Ty-Shou that he should leave while he is able to
- [] Jin-Gu tries to take control of the conversation, thanking Kitsai for the information and inquires why she came here of all places
- [] Kitsai, looking to Ty-Shou, tells him that she saw him try to save her brother when everyone else ran. She think he is a good person who shouldn't fall victim to Vareeshi infighting
- [] Ty-Shou rebuttals that there are Vareeshi in Bei-San, and that all the people of the world are his charge, but they are on the wrong path soon they will see that he is the true god
- [] Kitsai laughs, confusing Ty-Shou, before saying she must leave as to not draw attention to the Bei-Sanians
- [] Ty-Shou offers his protection to her and orders his men to take what they can and prepare to flee
- [] Kitsai asks if he has a plan, Ty-Shou says that his light will guide them
****  Ty-Shou and Kitsai have a private conversation where she ends with asking permission to call him Ty-Shou
- [] Ty-Shou's soldiers are prepping to move out, packing carriages
- [] Kitsai follows Ty-Shou through the compound to his private section
- [] (Show something about his character here, or history, not sure what to put here for artifacts)
- [] Kitsai marvels over small artifacts in his quarters, pieces which are innocuous to Ty-Shou, but are older than the Delmian Empire
- [] Ty-Shou grabs a light gem infused sword
- [] Kitsai asks if Ty-Shou has a real plan beyond brute forcing his way out of the city
- [] Ty-Shou believes that they can talk their way out of the city, and that everyone will she how blatantly Anut is lying
- [] Ty-Shou thinks that they can easily sort this out and that Kitsai can retake her place in the Cong Lang pyramid. She declares she will be her own Candidate
*** Chapter 5
**** Chaos in the city breaks out
- [] The civilian population begins to riot and attack, Anut has weaponized the people against Kitsai
- [] The Bei-Sanian's have to leave in the night, and sooner than planned
- [] They try carriages and they get stuck in the crowd
- [] Kitsai brings them down into the underground old city, from the era of the Gods
**** The group runs into the Vang Do contigent in the old city
- [] Malesh sees Kitsai and asks what Ty-Shou's plan is once he leaves the city, she realizes he doesn't have one
- [] She bargins for their help escaping the city
- [] The party is ambushed by Anut's men, they nearly kill Ty-Shou who is low on light in the underground city (establish fear of death and obsessive controlling)
- [] Ty-Shou is unable to kill his attackers, Ji-Xing (or is it better if it's Kazon) kills the attacker 
- [] They manage to leave the city, but have to walk on foot to the nearest friendly town
- && Add a lecture here or next chapter from Ji-Xing about him needing to kill, but Ty-Shou is unable to reconcile it with his goals to help and save the people of this world
** Break Into Two
*** Chapter 6
**** The party makes it on foot to a smaller nation between Cong Lang and Bei-San
- [] The party has been traveling for a few days, King Making should start today
- [] Kitsai has picked up some small number of followers
- [] The leader of the nation recognizes Kitsai, but news of Anut's betrayal has not yet reached them
- [] The leader of the nation asks if she is here to demand their subjugation for Cong Lang, she instead demands subjugation to her own pyramid
- [] The leader laughs, but lets them into the city
- [] Tesaak advises against the danger, Kitsai acknowledges it but can't afford to seem weak
- [] They are welcomed into the hold for a meal, why eating the bells for King Making ring and a fight breaks out
* Part II
*** Chapter 7
**** Wosa tells Ty-Shou to turn Kitsai over to the monks
- [] Wosa is outside the walls of Bei-san with troops, and Vareeshi monks when Ty-Shou arrives
- [] Ty-Shou is confused, Wosa tells him that Anut has formally requested Kitsai be investigated by the monks for illegal non-king making murders

- [] Wosa says that it isn't their place to judge right and wrong for the Vareeshi, and that there are procedures in place for this. Believes they shoudl stick to tradition
- [] Kitsai explains that Anut is the one that should be investigated and refuses to be handed over,
- [] Lai-Ren greets them
- [] Kitsai marvels at the wonder of the city, maintaned since the time of the Gods
- [] Lai-ren informs Ty-Shou many of the nobles have yet to heed his call

- [] Wosa says that it isn't their place to judge right and wrong for the Vareeshi, and that there are procedures in place for this. Believes they should stick to tradition
- [] Kitsai explains that Anut is the one that should be investigated and refuses to be handed over
- [] Ty-Shou sides with her, insisting she is innocent until proven guilty and that there should be no problem with her styaing in Bei-san

- [] Ji-Xing subtly accuses Lai-ren of not summoning them
- [] Lai-ren asserts he has always been loyal, even before Ty-Shou's arrival, and that he only ever ruled in the name of Ty-Shou
*** %% Kitsai pleads her case to the Bei-Sanian nobility, Ty-Shou declares war 
- [] The nobles all physically kowtow when Ty-Shou enters. He has to tell them to rise
- [] He tell his nobles that a great injustice has come upon Cong Lang, and that Kitsai requires their help to correct it
- [] Kitsai explains that her brother has been murdered, before she can help nobles interrupt her
- [] Nobles speak condescendingly to Ty-Shou insisting this is too large and complex and issue for him to make such a quick assessment
- [] His rage (indignation) powers flare
- [] Wosa calms the situation and reminds the nobles of Aredal's role in saving them all
- [] Declares, since King Making is starting, that he will take their armies and assist Cong Lang
- [] Kitsai calls him out, saying it isn't so simple, and that he will need to become Vareeshi and create a pyramid if he wishes to participate
*** Ty-Shou visits the Vareeshi quarter of Bei-San and officially declares himself a Candidate
- [] Wosa believes that Kitsai was out of line calling him out, and should have asked permission to speak
- [] The Vareeshi of Bei-San are as reverent of Ty-Shou as Bei-Sanian's. He feels what he believe to be genuine love (but is not) in the way they worship him. (Possible flare up of his special power)
- && Wosa advises strongly against being a candidate. [Does Revictus want this by now or not]
- PUT MORE TO THIS SCENE
- [] Wosa refuses to be his second, reiterating that they should not become so deeply involved
- [] Ji-Xing becomes Ty-Shou's second, suggest Kazon to be high up in the pyramid
- [] Ty-Shou asks Kitsai to join her pyramid to his. She tries to politely and quietly refuse, he forces the issue and she publicly rejects him before leaving the scene
- [] Maalesh asks him why just Cong Lang. Points out that as soon as he declares himself others will come to fight him, regardless of whether he wants to fight them. It is just the Vareeshi way, and Bei-San and Ty-Shou are too great a prize to ignore
*** Ty-Shou's inner circle reviews all the King Making decelerations. Wosa pushes Ty-Shou to argue with Kitsai
*** Ty-Shou summons Kitsai to demand again that she submits.
- [] Ty-Shou summons her to his throne room for a private audience. (Maybe Kazon can be there as named guard)
- [] Ty-Shou demands she address him formally and kowtow as his nobles do. She refuses to kowtow but reverts to using his formal titles
- [] Kitsai asks why he called the meeting. Ty-Shou's says it is because she disrespected him. She asks why he felt so strongly to call this meeting in this place
- [] He says, with a petulant tone, that he is god and she should respect and follow him
- [] She questions directly where this idea comes from, and why her respect has to be total submission
- [] Kitsai offers concession to show she does respect him, but she does not follow him and is his equal and ally
*** Apathasaw shipment arrives, Maalesh leaves, Ty-Shou is informed that Hysho is after him
- && Either a shipment of guns and powder arrives with men that were trained in Apathasaw || the shipment arrives with a select few officers who are sent to train Bei-Sanian soldiers
- [] A Vang Do ship arrives to return the Vang Do contingent to their home land
- [] Maalesh makes no solid promises of allyship or help, despite Ty-Shou's multiple requests. Says he must prove himself to her, Vang Do, and all Vareeshi before anyone will help him
- [] Maalesh could suggest a war target which could give Bei-San supplies as she subtly wants to increase Vang Do trade power in the region and knows Ty-Shou will be amendable to her traders over others
*** && Possible Wosa/Liu chapter here about planning the offensive with skirmishes against Xi-Rin troops
*** && Decide and objective for Bei-San to pursue in Xi-Rin. Kitsai will pick up more followers as they move through towards Xi-Rin. Hysho will come to them
*** Hysho traps Bei-San between them and Hai-Xin, forcing a Bei-San to fight one of the two.
- [] Ty-Shou thinks that Wosa is always right, and was right that they should not have gotten involved in the conflict
- [] Monk outriders arrive to discuss terms with Kitsai and Ty-Shou
- [] Kitsai reassures Ty-Shou that they can win the battle ahead
*** Ji-Xing takes the bulk of the army to harass Xi-Rin and keep them busy. Meanwhile, Ty-Shou and Kitsai's army go to confront Hysho
- [] Ty-Shou fights the leader of Hysho and wins
- [] Kitsai is in a life or death situation and Ty-Shou activates a love power and saves her life killing someone in the process
- [] Ty-Shou's fight ends as the sun sets
- [] Ji-Xing uses gun and a lopsided Herald advantages to win from a numerically lower position. (Kazon should probably contribute)
*** && Two versions of this post battle scene
- [] Anut's scouts are spotted while the monks do sabbath counts
- [] A message from a dark herald monk is a call from Anut
*** The dragon guy arrives with airships and bombs the newly capture Hai-Xin city. Killing Ji-Xing
- [] The fight is as the sunsets going into sabbath
- [] The dragon lord talks about how he was going to attack Cong Lang, but they gave him a bigger target. Ty-Shou
- [] Ji-Xing sacrifices himself to save Ty-Shou. Ty-Shou realizes that he can't save everyone and is putting those who care about him in danger
- [] Ty-Shou declares he is going to march on Cong Lang
** First Pinch Point
* ACT III
*** A shipment 
** Midpoint


** Second Pinch Point
=======
** Break into Two
 
** First Pinch Point
* ACT III
** Midpoint
** Second Pinch Point2

** All is Lost
* ACT IV
** Break into Four
** Final Confrontation
** Closing Image

* Characters
** Bei-San
*** Ty-Shou
Primary light emotions are loved based.
*** Wo-Sa
Ty-Shou's closest friend and advisor
*** Lai-Ren
Old Bei-sanian noble, previous steward of Bei-san. Appears duplicitous. Undecided if he is actually loyal
*** Jin-Gu
Wosa's aid, another dark Herald
*** Ji-Xing
Ty-Shou's chief general and military advisor. Older man, and Herald. 
*** Qi-An (Liu)
Half Delmian, half Bei-sanian child. Selected by Ji-Xing from recent graduates to serve as part of Ty-Shou's security details. Personally works very closely as a guard.
** Vareeshi
*** Kitsai
Challenger to be the largest pyramid holder in Cong Lang. Love interest for Ty-Shou
*** Norlin
*** Jakari
Kitsai's brother and heir to Cong Lang
*** Tesaak
Kitsai's body guard, a friend of her brother, and an Object Herald
*** Anut
Inherets the pyramid after killing Kitsai's brother. He wants to develop Cong Lang's natural resources. He is insecure about his previous position as advisor, in a Stalin-esq way.
*** Ruit
Leader of Khua. A military genius. Flamboyant and patron of the arts.
*** Maalesh
Leader of Cong Lang. Seductress archetype. Wants to slightly destabilize the region to push them towards Vang Do's ideology. Might betray Ty-Shou.
*** Taleit 
Leader of Hysho




