#+title: Billy
* To-Do
- make more moments showing Billy's tenderness towards Damin
  - sacrifices food for Damin
  - plays game
- Billy recounts how he didn't have time to feel anything after killing Aldwin
- for chapter i-v, swap time powers for light ones
* Chapter I
"HRGH!" *Chhnk.*
"HRGH!" *Chhnk.*
"HRGH!" *Chhnk.*
Tough, rough, hands, colonized by puss and calluses, swung a iron head against chipped rock. A flickering lamp intermittedly illuminated the concave rock face.
"HRGH!" *Chhnk.*
Rapid breaths collapsed the space. The hands dropped the pickaxe, and a small echo rung through the cave walls. Its former holder, a disheveled, gaunt man with a hard, sunken face, collapsed one sleeved arm against the rock face. His face was covered dust, scars, and a bitter grimace, but all that somehow seemed like makeup overtop an actually youthful face.
A few more deep inhales calmed his breath to a silent pace. He stared down at the indents where his pickaxe had previously lit sparks.
*CRK!* He HOWLED and his back popped open, his chest and neck nearly hitting the sharp cave wall.
*CRACK!* He screamed again and spun around. Two whip lashes had come from behind, held by a stocky foreman with a wide, round jaw. The foreman stepped forward, and shoulder lifted barely to prepare another swing--
The lamp from the light snuffed. Instead, a red hot rock glowed between the fingers of the miner.
"Raise that whip again and I'll kill ya."
His voice was gravely, his vocal cords so dry and stretched that it sounded as if multiple people were speaking at once, as though the dead were speaking.
"You idiot," the foreman grunted. He lurched forward--
The miner chucked the glowing rock at the tunnelface where the foreman was standing. At the last second he whipped his wrist, as if purposefully redirecting the throw.
The red rock slammed into the rockface, a body's length away from the foreman. The tunnel shook. Rubble exploded from the roof. The foreman's howls crashed through the tunnel.
Grunting in the pitch blackness.
"You-- dirty-- bastard--"
Rocks crunched together. Feet shifted against the gravelly floor.
*HWPP!* The crack of the whip echoed through the air.
*FTSKKkkk*. A flame brought itself to life and expanded from a match in the foreman's fingers. A yellow smile came across his dust-covered face.
"You're gonna wish you had the balls to kill me," the foreman said.
*HWPP!* *HWPP!* *HWPP!*
Scream after scream of agony echoed down the halls of the mineshaft.
:Comment:
add names here, kinda confused who we're following
:END:

The miner limped towards the light at the exit of the mine.
Both his hands clutched his biceps, like he was shivering, giving himself a desperate hug. Raw, red wounds covered his face and arms, and his jaw and the bottom of his eyes hung open like a zombie.
At the entrance of the tunnel, he met another foreman, this one thin and mechanical, at a wooden booth. He turned to the foreman with desperate, hollow, shaky eyes.
"No pay today. Actually what you did will be four weeks off your pay," the foreman said nonchalantly, staring down at papers, not even addressing the miner.
The miner stared there, shivering, like a starving child hoping for a morsel of solace. The foreman finally glanced up at him with a scowl.
"You're lucky, you know? We could've fired you, or put you in jail. He could have beaten you to death and we could've said it was a mining accident. You should thank us."
The miner clenched his jaw. Underneath the tiredness and desperation, was a seed of hatred.
"Say thank you."
The miner kept glaring at the foreman.
"Say it."
The miner turned away, and kept limping on. After he had made it some distance, he heard a shout from the booth.
"Thats another week off your pay! The next five weeks, you come in, no pay!"
He continued to trudge on in the cold, bleak desert, a good mile to a small wooden town illuminated by lampposts.


The door slammed open, and the miner collapsed into the cramped, creaky wooden bedroom. Cramped between the low roof and the top of a bunk bed, a thin teenager, though he barely looked it, plopped up, his long hair flowing over his face like a poofy tree.
:comment:
Add a bit more description of the room, this scene has a white box problem currently
:END:
The miner went right for a bottle of rum atop a drawer. He chugged it. The strong burn of the liquor washed away the pain which pricked at every inch of his body, and he exhaled.
He turned to the teen atop the bunk, who had been staring at him this whole time. Though he was obviously interested in the miner, illuminated by flickering candlelight, his small form dissappeared into the dark wooden walls, and he seemed invisible.
:comment:
the phrasing on this last sentence is clunky
:end:
"No nightmares, right?" the miner asked as he collapsed against the wall, nursing the bottle. It creaked against the weight of his back. The teen shook his head no.
"Good", the disheveled man smiled with soot-filled teeth. In this intimate space, despite the ugliness of all the grime, blood, and fresh wounds on his face, he had a noticeable ruffian charm; the sort that one's heart would yearn to trust even though they know they shouldn't.
"What happened?" the teen asked with a voice like what a kitten would have if one could talk.
"Nothing," the miner said defiantly. He cleared his throat and returned with a smile to the boy. "Work's still good?"
The thin teenager paused. He shrugged. His eyes were still wide with concern at the wounded miner.
The disheveled man nodded. He paced against the squeaking wood, gesticulating, stuck in his own world.
"I finally got a musket to hide underneath that loose plank the against wall with that painting over it," the man said in his usual scratchy rasp. The teen looked up at the man, a pained look on his face. The man clenched his jaw; he knew that the teen knew that it was stolen, and that though the teen used to the man's theivery, was uncomfortable with it.
"It's gonna get busier this time of year," the man continued. "Now there's a way for you to defend yourself safely no matter what you're up against."
"I-I really don't think it's gonna get that much busier," the boy replied. "Mister G hardly has any customers. Just some old guys. And, I don't even know if they're customers... they don't seem to buy anything."
:comment:
Are the customers supposed to be like gods or a mystery for the reader to ask abt?
:END:
The man scratched his chin. "It must get busier in this season. How else does he make his money?"
The teenager shrugged again.
"Maybe he's the one we need to look out for. Damn it. I hate I have to leave you alone here, Damin," the man scrunched his lips. "Is there any way we can get into his private little room?"
:comment:
Private little room sounds like, kinda gay lmao
:END:
Damin's eyes darted around. "Maybe we shouldn't. I mean we've been here a month, and his price is fair. He probably wouldn't like us snooping around. After all we've--" he replied.
"I know, I know," the man said. "It's just-- if he does anything-- anything weird at all--"
"I'll tell you, Billy," Damin said nonchalantly.
Billy sighed. Damin kept staring at Billy with his hands lazily crossed in between his legs.
"I've decided," Billy paced around the room, clinking the bottom of the bottle with his fingers as the teenagers' eyes followed him. "I'm gonna do the duel."
For the first time, Damin sprung awake. "No no no no. Why would you do that? We're finally safe again!"
"I know," Billy said. "But I also know I can win. I finally-- got us a working musket. And it's a lot of money."
"You don't care just about money. If you cared about money, we would've found another circus, or joined a gang. You-- you care about us being safe," Damin said. "About us staying alive! And that's good!" The boy looked up to Billy.
"Money is us staying alive. And more importantly, it's enough for *the trip*," Billy towered over Damin. His hand shook with an unstable passion.
"Billy," Damin sighed, burying his face in his ragged leather shirt. "*That's* a pipe dream. It's in *two weeks.* And we've got nothing."
Billy pointed at Damin. "Exactly! We've been *fucked* every time, and finally something just lands in front of us. It's more than enough money for food, supplies, and two trips for two people. I asked Benjy. And I can *win*."
:comment:
In this section above, add more exposition or movement style action. The dialouge is good but it feels like it needs to be broken up. The pace is weird
:END:
"How do you know that?" Damin shook his head. "And how do you even know Parsmo'll pick you?"
"'Cause I'm a Herald? And the best shot in the city, by far?" Billy raised his hands, like it was a truism.
"Parsmo doesn't know that. Parsmo didn't see you at the circus," Damin retorted.
"Parsmo's shrewd. He's having tryouts just before the duel, and I'll win," Billy said.
"Callaghan's more shrewd," Damin said. "How do you know you're not going up against the best Subject Herald in the state?"
:comment:
I understand Parsmo and Callaghan, but maybe some details here about how Billy heard of the duel. If he's met either of the men before, and who they are is good
:END:2
Billy bit his lip. "Yeah, Subject's good, but they always think like they're against other Subjects or other normals. They just try to draw as quick as possible and win off the bat. No one expects Light."
"And what if you screw up?" Damin challenged Billy with his quiet voice. "What if they draw first, and kill you, like you "
"I-I'll negotiate with Parsmo to pay a doctor if I get injured, whether I lose or win. And guarantee payment--"
"Yeah right. He's the boss, not you. He'll take someone else. And even if he doesn't, so what? I'll have enough money to bury my brother?" Damin's eyes watered.
Billy looked down, crushed. "I'm sorry. You're right." The disheveled man scrunched his fist and slumped against the wall.
The two brothers stared at each other with dead eyes, both their bodies collapsed. For the first time, Damin was over Billy.
"I just want to see him. I promised five... and now it's ten..." Billy's hands shook.
"I know," Damin leaned forward.
"FUCK!" Billy spun around to smash the bottle of whiskey against the floor. Damin jumped back onto the bed and shielded his eyes.
"Sorry", Billy sighed. He crouched up towards the bed. He winced at the short, muffled pantings. "S-sorry Damin."
Damin kept his back towards Billy. With a hint of panic, Billy lifted up the candle and stuck its aura of glow near the trembling boy.
"You're not... *it's* not happening, is it?" Billy's voice trembled.
Damin shook his head, though he stayed turned away from Damin. Billy's shoulders relaxed.
"Get some sleep, I'll clean it up," Billy said as he set down the candle.
Billy pulled the raggedy blanket over the teenager. Damin stayed with the blanket stretched over him awkwardly, his fingers holding the top above his neck.
"I've got no pay for five weeks," Billy said. "No matter what we want, I gotta do that duel and we gotta get outta here."
With a deep sigh, he got on his knees and picked up the shards of glass one by one.

* Chapter II
Light peered in through the window. Damin rubbed his eyes with a yawn. He turned at the glurgle of drinking, and his eyes widened as he saw Billy on the floor, with a new bottle of whiskey in his hand, chugging.
"Billy? Shouldn't you be at work?" A pile of shards lay next to the man.
"I'm not going in this week. They're not paying me, so why should I go in? That's probably another two weeks of pay off, but whatever. Not like there's anything to save for anyway."
"Billy", Damin shook his head and got out of bed. "What if they let you go?"
Billy paused in consideration. "They won't," Billy shoved down the thoughts with a large gulp.
Damin sighed. "Well it's too late now anyway, the state you're in." Damian got out of bed.
"This is... this isn't gonna keep happening, right?" The boy's voice was shaky.
Billy just shrugged, eyes lifeless.
Damin sighed. He moved to leave the room, but stopped in his tracks as his hand met the plank wood door.
"Tell you what, Billy." Damin crouched down and lowered his voice to a whisper. "If you stop drinking. Sober up, and go back to work tomorrow, and for the rest of the week-- I'll try to find a way to snoop around upstairs. See if Mr G has any money, or anything valuable we could sell."
"Shrewd thinking, Damin. But like you said, it's a *pipe dream*", Billy took another chug.
"Just stop, Billy. Put down the bottle, and think with your head-- please."
Billy took a pause. "Well, you said there's little customers, but the guy seems oddly calm. And I don't see him going off to any farm, but he manages to keep us fed. And there's no way he can sustain this just from my rent alone. This guy's definitely got some nest egg somewhere-- and probably something pretty decent."
Damin looked down, his eyes pained, but he nodded. "See. So it's a deal."
Billy glanced at the bottle, then set it down. He threw the cap back on.
Damin gave a tense smile and pushed the door open.
Billy raised an arm. "Wait." He motioned for Damin to close the door again, and Damin turned back to Billy.
"Let me sober up a little. If anything happens, it's you and me against him."
Damin looked down at his feet, then sighed.
"Okay, Billy."
:comment:
Add more of Damin's internal monolouge. This is our first time being in his head, we should use it
:END:


*Knock, knock.*
Damin waited at the worn but sturdy wooden door. He paused for a few seconds. A low, constant whir came from behind. Damin turned his ear in.
He knocked again, louder this time.
The whirring stopped. Then footsteps approached.
Several clicks came from a large bronze contraption entrenched in the door -- an unfamiliar lock mechanism to Damian. The door creaked open and a short sharp strand of white hair, like the tail of a dog, peeked through before it opened up to the beard of a short, elderly man, who smiled, eye-to-eye with the teenage Damin.
"Hello Damin, customer need me?"
"O-oh no, Mister G," Damin gave a fake smile back. "I've worked here a month... and I'm just curious what you-- what you do in there all day? I don't mean to--"
:comment:
If the brothers are supposed to be more transient, thats ok. But I feel like the relationship with Geatro works better if Damin has worked there longer
:END:
Mister G gave a hearty laugh.
"Oh Damin, I'd thought you'd never ask. The last fellow was just content to do nothing all day. But you're a boy! And boys are still curious," Mister G widened the gap between the door just enough that Damin could squeeze through, but when he peered behind he saw the man was surrounded by hanging curtains, blocking the view of the room behind.
"And I'd like to think that I never stopped being a boy, in that way. And... after all this time... ALL this time... I'd like to know maybe I helped another boy to never stop being a boy... in that way."
Damin scrunched back a bit.
"But-- if there's too many boys like us... things get a little bit mad. So, you have to promise that you won't whisper to any of your friends?"
"I--", Damian looked down. "I don't really have any friends."
"Oh," Mister G's playful smile dissappeared into a tight-lipped frown. "Well then, I guess that solves that."
His smile returned. "Well come on, then!"
Mister G ushered Damin inside. With a heave he shut the door, Damin could see that it was extremely thick, and only the outer panels were made of wood, the inside being made of some hardy steel and bronze. Mister G pulled a lever, and inside the door the same clicking commenced, locking it.
"I've never seen a lock like that--" Damian started.
Mister G laughed, then simply raised the curtain, Damin ducked under to sound of *clicking* and *whirring*--
Damin's jaw dropped.
Every square inch of the room-- even the ceiling-- was covered by something that belonged in a museum-- something totally foreign to Damin's eyes. He quickly scanned, locked in on something, then scanned again.
"W-wow... I--"
A long bench lined each wall, filled with little contraptions, loose mechanical parts, jars containing strange plants floating in water. At the end of one was a large glass tank, filled with several illustrous fish and exotic sea life. The strange plants popped with both color and motion that threw Damian back; it was alien. He took a step forward--
"Oh, sorry my boy," Mister G said. "Would you mind taking off your shoes?"
Damin looked down at his feet-- the floor was one giant papyrus, covered with strange drawings, blueprints, and calculations. He paused for a few seconds-- but it was entirely symbolic, another language to him, though some shapes looked intuitive. He slipped off his sandals, and then glanced around the room-- there were blueprints, and large landscape paintings, lining every single wall, some even stacked ontop of each other, which he did not notice till now.
"Mister G... you're a-- you're a... genius!" Damian shouted.
Mister G chuckled. "Oh no, oh no. I just have a lot of time on my hands, that's all."
Damian looked at the man, who gave a wrinkly smile. Damin shook his head.
"Well most old men... just get drunk or sit on their porches all day," Damin said. "No offense, Mister--"
"Well of course I do that too, boy!"
"Well then you're definitely a genius. But-- with all these inventions--" Damin strut around. He peered down at an ever-so complex looking device with lots of pedals that connected to levers, which was covered with paper at the top. "Why do you only sell nails, and-- no offense, plain ol' tools?"
Mister G chuckled. "Oh... this is all just a madman's playhouse. Those tools you sell-- they're good for people, useful." His voice trailed off a bit.
"Yeah and these are--," Damin scrunched his eyes as he moved onto a strange box with weird symbols on it and more gears within then he could count.
"If I sold it to people, I'd lose money with the amount of print that would have to go along to tell them how to use it," Mister G said. "And... on the off chance people did find an interest... well I'm not prepared to handle Herald thiefs trying to get in here."
Damian clenched his throat.
"That light confuses the Light Heralds though, in case any of them try to get a peek in here, and tell their friends." Mister G said. "Makes it look like one big empty room."
:comment:
How does this light the work, or describe it more
:END:
Damin squirmed as he kept looking around at all the items. Even if there was a safe in here, he'd have more trouble figuring out what it looked like.
Damin turned to Mister G.
"Okay, but surely, even if it's just one thing, you should be able to sell something better than we sell right now!" Damin said.
"I'm not a salesman, Damin. That's why I have good lads like you work the shop," Mister G smiled.
"These new items will sell themselves. Here, this one. Even I can tell-- it heats up things." Damin zoned in on a small steel-box looking device which had some black liquid inside that was steaming. "And it looks pretty simple to use to. Even if you don't want to sell it-- one of those industry guys would pay-- us-- real good."
Mister G shook his head. "It's my contraptions. And I say no. Now please, if you're only interested in selling it, I rather you leave and forget about this."
Damin clenched his lips. "No, it's your stuff. I'm sorry."
"It's okay, lad," Mister G. "It's heartwarming to see someone so eager. Take a look around!"
Damin's eyes glanced around. His eyebrows raised when he met a strange silver-coated small gun at the end of the table. He approached it.
It was like no gun he'd ever seen before, not anything like Billy's guns, even the dueling pistols he used in the circus. For one-- it was much more elegant but without trying as hard. And it was smaller, even then the dueling pistols. Damin was almost unsure of whether it was a gun it was so small, but it had to be-- it had an obvious handle, and a barrel, and a trigger.
:comment:
This is a good place to exposit about the current state of guns in the world
:END:
"What's this?" Damin asked.
"Oh," Mister G smiled and picked up the gun. Then, he took his hand and spun a small cylinder in the centre of the gun, much to Damian's surprise. He mimed out a couple shots, and then smiled.
"It does shoot. Unfortunately, you're going to have to take my word for it, as I don't really want to break anything in here, or get noise complaints," Mister G chuckled.
"But what could it shoot that's so small?" Damin asked. "And uh, how do you load it?"
Mister G smiled, and popped open the cylinder in the center, much to Damin's surprise. He flipped over the gun so Damin could see there were 6 small holes in the cylinder.
Damin raised an eyebrow. "Where do you get ammo that small?"
"I make it of course," Mister G walked over and patted a large, complex rectangular machine next to the wall, and patted it. "Only got about a hundred," he grabbed some bullets out of a large black cloth bag on the table and showed Damin.
"Here try! Just don't shoot!" Mister G handed Damin six bullets and then the gun in one hand.
Damin took the bullets and gun with a shaky hand. He gripped it, then nodded as he got a feel for the craftsmanship.
"So uh... being so small... does it shoot as good as a regular musket?" Damin asked as he popped open the cylinder.
"Oh no, it's much more powerful. And such small, nicely shaped bullets--"
"Fire much faster than a musket ball." Damian and Mister G said in unison.
Mister G laughed. "You got it, lad!"
"And uh... what are you calling it?" Damin asked as he slid in each bullet one by one.
"Oh. To be honest, I don't really come up with names. Well-- it shoots six... I guess it's the six shot!" Mister G's eyes lit up like a little boy.
Damin nodded slowly. He aimed it at the corner of the room.
"Hm. Six-shot."
"Yes," Mister G nodded. "I think the muskets are rather... slow, and wasteful. And who can lug around that big thing all the time?" His face shifted from thoughtful to a lax smile. "But I was never much one for war, anyhow. This is just my little toy."
Damin nodded. A few seconds of awkward silence passed.
"And do you... do you sleep in here?" Damin asked.
"Oh no. If I sleep in here... well I can't," Mister G laughed. "Too much... thinking going on here to get a good night's rest. My room's upstairs." Mister G pointed to the staircase at the far end.
Damin nodded.
"Well then," Mister G scratched his scraggly forehead. "You should probably go back to manning the shop, in case someone comes in. But uh, feel free to come up any time it's not business hours," Mister G smiled.
Damin nodded, then gave a weak smile back.


Damin peered through the door and slowly pushed it open. He winced at the creek.
Billy was still on the floor, passed out, but his eyes fluttered open as Damin entered the room.
"So, you find anything?"
Damin turned to shut the door.
"Uhm... so much stuff."
Billy's eyes widened. "So he's got something we can steal?
"Well, yes... but, not exactly... I mean...,"
"Spit it out!" Billy got up.
"Well..." Damin lowered to a whisper. "He's an... he's an inventor of some sort. He's got all sorts of stuff... but whether its valuable, or not, I don't know..."
"Well, did you see any shiny shit? Or a safe?" Billy asked.
"Not really, but uh, he's got some inventions... and a couple paintings..."
"Paintings," Billy pointed. "That can be good."
"But uh, I think he painted them himself. There's no way they're antiques," Damin said.
:comment:
Is it ironic that they might actually be antiques
:END:
"So what? There's nothing worth stealing?" Billy's voice raised.
"I-- I don't know. There's just so much stuff, and it's all really weird. Maybe we could steal one of his blueprints and sell it to an industrialist."
Billy shook his head. "We're wanted, Damin. We can't do any legal business like that. And that's not gonna make us money *right now.*"
Damin stared down at the floor, thinking. Billy pushed past him.
"You know what? Fuck it. He's an old man, we can over power him. Sort through all his stuff, take over this operation if nothing else. It's worth at least the money we need," Billy said.
"Billy, stop!" Damin grabbed Billy's shoulder. "Come on. You're right, he's old. This is all he has, and he was kind enough to show me his stuff."
Billy looked Damin in the eye, and scowled.
"Don't do this," the teenager said.
Billy sighed and rolled his eyes. "Ugh, fine." He crouched down and reached under the bed, and grabbed a long bottle of rum.
"Well, guess I might as well relax then," Billy said as he popped open the bottle.
Damin looked down, defeated.


Damin laid awake in bed, eyes open.
He stared up at the pitch blackness above him, which he knew to be Billy' bunk. From it, loud, violent, but repetitive snores.
Damin's fingers tensed up around his blankets. He bit his lip, then exhaled deeply.
He pushed off the blanket, then rolled out of bed.
Damin took a deep breath. He took off his shirt and pulled it tight before tying it around his own mouth as a gag. Then he took another deep breathe through his nose.
:comment:
Explain why hes doing this. Cause I'm even confused by why
:END:
He outstretched his hands together in front of him, then extended one out from the other. As his hand moved, from the still one grew a dark yet glowing luminesensce, visible even in the pith black darkness. It was otherworldly-- one could immeadiately tell it was like a hallucination; it was as if smoke had an alien, captivating cousin.
:style:
Not sure about the description here
:END:
He formed his hand up, and the gas-like substance grew with it, expanding. He jerked his moving hand back-and-forth, and two identical thin arms sprouted out from the thin smoky triangle.
Finally, he moved both hands up to the top of the triangle, where there was no substance yet, and then spun them around, as if he was grasping the surface of an invisible ball. And with that, the smoke grew a large head, with a long tail at the top of it exhausting like steam into the darkness.
And it had eyes. Large, crescent, violet, eyes that stayed in place, yet like the rest of it, moved like smoke. And it's mouth curled into a similar crescent form, before dissapearing into the same substance as the rest of its body.
Damin gave a small smile at his Creation.
*You know what I need, Xanas. Lead me. Open the door.*
Xanas and its curved, pupiless eyes formed upwards with its similarly crescent mouth in a smile.
Xanas slithered under the door, its body like gas. Then from behind, it gradually pushed open to let Damin through.
Damin winced as it squeked. He looked back-- Billy was still snoring.
Damin slid through the door, peeking out first for Xanas. Its purple eyes shined at the top of the stairs in the utter blackness.
:comment:
Establish the geography of the house a bit more. A few more lines of description in chapter one when Billy comes to the house could fix this
:END:
Damin took each step with apprehension. He felt like the house would crash down at every step.
*Chhk-chhk-chhk-chhk*--
Damin's heart stopped. He knew it was the sound of Mister G's door unlocking, but in the dark, everything seemed louder, and every noise was like a threat. Finally, he unfroze.
*Good, Xanas*, he thought. *Keep it quiet.*
A sudden FLASH OF COLOR AND LIGHT-- the pitch black turned into a crisp bright day on plains. An army SHOUTING--
Damin shouted, but immediately muffled himself using the bedsheet. The vision dissapeared in an instant to black.
:comment:
Not sure I like how the visions work here. They are way too abrupt and random with them not happening. Damin needs internal monolouge here at least to express how it is affecting him
:END:
*It's nothing, Xanas. Keep going.*
The door opened at an uncomfortably slow speed, and Damin now followed only the smoke and eyes. He held his arm in a sneezing position to prepare for the curtain, which rubbed against it.
*You know what I'm after.* Damin pictured the six-shot in his mind, and fed the thought to Xanas. Damin took slow, direct steps towards Xanas, who turned around and reached straight out to Damin with a large smile, like a creepy kid showing his dad his new toys. And those three toys were the six-shot, a large, silk bag-- a bag of ammo, and a beautifully crafted leather holster.
Damin took them from Xanas. *Good work, Xanas,* he thought.

"Wake up, wake up!"
Billy erupted from the bed as his vision faded into a haze of light, and the rest darkness.
"Jeez, Damin! What is it? There's no way it's time for work yet!" Billy air-swatted his brother.
"I did it, Billy. But we have to go," Damin jumped down from Billy's bunk.
"Did WHAT?" Billy shouted.
"Shhh," Damin said. He sighed and held out the six-shot and the bag of ammo. "I got what you wanted."
Billy squinted in confusion. "What do you mean? What the fuck is that?"
"It's a gun. For you. To do the duel," Damin said.
"I have a fucking gun. That's not a fucking gun," Billy shimmied out his bed and jumped down.
"It's *more* than a gun," Damin said, turning the holster to Billy. "It shoots six bullets. The handle's *perfect*-- and it's *small*-- you can draw it faster than any other duelist. And the projectiles--"
:comment:
Damin should think about his plan more before this. The audience should understand his motivation to steal the gun before he tells Billy
:END:
Billy yanked the gun and the bag of ammo out of Damin's hands and bent over next to the candlelight.
His eyebrows furrowed further as he rubbed his hands over the small ammo.
"What the fuck is this? What?" Billy laughed. "Is this a joke, or something? What is this gonna do, shoot sugar for the other guy to eat?"
"He said it fires faster than the modern rifles, on account of its small ammo. I think it's undodgeable," Damin said.
"Pmpph. And how do you know that?" Billy set down the gun. "Did you shoot it?"
"Uhh...," Damin scratched the back of his neck.
"Well, there's one way to find out," Billy picked up the gun and the bag and headed for the door.
"W-wait--"
Billy spun back to Damin. The teenager bounced back in surprise.
"Listen, Damin. Duel's at sunrise, and I got one shot," Billy shook the gun at the teen. "Now either this works, or it doesn't, and I'm dead. So I'm gonna go shoot this thing, and if it works like you say, we got our ticket. And if it doesn't, we're gonna get kicked out of the only place we can afford in town for stealing crazy Mister G's little toy here."
With that, Billy barged out of the room.

Billy marched down the dusty, shrubed-sparsed hill. The hill was gradual, but he approached a giant cliff which led to a massive oval valley, with large ridges like the one he was standing on looping around it.
In the valley, small cacti, rocks and birds populated a dull scene. The air was cool but still, a temperature too comfortable that it was uncomfortable, making one itch for a little shake or a warm sun ray, perhaps due to the utter dryness, which pecked at Billy like invisible salt.
Billy came out of himself and shimmmied open the cloth bag of ammo. The gun's handle was rough, but just enough to grip, but the metal felt smoother than Damin's hairless skin, and lacked the rusted smell of other pistols he'd shot. He hadn't really been paying attention earlier, but now he gently squeezed the gun's grip finger by finger.  He glanced over the body-- it was finished in a perfect polish that gave it reflection off the light while not being too glaring. The shape was defined, and while different, not alien-- it was a true craft.
Billy then raised his eyebrow. He pressed on the cylinder, which *clicked* out at rapid speed.
"Hm," Billy opened the bag of ammo, and back at the holes in the cylinder. He scratched his chin, and then popped in bullets one by one. He raised it up to his eye level and squinted, then smiled. He had to admit, if it worked, it was an ingeniously inventive machine.

*Chrrchh Chrrchh.* Billy spun around to the sound of rocks crunching, fist raised. He relaxed when he caught Damin struggling to get down the hill.
"Here," Damin panted. Billy closed his lips, looking unimpressed at the measly boy.
Damin reached out from behind his back and held out a leather holster. "How are you gonna do a duel without a holster?"
"Oh," Billy's glare turned into a smirk. "Good memory, Damin."
Billy took the holster with a nod and clipped it onto his belt. He scanned the massive valley below, before his back to it. He took a deep breathe.
His fingers wove up and down as he looked back over a nervous Damin, to the town over the hill.
He shut his eyes. He stilled himself. His right hand moved to his side, his fingers still waving.
The world around Billy stilled. A tumbleweed bounced down the hill from the town. Damin stared at the wounded man.
Billy whipped out the gun. He spun around to face the dry valley in one rapid motion.
Crows picked at the dirt some hundred paces below. Billy leveled the sights at them.
BAM.
The gun recoiled. /SQUAWK SQUAWK/. The other birds flew off in random directions.
Thirty or so paces down the valley, bird brain was spilled out over rocks.
:style:
bird brains might be too graphic
:END:
Billy looked at the gun in surprise. Then he quickly glanced up to see a bird flying about forty paces out and above.
He raised the gun at the bird.
Billy fired, but pulled his hands to the right as he did so.
The bullet shot right past the bird. It flew upwards and redirected itself after the boom of the gun's fire shook through the valley. He shot again. And again. And again. Every shot missed, but then he clapped his leg and laughed.
:comment:
confused what redirected itself, the bullet?
:END:
"Woah!" Damian laughed and ran towards Billy.
"Well that's ah... that shot's hard to make," Billy chuckled.
"But you came close, from the looks of it!" Damin said. "C'mon, you made that first shot, the thing looks pretty good!"
"It's not pretty good. It's fucking great!" Billy raised himself to face Damin. "You're right. I don't even know if this is dodgeable," Billy chuckled. "Dang, maybe Mister G's not so crazy after all."
Billy snapped himself to attention, and swept up the ammo bag.
"But we gotta go," he said.

"Too late mista," the plump, bald man said as he walked alongside Billy. "I chose ma man."
They were in a crowd of about a dozen or so, lined up on a long, dusty road, that was surrounded by large wood buildings, but not cramped.
Billy speed-walked next to the man like a poor opportunist asking for a job. "C'mon. I've got a great shot! And I got my own gun! And it's better than yours!" Billy shouted.
Parsmo paused to look Billy up and down, and his face curled in disgust. Billy was dressed like the rest of the crowd, in dirtied but plain clothing. "I highly doubt that."
"Alright Jimmy, ya ready?" Parsmo hollered at a stocky man dressed in a matte, clean coat with a black mustache. The man gave a solid nod back. He was armed with two pistols that looked like they were made out of an opulent painting frame.
"You said you would pick the best man! You said you'd see how good everyone shot!" Billy shook his fist.
Parsmo brushed off Billy. "Well, it's ma money on the line, and ma dispute. And from the looks of it, you ain't a Subject, or you woulda lead with that."
:comment:
Explain Subject Heralds here or in the previous chapter when Damin and Billy discuss the duel
:END:
The plump man motioned to the black-moustached shooter to come with him to the center of the crowd.
Billy clenched both fists and kicked up a dust cloud. Some particles flew onto the bystanders in front of him, but most just flew back onto his clothes. He coughed.
The bystanders turned, scowled, and spit at his feet, then turned back around again.
Billy raised his fists again. He strut forward, but stopped as he felt a touch on his arm. His face and arms softened as he looked down at Damin, who looked up with concern. Billy turned back around to the center of the road where Parsmo was face-up to his enemy.
"Well Callyhanny! Where's ya shoota?" Parsmo clutched his belt.
"He's right here," Callaghan, a tall, gray-haired man said. He pointed to a rectangular-faced, older man with a dust-stained formerly white hat with a rusted copper medal on its brim. Though wrinkled, his face sunk into his skull in a way that was both hardened and uncomfortable. The man tipped his hat.
Parsmo's face turned red. "He's a lawman! He--" he sputtered. Billy, holding Damin's arm, moved closer into the crowd.
Callaghan raised his hand. "This is a public duel to settle our dispute. All that entails is that there's two duelists, with weapons, who start at the same time, at an agreed upon place. But the duelist can be anyone, as can the weapons," Callaghan gave a smug smile, and Billy's face scrunched up. He didn't care for Parsmo, but that special kind of arrogance made his body tighten.
"Uhm, sorry Mister Parsmo," the moustached man gave a dumb smile and held out his rifle as if he were a boy sheepishly passing off an antique he broke to his parents. "I can't take this one."
"What?" Parsmo shouted, dismissing the rifle. "I named you, Donnal! C'mon, he don't shoot no better just bein' a lawman!"
Donnal shook his head, and held up the rifle.
"You little coward!" Parsmo's moustached lip curled up and his cheeks popped. He snatched the rifle.
"I guess you lose," Callaghan said with a smirk. Parsmo snapped to face him, seething.
Billy waited for the two men to glare at each other, for the hatred to settle until everyone surrounding felt someone had to break the silence.
"I'll take it," he stepped forward.
"Billy, he's a professional, and he's not just a professional, he's a Subject Herald, and probably the best in this sector!"" Damin whispered. Billy faced Parsmo with a determined stare, like his brother was invisible.
:lore:
Sector is maybe a weird word. It feels too modern imo
:END:
"O-Okay," Parsmo nodded and gave a too toothy, uncomfortable smile. "Yes. We still have a match."
"What's the range?" Billy asked.
"It's a hundred-fifty steps," Callaghan said. "I mean, if no one else--," Parsmo checked his surroundings, "then okay, I guess you're all I got."
Parsmo held out the rifle to Billy. Billy dismissed him.
"All good. I got my own gun," Billy said.
"Billy!" Damin whisper-shouted. "No matter how good Mister G's thing is, it's like a dueling pistol. There's no way it's that accurate up to a hundred-fifty!"
Billy ignored his brother again, his glare unyielding at the lawman.
The rectangular lawman stepped forward, so that both him and Billy were face-to-face in the center of the dusty town road, surrounded by the crowd of around a dozen or so. The man had a long wooden rifle strung over his back.
The lawman looked at Billy with a dead, grizzled stare. He was much older than Billy, his skin like a dried apricot. The previously noisy crowd came to a silence.
Finally, he uttered in a deep voice. "I'm a lawman, and the law's this: you can still quit. Walk away from the money, and if no one else steps up, Parsmo loses this spout. That's all. It's just walking away."
Billy looked down in thought.
"You don't gain anything... but you don't lose anything," the man looked at Billy with concern.
Billy looked down at Damin's pleading eyes. The boy shook his scruffy head no.
Billy's contemplating gaze snapped up into a predatory stare.
"No. I need this," he rasped.
The lawman paused, and looked down like a war had already been fought. But finally he gave an accepting nod. "Alright."

"Eighty-one, eighty-two..." Billy muttered under his breathe. He still struggled to walk after his beating from earlier.
"One-hundred fifty steps each. One-hundred fifty steps!" A portly man in the center shouted.
Billy snapped his head down and kept walking. He fake drew his pistol several times, jerking his elbow in a quick motion as practice.
"Eighty-eight, eighty-nine...," Billy stopped as he caught Damin in the crowd. He was surrounded at all sides by men much larger and rounder than him, covered in brown dress coats which just rested on the outside of their tight-buttoned shirts. Though he was so out of place, he was so small and unnoticeable, like a little sparrow among cows.
Billy met the boy's eyes, which were wide, desperate, and fearful. They stared at each other, and the dryness of the dust and the stakes settled onto Billy's tongue.
"C'mon, move along! One-hundred fifty paces!" The portly man shouted at Billy's back.
Billy turned to see the lawman who stood still, facing him. Primed.
He sighed and turned back to walking. With each step, he felt the dust that was kicked up under his boots.
"Ninety-nine, One-hundred."
He squared perfectly parallel to the lawman. He couldn't avoid glancing down at his own trail of footprints which led to where he currently stood.
"OKAY!" the portly moderator bellowed, now just in front of the crowd, who were a couple horses' length from the footprints between Billy and the lawman.
The air quieted and the moderator shouted so they could both here. "This is a classic duel. One weapon allowed. First man to drop to the ground loses. Running allowed, but only forward! Start with your backs parallel, and if I see ya turn before I've shouted, you lose, and you die! And don't get sneaky-- I'm a Subject too. Any objections?"
The moderator turned for a couple seconds of silence to Billy, and then to the lawman. Nothing.
Billy looked in the crowd for Damin's wide eyes. The short kid stood in between too large, potbellied workers, tiptoeing in the gap between their shoulders to get a view.
"ALRIGHT. TURN AROUND!"
Billy took a deep breath, and turned his back to the lawman and the crowd. He pushed out the cylinder where the bullets were held with the tip of his finger.
"ON MY COUNT OF THREE!" The moderator bellowed. "THREE."
Billy narrowed his eyes. He stared down at the tiny bullets inside the six chambers. His mind focused on the recent past, on the foremen, on their painful whips and the joy they got from their cruelty, and their disgusting, arrogant smiles and voices, and even more recently Parsmo's smug dismissal of him. His skull filled with the pressure of rage. The recent events were always better. He felt the blood flow through his fingers, and then, something much more powerful. /Indignation/. His index finger glowed red hot. He touched the tip of the bullet on the opposite side of the chamber, and the tip glowed with the same red.
"TWO."
Billy flared his nostrils. He smelt the musk of his own sweat on his rolled-up sleeves. He moved his finger to the next chamber.
"ONE."
He slammed the cylinder back into the gun. Billy exhaled and held his breathe. The tips of his fingers curled inches from his six shot.
"FI--"
Billy gritted his teeth. His muscles strained, like instead of pushing back agaisnt air he was submerged in thick mud.
"RE!"
Billy commanded his body to spin around. He crouched down.
He leaped and leaned to the side. A gust of wind shot past him-- the enemy's shot. His dodge was crucial.
The lawman was faster, inhumanely fast as a Subject Herald, but he still had to reload his gun. Billy raised his weapon at the tiny stick in the distance that was the lawman.
Billy searched deep down for that touch of instinct; the push of the subconcious. He lowered the gun ever so slightly.
/"BAM!"/ Billy fired.
/"BRGHHh!"/ A massive plume of sand and dirt geysered in front of the lawman. He fell backwards. The crowd gasped. Billy /sprinted/ at him.
"HE'S NOT DOWN! THE BACK OR BOTH ARMS MUST HIT THE GROUND!" the judge shouted.
"STAY DOWN! OR NEXT TIME I'LL SHOOT TO KILL!" Billy shouted.
Billy's eyes narrowed. The lawman shuffled forward, reaching for his fallen gun--
"BAM!" Billy fired again. This time, the lawman was BLOWN backwards, and a huge ball of sand and wood from the gun's body exploded in the air. The lawman howled.
Billy ran forward, keeping his gun trained on the fallen lawman.
"Urghhhhh," the lawman clutched his woodchip-infested arm in agony.
"Lie down," Billy aimed his weapon at the man's chest. "Or you're guts'll be blown out all over the ground like that gun."
The lawman collapsed back-first onto the dirt.
The previously statue-like crowd livened up; some claps, Callaghan's cursing, and Parsmo's cheers.They moved in to surround Billy and the fallen lawman.
"Ho-ho!" Parsmo shouted. "Five thousand Dunnes, as promised." Billy gave a solemn nod and reached forward to grab the handful of paper money.
He flipped through it as the judge, Parsmo, and Damin all watched him like three children waiting in fear for their strict father's verdict.
Billy grabbed a thinner wad and threw it at the judge, who scurried back in surprise. He motioned with a jerk of the neck back at the fallen lawman.
"Now get him a doctor."
Billy shuffled away as the judge and some bystanders picked at the money and helped the panicking lawman up.
His gaze latched onto two figures in the dispersing crowd: the stout and thin foremen of his mine, who were walking away, having a laugh with each other.
His face hardened, and his fingers wrapped around his holstered six-shot. With this weapon, in an instant, he could kill them both.
He felt a tap on his shoulder, and he turned, releasing his hand from the holster. A wide-eyed Damin greeted  Billy for a big hug. Billy gave a hearty laugh and gave the kid a warm embrace.
Behind the back of the teen, Billy pulled out the six-shot and admired its body, and he ruffled the bills in his other hand.
"With this," he whispered with a smile to the boy. "We finally have all we need to see dad again."
Billy's smile straightened into his usual hard glare.
"And to make things right."
* Chapter III
** notes
We need to establish what the purpose of their trip home is earlier. It is never super clear that
A. Their dad died
B. They want to celebrate the anniversary of their death
C. Why they think they need to/should go back 
** Chapter 
Billy ruffled the few bills in his hand as he leaned against the algae-infested ships' edge. He stared down at the thick black ink, and the oval-framed outline of a landmass, which he knew to be Marshton. He glanced up over the other side of the ship, past the dock to the dusty hills which he knew to be the real Marshton. His mind slipped through the struggles of years past, much like the ship itself: so near now, but sailing away.
"How much do we have left?" Billy was jolted out of his ruminating by Damin's voice.
"I paid for both there and back. So only about two thousand. Enough for food and clothes once we get there, and a bit of emergency money," Billy took off a small pack on his back.
Damin nodded, though his lips were pulled in his usual anxious purse.
"And what are we going to do when we get back? We can't return to Mister G, after stealing--"
"Don't worry about it," Billy shoved the money into his pack. "We'll find something. We always do."
Damin nodded again, but his lips stayed pursed. Billy glanced out back to the Marshton coast as the ship pulled away, before setting his sight on the unending ocean on his side of the ship as he pulled his pack over his shoulder.

Billy down at the grime-stained planks, and then up at the grey overcast. It was still bright enough for Light to fill his body, but he wouldn't be as potent as on a sunny noon in Apathasaw. He stepped back just as a drop of water fell down from the sky.
"Watch yourself," a low growl rumbled just as Billy felt his back elbow rub against a damp, rug-like surface. He turned and glared at a crewman wrapped up in a dark, heavy jacket. The crewman huffed, and Billy turned back to the line of men, a dozen or so deep, in front of a wooden countertop nailed into the ship. At the front of the line, men grabbed plates and were served stew from a tall black, iron pot. Despite his nose having gone blind to save himself from the constant stench of grime, fish, salt, and sweat, saliva still flooded Billy's mouth at even the promise of food. Billy looked down at Damin. When their eyes met, he gave a soft smile, and Damin returned one.
"Attention shipmates and guests!" The light chatter of men already seated in the long benches next to Billy stopped and attention focused on a burly man in an apron stained with a flurry of hearty sauce and spice. "I hate to be the lookout that spots a pirateship, but we've found rats in a portion of the rations," groans overthrew the man's voice and he raised his arms to silence them. "SO-- we're limiting the portions for these first few nights. I've been 'cross the Sethenin many a time, and it's always the latter legs of the trip where folk get the most cranky."
Billy sighed. Damin looked back up at his brother with those same wide eyes, but this time, all they had to exchange was pursed lips.
Billy handed Damin a bowl before grabbing one himself as they got to the front of the line. He raised his bowl to the crewman who lifted a mushy stew that tasted of fish and thick greens. He gave one scoop to Billy and one to Damin. It was about a third of a meal, much less a day's filling.
Billy led Damin to a bench that was empty besides a few men on the opposite end. The two sat down across from each other.
Just as they sat down, Billy leaned over the table and used his spoon to pour his stew into Damin's.
"Y-you don't have to, Billy. You're bigger than I am."
Billy kept shoving his food into Damin's plate.
He waited, arms crossed, over his now empty bowl as Damin pecked at his first bite.
"It's not bad," Damin said, as he took another spoonful.
"Good," Billy smiled. "Stay here. I need to take a leak."
Damin nodded and returned to his meal. Just a few seconds after Billy had left, a hulking man outfitted in overalls with greasy, pink skin, like a plump, overgrown mole rat, plopped down on the bench next to Damin. Shaking, Damin stole a glance at the massive man before returning to take another spoonful.
"Hey, your portion looks awfully large... especially for such a runt," the scarred man said.
"Uh--" Damin's voice froze in his throat.
"Here, why don't ya share a lil?" The man lifted Damin's plate and shoved food into his own. Damin watched with desperate eyes, but stayed seated.
"That's my food."
The massive pink man turned his neck to see Billy standing over the table, in between Damin and himself. "I chose to give it to him," Billy continued. His eyes narrowed, and he felt a familiar tingling as they scanned over each and every little tear in the man's large coat. /Suspiscion./ "Why the fuck are you taking it?"
The pink man glared at Billy, then gave a rotten yellow smile, a few teeth missing. "Well, he chose to give it to me."
The pink man continued scooping-- but Billy grabbed his plate.
"Let go!" the pink man shouted. Billy's glare narrowed, and he kept his hand on the plate. The man's meaty fist came swinging down, but Billy let go just in time. He swiped his arm out of the way, and the man's fist cracked the wooden table.
The man screamed. With a huff he stood up. He swung, but Billy was faster. He kicked the man in the stomach, sending him flying onto the floor.
The massive man turned onto his back, but by the time he had done so Billy was on top of him with a spoon inches from his eye.
:comment:
If Billy is using light powers here, make it more obvious
:END:
"If you even twitch before I tell you, I'll scoop your eye out," Billy said. "Understand?"
The man stared wide-eyed at Billy.
"Understand!?"
The man nodded like a little boy.
"I'm gonna stand up, and after five seconds, you'll stand up. Then I'll hand you back your bowl, and you'll go sit somewhere else. Got it?" Billy asked.
The man nodded repeatedly.
"Good," Billy kept his eyes glued to the man's hands as he stood up. Shaky by shaky leg, the man stood to his feet.
As the man still clutched his stomach, Billy grabbed the man's bowl. Billy took a spoonfull. It tasted of spinach, potatoes, and white fish.
He turned to a frozen Damin. "You're right, it's not bad," he said, before pouring nearly all its contents into Damin's.  Damin's expression remained unchanged, but eventually he cracked a small smile.
Billy turned back to the man, holding out the nearly empty bowl. The man took the bowl with a shaky hand. Billy's glare did not leave his the entire time.
Billy readied a fist-- his heightened hearing from Suspiscion heard the man stop behind him. He was considering a strike back to reclaim his defeated ego.
The man turned, and Billy relaxed after he had continued to take a few steps away.
Damin stared at Billy with tight lips. "You didn't have--"
"I did," Billy cut him off.
"People who think they have power always think they can take from people like us. And they almost always get away with it. When we have a chance to strike back..."
Billy turned over his shoulder to the pink man, who continued to hobble away.
"All that's good in this world rides on the fact that we hit hard enough."
Damin returned to his meal, and didn't say a word till he was finished.


 "Billy! Billy!"
A bright light bursted through as the cabin door busted open. Billy hadn't heard this childish excitement from Damin for as long as he could remember.
Billy rubbed his eyes as his kid brother grabbed his shoulders. "What?" he grumbled.
"We're here. Come on!"
Billy let Damin tug on his shoulder like a little boy trying to drag his father out of the room. Finaly, he relented and pushed open the cabin door with a grunt.
Billy shielded his eyes from the blinding glare of the sun as he approached the side of the ship with Damin. The few guests, spun up in delicate dresses and suits, also looked out with awe. Their foresty perfume got through even the stench of the sea.
"It's... it's home," Damin whispered out to the dock which enveloped the pastel town just beyond. Compared to Marshton, or frankly anywhere Billy had been in the past ten years, the Metheno dockside and town square was a piece of candy, so bright, sweet and clean that it made Billy want to tear it open to see the ugly guts and machinery beneath-- it looked too perfect and clean to be truly operational.
:comment:
Description of Metheno here.
:END:
Billy's arms trembled. He hadn't thought of this place as home, or any place as home, for a decade. He felt his cheeks warming and his eyes watering, but he clenched his jaw and swallowed.
Damin pointed. "This is the dock we left! This is--"
"Quiet!" Billy threw his hand over Damin's mouth. He brought the teen into a huddle. "We don't know if anyone we know is still here."
Damin's wide eyes relaxed, and he nodded.
Billy released his hand from Damin's mouth. The boy panted as the two turned back to the dock. "I just-- I didn't think I would remember anything. I couldn't picture this place when I tried to remember it before... and now it's all coming back."
Billy looked out to the dock. He clenched his jaw and tightened his fist to stop the shaking before closing his eyes.
"Yeah. It is."
Memories flooded his mind. Dimpled children in a forest. Open smiles. Running. The animalistic sounds of joy. Middle-aged craftsmen turning from weary focus to a sentimental smile. Reverent gatherings in the center of town. A bald infant with closed eyes being held. SCREAMS.
"Attention, guests and crew!" Billy's eyes snapped open. The ship had pulled into the dock, and all eyes pulled to a tall man dressed in a loose black wool shirt, the first mate. "We have arrived. Tell all near to you. Get your things, the crew will not assist you unless you are travelling alone, you are to depart!"
The primmed guests let out laughters of awe at the town. Billy's eyes narrowed at them, those pretentiously polite peacocks who saw none of the real flaws or goods of this town, but looked upon it like a doll house for their amusement. Over the three weeks as he had heard those same conceited laughs, knowing that they enjoyed exported delicacies while the rest of the ship rationed out the fish stews, he had to resist the temptation to march up to the upper deck and give them the taste of dusty, furious reality he was so used to.
Luckily his mind was focused on something greater. In a way, though not as superficial as theirs, he was excited, though he was careful to hide it. He looked down at his brother, who just seemed more shocked than anything.
The boat pulled in and knocked against the dock. Billy grabbed Damin's by the shoulders and helped him up the dock and he himself got up.
:question:
confused what is happening here. They should probably have some luggage. A bag at least
:END:
Billy turned at the clicking of boots against the dock.
"Halt!" A well-built man in a studded leather breastplate on the dock raised a hand towards Billy.
"We must do a check-in of your ship, its contents, and its passengers before anyone disembarks."
Billy just raised an arm over Damin's chest and took a step back, but did not move. The first mate sighed and stepped up to the dock, and the two men whispered for a few seconds. Billy eyed them the entire time, knees readied like a cat waiting to pounce at any time.
"And when can we expect their departure?" the armored man asked.
"A sister ship in our company will arrive in a two weeks time, which will return them home," the first mate said.
The armor man nodded. He turned to Billy and Damin, gave them a quick look over, and then turned to the crowd of a few dozen passengers which had gathered on the main hull of the ship.
"Welcome to Metheno. I am Devinar Vakas, port marshall. There are two businesses which accommadate guests, a more expensive accommadation on the north side of town, on Revictus street and a cheaper one on the east side, on Nexon street. I can arrange guides to bring you to each. No matter which you choose, you will be expected to report to your rooms every night. Guests are allowed in Metheno, but you must submit to the Kuarko and show no dishonor to our gods, or you will be removed."
:comment:
This guy should be a Krusadar
:END:
Billy's nails dug into Damin's arm at the mention of the Kuarko. The boy whimpered, and Billy loosened his grip.
"If you are unaware of our customs, we will be happy to show you," the armored man continued. "But we will not warn you twice. Understood?"
The crowd nodded in unison to the Devinar.
"I can't speak for the rest, but my wife and I are *splendidly* acute to your customs," a suited man with a thin mustache said. "We studied--"
"Silence," the Devinar raised a gauntlet, and the suited man's smirk turned to a shocked purse. "It is customary that all refer to clergymen with their titles. I am Devinar Vakas, if your memory has aleady failed you," the armored Devinar said without the expected sass.
"Though the Versalist world has not seen it urgent to spread the Truth to Apathasaw, and Apathasaw has rejected the Truth repeatedly, we are still told to spread it. Thus, if any of you wish to join us, as the Versalist world is not a world bound merely by nation, come to the chapel. We will arrange something," the Devinar continued.
:comment:
Vakas should mention the pirates. Or Billy should be surprised by how unharassed they were
:END:
The crowd on the hull fidgeted like bored schoolchildren, but Billy was especially antsy being overlooked by the Devinar so long, and especially his being commanded by one.
"One last thing," the Devinar spoke. "If you go out at night, bring a lantern. Anyone out at night without a lantern will be treated as a hostile Dark Herald by the Devinars."
Damin shook, but Billy squeezed his shoulder to stop any motion. The Devinar turned to Billy. After a few seconds, Billy gave a cheesy smile, but the Devinar remained stoic.
"Come now," the Devinar said. "Let us exchange your money, and get you settled."

Billy felt the dew on his hands, neck, face, and ankles-- every part that wasn't covered by his new-- well, new for him-- coarse wool tunic and thin loincloth. They were customary for Wreathwardian commoners, rather than the durable leather he sported in Apathasaw. It was shabbily cut, not that Billy cared, though the colder weather made Damin shiver. Damin's feet crunched against the pebbles on the dusty path, he floundered forward; it looked as though he could collapse at any step.
:comment:
loincloth might be too primitive
:END:
Billy turned to him with a scowl. Billy had a pack full of clothes and money, and Damin had nothing-- and the boy was still struggling just to walk. There was just a little sting that maybe it was Billy's fault for sheltering the boy all these years, but Billy quickly shut that down-- no poor orphan kid was ready for the struggle and chaos of life alone in Apathasaw, let alone Damin.
"Come on. We've been waiting for this for *years*. You're walking like a criminal about to be hung," Billy's throat shook with passion.
Damin stopped and looked up to Billy with wide but dead eyes. He just gave a nod, and then continued tumbling on, just a bit faster.
Billy exhaled and blasted off into a jog. He turned his neck, Damin panted on, but the gap between him and Billy widened.
"Come on!" Billy shouted.
His voice quited between pants. "We have to find dad."

Billy groaned as he tredged up the grassy hill. It was just the last few steps, and he had slowed down to let Damin catch up. The boy's chest pumped up like a panicked dog's.
Billy grabbed his brother's arm as they got to the last few steps. They gave each other a brotherly nod as they got to the top of the hill. The sun basked down on Billy's skin, and he gave a big yellow smile. He put his hands on his hips and peered out over the valley below-- and the rows of graves that filled it. His smile disappeared into a solemn purse of the lips, and he met Damin's irresolute stare.
Billy glanced back to the valley of graves. He blinked to stop his eyes from tearing up. He glanced back to Damin, whose childish eyes pierced his soul in the way only a child could. Billy marched down the hill to avoid his brother's gaze.
:comment:
Add more transitions between these snippets it too jarring as is
:END:
"I--I don't know. Maybe-- just maybe it's not--"
"C'mon. It's-- FUCK!" Billy shouted and kicked up dirt onto a nearby grave. He looked out over the rows and rows of graves they had already checked.
"We came all this way-- I'm gonna keep lookin, I'm gonna keep lookin. Maybe we missed it." Billy's throat shook with resolution as his eyes dashed from one grave to the next. His ankles shook in his dirt-filled shoes as he ran from grave to grave, and he ignored his aching legs' plea for rest and food.
Damin perked up behind Billy. "It's-- I already checked that side, Billy. We didn't miss it. It's--"
"Damin-- please--" Billy's hand shook as he turned around to the boy, who shivered.
"He was a criminal in their eyes, Billy," the boy's voice barely escaped his lips. "They didn't bury him."
Billy's bony hand and manic eyes shook at Damin, like an insane magician cursing a man. In an instant, the zealous energy left his face, and he collapsed onto the dirt.
Damin rushed to his aid, but Billy turned as if the boy wasn't there, to the nearest grave, marked Yorval Arektre. His tunic smattered with dirt, he shook his fist at the grave.
"Dad, wherever you are... you'll see it through my eyes. You'll rest-- knowing that they paid with their lives... they'll pay for taking yours... for stealing ours," Billy's fist smothered the dirt. He pounded his fist, as though his father was trapped behind a wall of dirt.
Damin opened his mouth, but he pursed his lips in reconsideration before anything could come out. Billy hurried to his feet like a dirty dog. The boy trembled with wide eyes as Billy grabbed his shoulder and pushed him forward, back towards the city which they had left.
:comment:
be explicit here with Billy saying his goal is to kill Aldwin
:END:

Billy pushed Damin against the white wood walls which glowed like a star in the center of the city.  Billy talked down with a pointed finger at the boy.
"Don't move a muscle. If there's a problem, you know what to do--," Damin said with Billy in unison, "stall, scream, scram." Billy nodded and gave the boy a pat on the shoulder before turning into the building. Inlaid on the doors shone a diamond, its corners pinned by four crystals, one green, one an ocean blue, one red, and one a piece of the sun.
Billy's nose squirmed at the unusually natural odor-- the nectar of a garden, as well as the strong musk of the forest. The scent brought back memories-- his mind already begun to picture the interior just as he entered.
And his sight confirmed it. At the back of the church, there were four massive altars, two on either side, each with a stained glass pattern depicting a symbol of the Four. The two ones on the right explained the scent: sunlight shimmered down from the stained glass symbol of three blue diamonds meeting at a centre vertex, giving light to a tower of unbound books, a bed of trinkets of wildlife: horns, seeds, plants, hoofs,  and a spot obviously left open-- a crude dedication to the values of Olitheon, Wisdom, Exploration, and Humility. In front of it was a much more sightly view, cast in the green tint from the stained glass pattern of three greenshapes which curled after each other like the ends of a hoe, illluminating an ordinance of flowers, miniature stone sculptures of humans and animals, and a large hide and tusks-- Nexon's values of Peace, Creativity, and Bravery.
On the left was Intillia, three red circles cast over an altar filled with coins, tools, and bushels of wheat: symbols of her Generosity, Discipline, and Loyalty.
And the front left was Aredal, three golden triangles with a simple white diamond in the middle, shining down on an altar lain with swords, and a large, bound tome-- the symbols of Justice and Truth. In the centre of it all was merely a small bowl-- Billy assummed it somehow must've been a symbol of the last value of Aredal-- Sacrifice. His fist clenched at the sight of Aredals' symbol.
His steely glare set fire to the entire building, until freezing upon a bald young man shuffling out from a backdoor. The man's robes, which bore the symbols of all of the Four, gave himself away as an Ather.
"May I help you?" The man said as Billy marched toward him.
"I'm a traveller, from Apathasaw," Billy said. "My father brought me here when I was just a boy--"
The Ather raised his hand for Billy to stop. Billy hardened, before the Ather gestured to two chairs in front of the space where the altars were. Billy took a seat after the Ather.
"My father brought me here as a child, and I met two men I'd never forget. I came all this way to see them... I'd thought they'd be here, honestly."
"And who might these two be?" the Ather asked.
"Ather Aldwin," Billy said. "And um, Infantis Okin. Though I'm sure he's a Rothar now."
The Ather's eyes lit up in recognition. "I guess we don't expect things to move so much when we're not looking," the Ather chuckled. "Okin is an Ather now, and Aldwin-- our Impalias."
Billy's eyes widened. "W-what?" His eyes moved back and forth. "So then he's--"
"In the Citadel, yes," the Ather replied, and gave a wry smile. "I hope you packed enough for another long leg of your journey."
Billy's polite facade dissappeared into concern.
"And I don't even know if you could catch Okin... he was sent to lead soldiers on the Farsunni front. If this meeting is as important as it sounds, I pray that the Discipline of Intillia is ignited in your heart," the Ather gave Billy a pat on the shoulder; Billy flinched before easing into the brotherly gesture. Billy stared into the Ather's eyes, his face frozen in contemplation.
"Well... do you know exactly where Ather Okin is stationed?" he asked.
"Oh, no, I'm afraid not, at least not to a level of Truth which Aredal would accept," the Ather said. "But from what I heard he was stationed along the Southern Front, in *."
"And is he set to return anytime soon?"
The Ather shook his head. "Not unless the Farsunni surrendered tomorrow."
Billy nodded. "Thank you for your Honesty, Ather," he gave a fake smile, and his heart flailed against him within.
"Of course", The Ather smiled back.
* Chapter IV
** Notes
- Add area where Damin disputes Billy killing Aldwin in the Citadel before it happens.
** Chapter
:comment:
Establish where they are here and what their goal is. It should be explicit they want to track down Aldwin.
:END:
"Wait here", Billy stopped Damin from advancing as he marched towards a coachman and his carriage on the top of the hill.
"What can I do--"
"We need to get to The Citadel," Billy interrupted the coachman.
The coachman raised his chin, accentuating his pencil mustache. "I wasn't planning on going that far... but depending on the compensation I could be obliged."
Billy glowered, but reached into his pocket and showed a handful of golden and silver coins.
"That fine?"
The coachman frowned.
"Oh, c'mon. Don't act like you don't need this," Billy said.
The coachman looked back and forth-- but his train of thought was interrupted by a feminine chuckle.
Billy snapped around to be confronted by a man in an impractical doublet with a mane of fur that was mirrored around his wrists, and a woman in an even more inflexible, wide-waisted gown. Their colorful presence fought against the dreary surroundings and Billy's dirtied form, and they shot through to the coachman with an energetic hop, and their brightness flowed through to the coachman's face.
"How might I be of service?" the coachman asked.
"Two tickets to *, good sir," the man said.
"Hey!" Billy barged through, raising his arms to push back the well-dressed man. "We were being served here!"
The woman gave an unbelievable scoff, and the man shook his head. "The coachman asked how he might be of service to our party, did you not, good sir?"
:comment:
Billy is rough, but I think he should kind have some more manners? At least Damin should try to, it feels more informed in relation to their background
:END:
The coachman's nervous glance darted between Billy's hard stare and the proper man, until landing on the proper man's smile and reassuring nod.
"T-that is right," he finally said.
The couple then stepped between Billy and the coachmen, the woman squinting and raising her chin at him. Billy had to dig his fingernails into his palms to crush his desire to pummel the two the ground.
"That'll be fourteen steltells," the coachman's eyes twinkled.
The man counted out several coins from a pouch into a gloved hand, and handed it to the coachman, who gave a curt bow.
The driver stepped up onto the front seat of the wagon with a manic energy in an attempt to rush past the steely wall that was Billy. The man gave a performative motion for the woman to get into the wagon before him, and with the man's help the woman lifted her massive dress to squeeze into the back seat of the wagon.
The man turned around to face Billy, who still just stood there in anger.
"Well, there'll always be another wagon."
With a whip of the reins, they were off. Billy kicked a plume of dirt towards the back, but it went unnoticed.
Billy grit his teeth and reached into his bag. He pulled out the sixshot, and the bag which held its bullets, just as the wagon rolled down the hill and onto the next.
"Billy-- don't," Damin rested a thin, pale hand over the sixshot.
Billy turned to Damin, glanced at the wagon in the distance, and then looked back to the gun. With a sigh, he put the contents back into his bag.
"So much you did," Billy pushed Damin back. The boy caught himself by doubling over, pressing both hands against the dirt.
:question:
Last time is confusing not sure what happened
:END:

:comment:
Transition here. Too abrupt again
:END:
"It's better this way, anyway," Billy shouted over the rhythym of pounding hooves and heavy breaths.
"Don't have to have small talk with some shaky little wagon driver, or fear that you say something stupid that gets us under heat."
Atop the horse, Damin looked like a kid who had just lost a sport. "We didn't have to--"
"Speak up!"
"We didn't have to steal them! You still had money!" Damin shouted.
"I wasn't gonna have another prick turn down what we had. And plus, it was in the middle of the night. He'll just think an animal broke in and they got loose!" Billy said.
"That doesn't make it right!" Damin shouted back.
"Right?!" Billy pulled his horse to a stop. Damin circled his horse around so that his saddle-side faced Billy. "We've been so far wronged, that this isn't even one drop in the bucket of the right we're owed!"
"That's not how right and wrong works," Damin shook his head. "There's right, and there's wrong, and us being wronged before doesn't make wrong things right."
Billy stared at Damin in disbelief. "Are you my brother? Have you lived life alongside me? Were you nearly *killed* for who you were, as an innocent child? Was your father *murdered* because he protected *you*, as an innocent child?!"
Damin's head lowered. Billy spit at the ground in front of Damin's horse.
"The only *right* is us stabbing back at this ugly, ugly, world."
Billy started his horse into a prance, passing Damin.
"What happened to us *was* ugly, but that doesn't mean this world isn't filled with beauty," Damin looked around at the fields of verdant green that went on forever, sprinkled with colorful flora.
"In fact, I hope one day we can see more of it."
Billy turned back to Damin with a harsh glare.
"We're getting out of here as soon as I've done what's needed to be done," Billy said.
"And how's that going to happen?" Damin's eyes grew serious. "What even is your plan, Billy? Do you even know how to find them? Do you even know how to get out, and get us back to Apathasaw, after all this is over?"
Billy's eyes, dead with determination, stared at nothingness. "I'll find a way, just like I always do. After I've delivered what's been coming."
With a whip of the reins, Billy dashed off. Damin's chest sunk, but after a few seconds, he followed.
:comment:
Good convo
:END:

"Stay close, now," Billy said as the neck of the crowd of riders and wagons shortened and widened along the road. The mass of riders, which created an ambience of neighing and chatter, were all under total shade. It was already evening, but they could barely see each other.
"Wow," Damin stared upwards at what appeared like a border of the world. Slabs of stone, each double the height of men, towered upwards, creating a horizon of the sky: a wall that hid the sun.
Billy bit his lip. Of course, the usual fire burned inside him at Damin giving such awe to the *monument* of the institution that ruined their lives, but he knew that Damin already knew everything Billy had to say on the matter.
"You think if the full force of the Delmian Empire at its height tried to invade The Citadel, they could?" Damin turned to his brother. Billy ignored him.
"What about Farsun? Like if an army of Black Knights was just dropped here?" Damin continued.
"If that ever happened-- which it won't-- well, it depends on the time of day, of course," Billy said.
Damin smiled. "So you think at the apex of night, the Black Knights could break through?"
Billy shrugged. "They'd basically be invisible... and they could project a whole army where they weren't, while it looked like there was nothing where they were. If they had enough cannons behind them, or other Heralds, to break through--"
"Heralds? But aren't the walls lined with heraldshell?"
"You really believe that shit?" Billy smirked. "There's no way they had enough heraldshell to line the entire wall. That would just be wasteful. You read too many books."
Damin shrugged. "Guess we'll just have to be here when there's a siege to find out."
Billy smiled as the line moved up. They approached an open gate, about ten men high, each door made of totally solid steel and embossed with large circles. The bustling noise of The Citadel now drowned out their conversation.
"Name and purpose, please!" A man covered in steel plate shouted. He held a torch in one arm, and next to him were three identically dresed men. The only difference in the armor was that of thin carvings which had been burnt onto their chestplates-- partially completed sigils of the Four, showing achievements in the Virtues of each man's respective God, and ommiting those not mastered. Billy's arms tingled-- these were Devinars, the muscle and steel of The Citadel.
"We're travellers from Apathasaw. We're here to behold this wonder... and maybe do a bit of trading," Billy shouted down from his horse.
"Seemed to be packed rather light for traders, the Devinar pointed to Billy's bag.  What do you got in there?"
"Antiques," Billy didn't flinch.
"Let me see," the man reached for Billy's bag. Billy's grip tightened around it, and he glanced to the nearby masked Devinar, who's shielded face bore down on Billy, hand on the hilt of his sword.
Damin grabbed his thumbs. With a shaky hand, Billy held out the bag to the Devinar. The Devinar snatched it and peeked inside. He peered down, for what seemed like ages, right at the body of the sixshot. Billy's hands sweated around the reins, and he glanced back and forth between the armored men, their expressions hidden.
"Never seen anything like that before. Guess Apathasaw really is a different land from here, huh," the Devinar handed the bag back to Billy, before nodding to his masked accomplice. "Well, enjoy The Citadel."
Billy closed the bag. A sigh escaped their chests as they crossed under the massive wall, which itself felt like the inside of a cave. But on the other side, the shimmering light and sounds of the city promised a whole new world, and even Billy felt a tingle inside his heart, the promise of utopia.
The Citadel was undoubtedly alive, and as such always growing, yet simultaneously every building felt like it had always been there; almost everything was made of stone, limestone that shimmered in the sun, or marble, which gave it all a statuesque look that sat upon eternity, fit with carved faces atop buildings which stood as watchers over the fragile men below. The roads were made of brick, without a bump, and thus, what was wood or any softer material was only the carriages, and thus it felt as though the bustling mass moved about an immutable city. Stone spires reached up far past what would be the tallest buildings in most other capitals, yet they were still dwarfed against the backdrop of the Citadel walls, which one could often notice if they focused through and far enough.
Even from the perimeter where they had just entered, one could also intuit the circular shape of The Citadel-- there were outer roads which curved perfectly around, as did the walls, which, along with the buildings, gave the place an obvious symmetry. And in the center, down the main road they had just entered, a guiding star shone, though it was day-- Billy shielded his eyes, though he did a double take-- it was not the sun, it was too white, and too narrow in its glare. What it was, he did not know, but it was perfectly in the center of the Citadel, what appeared to be miles down the main road, atop the tallest building in the entire Citadel, reaching over two-thirds the height of the walls, though it was obscured by the glowing light.
Billy and Damin continued towards it. It was high up enough that though brutally bright, much like the sun, it could be ignored if one kept there eyes at normal level.
:comment:
what is giving the big glare
:END:
Billy's eyes darted around the crowd, and he locked in as he found an Ather, clad in the quadruple-colored robes. Billy jumped off his horse and grabbed it by the lead, and cut through a crowd of passerbys to the man.
"Excuse me, Ather! I'm a newcomer here-- do you know where Ath- Impalias Aldwin might be this morning?"
"If not in the Kuarko, he'll be at the Grand Temple of Aredal," the Ather replied, unimpressed.
"And where might that be?"
The Ather pointed down the main road. "Follow the Light."
Billy gave a curt nod, before finding a clear enough spot to mount his horse.
"Looks like destiny has made things easy for us. Following the light down one road," Billy said to Damin dryly.
"I thought you didn't believe in destiny, Billy," Damin said.
"I might after today," Billy replied as his horse trotted on.
As they got closer to the center of the Citadel, and the Light got higher, the massive building which upheld it became more clear-- it was not only a massive building, carved with detailed spiral patterns which made the eye flow upwards like a staircase, but atop it was an equally massive statue, which in its hands upheld the shimmering Light. A muscled, yet youthful man with a cape that coalesced into a mane of fur around his neck presented the Light to the world, a legendary figure of white marble that upheld glory to the entire city-- but Billy knew he was no man, but rather the God of Light, Aredal. He could now tell that there were two similar statues on either side of Aredal, though the faced in opposite directions to each other, and though he could not see it, he knew that behind Aredal another statue of equal measure faced the opposite direction. Aredal, Olitheon, Nexon, and Intillia-- the Four.
Though Billy just looked upon the statues much as a wild animal would look upon any human work of art, not with awe, but an empty stare of indifference, Damin was truly blinded by the Light. As he saw his brother's unfiltered reaction, Billy took a second look to pour over the intricate embeddings and embossings of the monument. It *was* breathtaking, even an animal could realize that. A little nag pierced his thoughts about how special this must be for Damin, and really, should be for him-- after years and years of crappy, dusty towns, to take in a masterpiece which could have been built by titans.
    But a feast of shouts snapped Billy out of his wonder. He and Damin turned to see a large crowd gathering in the intersection of the road.
Billy slid off his horse, and Damin followed suit. They tied their horses to a nearby hitch as they moved toward the outskirts of the crowd. The crowd was gathered around a wooden podium, atop which stood several Devinars, as well as one man that looked like an Ather, but his robes were more colorful and ornate, and in the center was a diaroma of the completed symbols of all the Four atop each other.
:lore:
I think this takes place at the Olitheon statue in the Okin chapter
:END:
The robed man's voice boomed with passion. Billy grabbed Damin by the arm and stabbed through the crowd, against the vicious retaliatory elbows.
Billy moved with determination, nearly losing Damin, his eyes not leaving the podium. Squirming, screaming, a thin teenager struggled against the steel arms of a Devinar, as ropes wrapped around his arms and legs.
"Darkness hides in many forms. It corrupts everything-- it takes pleasure in using our greatest goods as its cloak. Deionis is the master of Deception-- he will not come as an ugly miser, but a beautiful woman! A feeble child!"
The Devinars slammed the teenager against the stake. The boy kicked desperately against the cauldron until ropes enveloped him.  As he saw this, Billy gritted his teeth; he felt himself kicking inside. He slowed Time and tried to make out the face of the robed man, but he couldn't. They were still far from the podium, on the outskirts of the crowd. He squinted against the waving arms and jumping bodies, but they still blocked him. He focused on the voice of the screaming orificer.
"One bit of Darkness corrupts all in its midst. Even the Gods could not survive alongside Tregale!"
He thought it *did* sound like Aldwin, but shouting that fervent sounded the same from every man, and though he had relived it a million times, the exact tone of Aldwin's voice was gone from his memory. Billy lurched forward, now *charging* through the crowd.
He jumped up, slowing Time as he did so. The world froze, his vision of the podium slowly sharpening, until the robed man's face was front and center--
Though Time was frozen, and only Billy's eyes barely moved, his heart exploded. It was *him.* Aldwin.
Billy released Time, scrambled for his bag, grabbed the sixshot--
:time:
:end:
*WHAM!* He was thrown onto the ground. "That's what you get, cutting through like that!"
His vision blurred, Billy palmed around for the sixshot. The crowd erupted in cheers.
Billy found the gun and stood up. As his eyes met the podium, the stake erupted into flames.
Billy stepped back in horror. The sixshot fell from his hands again with the howl of the child.
He didn't slow Time, but it slowed anyway. It felt like his mind left him. The fire danced, yet it was frozen. He was swamped in a sea of elbows and shouts, yet he was alone.
For a second, he saw the face of terror on the tied teens' face as his brother's. A frozen image of his brother's usual dark, small, hidden expression illuminated by the desperation of doom.
Then reality returned, as did Billy's normal state. His grip. His determination.
He spun around, back and forth, until he caught his anxious brother, hiding behind a tall, jumping man. Billy captured him by the shoulders, and lifted him up off the ground.
"You wanna see the world, Damin? You want to see the fucking world?" The calluses on the back of Billy's clenched palm dug into the supple skin on the back of Damin's neck, forcing his face towards the fire.
"Open your eyes! This is the fucking world!" The crinkles of the consuming fire gave a rhythm to the chorus that was the desperate howls of the child.
Billy raised the hand on Damin to yank the boy's hair backwards, keeping him in place. He nearly bit the boy's ear as he pounced in to whisper.
"This is what the world would do to you. This is what they would've done to you if dad didn't die for us! The only warmth they have to offer you-- is fire."
Damin squealed, and Billy finally let him go.
"Don't do it Billy!" Damin whimpered as he buried his face in his hands. But Billy turned from his brother. The flames danced in his eyes.
Billy looked down for the gun, and saw it in between the legs of a jumping man. He snatched it.
Leveled the sight at Aldwin's head. Froze Time. Closed an eye.
Fired.
* Chapter V
** note
This doesn't line up with the Okin chapter. The two should probably be one chapter
** chapter
Aldwin's breath fled his body. Searching for it, he clasped his collar with both hands. His eyes rolled back in his head, and he collapsed.
Billy was amazed how long it took for the crowd to realize what happened. Though both forms of high adrenaline, it seemed like the crowd needed to be lowered out of their excited roars of religious ecstacy to be reheightened into screams of terror.
Just as soon as the ring of the shot faded, Billy snapped back into alertness--
  But he froze as the crowd scattered and he lowered his gun. A bald man, in his early thirties, stared right at him, the only one in a sea of panic to spot the killer. With just a look, he said to Billy, "You-- I know you did this."
And Billy knew his eyes returned a look of pure recognition.
"Okin?"
Billy raised the sixshot at the bald man, but the crowd interspersed like a mass of crows, a sea of skin crossing and overlapping until the bald man no longer remained in Billy's sight. Billy thrust through the crowd a few paces. His eyes were fixed on the same spot where he saw the bald man.
He was yanked back.
"Billy!" Billy turned to see Damin's arms on his shoulder.
"He's there! Okin! I saw him!" Billy spit and squirmed from Damin's grip.
"If you try to find him, we'll be caught and killed!" Damin said. "What justice will that be?"
 Billy's bullish rage receded. He caught the armored Devinars descending on the crowd, and Okin nowhere in sight.
 He stuffed his gun back in his bag, and then turned and motioned with Damin to morph into the panicked, dispersing crowd.
 Shouting and flailing limbs spiked the atmosphere, shrinking Billy's perception to the immeadiate. Commoners burst back and forth like cotton balls in a vacuum, spirred by panic, but unsure where to really go. Billy's determination rushed back to his head; he held his bag close to his chest and grabbed his brother on a cut for where he hitched the horses.
 "Get on!" Billy shouted. Damin pulled himself onto his horse, and Billy cut both the hitches. He hoisted himself up onto his horse, and started to turn it around, when he heard rapid galloping approach him--
 "Billy!"
 Billy whipped the reins, just as a torpedo of fire exploded at him, torching his right shoulder. He was thrown in the air as his horse blasted off. He felt his skin singe as the shoulder of his shirt burned away. He smacked himself to put out the fire on himself. His horse neighed in agony. The horse stumbled off its initial direction in jerked, panicked, movements, screaming all the while. Billy wrapped himself in a ball around his bag and threw himself off his horse, hitting the cobbled path with a thud and a roll. He scrambled to his feet, ran a few paces and turned to see his horse's mane burning, as the animal ran around in panicked circles. Billy grimaced at the sight of the poor animal. The nightmarish scene spread its panic to the crowd, creating a circle of terrified chaos. But behind it were, glistening in the fire, were three steel soldiers advancing on him, one holding a lantern up high.
 Billy turned around and sprinted off. He could see Damin's horse ahead, far through the crowd. He shoved through, pushed forward by the encroaching rumble of the steel boots behind him.
 He dodged an approaching carriage. He passed face after face as andrenaline took over. The steel rumble did not stop. He sweated at the terrified anticipation of another plume of fire headed his way. He tried to hide behind crowds and carriages as he passed them, hoping the wrath of the Rothars would not permit them to burn down a crowd.
 "That guy! GET HIM!"
 Billy turned to see an approaching duo of Devinars from an intersecting street. They were jolted alive as they saw Billy running. Billy swerved off to the far side of a carriage, so they were blocked. Though his body could barely handle it, he sped up.
 It seemed like both seconds and hours by the time he reached the outer wall. The boots of the Rothars had fallen behind, but they still rumbled in the distance. He glanced for Damin through the gate, and saw him atop his horse, next to the long line slowly moving in and out of the Citadel.
 Billy sprinted through the gate, passing once again from the dense, architectured space of the Citadel out into the outside world.
:comment:
they're probably too far for this to make sense. The chase should be longer
:END:
 "Rothars at the gate! The man running! Stop him!"
 Billy heard the shout of the Rothars behind him just as he passed through the gate, but even their loudest shout was quiet to him. Still, he turned and saw the Rothars at the gate snap to attention.
 "That man! Get him!"
 The closest Rothar pounced on Billy. Billy slowed Time, jumping an inch from his tackle. The rest of the Rothars drew their swords. Billy crouched into a wrestling stance as the Rothars circled around him.
 Billy glanced between the four of them, his hand inside his bag.  The Rothars that had fallen behind reached the gate as well, forming a line behind those that circled Billy.
 Billy felt the trigger of the sixshot inside the bag. His resolve faltered, as he kept Time slow, anticipating an attack from any angle.
 From behind, he heard hooves click--
 Billy tried to dodge back further, wanting to avoid whatever it was, but knowing hif he turned his head it would be the end of him. He drew his gun just as the two closest Rothars charged at him--
 A black plume of smoke exploded in Billy's peripherals. The Rothars all jumped back, and he even heard shrieks of fear. Billy turned-- just next to him Damin stood atop his horse, but it was a shifting, long black form of smoke which had terrified the Rothars. It had a glowing purple smile.
 "It's a dark one!"
 The Rothars all stood in a defensive stance. Their attention completely shifted from Billy to Damin and his dark form.
 Billy looked to Damin. He met the boy's trembling eyes. He couldn't say it, but he knew that after all their years together, his look said it, and Damin's agreed-- *run!*
 "Don't be afraid! They have no hope here, in the beating heart of the Gods!"
 The Rothars with the lantern stepped forward.
 Damin whipped the reins and spun his horse around, kicking up a plume of dust. Billy closed his eyes and followed suit. The roar of the fire and its fierce glow burned just behind him, consuming the being of darkness.
 Billy's parched throat tasted dust. He jerked his arms violently to keep pushing himself forward.
 "ERRGH!" He screamed in agony. A sharp pain flooded his back, and he collapsed to the ground in a ball of dust. He rolled over, clutching his back. He bit his lip as he felt another sharp pain as the arrow in his back cracked against the ground. He heard Damin's horse screech to a stop.
 "Keep--- aghh! Keep going!" He shouted. But he heard no more hoofsteps. "Damin-- keep--"
 His vision was filled by the empty blue sky. The earth shook his body with the pounding of each step of the approaching Rothars. He thought this was the end, and felt an envy, a feeling of being cheated that his life did not flash before his eyes. In fact, there were no visions. Just the big, empty blue.
 A shocking flash of pure white blinded his sight, forcing his eyes closed. *Death.*
 But he felt another thought come-- *At least I got one of them.* And then another-- *How did I think that?* And then his eyes fluttered open--
 He was pulled up by both arms. Before he could ground his feet, he was pushed forward.
 "Get in!" A woman with striking silver hair and eyes shouted toward a indigo, swirling portal. Billy glanced around for Damin-- he was nowhere to be found. But the shouts of the Rothars were feet behind him.
 He ran into the portal.
* Chapter VI
Billy stumbled out of the portal, barely retaining balance. His boots clacked against the wood planks. As soon as he got to his senses, he heard someone else come in behind him and the portal close.
"Billy!" Billy looked up and was greeted by a hug from Damin. He grimaced as Damin hit the arrow stub on his back, but found a smile as a felt the warmth of his brother.
Damin released the hug, and Billy glanced up to see a young, thin woman, and a dark-skinned man facing away from them, near the edge of the ship. Out from behind him stepped another woman, tall, with shimmering silver hair and eyes. The woman who had lifted him up from the ground.
Billy gave the group a crooked smile. "Well, we do appreciate the help, and if I had a spare coin to toss ya, I would. But it ain't so, and we've got our own plans. So we'll be seeing ya."
Billy strutted to the edge of the ship. He slammed back as his hands hit the side railings, and the silver-haired woman rushed to catch him. Then, with hesitation, he leaned over again, and stared down--
The Citadel was below them, like a little play castle that he could reach out and touch, among the winding roads and empty grasslands. They had to be almost a mile above the ground. On the ships' edge, he caught some whimsical, delicate glowing tentacles, which triangulated above the ship to a giant jellyfish-like being.
"What the fuck--"
Billy turned to Damin.
"I know!" Damin said with wide, excited eyes.
Billy elbowed the silver-haired woman back, and she relented. He hadn't noticed it before, but a mass of tentacles were wrapped around the dark-skinned man. The man's face now turned to him, Billy could see his eyes were pupiless, glowing with a dark violet.
"What's going on here? What the fuck is this?" Billy snapped.
"Don't worry. We're only here to help," the silver haired woman said.
"If that's true, you can find the nearest town and set down a mile from it," Billy replied. He crouched into a ready position, and his glare darted back and forth between the three strangers.
The silver eyes stared at Billy with still seriousness. Billy glanced to Damin, who looked as the child he was, waiting docile for the pronouncement, with apprehension and curiosity.
"We saved your lives, we only mean to help you. And that is just the beginning. What we have to offer you, and especially your friend, is the greatest gift," the woman said with measure.
"He's my brother," Billy said. "And speak a little more vaguely, will ya?"
The silver-eyed woman didn't move a muscle, except to clear he throat in a robotic manner. "You are wanted by The Citadel. You do not appear to be wealthy. We offer you refuge," she turned to Damin. "And for your brother, an opportunity to become the best Herald he can be. A great purpose."
Billy glanced between the dark-skinned man, who had turned back into himself, his slight movements causing tension and release in the tentacles; the thin woman, who eyed him with a wonder an innocence similar to Damin's, and the silver-eyed woman, whose sterness was ever-near.
"Three Heralds, working together. I knew something was up. So this is like a little Herald club, then?"
"It's more than that," the silver-haired woman said. "It is a community. A way of life. A higher calling. A home."
"Well, I happen to be a Herald too," Billy said.
"I knew it!" the petite woman shouted.
"All the better," the silver-haired woman's calmness remained. "Then I offer you both the same opportunity for enlightenment."
Billy's eyes narrowed. He paced around, circling the group, who's gazes remained on him.
"Sounds like a bunch of bullshit," he said. "You make all these holy promises and then get a bunch of slaves to work for you, who won't rebel because they're stupid enough to believe it's some *holy calling*."
"We are not The Citadel. Our community is local and transparent," the taller woman said.
"Come on, Billy," Damin said. "Give them a chance."
Billy looked to Damin. The boys' eyes betrayed his starvation-- not just for food, but for a more meaningful life.
:comment:
More argument here. And name intros
:END:
"Okay," Billy relaxed his shoulders. "So where are we going? What's gonna happen?"
"You will experience our way of life at the Tsuman Monastery," the silver-haired woman said.
"And if it sucks?"
The silver-haired woman paused. For the first time, her eye contact with Billy broke.
"You'll kill us?"
"We won't kill you," her stare resumed on Billy's face.
"So what then?"
Billy heard the gears churning in her head, the fabrication of a false, satisfactory answer. "We'll find a way to let you leave unharmed," she finally said.
More bullshit. But what could he do? They had no food, no clothes, no plan, nowhere to go, and The Citadel on their trail. These people could kill him and Damin and no one would know-- at least so far they hadn't, in fact, they'd saved him and Damin. But why? Such random altruism for two nobodies, even if these people claimed to desire them because of their Heraldry... was still suspicious.
"It sounds like this will be a permanent choice," he rumbled.
The silver-haired woman's lips pursed. "As I said, if things go poorly, we will find a way to you leave you unharmed. But-- yes."
The smaller woman spoke up. "If you wish for us to leave you, we can do that. You're missing out on something beautiful, but we're not gonna force you."
Permanent. Billy hated that. The word might as well be "prison". Was he about to buy into a cult? The people seemed *pretty* normal, despite the giant jellyfish ship, and the silver woman's static mannerisms.
:comment:
Billy should maybe know about the jellyfish ships. Unless they don't exist at all in Apathasaw
:END:
He sized up the three Heralds. Could him and Damin take them, if it came to that? The way the conversation was going, he'd be lucky if Damin lifted a finger against them. Could he take them all? It seemed unlikely. He had no idea how powerful Heralds they were, but they were confident to hold off a dozen Rothars, one who was a Gas Herald. For most people, a Teleportation Herald was an existential threat-- before they could act, the Teleportation Herald could blink behind them and knife them and stab them in the back, but /Suspicion/ tensed every muscle in his body. Maybe it would be enough to react to the blink and surprise the Teleportation Herald. And the Mind Herald probably couldn't be as active in a fight-- but he could be deadly if it came to that. Billy felt for his bag-- he still had the six-shot, and there was no way the Heralds knew about it. If the Mind Herald entered the fight, would he drop the ship, killing them all? If Billy somehow won, would he hold the Mind Herald hostage? And would the Mind Herald cooperate?
Billy glanced to his brother.
And most importantly, could he ensure Damin didn't get hurt?
No. He hated to admit it, but the situation was too risky. It was a position that brought the acid from his stomach up into his mouth, but he had to be a good pet.
Billy recaught everyone's stares.
"I'd like to know more," he put on a polite ruse. "Who are you? Why did you save us? What *exactly* are you offering?"
"Of course," the silver-haired woman said. "We are the Tsuman Monastery, an order which tasks itself with growing the most noble, potent, and wise Heralds. We accept non-Heralds as well, who are tasked with more humble duties. We train in solitude, away from the world, to ensure that we are focused and uncorrupted, but, as we have shown, we are willing to be peacemakers if the time arises."
The silver-haired woman maintained her solemn delivery, but there was an ounce of passion brewing with each sentence. The smaller woman smiled and tingled like she was holding back a round of applause. Even though Billy was a Herald, he felt a bit of disgust of hearing that the non-Heralds were tasked with "more humble duties". Surely a sugarcoating of "hard, back-breaking, thankless work".
"I am Mei-Li," the silver-haired woman motioned to the smaller woman, " this is Voshri," and then to the man with violet eyes, "And this is Rakaal."
The dark-skinned man smiled.
"And where exactly is this Monastery?"
"Well. That's-- ," Rakaal chuckled. "A bit complicated."
"What the fuck is that supposed to mean?" Billy asked.
"It's not a fixed location," Mei-Li said. "The Monastery travels in the clouds, far above the ground."
"Okay, okay. That's enough of your fairy tales. Are you people fucking delusional?" Billy stomped towards the back of the ship, where a cabin lay.
"I mean, Billy, they got a flying ship, wouldn't it make sense they live in the sky?" Damin interjected.
"I mean, you're all Heralds... maybe this is all one big Illusion. Is there a fourth person on board? Cause it just seems like something else is going on here," Billy eyed the three Heralds like a hawk. His senses rose as his Suspicion grew, but he just felt the breeze harder.
"I know it's hard to believe, but we are serious. We are only here to help you, and hope you will join us," Mei-Li said. "Now it looks like you've had a long week. Please, we have an empty room for you. Why don't we get you some rest."
Billy's insides prickled at the prospects of sleeping on the same ship as these oddballs. He *was* exhausted, but he planned to cycle staying on watch with Damin.
"Okay," Billy nodded. "But this isn't over. You're not gonna make any decisions for us until I find out *exactly* what's going on here."
Mei-Li gave a curt nod. "Of course. As I said, you'll experience it soon enough."
Billy followed Damin's childish gaze off into the endless horizon of the evening sky, the explosion of violets and crimsons before they followed Mei-Li and Voshri into the cabin of the ship.


"Can you believe it? We're flying!" Damin bounced up and down on his cot.
"Yeah, yeah," Billy paced around the room, checking for anything that looked suspicious. The room was bare-bones, with two beds, and a nightstand upon which a lit candla nd a small pile of books lay. "But these people are so *weird*. And that silver-haired chick's stiffer than an Apathasawian cactus in the middle of a drought."
"They saved our *lives*, Billy," Damin said.
"Eh. We could've made it out of that."
Damin gave Billy a look that said, *Seriously? Even you don't really believe that.*
"Okay, fine."
Billy sighed. He tried to think about what the future held, but there was nothing. It seemed like his situation in Apathasaw was an eternity, the starving, dry, desperate grind for the next meal. Could a hungry dog ponder the future, the meaning of life, the pursuit of wisdom and right living? Of course not. Billy's hunger for revenge and worries about Damin were the closest thing to non-animal desires that colored his days.
"Isn't this what you've always wanted? An opportunity for something new, to connect with people that might actually care, instead of foremen who want to beat every living breath out of till you have none left?"
Billy closed his mouth, and met Damin's wide, innocent eyes. Sometimes it seem like his brother could read his mind. But as for what had actually just been stirring in his mind, no, he had never really pictured any clear fantasy of the sort, only a desperate, uncolored, thirst for relief. If anything, his fantasies had been ones of death. But despite his small imagination, something *new* did sound appealing.
"Yeah, I guess, if there isn't a disease-ridden rusty knife hidden underneath the tapestry," Billy said.
Damin sighed and sat criss-crossed on his bed. "Billy, I know you've had it rough providing for us, and I know others have always been brutal towards you, but you can't always just go through life-- you know."
"Listen Damin," Billy drew closer and knelt down next to Damin's bed, until he was below his eye level. "This is something you got to understand. I know you don't really remember Metheno, but I thought you would have known it by now after what happened to us at the circus. If you let your guard down, if you show weakness-- people will take from you, or they will hurt you, or both."
"But--"
"EVEN those who might wish to help you. It's not even just a conscious thing. It's an instinct that all men and all animals share. Things are scarce in this world. You must be alert. You must show strength."
Damin pursed his lips, and Billy could tell the boy was seriously processing what he said. *Good*, he thought. *Better he learns this lesson the easy way-- or, at least not any harder than he's already had it.*
"Alright. Get some sleep."
Billy stood up to snuff out the candlelight.
"Billy-- if there's nothing wrong with these people, are we gonna stay here?"
Billy stopped, his fingers hovering over the flickering fire. It seemed like if he accepted these people, it would change their entire future. And the only thing in the future Billy had thought of for the past few years was visiting his dad, and killing those primarily responsible for his death, Aldwin and Okin.
"We'll have to see what they do. And then we'll do what we have to."
He snuffed out the candle.
He waited until he heard Damin turn over, and then laid down in his bed.
Aldwin and Okin. In all the adrenaline, in the chaos of The Citadel, Billy never stopped to realized that he *did* kill Aldwin. To relish that he did serve justice, that he fulfilled his fantasy of ten years in one moment. He searched for feelings of accomplishment, of retribution, of relief, in the utter darkness, where deep feelings could best arise.
But none arose. Perhaps it was just because of all this nonsense, or more likely, because him immediately seeing Okin afterward set his mind on running the back half of the marathon.
He knew why the catharsis owed to him of seeing his father again was unpaid, because his father wasn't given a grave, and thus, he never really saw him again. But where the sense of justice for killing Aldwin, the man who ruthlessly executed his best friend and tried to burn that man's son alive, should have been, there was just void.
Billy turned over in his bed. Yes, it was because his conscience was serious, it would not be satisfied with just one half of the job done. He gathered up all his rage, his strength, his Resentment, and focused on Okin. The greatest betrayal of all, from his childhood best friend. A man who needed to die.
* Chapter VII
Billy stared out the porthole of the room that had been granted to him and Damin. Below them he could see only the endless blue expanse of the ocean. He guessed this was the Dehden Ocean, to the West of Wreathward. He'd glimpsed a desert on the horizon last night that could have been Farsun.
They'd been on the boat for just over a day now, and despite his best efforts Billy hadn't been able to get any sleep. It had been a struggle to keep Damin in the room, all the boy wanted to do was explore and interact with the strangers. He'd bought in fully to their propaganda, to their noble lie of purpose. Billy admitted it was a good lie, one a part of himself wanted to believe. But he wasn't as naive as his younger brother.
A knock came at the door and a feminine voice spoke, "I brought food."
It was Voshri, the younger of the two woman on the boat. She had delivered the food late last night when Billy had refused to go to the mess for dinner.
Damin sat up in his bed looking to Billy, searching for permission to speak. Billy reached down to unbuckle his holster, the cool metal seeping into his fingers as he wrapped them around the six-shooter's handle.
"Come in," Damin yelled.
Voshri was a short woman, more than a head shorter than even Damin. She had mahogany skin, with a cool silver undertone, and black curly hair tied back in high tail. She placed two bowls of stew on the table and a cloth wrapped portion of bread. "We'll be arriving soon. You should come up on deck, the view will be /amazing/. I promise!"
"Sure, sure," Billy waved her out of the room as he sat at the table. How could anyone be so chipper and energetic? He was reminded of the performers at the circus-- always putting on bright faces to the crowd, then rubbing off the so-called joy with their makeup in the backrooms. /Why even go through the exercise?/ he always thought.
Once door was shut Damin spoke, "can we please go out? I'm sick of being stuck in here."
"I thought you'd be use to staying inside, it ain't like you went out all the time in Apathasaw." Billy tore off a chunk of bread and proffered it to Damin as the boy took a seat at the table.
"But we're flying Billy," Damin's eyes lit up as he spoke. "Think of all the things we could have saw that we missed. Did you ever think we'd fly? There was no way we'd have been able to afford an airship, no matter how many cheap duels you won. I know you wish we could fly, don't you remember when we use to go work on the docks? We'd sit out there watching the airships coming in, imagining what kind of adventures we could go on if we had a ticket on one of those."
Those had been Damin's fantasies, Billy never had the luxury of entertaining those ideas.
"Okay, fine, we can go up after we finish eating. But let's keep to ourselves, the less we talk the less they can use against us."
Damin shook his head furiously, "ok, ok, ok. I promise Billy."
A smile grew on the older man's face as he watched his brother's unadulterated joy.

The air on the deck was frigid, nearly colder than a night in a desert canyon. Mei-Li and Rakaal huddled together in the far corner of the deck. Rakaal wore a long fur overcoat, Mei-Li wore a traditional Marthian robe, both held various navigational instruments in their hands. He breathed hard, even though he was standing still. The light was brighter, brighter than he had ever experienced. His muscles vibrated with the potential, with more Light than he ever felt. The cold ebbed away and Billy was forced to take a shaky breath as it all overwhelmed him.
Damin excitedly ran to the rail, and Billy had to pull the youth back by the collar of his shirt. "Be careful."
"Right, right, sorry."
Damin slowed to a speed walk, but still moved too quickly for Billy.
Voshri was leaning against the rail, the only other person on the whole deck. The vessel was shaped like an enlarged canoe, with thin pointed ends. It wasn't the largest ship Billy had ever been on, but if the ship had been a seafaring vessel it would have been crewed with at least twenty sailors. He could cover the width of the deck in five long strides, and the length in less than twenty. The vessel had at least three decks, but Billy hadn't gone down past the second, where there room was.
Where were the other sailors? He doubted there were truly only three of them on this whole ship. There had to at least be a chef. 
"Billy, look!" Damin's yell drew the attention of the other three as Billy approached the rail.
"What is it?"
"Don't you see it? Down there!" Billy peered down to see huge whirlpools of water laid out in an S shaped curved. Between each pool the shadow of something moved. It had to have been gigantic to be visible from this height.
"It's the Leviathi!" Damin's smile fell as he saw Billy whirl on the two older Heralds.
# Should we just say its the strait? idk if commonser should know about the leviathi?
"Where are you taking us? That's the Leviathi down there, which means we went North!" He took three quick strides and was upon Mei-Li and Rakaal. "Are you delusional enough to take us to Krinosas?"
Rakaal glanced to Mei-Li who put up a hand. "We're not taking you to Krinosas. Like I said before, we're taking you to the Monastery. We had to come this way to catch it's path."
"It's path?" Billy took another step foward. Mei-Li was surprisingly tall for a woman, she owed that to her Bei-Sanian heritage. She was only a bit shorter than Billy and easily met his stare.
"You'll understand soon enough. We're nearly there." Wind roughed Billy's hair as the ship sped up.
"No. You tell me now," the ship was rising.
"It's better if we show you. Most find it unbelievable at first."
"Billy look!" At the sound of his brother's voice Billy turned. He backed away from the silver hair woman, /Suspicion/ thrumming within him.
Over the side of the rail, and ahead of the vessel, Billy could see a create who's size dwarfed any he had ever seen. This was one of the legendary beasts of folk lore, like the Leviathi, it had to be. Nothing else could be so big.
The creature had orange, stony looking skin. Two huge wings held it aloft, and two small claws jutted out from it's body. Along the spine, rose bone white--- teeth like -- spikes.
They rose higher and Billy finally saw the head of the Beast. The head itself was huge, as big as the whales people hunted in Northern Apathasaw. It had a bird like beak which opened horizontally, but he couldn't imagine what the beak was for. Surely a Beast like this didn't feed on regular food.
"Do you see now, why I did not explain?" Mei-Li had moved to join the brothers at the rail, and Billy had been too distracted to see. How could he have been so careless?
Mei-Li waited for a response, but Billy gave only a simple grunt.
"Do they know we're coming," Voshri asked from the front of the vessel.
"I just called your brother," Rakaal said. "He didn't seem please. Not at all. Nor does the council."
"I'll shall handle the council," Mei-Li said. "Did he tell you where to dock?"
Rakaal nodded, which seemed to end the small spat.
Damin hadn't taken notice of it at all. The boy was transfixed by the Beast, and Billy could only imagine the questions that would be in the youth's mind. None of which he could answer.
"I see worry on your face. Suspicion perhaps?" Billy suppressed the surprise in his expression at Mei-Li's guess. "Do not fret, I have guaranteed your safety and freedom. And those of us in the Monastery stand by our vows."
"As long as we agree to join your cult?"
Mei-Li made a small *tsk*, "what will it take to dissuade you of your assumptions? We are not a cult, nor will we take your prisoner. If you wish to leave, your freedom will be arranged for. But I truly believe you should consider our offer. Our purpose is noble."
"Everyone thinks that," Billy said.
"What more noble purpose is there than self improvement?"
Billy saw Damin from the corner of his eye watching the conversation.
"Getting what you're owed, what you deserve. That's what. Life is short. We don't all have time to sit around doing exercises." Billy jerked his thumb towards himself. Mei-Li gave a soft, pitying, smile, a smile that made Billy want to reach out and flood her with the power of /Indignation/.
"We're coming in," Voshri's high pitched voice came from the front of the vessel. They had pulled up near one of the massive spines on the Beast's back. Billy could see that the spines were pocked with holes and arches--- if the pattern had not been so regular it would have been sickly, in fact it still was. Near the top of the spine a series of larger arch ways ringed the spike. As they floated up to the massive arches it was clear each led to some sort of dock. Many of the arches were filled with similar, but not identical, ships to the one Billy and Damin rode.
The empty arch they entered had a metal walk way around the perimeter, half way up. Two men stood together, watching the ship's approach. One had the same mahogany skin tone as Voshri and a circular head of curling hair. The other was a short portly man in flowing navy robes who stood with his hands on his hips.
"They don't look happy..." Voshri said.
"They do not," Rakaal agreed.
The vessel entered the arch and Billy was struck by a sudden sense of warmth.
"Woah, the air, it's so warm..." Billy saw Mei-Li flash a smile at the reaction. It wasn't just warmer, but the whole arched chamber seemed to have a different climate to the air outside. The air was more humid here, and didn't seem to flow out to the colder opening, the way it would in a building in a dessert day.
Dock workers that were previously hidden came out on the catwalk, throwing lines to the vessel which Mei-Li and Voshri caught. Billy pulled Damin back, letting the pair work.
The pair that Billy had spotted over made their way up the catwalk, as a plank was extended to bridge the gap from vessel to catwalk.
"Calkesh!" Voshri hopped down the plank and was swept up in a hug by the mahogany skinned man.
"I'm glad you all made it home safe," the portly man said from the catwalk. Now that he was closer, Billy could see the black curled handlebar moustache and short combed hair the man wore.
"As am I master Avador," Mei-Li tied the final knot off, leaving the vessel in place and suspended by the massive jelly fish above. Avador stepped from the plank and onto the ship. Rakaal gave him a deep bow from the farside of the vessel. Mei-Li bowed too--- with her fists locked against each other ---in a deeper bow than the one Rakaal had given. Avador returned the bow, with the same hand gesture. Billy could see the portly man eying him from the corner of his eye.
"I ain't bowing," Billy spat out a wad of flem onto the deck near Avador's feet.
"I'm sorry about my brother," Damin shot a glance up at Billy that caught the older man off guard. He didn't understand how his brother could be so quick to defend these strangers. He should have experienced enough of the world to know this whole deal was too good to be true.
"It is ok," Billy felt himself shift into Indignation at Avador's beaming smile. The Light within him vibrated, begging to be let out. It was only with great effort that Billy kept himself from exploding in Indignation.
Mei-Li, having seemingly squared the ship away, leaned over to whisper in Avador's ear. Billy's sense opened, his hearing growing sharp with Suspicion.
"Rakaal informed me that the council is aware of our actions, is this true?"
Avador had no visible reaction, but turned to hide his words from the brothers. "I informed them as soon as I knew."
"Why Master?" There was terseness in Mei-Li's voice that betrayed her calm, respectful, words.
"What was your plan child? Show up unannounced and pray the council was no your side? You thought to escape their ire at your expedition by distracting them with outsiders?"
"I- I don't know master." So she was stupid, but Billy knew that already. You had to be stupid to stick your neck out for two strangers.
"Peace child, I informed the council so there was time for their ire to mellow, and so cooler heads may prevail. Deep down, they know our isolationism can't continue. Still they cling. Foolish I think."
Mei-Li nodded her head, "the council will call for an audience then?"
"They already have," Avador replied. "The council is not fond of being made to wait."
"I know master."
:comment:
maybe Billy shouldn't be able to understand this convo
:END:
Mei-Li broke from the huddle to find Billy starting her down. "What's the council, they the big shots around these parts?"
The woman's cheek twitched as she bit her tongue.
"Thou has fine hearing," Avador chuckled, patting the woman on her back. "Very good guess. Big shots... yes, that is correct, I believe."
Avador took a step towards Billy, as his hand twitched down to the six-shooter at this side. He had barely aquired the gun, and he was already becoming reliant on having it at hand. Billy cursed himself for that.
:comment:
Change phrasing of above sentence maybe
:END:
"You foreigners use such strange words, where are you from?"
"Wreathward," Damin said at the same time Billy spoke
"It's none of your business."
Billy poked his foot at this brother's. They had so few cards to play here, any question asked was one more they could use against these people. Even if Damin believed Mei-Li's offer was genuine, there was no telling her far her guarantees could extend in a place like this.
"My, my, yes. Thou hast the correct appearance. But thine accent's are wrong." Avador looked specifically at Damin.
"Why do you need to know?" Billy said
Avador looked past Billy to Damin, placing a soft smile on his lips. "When I was but a child, the world was only the spines of this great beast. As I grew, more and more of thine world was open to my eyes. Yet, we still want for knowledge of all those new peoples."
Billy took a step forward, trying to Damin in his shadow.
"We spent a lot of time in Apathasaw," Damin's reply ellicited a raised eye brow from Avador.
"Tis rare to encounter ones from those yonder lands. Doth thou truly-"
The man's ancient ramblings were cut off by a cough from Mei-Li. She leaned down to whisper in her master's ear. He nodded solemnly before waving Billy and Damin forward.
"The council beckons. We must head the call. Come, come."
Avador gestured the party forward as he swept off the ship in long strides. Billy hesitated, remaining by the railing, as Damin followed the portly man.
"Ladies first," Billy said. He could see the tensing of Mei-Li's jaw as she bit back a reply. Her shoulder bumped into his as she brushed past him. Billy nearly reached out to pull the women back, but let the slight pass with a deep breath.
Avador led them out of the vast chamber and through a heavy wooden door. Like the chamber where the vessel had docked the hall was carved from the the spines of the creature. The low ceilings, and slight discoloration in the material, reminded Billy of stains water would leave on the mining tunnel. Each step the party took echoed through the halls. Billy expected to hear anyone, anything, but got only the echo of their footsteps.
As they walked, Billy could see tunnels going off from the main at seemingly random intervals. Sometimes they would walk for minutes before seeing an off shoot, other times there would such a density of off shoot that Billy wondered how they could navigate such a place.
Slowly, the hall began to slope up as Billy felt themselves climbing up. The climb seemed almost endless as he felt them winding around, and around, and around the spine.
Finally, the party arrived at a pair of metal double doors. Two guards stood to either side. They wore an archaic style of armour, with a metal breast plate and pleated leather skirt. 
* Fragments
** Monastery training
"Revenge. Injustice. All from one moment. In one moment I went from seeing the world the Citadel laid out to the rotten world that really is. It's fueled me since that day, fueled my Indignation, fueled my Resentment."
"You are lucky, Billy. Not everyone has something that powerful, that consistent to drive them."
"You think ANYTHING about that is fucking lucky!? Do you know what fucking happened!?"
"Calm, Billy. This is not the time for training."
"What? This is all some exercise to you people?"
** Nexon Chapter
"You see the thing is about these things, especially ones THIS big, is that they're tougher than us regular Heralds. You can't just walk up to them with a pile of Shell and make their powers go away, and even stabbing them with a Shell spear won't do enough, unless you do it enough times till it looks like a big ol' snake had child with a big ol' porcupine. And that's not really doable, even with all the Time in the world, trust me, I'd know. But the thing about this kid is as a Spacie he's an especially tricky case, cause let's say you're somehow able to get a huge pile of it, he'll sense before it's able to really disable his Heraldry, and he'll just fuck right off. So, we need him to get exposed to a huge amount, without him knowing, until by the time he knows it's too late and his powers are already gone."
Billy nodded.
"And you know what all us boys like, men or beast? A good meal. So we stuff some Shell into several crates full of fishies. It'll take him some time to digest it enough and the Shell really to be exposed to his body, giving us enough time to feed him quite a few. And when he's tasted enough, I'll swim down there and give him a good ass-kickin'."
** Krinosas First Chapter
"I FORGIVE YOU!" Billy's hands shook as he tried to concentrate Light in his hands. "I FORGIVE YOU!"
"Please, PLEASE, LET ME FORGIVE! I LOVE you. So I *must* FORGIVE you! Why is there no Forgiveness in me!?"
The Light energy glowed in Billy's hands, and then he clutched a piece of driftwood, and it grew red. Indignation. He threw the driftwood in the air. It exploded, chips of wood falling around the beach.
"ARGH!" He screamed. "I forgive--,"
Billy caught himself, and swalllowed. His eyes grew red.
"I don't forgive her. She's why we're here."
He looked down.
"I don't forgive him. Or HIM. They're why we're *here*. I still want to kill him! So of course I don't forgive him! I don't even forgive /him/! /He/ should have protected you better! I don't forgive me, *I* should've protected you better! I don't-- I don't-- I don't forgive you..."
He looked back to Damin's dead face. His eyes welled with tears.
"I don't forgive y-you. I-- don't-- I don't--"
"Oh-- I don't forgive you! I DON'T FORGIVE YOU!"
Billy collapsed over Damin. His tears soaked into the boy's shirt, and his palms grew white clutching it, but not from any Light.
** Tregale Excerpts
*** Thoughts on the capabilities and purpose of humanity
Filip and Hlith'ei have falsely characterized my philosophy as arrogant, esoteric, and selfish. This is a strawman; I am the only one in this multilectic that simultaneously holds a /humble/ view of myself and humanity, while also one that is not self-serving. For there is no higher arrogance and selfishness than to falsely perceive oneself as the ultimate end, as the destiny of reality that should and will by necessity be maintained-- what is the purpose of any dialogue if we assume we are the highest end to be conserved? Neither is my philosophy /esoteric/, for my philosophy transcends the being of humanity to universal being, and what could be more esoteric than to cordone off truth and the volition of our consciousness to the humans of our contemporary era? Neither do I /debase/ humanity, as we are a /necessary/ step, the currently highest example of a conduit seen in being: I acknowledge we are of the highest complexity, second to possibly the so-called /Beasts/ which torment us, but they are too /unique/ to be sustainable conduits; it is our apex of complexity and consciousness that gives us the duty to be this conduit to further complexity, for it is absurd that we ask of plants or pigs to be this conduit, but it is also absurd, arrogant and selfish if we, the only ones capable of this conduit, instead of performing our duty, decide that we are not a conduit, even though all that has came before us served its duty in leading to us as conduits; we decide instead to cut off every conduit and instead rest in our self-satisfaction and comfort: what could be more arrogant and selfish than this!

For I now theorize, after witnessing some of Filip and Rosthand's discoveries and recordings of the taxonomical kind, that there are potential conduits which have been cut off, and really been end-nodes. And that is what lies before us if we do not act. For it is the order of /increasing complexity/ that unites the progression of conduits generally (the conduits that form a conduit-series), but that complexity is not of uniform nature-- humanity has been given /specific/ properties that are required to create a true conduit beyond humanity, namely, imagination, a mode inside universal being that yet transcends and manifests being-- it is simultaneously /being-as-it-is/ in its initial act of imagination, /being-becoming/, in that gives way to /another/ conduit of being that it is not, and /being-negated/ as the imagination of the being is not the same being it is imagining just as a painting of a lily is not a lily. It is only because imagination simultaneously operates these three modes of being that seem on the surface contradictory that imagination can serve its purpose as a conduit /beyond/ humanity, a conduit /beyond/ itself and abstraction, yet higher than non-abstraction, or what we call /material being./ Some may say that the true specific property gifted to humanity is /abstraction/, and while it is one, it is before and lesser than imagination; for abstraction cannot be the tool which humanity uses to fulfill their duty as a conduit, for all it can do, at least alone, is simplify, reduce, and create beings in the mind. It is only imagination-- or should I say, the /condui of imagination/-- that can lead to being a conduit in the sense of being, the conduit that is necessary to go beyond humanity. The property of imagination itself also has its own conduit, and this conduit may begin with abstraction, and we are at the beginning of imagination's conduit; we have a /fetus of imagination/. If we suspend the question of abstraction's role in imagiantion by saying that abstraction is /i0/ in the conduit-series /i/, and this /fetus of imagination/ is /

But even our gods

Perhaps soon Ivopp or Filip or even Samson through pure observation will discover that
