#+title: Okin
* Chapter I
"...and instill your Bravery in each of these men's hearts, every one, especially those of your Light, so that none may be deterred either by fickle emotions or the Vices of the One and the Five."
The square-faced man took a pause from his whispers. The flame sung a rhythym under his breathe. He remained still, hunched over with his arms raised in a reverent kneel in the corner of the room.
"And if I may ask again, that you may instill that same Bravery into my heart, not for my achievement, nay, but for my Arising to you."
His golden draped silk sleeves lowered from their raised position until his arms were clasped against his chest. His left index finger traced an invisible line over the back of his right palm, connecting to a line of golden paint already there.
"Bravery", he said under his breathe.
He raised his finger and brought it back in place to repeat the motion.
"Bravery."
Again, and again.
*SLAM!* The door, feet from him, smashed against the wall. The square-faced man jumped. He swung around, arms raised in an awkward stance, barely intelligible that it was one of defense.
They lowered, along with his wide eyes, as he noticed his intruder. From a violent shake, his body gradually stilled.
"Devinar Previa!" he said. "What is the meaning of this?!"
"S-sorry, Okin," an adolescent, crooked smile and slight blush appeared on Previa's face.
Okin shook his head. "I know your father taught you not to disturb a man during his prayers. So I must conclude that this is just carelessness on your part. And that's ATHAR Okin to you."
Previa rolled his eyes. "Since Krusadar Caldro is gone, I was more focused on maintaining the chain of command," he said. "You know me, it's hard to focus on more than one thing to remember at a time... and there's something much more important to remember than that."
Okin raised an eyebrow.
"Maldin tracked the Farsunni who captured Islovol's squad. We're gonna get 'em back!"
Okin's eyes narrowed on Previa. Something inside him was always poked by the young man's childish declarations.
"That is Caldro's decision to make."
Previa looked at Okin with wide eyes. "They'll be killed by then!"
Okin's stare didn't flinch. "As much as it pains both you and me, if they wanted to kill them, they'd be dead by now."
Previa shook his head. He turned away and opened the door again. "Every second we wait, is a second they're more likely to be killed by those monstrous heretics. What if you're saying that, and they're still alive, then their blood is on our hands!"
Previa turned back to Okin. "Isn't it in Bravery that we risk our lives to save those that need us?"
Okin's lips pursed. His harsh stare softened, and his shoulders shrunk. *Bravery.* He felt his finger against the back of his hand again. His gaze fell from Previa's eyes. *Bravery. Bravery.*
"No." Okin's sternness returned to him. "It is in Temperance and Truth that remain patient, that we get more information about the Farsunni outpost, and most importantly that we follow the orders of Krusadar Caldro to remain on the defensive."
Previa turned and ran like a petulant child, the door sputtering shut on his way out.
"Previa!" Okin shouted after him. He strut through the doorway and turned into the hallway. Previa was quick, and Okin just made out the end of the young man's leather boots turning down one of the fortress' stone brick hallways ahead.
Okin looked down to his unathletic rounders. He grit his teeth and made off, his awkward, intense strides being made by the softness of his rounders and flowing Athar's robes made him look comedic, and he knew it, but he had to catch Previa.
As Okin turned down the hallway Previa had, the young man was nowhere in sight, his footsteps could be heard in the distance but the echo diminished. Still, Okin kept running, he knew where Previa was headed.
A load of heavy breathes and a forehead of sweat later, it was Okin's turn to burst through a wooden door. Before even shoulder-checking it open, he could hear the clank of iron boots being fastened and swords being sharpened.
*THUD.* He burst through, before instantly grasping his forearm in pain. However, he was given no attention, the few dozen soldiers scattered around the benches were focused on hastily equipping their armor, and clammoring with a mess of different chants.
He was shoved aside by an armed soldier already leaving the barracks.
His eyes urgently danced around the room for Previa. The young soldier had armor like an alien quartz statue, shimmering with an austere beauty. It was not painted steel, but a material of its own, like a glowing pearl.
The row of soldiers marching out past him, the clanging of the iron boots, made Okin and shrink. He snapped at himself for his Cowardice, and straightened his posture before marching up to Previa.
"Stop them!" Okin shouted. Even with the commotion, he knew Previa heard him, though it was easy for the young soldier to pretend that he didn't with his visor totally hiding his face, and towering armor supporting it a whole head over Okin.
"I thought you said you wished to maintain the chain of command! I command you to stop them!" Okin got up next to Previa's shoulder and shouted upwards.
Previa turned, his blue eyes just barely visible as he stared down at Okin between the white visor. "And you always tell me that all men are truly ruled by the Four, and should be guided by their Virtues. So I am doing just that."
Previa fully turned and hilted his long steel sword. He tilted his head up so his eyes were gone, and again he was like a magnificent white statue. He took a step forward that shook the ground. Technically, maybe, Okin could keep standing in his way; Previa was the one going against command, and it would be a true crime to attack Okin, and Okin knew that though the adolescent was brash. But he could not do it, his instincts took over to step aside and let the moving white tower thunder past him.
After Previa had noticeably left the room, the rest of the men who were still inside the barracks rushed themselves and each other to follw him, clumsily putting on boots or still having their helmets tucked under their arms. Okin should've stopped them, he had the authority to, but was frozen, and could only let out small utterances.
He followed them out, stuck in between two armored men; he knew, on paper, they knew who he was, his Athar's robes told them that, and he had even counseled them before, but now they were locked into war, and he was just an object to get past. The collosal raindrops of their pounding boots drowned out his thinking; he didn't really know what he was doing, just that he had to do SOMETHING.
After turning down another hall dimly lit by torches, the white stream of the world burst onto him. Three hallways met upon a masssive iron door which had been pulled open, through which the stream of soldiers marched out of.
As he ran through, the soldiers behind him swarming past, Okin scrunched his nose at the kiss of the hot air. The soldiers climbed atop their horses, those who were ahead circled or doubled back and forth to channel the energy they were amping up. Okin looked around for an empty horse, but it seemed that just as he thought one was unreserved, it was taken. Finally, he just ran up to the group of trotting mounting soldiers. As he approached, their walks became more ordered, until they were totally circling around one figure in the middle, and it felt like a defensive shell against Okin. The figure in the middle was that white obelisk glimmering under the bloody morning sun, the mounted Previa.
Previa raised his fist. Okin froze, and the circle opened on the opposite side of the Athar, and Previa's horse trotted out ahead before stopping, the rest of the circle curving to line up behind him. Once they had, he turned his horse back to the squadron. He opened his visor, revealing his thin but energetic face, and raised his armored fist again.
"The energy in the barracks has been morose. We came here to FIGHT Darkness in strength in the open promise we made to The Citadel as Devinars, not slowly watch our friends die and be captured and hear that they burned down another village of our faithful, and capture our brothers, many of who you have been mourning. But-- you have mourned falsely. They are not dead. Now, here, is our chance to fulfill our promise! Open your visors, brothers! Let me see your smiles, let me see your passion!"
The men howled, and most followed and opened their visors. Okin understood the passion. Many of them had been dissappointed by the brutal, yet slow pace of the war; instead of glorious battles, it was characterized by ugly raids, by strategically sound but dishonorable uses of attrition. And though the enemy teased them by setting camps a mere ride from their bases, the message from high command was always to hunker down, prepare, and play the long game. But here, standing with his sword raised, was an opportunity for these young men to earn the glory they came here for.
"When you draw your sword today, men of Nexon, let me see your Joy! Men of Olitheon, show me your Sacrifice! Men of Intillia, show me your Discipline! Men of Aredal, show me your Bravery!"
Their swords sprung from their hilts, and their passion sprung from their hearts. Even though Okin was trying, in vain, to stop this, the strong summoning of brotherhood gave him, as it would any man, the urge to support this valiant effort, even when Okin knew it came from an otherwise forgetful, foolish boy-- in that white armor, on that horse, that boy was gone. A soldier, a leader remained.
"This is not some dishonorable raid, some backhanded pillage like those animals did to the innocent towns on our front! It is snatching our loyal brothers from the venomous jaws of Darkness! And if you are here to fight for your brothers, then RIDE WITH ME!"
Previa raised his sword again. The rest of the men did in unison.
"VIR VERSALIS!" The men shouted. "VIR CITADEL! VIR VOUR!"
"CHARGE!" The men hilted their weapons, then screamed and whipped their horses into a sprint. Previa raised his sword even higher to the sky.
Okin was thrust out of the moment-- he was here to stop this. But it seemed his chances were charging away towards the enemy camp.
"Previa!" Okin shouted with his whole body just as the white-armored soldier had finally hilted his sword to join the rest of his charging army.
Previa stopped just as he was about to whip the reins of his horse. He turned around just as Okin ran up to his saddle-side.
"Okin?" Previa stopped and pulled up his visor. His face was mired with geniune concern and shock. "Get back in the bunker!"
"You have to stop them, Previa!"
Okin looked like a child next to the mounted Previa. Though Okin was almost a decade older than Previa, Previa stared down at him like a concern adult to a lost child.
"Even if I wanted to, it's too late. They would fight on even if the Mouth of the Gods showed up to stop them," Previa sighed. "But you do not want to be here when the enemies' riders and Portalers chase us to try to get their prisoners back."
"Previa--"
"Go inside, Okin. I'll see you later."
Previa turned back to his charging army, and made off.


"Unacceptable!"
The mustached man's meaty hands slammed down on the stone table.
"But Krusadar, what I'm saying is right! We got Islovol's squad back, all alive! The mission was a success--"
"Did your mother make you out of dirt? That's the not the point! You disobeyed orders!"
"To save lives--"
"Do not speak over me, Devinar Previa!" The Krusadar rose to his feet. "You saved no lives. The Farsunni thought your attack was just the start of a proper raid, and sent out an entire company after you killed the original pursuit. To ensure that the entire front wasn't destroyed, the neighboring forts had to send out nearly half their men. We're now waiting on reinforcements as far back as Klivor, and there will be much more casualities than anticipated," the Krusadar's thick eyebrows stared down harshly at Previa, who looked down in embarassment. "You might've saved a handful of men, but you've doomed thousands."
Previa's hands clapsed the bottom of the wooden chair, and he rocked back in forth in it, his eyes glancing around to the drawn maps of the region on the walls, desperately avoiding the Krusadar's harsh, continuous stare.
"Now you, Athar," he turned to Okin. "I put you in charge of the men, despite your lack of military experience, as I wanted someone higher than a Devinar to be my substitute. I saw how the men respected your character. I hate to be wrong, but I was, wasn't I?"
Okin looked down. "You are right. I tried to bring order, but it was my lack of character that got in the way."
"Honest as ever, even when it hurts you," the Krusadar paused, his large hands clasped just under his wide chin. "But I cannot respect your lack of authority when I put you in charge."
"You are both hereby dismissed as acting service members of the Versalist military. Athar Okin, as we are equals, and as I assigned you to a post of which you would not normally be expected, you are merely released to go back to your regular town cycle or to return to The Citadel or another center for reassignment. Devinar Previa, as you were the instigator of this unauthorized assault, as your commanding officer I am issuing a discharge and a description of this incident will be added to your permanent record. Any questions?"
Previa's head hung low. Okin just shook his head.
"Good. Now get out of my sight."


Okin stared out over the horizon which stretched across over the sandy mountains, where a light breeze created a pleasant translucent curtain of sand, the red sun comfortably veiled by both the curtain and its seat between two mountains. He appreciated the natural beauty of all lands he came across, and always thought to how each of the Four contributed. All gave an equally necessary contribution, but some he had an easier time than others understanding; Intillia brought both the earth, and the waters, and the gasses and winds in the sky; Aredal brought the Light for all living things to see by, through which this view would otherwise be impossible, and by it the heat which allows all living things to survive, and according to some of the newer Istars apparently, also the sustenance for plants; Olitheon, he could somewhat understand, brought the actual area where all things are, even the stars, but not the actual objects itself, those were still Intillia and Aredal. Him and Nexon brought many other things that were quite confusing. Okin tried to comprehend it abstractly on his own time, and even ask Istars he met in the natural sciences, though it made him uncomfortable, but still, he could not really comprehend it. Still, he trusted it and felt it in his prayers, which was what was most important.
"I'm sorry Okin."
Previa interrupted Okin's tranquil observation, and brought him immeadiately back to his current air of disdain. Okin turned around and continued heading forward with Previa up the hill.
"That's Athar Okin to you."
Previa raised his hands, "Oh come on, Okin, we've known each other since we were kids--"
"That's Athar Okin to you," Okin's voice sunk like a swamp.
"Okay, okay, ATHAR Okin," Previa said. "So, uh, now that this all over, what's next for ATHAR Okin?"
Previa looked to Okin with the open eyes of a puppy. Okin ignored him.
"Come on, I know you have some plan in that big, meticulous brain of yours."
Okin's glare snapped onto Previa.
"This isn't nothing, Previa. I came here for a reason. To force myself to really JUMP into Bravery."
"You didn't come here to help the Citadel spread the holiness of the Four against the corruption of the Farsunni heretics?"
Okin glared at Previa. Previa gave a sheepish smile, before sighing.
"This was important to me, too. This was a chance for me to grow in Bravery, and Temperance, too. I know how you feel."
Okin's glare softened. He waited for Previa to hoist himself upwards into the cart. Previa offered Okin a hand, but by then Okin was already himself getting into the cart, and he didn't take it.
Previa collapsed against the side of the cart, and rested his cheek on his arm which he rested on the side of the cart. The cart bumped up and down against the cobbly road, and the young Devinar just let his face slide into his hand like melting wood.
"Well, if you have to know, I'm going to the Citadel. Probably to see Impalias Aldwin."
Previa sighed again. He stretched his arms and readjusted so his arms provided a cushion for his back against the cart.
"Yeah, I think I'm gonna have to go see dad too."
Okin stared away from Previa, outside the cart. His eyes drifted, not on any of the dry yellow countryside, but past it. His mind was on what the future could hold, but it was just soft, meaningless impressions.
He raised the back of his hand into his gaze. The singular golden stroke shone in the Light. *Truth.*
He stretched his other index finger against it. He drew out an invisible stroke, coming out from the other golden stroke. *Bravery*, he said to himself.
He drew the stroke again, keeping his finger on it even as the cart jumped upwards and his whole body shook.
*Bravery.*
* Chapter II
