#+title: Okin
:generalnotes:

:END:
* Chapter I
:chapterOneNotes:
Explain Farsun earlier. Probably around the first mention, so the reader understand the context of the war and the front.
:END:
"...and instill your Bravery in each of these men's hearts, every one, especially those of your Light, so that none may be deterred either by fickle emotions or the Vices of the One and the Five."
The square-faced man took a pause from his whispers. The flame sang a rhythym under his breathe. He remained hunched over with his arms raised in a reverent kneel in the corner of the room. His palms shouted to the ceiling above.
"And if I may ask again, that you may instill that same Bravery into my heart, not for my achievement, nay, but for my Arising to you."
His golden silk sleeves lowered from their raised position until his arms were clasped against his chest. His left index finger traced an invisible line over the back of his right palm, connecting to a line of golden paint already there.
"Bravery", he said under his breathe.
He raised his finger and brought it back in place to repeat the motion.
"Bravery."
Again, and again.
*SLAM!* The door, feet from him, smashed against the wall. The square-faced man jumped. He swung around. He raised his arms in an awkward stance; it barely intelligible that it was a defensive one.
:question:
where is Okin? is he in a small prayer chamber in the fortress?
:END:
They lowered, along with his wide eyes, as he noticed his intruder. From a violent shake, his body gradually stilled.
"Devinar Previa!" he said. "What is the meaning of this?!"
"S-sorry, Okin," an adolescent, crooked smile and slight blush appeared on Previa's face.
Okin shook his head. "I know your father taught you not to disturb a man during his prayers. So I must conclude that this is just carelessness on your part. And that's ATHAR Okin to you."
Previa rolled his eyes. "Since Krusadar Caldro is gone, I was more focused on maintaining the chain of command," he said. "You know me, it's hard to focus on more than one thing to remember at a time... and there's something much more important to remember than that."
Okin raised an eyebrow.
:comment:
maybe explain Previa and Okin's relationship a bit here. Call Previa a childhood friend or someting
:END:
"Maldin tracked the Farsunni who captured Islovol's squad. We're gonna get 'em back!" Previa's eyes lit up.
Okin's eyes narrowed on Previa. The young man's childish declarations always poked something inside him.
"That is Krusadar Caldro's decision to make," Okin replied. He turned back to the candlelit corner, even though he knew that it wouldn't be the end of the conversation.
Previa looked at the back of Okin's head with wide eyes. He stepped to the right so his shout was basically in Okin's ear. "They'll be killed by then!"
Okin's stare didn't flinch from the light in the corner. "As much as it pains both you and me, if they wanted to kill them, they'd be dead by now."
Previa shook his head. He turned away and opened the door again. "Every second we wait, is a second they're more likely to be killed by those monstrous heretics. If you're saying that, and they're still alive, then their blood is on our hands!"
Previa turned back to Okin. "Isn't it in Bravery that we risk our lives to save those that need us?"
Okin's lips pursed. His harsh stare softened, and his shoulders shrunk. *Bravery.* He felt his finger against the back of his hand again. *Bravery. Bravery.*
"No." Okin's sternness returned to him. "It is in Temperance and Truth that remain patient, that we get more information about the Farsunni outpost, and most importantly that we follow the orders of Krusadar Caldro to remain on the defensive."
Previa turned and ran like a petulant child, the door sputtering shut on his way out.
"Previa!" Okin shouted chasing his friend out the door and into the hallway. Previa was quick, and Okin just made out the end of the young man's leather boots turning down one of the fortress' stone brick hallways ahead.
Okin looked down to his unathletic rounders. He grit his teeth and made off, his awkward, intense strides being made by the softness of his rounders and flowing Athar's robes made him look comedic, and he knew it, but he had to catch Previa.
:comment:
Not sure what a rounder is, a shoe type?
:END:
As Okin turned down the hallway Previa had, the young man was nowhere in sight. His footsteps could be heard in the distance but the echo diminished. Still, Okin kept running, he knew where Previa was headed.
The Ather passed out from the stone halls into the fortress' central courtyard. Devinars in polished armour spared with each other or ran drills. Okin heard his name called in greeting as he passed. He gave the voices a slight nod as he tried to keep pace.
Previa had disappeared in the crowd, but Okin didn't need to see him. He passed through an arch way at the opposite end of the courtyard sprinting into the barracks. He passed the Krusadar's private rooms and the Devinar's dormitories. Pass the officer's mess and towards the armory used by Caldro's unit.
Okin's burst through the wooden door. Before even shoulder-checking it open, he could hear the clank of iron boots being fastened and swords being sharpened.
*THUD.* He burst through, before instantly grasping his forearm in pain. However, he was given no attention, the few dozen soldiers scattered around the benches were focused on hastily equipping their armor, and clammoring with a mess of different chants.
He was shoved aside by an armed soldier already leaving the barracks.
His eyes urgently danced around the room for Previa. The young soldier had armor like an alien quartz statue, shimmering with an austere beauty. It was not painted steel, but a material of its own, like a glowing pearl.
The row of soldiers marching out past him, the clanging of the iron boots, made Okin and shrink. He snapped at himself for his Cowardice, and straightened his posture before marching up to Previa.
"Stop them!" Okin shouted. Even with the commotion, he knew Previa heard him, though it was easy for the young soldier to pretend that he didn't with his visor totally hiding his face, and towering armor supporting it a whole head over Okin.
"I thought you said you wished to maintain the chain of command! I command you to stop them!" Okin got up next to Previa's shoulder and shouted upwards.
Previa turned, his blue eyes just barely visible as he stared down at Okin between the white visor. "And you always tell me that all men are truly ruled by the Four, and should be guided by their Virtues. So I am doing just that."
Previa fully turned and hilted his long steel sword. He tilted his head up so his eyes were gone, and again he was like a magnificent white statue. He took a step forward that shook the ground. Technically, maybe, Okin could keep standing in his way; Previa was the one going against command, and it would be a true crime to attack Okin, and Okin knew that though the adolescent was brash. But he could not do it, his instincts took over to step aside and let the moving white tower thunder past him.
After Previa had noticeably left the room, the rest of the men who were still inside the barracks rushed themselves and each other to follw him, clumsily putting on boots or still having their helmets tucked under their arms. Okin should've stopped them, he had the authority to, but was frozen, and could only let out small utterances.
He followed them out, stuck in between two armored men; he knew, on paper, they knew who he was, his Athar's robes told them that, and he had even counseled them before, but now they were locked into war, and he was just an object to get past. The collosal raindrops of their pounding boots drowned out his thinking; he didn't really know what he was doing, just that he had to do SOMETHING.
After turning down another hall dimly lit by torches, the white stream of the world burst onto him. Three hallways met upon a masssive iron door which had been pulled open, through which the stream of soldiers marched out of.
As he ran through, the soldiers behind him swarming past, Okin scrunched his nose at the kiss of the hot air. The soldiers climbed atop their horses, those who were ahead circled or doubled back and forth to channel the energy they were amping up. Okin looked around for an empty horse, but it seemed that just as he thought one was unreserved, it was taken. Finally, he just ran up to the group of trotting mounting soldiers. As he approached, their walks became more ordered, until they were totally circling around one figure in the middle, and it felt like a defensive shell against Okin. The figure in the middle was that white obelisk glimmering under the bloody morning sun, the mounted Previa.
Previa raised his fist. Okin froze, and the circle opened on the opposite side of the Athar, and Previa's horse trotted out ahead before stopping, the rest of the circle curving to line up behind him. Once they had, he turned his horse back to the squadron. He opened his visor, revealing his thin but energetic face, and raised his armored fist again.
"The energy in the barracks has been morose. We came here to FIGHT Darkness in strength in the open promise we made to The Citadel as Devinars, not slowly watch our friends die and be captured and hear that they burned down another village of our faithful, and capture our brothers, many of who you have been mourning. But-- you have mourned falsely. They are not dead. Now, here, is our chance to fulfill our promise! Open your visors, brothers! Let me see your smiles, let me see your passion!"
The men howled, and most followed and opened their visors. Okin understood the passion. Many of them had been dissappointed by the brutal, yet slow pace of the war; instead of glorious battles, it was characterized by ugly raids, by strategically sound but dishonorable uses of attrition. And though the enemy teased them by setting camps a mere ride from their bases, the message from high command was always to hunker down, prepare, and play the long game. But here, standing with his sword raised, was an opportunity for these young men to earn the glory they came here for.
"When you draw your sword today, men of Nexon, let me see your Joy! Men of Olitheon, show me your Sacrifice! Men of Intillia, show me your Discipline! Men of Aredal, show me your Bravery!"
Their swords sprung from their hilts, and their passion sprung from their hearts. Even though Okin was trying, in vain, to stop this, the strong summoning of brotherhood gave him, as it would any man, the urge to support this valiant effort, even when Okin knew it came from an otherwise forgetful, foolish boy-- in that white armor, on that horse, that boy was gone. A soldier, a leader remained.
"This is not some dishonorable raid, some backhanded pillage like those animals did to the innocent towns on our front! It is snatching our loyal brothers from the venomous jaws of Darkness! And if you are here to fight for your brothers, then RIDE WITH ME!"
Previa raised his sword again. The rest of the men did in unison.
"VIR VERSALIS!" The men shouted. "VIR CITADEL! VIR VOUR!"
"CHARGE!" The men hilted their weapons, then screamed and whipped their horses into a sprint. Previa raised his sword even higher to the sky.
Okin was thrust out of the moment-- he was here to stop this. But it seemed his chances were charging away towards the enemy camp.
:comment:
probably establish where the enemy camp is in relation. And they probably wouldn't charge from so close. Depends on the distance to enemy camp.
:END:
"Previa!" Okin shouted with his whole body just as the white-armored soldier had finally hilted his sword to join the rest of his charging army.
Previa stopped just as he was about to whip the reins of his horse. He turned around just as Okin ran up to his saddle-side.
"Okin?" Previa stopped and pulled up his visor. His face was mired with geniune concern and shock. "Get back in the bunker!"
"You have to stop them, Previa!"
Okin looked like a child next to the mounted Previa. Though Okin was almost a decade older than Previa, Previa stared down at him like a concern adult to a lost child.
"Even if I wanted to, it's too late. They would fight on even if the Mouth of the Gods showed up to stop them," Previa sighed. "But you do not want to be here when the enemies' riders and Portalers chase us to try to get their prisoners back."
"Previa--"
"Go inside, Okin. I'll see you later."
Okin stared at Previa. Part of him wanted to jump on the back of Previa's horse, or run back in and grab some gear. But then he looked down at what he was wearing, and his shivering body, and by the time he looked up again, Previa had already turned back to his charging army, and made off.


"Unacceptable!"
The mustached man's meaty hands slammed down on the stone table.
"But Krusadar, what I'm saying is right! We got Islovol's squad back, all alive! The mission was a success--"
"Did your mother make you out of dirt? That's the not the point! You disobeyed orders!"
"To save lives--"
"Do not speak over me, Devinar Previa!" The Krusadar rose to his feet. "You saved no lives. The Farsunni thought your attack was just the start of a proper raid, and sent out an entire company after you killed the original pursuit. To ensure that the entire front wasn't destroyed, the neighboring forts had to send out nearly half their men. We're now waiting on reinforcements as far back as Klivor, and there will be much more casualities than anticipated," the Krusadar's thick eyebrows stared down harshly at Previa, who looked down in embarassment. "You might've saved a handful of men, but you've doomed thousands."
Previa's hands clapsed the bottom of the wooden chair, and he rocked back in forth in it, his eyes glancing around to the drawn maps of the region on the walls, desperately avoiding the Krusadar's harsh, continuous stare.
"Now you, Athar," he turned to Okin. "I put you in charge of the men, despite your lack of military experience, as I wanted someone higher than a Devinar to be my substitute. I saw how the men respected your character. I hate to be wrong, but I was, wasn't I?"
Okin looked down. "You are right. I tried to bring order, but it was my lack of character that got in the way."
"Honest as ever, even when it hurts you," the Krusadar paused, his large hands clasped just under his wide chin. "But I cannot respect your lack of authority when I put you in charge."
"You are both hereby dismissed as acting service members of the Versalist military. Athar Okin, as we are equals, and as I assigned you to a post of which you would not normally be expected, you are merely released to go back to your regular town cycle or to return to The Citadel for reassignment. Devinar Previa, as you were the instigator of this unauthorized assault, as your commanding officer I am issuing a discharge and a description of this incident will be added to your permanent record. Any questions?"
Previa's head hung low. Okin just shook his head.
"Good. Now get out of my sight."


Okin stared out over the horizon which stretched across over the sandy mountains, where a light breeze created a pleasant translucent curtain of sand, the red sun comfortably veiled by both the curtain and its seat between two mountains. He appreciated the natural beauty of all lands he came across, and always thought to how each of the Four contributed. All gave an equally necessary contribution, but some he had an easier time than others understanding. Intillia brought both the earth, and the waters, and the gasses and winds in the sky; Aredal brought the Light for all living things to see by, through which this view would otherwise be impossible, and by it the heat which allows all living things to survive, and according to some of the newer Istars apparently, also the sustenance for plants; Olitheon, he could somewhat understand, brought the actual area where all things are, even the stars, but not the actual objects itself, those were still Intillia and Aredal. Him and Nexon brought many other things that were quite confusing. Okin tried to comprehend it abstractly on his own. He had even asked Istars in the natural sciences he met, though it made him uncomfortable, but still, he could not really comprehend it. Still, he trusted it and felt it in his prayers, which was what was most important.
:comment:
Is he uncomfortable because he is asking women?"
:END:
"I'm sorry Okin."
Previa interrupted Okin's tranquil observation, and brought him immeadiately back to his current air of disdain. Okin turned around and continued heading forward with Previa up the hill.
:comment:
They should probably be in carriage here or on horse back. Also, maybe it makes sense for them to travel with some baggage. Maybe mail? Or for them to take a space network trip back so we can establish the space network.
:END:
"That's Athar Okin to you."
Previa raised his hands, "Oh come on, Okin, we've known each other since we were kids--"
"That's Athar Okin to you," Okin's voice sunk like a swamp.
"Okay, okay, ATHAR Okin," Previa said. "So, uh, now that this all over, what's next for ATHAR Okin?"
Previa looked to Okin with the open eyes of a puppy. Okin ignored him.
"Come on, I know you have some plan in that big, meticulous brain of yours."
Okin's glare snapped onto Previa.
"This isn't nothing, Previa. I came here for a reason. To force myself to really JUMP into Bravery."
"You didn't come here to help the Citadel spread the holiness of the Four against the Corruption of the Farsunni heretics?"
Okin glared at Previa. Previa gave a sheepish smile, before sighing.
"This was important to me, too. This was a chance for me to grow in Bravery, and Temperance, too. I know how you feel."
Okin's glare softened. He waited for Previa to hoist himself upwards into the cart. Previa offered Okin a hand, but by then Okin was already himself getting into the cart, and he didn't take it.
:description:
Add some description here about the cart starting to move after they get it. Right now its a bit confusing
:END:
Previa collapsed against the side of the cart, and rested his cheek on his arm which he rested on the side of the cart. The cart bumped up and down against the cobbly road, and the young Devinar just let his face slide into his hand like melting wood.
"Well, if you have to know, I'm going to the Citadel. Probably to see Impalias Aldwin."
Previa sighed again. He stretched his arms and readjusted so his arms provided a cushion for his back against the cart.
"Yeah, I think I'm gonna have to go see dad too."
:style:
I feel like Previa would say father
:END:
Okin stared away from Previa, outside the cart. His eyes drifted, not on any of the dry yellow countryside, but past it. His mind was on what the future could hold, but it was just soft, meaningless impressions.
He raised the back of his hand into his gaze. The singular golden stroke shone in the Light. *Truth.*
He stretched his other index finger against it. He drew out an invisible stroke, coming out from the other golden stroke. *Bravery*, he said to himself.
He drew the stroke again, keeping his finger on it even as the cart jumped upwards and his whole body shook.
*Bravery.*
* Chapter II
** Notes
- maybe change the intro as Previa should be wearing the armor
- maybe they should have squire-like Infantis assistants
- unit of measurement mentioned, right now feet
- Neiman mentioned
** Chapter
"Impalias Aldwin," Previa said. He bit his lip till it formed like a parted wave, and his eyelids covered his irises in a bored expression. "You know, *Impalias.* There's only like ten of them."
"Yeah, exactly, I know, *Impalias*," the bearded man shot back. "But for what reason on Opartha would a kid like you need an Impalias for? Or better yet, why would an Impalias take their precious time to meet with a kid like you?"
:comment:
Establish where they are at the start of the chapter. And some indication of who the breaded guy is.
Give time that it took them to travel to the citadel
:END:
"It's not for clerical duties, Virtues, or anything of the sort," Okin stepped in, already feeling enough embarrassment from Previa. "It's a personal matter. We know Impalias Aldwin personally."
"He's my father," Previa scratched the back of his neck and smiled sheepishly. The bearded man gave an unimpressed nod, and Okin scowled.
"Oh. Well, regardless, I don't really have anything to give you beside the common knowledge that the Impaliases spend most their time near the center of The Citadel," the mustached man grunted.
"Oh," Previa's smile faded. "Well, thank you anyway, and may the Four bless you."
"Four bless you too," the man said plainly before strutting away.
"Ugh," Previa shook his head. "Made myself look like an idiot, and I still have to have all this anxiety as we wait to find him. Of course some random Rothar wouldn't know where we dad is."
"Temperance, Previa, Temperance," Okin said.
"You know, it's not that I'm impatient, it's just that it's like-- it's basically like what's happening right now is the same as when I was a kid," Previa blushed, "...coming home to dad after getting in trouble."
Previa glanced to Okin, checking to see if his friend related, but Okin gave away nothing.
"Oh come on, don't tell me you never got into trouble as a kid? I mean come on, you weren't *that* stuck up and perfect, Okin," Previa raised an eyebrow at his own question, and then leaned closer to Okin. "You weren't, right?"
Okin just bit his lip.
"I coulda sworn I saw you got in trouble with one of the Istars," Previa rubbed his chin. "Yeah."
A slight smile appeared on Okin's face. "Your memory is better than I expected, Previa."
Previa matched Okin's smile with a toothy grin. "I knew it! I told Vashod you were one of us!"
Previa gave Okin a friendly slap on the shoulder, and Okin's smile faded. Previa chuckled a bit more, and Okin let it fade off into awkward silence between them, as the bustling of The Citadel to fill their ears. Okin and Previa both glanced around for a while. Though he was by no means a listless slacker, and Previa, though less conscientious, was definitely more filled with actual energy which caused a certain form of industriousness, Okin was surprised and with the Citadelian's sureness of movement, in a sea of other men, inches away from them, all on their own path and mission, they just stared straight ahead as if they were the only ones in existence. It reminded Okin of the preoccupation of wild animals, and in that way, it made the people feel less human, and though definitely more alive in some senses, less in others.
:question:
I don't understand what exactly you're trying to convey here. Is it just the hustle and bustle and energy of the city?
:END:
Okin cleared his throat before turning back to Previa and continuing. "But I liked your attitude on our trip here more than this distracted nostalgia. Now is a time to learn from what happened and look ahead, regardless of your feelings of shame."
Previa's lips pursed, and then he nodded. Okin often debated with himself whether Previa really took his advice to heart as best as he could and mostly suffered due to his own undisciplined nature, or if the lad just wanted Okin to like him and thus just tried to appear as if he was processing things.
"Good advice, Okin," Previa said, but his focus was obviously on something else. Okin peeked over the young man's shoulder and saw what he was staring at-- a market stand where some young dough-faced boys were being handed a large, thick yellow pastry covered with thick sugars on the top.
"Well, you never said how far I should look ahead, and looking ahead about thirty feet, I see something very tasty--"
Okin sighed and shook his head. "Go ahead, Previa."
Previa smiled and ran forward a few steps, before turning back to Okin. "You want any?" he asked.
Okin shook his head no. "Temperance requires especially that times of personal dissappointment are not met with indulgence but with quiet, even uncomfortable, introspection."
Previa looked up in thought, and then took a step back. "You're right, I won't have any."
"No, no," Okin looked down. "I'm sorry, Previa. I'm probably coming off as a stickler. I didn't mean you shouldn't have one."
Previa's lips pursed. "Yeah, but, I feel bad having one if you don't. What about, I just get one, and we split it. It'll still cause me to do like, that introspection, 'cause normally I'd probably have-- well, two."
Okin laughed and shook his head again. "Oh, alright," he said.
Previa ran to the stand, excitedly exchanged some coins for the pastry, split it in half and handed it to Okin. The two enjoyed the snack as they kept along the large stone brick main road of The Citadel, towards the towering statue of Olitheon ahead.
"So, do you think," Previa said between bites, "that the Citadel will be able to beat Farsun and Surkusch without us?"
Okin bit into his snack. His eyelids lowered to say, *seriously*?
"I'm kidding. But I mean, in seriousness, do you think we'll win?"
"Well, the Onorun says we will encompass the world. We've beat them before, and they have less men then us, and they seem to be losing now," Okin paused. "So of course we will win."
"Yeah, but I mean like, when? Like you know, do you think we're living in... like, the Advent?"
Okin's eyes narrowed, but his head was obviously spinning.
"Only a fool or a demagogue, will say, before the signs have come, that they are near, and therefore, change should be upon us."
"Neiman Seven, Eighteen Four," Previa finished with Okin in unison. Okin raised an eyebrow and smiled.
"But I mean... you've heard the rumors that there's a man in the East..."
"Enough," Okin said.
Previa nodded. Okin looked away to get his mind on something else. It was true that he did think of these things, but he trusted in that verse, and understood why it was there, not just to heed people against manipulative opportunists, but also for the sake of the ordinary Versalist's sanity. Though the Onorun ultimately foretold the events during and after the Advent as they lead up to paradise for all, Okin was still fearful that things would change too fast, that his lifetime would be derailed. But those were selfish, small-minded, unholy thoughts.
Okin looked forward as the already busy streets got more dense and noisy. Ahead, a large crowd had gathered, all within the shadow of the massive statue of Olitheon, which was being cast to the left. He and Previa stopped just at the edge of the crowd. Near the front of the crowd, low horns rumbled.
:comment:
Add a description of the statues or cathedral here. Or earlier in the chapter
:END:
"Dad should be serving near here... but this is an awfully large crowd just to get into one of his services," Previa said. "Still it is Olithday, so..."
Okin tiptoed to get a better view, and could see a large wooden pole peeking above the crowd. His stomach twisted. "I-I don't think it's a service."
"Let's get closer," Previa said as he started manuevering through the crowd. Okin squeezed behind him, uttering constant "excuse me"s and "sorry"s.
As they reached a few rows from the front of the crowd, Okin's suspicions were confirmed. He stared up at the wooden platform, upon which the large wooden hanging post sat. His throat squeezed up.
"Oh," Previa said as he also looked upon the wooden post. The Devinar's eyes bounced away to the group of men on the side, just next to the stairs where the post, coming out from the entrance of a large cathedral made of painted stone.
"There he is," Previa pointed to one of the men in the middle who wore robes similar to Okin's, but with purple stripes instead of golden ones. A large cape came out in an apron-like structure but split in the middle, outfitted with geometrical engravings. He was clearly the central figure of the group, being guarded by many heavily armed men.
:comment:
We can probably just say this is Aldwin here. Works better and makes Previa's line less confusing later.
:END:
"I think he's the one hosting this."
The horns, which had been playing a low, ambient rumbling, suddenly erupted. The man in the ornate robes marched onto the stage, surrounded by five guards all in different, unusual colored armor-- one was the same as Previa's, glowing with a softer version of the sun's glare, one a goldish yellow, one a crimson red, one a deep blue, and one a mix of several colors in a swirl, all glazed over with the same glow, shiny yet contained. They separated out onto different corners of the stage, except the one with the white armor. They grasped a thin dirt-faced man, pushing him forward, just behind the central robed figure.
"I'm gonna move back just a bit," Previa whispered into Okin's ear. "I don't want dad to see me and get distracted."
Before Okin could protest, Previa snuck backwards and the crowd moved forward to fill the gap. Okin's eyes returned to the thin man, shivering under the massive shadow of the armored white man behind him.
The horns erupted again, even louder this time. The robed man raised one arm, and there was silence on the other side of the blast.
"Olitheon bless you on his day," the robed man smiled. "Let us all, and especially those moving towards his heaven, be filled with his Virtues. Curiosity, Humility, Wisdom, and Sacrifice. We are standing under him today in more ways then one." the robed man looked up at the massive statue above, and there was some chuckles.
"As we observe our world, and our language, without the enlightenment of Versalism, we often see the opposite of Darkness as Light. This, while intuitive, is a Deception from the Darkness itself. It is a misunderstanding that creates an imbalance in our worldview and priorities. The reality is, that it is all Four, in balance, that stand in opposition to the Darkness. And today, as every Olithday, we stand in recognition of how Space works in opposition to the Darkness. In fact, it was the Wisdom of Olitheon which first saw the evil of Tregale, as well as the Sacrifice of Olitheon which saw to his banishment."
The white-armoured man threw the thin man against the post as the robed man continued his speech. The thin man groaned, and Okin could see that he was barely a man, moreso an adolescent.
"But even though Tregale's banishment prevented Darkness from taking over our world, the war against its evil was not finished, nay, the Gods desired that many things be spread to us, that we be a part of their mission so that we could join them in the Four heavens. That we all take part in the war against Darkness, and spread the Four rightfully across Opartha."
The thin man let out a moan like a pleading animal. He was silenced by a backhand from the white-armored man, which erupted in a squeal, and a pang in Okin's chest. Okin shielded his eyes.
:question:
What made the squeal?
:END:
/These are the Forces of Darkness... they seek to destroy Versalism, the Citadel, and the world... there should be no mercy for them, as they have no mercy.../
Okin looked back to the stage. The robed man pulled out a torch.
"Every destruction of the followers of the Darkness is one step closer to its total banishment, to the total arrival of the Four on Opartha."
The red-armored guard walked over to the robed man, lit his torch, and then stepped away. The robed man raised the torch high in the air.
"Vir Versalis!"
The robed man shouted, and the crowd erupted with him.
"Vir Citadel!"
Their shouts punched across the dense streets.
"Vir--"
FTSK! Several balls of fire sparked into large plumes of smoke near the stage. Screams tore through the streets, and Okin shielded his eyes.
* Chapter III
** Notes
- feet mentioned as measurement
** Chapter
<<<<<<< HEAD
Coughing. Screaming. The crowd crashed like restless waves. The central cloud of smoke consumed the platform. . The colored armed guards ran into the smoke. Okin knew something was happening... that his mentor and friend, and his friend's father, was under attack. But what would he do? He would get in the way of those who could actually defend. And the screaming, the smoke, the fear he admittedly felt but hated at the prospect of the thin man being burned... it was too much. Okin was taken up by the waves of the crowd. He surrendered himself into its waters.
But after running a few paces with the crowd, he had to turn back to the chaos of the central platform. A man emerged from the smoke. He was dressed as an ordinary urban peasant of the Citadel, in a long tunic of natural browns. But Okin knew the man was not just an ordinary peasant, he was the one who had created the smoke. Okin was some twenty paces past the man, with the crowd flowing in between them. The colored guards were stuck in the smoke, and it seemed that neither them nor the crowd noticed this man descending from the platform. Maybe this was his chance. His chance for Bravery.
Okin turned against the weight of the crowd. The shoulders moving against him bucked against his, but he stood his ground. Suddenly, Okin's gaze met the man's eyes. His  face was gaunt and scarred, more dark and weathered than most peasants in the eastern Versalist lands, though it was still obvious that this was a rather young man. But something in the man's eyes, a deep, fiery hatred, screamed that he knew Okin. And with that gaze, and some features of the man's face, and with the knowledge that that man had attacked the robed man, Previa's father, a thought coalesced in Okin's mind.
=======
Coughing. Screaming. The crowd moved like restless waves. The central cloud of smoke consumed the platform. . The colored armed guards ran into the smoke. Okin knew something was happening... that his mentor and friend, and his friend's father, was under attack. But what would he do? He would get in the way of those who could actually defend Aldwin. The screaming, the smoke, the fear he admittedly felt and the hated at the prospect of the thin man being burned... it was too much. Okin was taken up by the waves of the crowd. He surrendered himself into its waters.
After running a few paces with the crowd, he had to turn back to the chaos of the central platform. A man emerged from the smoke. He was dressed as an ordinary urban peasant of the Citadel, in a long tunic of natural browns. But Okin knew the man was not just an ordinary peasant, he was the one who had created the smoke.
Okin was some twenty paces past the man, with the crowd flowing in between them. The colored guards were stuck in the smoke, and it seemed that neither them nor the crowd noticed this man descending from the platform. Maybe this was his chance. His chance for Bravery.
Okin turned against the weight of the crowd. The shoulders moving against him bucked against his, but he stood his ground. Suddenly, Okin's gaze met the man's eyes. His face was gaunt and scarred, more dark and weathered than most peasants in the eastern Versalist lands, though it was still obvious that he was a rather young man. Something in the man's eyes, a deep, fiery hatred, screamed that he knew Okin. With that gaze, the features of the man's face, and with the knowledge that that man had attacked the robed man, Previa's father, a thought coalesced in Okin's mind.
>>>>>>> 88e198603f772eab3a1c5d805abdd1e2db78bdc1
/Is that-- is it Cynin?/
And then, as it often does, Okin's mind exploded in panic. /He's a Herald. And he just killed Aldwin. And he's here to kill you too./
Okin dived back into the mass of the crowd and ran with it. He crossed shoulders with many people, hoping to lose Cynin in the sea of the crowd. He did not look back.
:comment:
Be more explicit about Okin's emotions. Because he turns back pretty soon after, it feels jarring as is.
:END:
Finally, the crowd slowed their movement, but Okin was still stuck inside its mass. It became clear to them that they had dispersed far away enough from the conflict, which seemed to not have escalated further. Okin, along with many of the others, turned back to the scene. Okin searched for Cynin, but he couldn't find him.
He pushed through, ignoring the murmurming and cursing. Reaching the edge, he ran back toward the platform. The smoke was still building, half covering the face of the cathedral behind it and half covering the bottom of the much taller statue of Olitheon to its right.
The guards had all descended from the platform. They were running to surround two figures on the ground-- it was Previa, with his father in his hands. Okin glanced around the entire intersection, and down the street him and Previa had come down before. Finally, he caught a man running to get on a horse. He wasn't certain, but was quite sure it was Cynin.
"It was him!" Okin shouted at the group of Devinars and colored armed guards, and pointed towards the man getting on the horse. "I saw him come out of the smoke!"
The guards took a second between them to decide if they trusted Okin, then nodded and ran towards the man on the horse. Okin watched them run towards Cynin. He could follow, but it was probably pointless for now, they would catch him or they wouldn't.
Instead, he turned back towards  Previa, who was sitting on the floor. The young Devinar sobbed. Okin moved to the side to get a better view of the robed man, who was collapsed in his son's arms. Okin grimaced; Previa's father looked beyond old, like if a man kept growing after he was dead. The first thing Okin noticed were the offness of the man's colors, his hair was much longer than before but scraggly and twisted in  different directions, though it was gray before, now it was streamed in several uncomfortable shades of grey, his teeth were yellow, and his skin was also a whitish-gray. The man's gaunt hands lay motionless. His fingernails, colonized by dust and puss, were half as long as his fingers. His eyes were stretched open, and massive drooping bags contrasted against his now ghoulish skin.
"Dad! No, no, no, no!" Previa shouted and kept shaking his father. Previa held his father's cold face against his cheek. "Please! Oh Aredal!" He screamed up, but past, the massive statue above. "Oh Aredal! Give your Compassion to my father! Oh Nexon! Give him your Care!"
He screamed directly at the statue just above them, with both its palms outstretched as if it was holding a large ball in front of its chest, "Oh, Olitheon, on your day, if it is my father's final hour, I know he will be blessed in your heaven, but please, give him some more time on Opartha, please!"
Okin's heart wrenched at Previa's sobs. He walked close enough that Previa could see it was him and leaned down and hugged his friend.
"I'm sorry," he said. "I'm sorry."
Previa kept hugging his father's cold body close to his chest, but he leaned into Okin's shoulder to wipe his tears.
"Who did this?" he said, his eyes red. "You said you saw who did this!"
Okin's throat froze as he pulled away from Previa and met the Devinar's teary eyes. "I-I'm not sure, but I think-- I think it was Cynin."
Previa's jaw tensed. "That's not-- he'd be dead, Okin."
"But, it would make sense, him coming to kill Aldwin. And he--," Okin said.
"How would you even know it was him?"
Okin flinched at the slight venom in his friend's words, "I-- like I said, I don't. But it just, it looked enough like him."
"I mean how far away were you?" Previa asked.
"I don't know. Twenty paces, or something."
Previa's fist clenched and he stared off in the direction of the street they came from.
"Devinar Previa," Both Okin and Previa looked up to see the red-armored guard standing over them. "I'm sorry, but we have to clear the streets and get your father to a hospital."
Previa nodded and wiped his eyes. Awkwardly, he slid held out his father's limp body to the red guard and another guard in plain armor who picked him up by supporting his back and legs respectively.
Previa immeadiately jumped to his feet like an angry teenager itching to get into a fight. "He went that way?" Previa said to Okin and pointed down the street.
"Y-yeah, but--"
Previa wooshed passed Okin, nearly knocking him over. The Athar sighed. He looked up to the statue of Olitheon, some several buildings' height worth above, just as the smoke was clearing from his face.  His head was numb, the events that just happened felt unreal.
/Oh Olitheon, I am sorry for all the evils that happen on your day... in all your Wisdom, you are probably looking down on us and shaking your head. Please guide us. I know I am of Aredal, but please guide me... through whatever this is.../
"Athar Okin," Okin was brought out of his trance by a fully armored guard holding a long spear. "I need you to come with me."
Okin met the guard's harsh blue eyes. He nodded and followed the man down the circular road which surrounded the statues and large cathedrals in the center of the Citadel. They turned into one of the cathedrals with paint that looked like navy leather with vines of bronze stretching down and around it.
:comment:
It's fine for Okin to recongize the catherdal
:END:
The guard led Okin up a set of stone stairs into a small but fancy room, outfitted with custom wood dressers, and a petite table and tea set that one would think fit for a rich old lady. The guard motioned for Okin to take a seat and he obliged.
"We're just having everyone close to Impalias Aldwin and any other potential targets under watch for the time being," the Devinar said. "I hope you understand."
Okin nodded. "We'll keep you fed and guarded and notify you if we have any updates," the guard continued.
He gave Okin a curt nod before leaving the room and bounding down the stairs. Okin just stared out at the parially transparent window, sitting upright in the chair much too small for him. His eyes seemed to ponder nothing but the second floor of the stone building on the other side of the street. But though his eyes were still, his mind was not. /How did Cynin survive all this time? Had he been waiting under their nose, just waiting for an opportunity, or was he living far away? Was Damin still alive? Did Cynin want to kill Okin? Was it really Cynin, or was it just Okin's fears that were getting in the way? What will Previa do now? Is Aldwin dead? Who will be the next Impalias?/
His train of thought was interrupted by a knock on the door. His head whipped to it like a bird noticing a predator, and his fingers grew white against the table. The door squeaked open, and he readied his fists--
He lowered them in a sigh as a short old woman pushed open the door with her lower back. She gave Okin a kind smile and he got up to help her with the tray she was holding, a plate with a loaf of sugared bread and some tea.
"Thank you, Infantii", Okin smiled. He sat back down as she left the room, accidentally slamming the tea tray too hard against the table with his shaky hands. The tea in the cup jostled, just barely staying within.
:question:
Is infantii the persons name. Is this to esatblish that old ppl can be infantis?
:END:
Okin stared at the tea, which moved back and forth yet maintaining the top surface as a perfect oval, and the ever-so-slightly rattling cup. His eyes fixed on all the tiniest details, on the slight ripples in the brown water, on the chaotic triangles and small smudges in the leaf inside, to the little white specks quite natural for the stone the cup was made out of. His gaze shifted to the small loaf of sugared bread, running down the gradient from a soft yellow to a warm brown, over the distribution of sugar droplets. He sat down into the chair without moving his head, still focused on the treats in front of him. His stomach rumbled, but he didn't move a muscle.
Okin stayed like that, waiting, salivating, feeling the dryness of his own body, analyzing the snacks before him, as the same thoughts bounced through his mind. He didn't know how long he stayed there. Eventually he started to hear the rhythym of his own breathes.
The door squeaked open again. This time, two guards in the same steel armor, indistinguishable from the one who brought him in before, shifted and crouched to fit through the small wodden door. Okin stood to his feet to greet them.
"Athar Okin, sorry for the wait," the first one said, plopping down his visor to reveal a face marked by spotted dark hair, on both his beard and eyebrows. His eyes went to the plate of snacks, untouched, and back to Okin.
"Did you catch him?" Okin asked. His eyes went back and forth between the two guards, and he could tell the answer was no before they said it.
"No," the second guard, noticeable by a scar across his left eye, said. "He was assisted by another group of Heralds, one of them Teleporation, at the North entrance."
Okin scratched his chin. "And was there two of them? In the original party?"
"We were not in the pursuing party," the dark-haired guard said. "But the reports so far say so, that two individuals fled for the North entrance after Impalias Aldwin was attacked, though we also don't know exactly how many accomplices there were or what their roles were in their attack."
"And the criminal? The one of the Darkness? Did he get away?" Okin asked.
"His whereabouts are unknown," the scarred guard said. "But if you have any information about either him or "
"I believe the attacker was a Light Herald," Okin said without skipping a beat.. "And uhm, I believe he may have an accomplice who's... of the Darkness."
The guards looked at each other. Their jaws clenched, and it was obvious they were forcing overly unphased faces. The scarred guard nodded.
"Understood," The dark-haired guard cleared his throat. "Uhm, that is not the only reason we're here. We've been notified that it is unlikely that Impalias Aldwin will be making a recovery soon, Four bless him."
Okin gave a solemn nod, "Four bless him."
"And the Impalias noted you down as a replacement in case of his temporary leave, until an election can be held", the scarred guard said.
Okin's eyes widened. His heart quickened. "I'm just a junior Athar. I've only achieved Truth, and I-I'm only thirty! I am far too inexperienced to be an IMPALIAS!"
:comment:
Okin can note some other notable young Impaliai here. Or talk about the typical job age range
:END:
"It is the will of the Impalias, who's authority is willed by the Mouth, who's authority is willed by the Gods," the guard said.
Okin shook his head. "In Truth, I felt I did not even deserve the title of Athar. This-- this is a mistake."
"It is not like this is our decision," the dark-haired guard said. "We are merely the messengers. Though if Impalias Aldwin has selected you, I'm sure there was Wisdom in his judgement."
"I do not mean to insult a man I so dearly respect," Okin said. "But he has known me since I was a child. I'm afraid that nepotism has clouded his judgement."
:style:
Nepotism is prob a weird word to use.
:END:
"With all due respect, it is not my job to debate you or encourage you," the scarred guard interjected. "My job is to take you to the central chamber, to prepare for you duties as Impalias. We'll go through the Nexon chamber, if you don't mind."
Okin nodded. The dark-haired guard held open the door for Okin and the three of them left the building.
As they moved back onto the main central street, it was clear and clean yet bustling; one who was not here a few hours ago would not have known that the event nor the violent attack took place.
They turned into an arch set between the legs of two of the massive stone statues into a large building made of a dazzling quartz-like surface, also outfitted with green, orangle, purple, and multicolor gems. Inside, Okin awed at the series of massive paintings. They depicted men and women in different outfits, most of a simple and ancient nature, yet different in color and shape. Some were portraits, some were landscapes, some set in the austerity of cold winter, some ontop of a picturesque mountain sunset, some depicted battles, others depicted meals. Yet though everything of the environment was different, and though the individuals varied in race and appearance, it was not just the style--- which were of a romantic yet semi-realistic nature, with deep, contrasting colors ---that told the viewer that these people all shared something in common; there was an unspeakable quality among them, like they knew the people in the other paintings, or even that they knew that the other people were in the paintings that they were in, even though the events depicted were nations and times away from each other.
:comment:
Having a hard time visualizing the hall. Painting descriptions are good
:END:
As they left the hall wherein all the paintings, and walked the steps of a stone spire, Okin's lungs squeezed inside his chest. Here he was, in the most powerful and holy complex in the world, about to be inducted as one of the most powerful leaders in the continent, after ironically being sent here by a failure. How could he tell the Council that he did not belong there? Surely, they would see that he did not, and it would all just be a quick, embarrasing moment to forget. It was Okin's dream to be here, in some ways, but no, because it just felt too distant. He remembered how he felt when Aldwin became an Impalias, how close it was to be so near to the heart of Versalism. And now, here, he was, and it felt surreal.
Okin stepped up to the exit of the claustrobic, dimly lit stair spire, and entered a tall, long hall with quartz walls set with topaz accenting that made long lines with swirling patterns at the end. Here, there were paintings as well, but they were all of one man, a figure who looked nearly identical to the statue of Olitheon that stood above them, with his narrow but still masculine face, tall frame, and long, pointy nose. Yet there was a quality different about him, mostly in his expression, which in every picture was a smile of some sort, both large, childish smiles, but also some soft smiles of an old friends appreciating each other in a quiet moment, as opposed to the kind yet serious expression on the massive statue outside. Like the paintings downstairs, these depicted the man in a variety of scenes; a few of the scenes had other individuals, but it was obvious he was the center and the throughline; In one he fought off four other figures, but it was him focused on the dominant side of the image, and the four on the other, and there were actually many with another man who looked identical to him that was no doubt the same man as the massive statue outside, Olitheon. In every artwork was composed to feel their closeness, and they both smiled, though the one that was not Olitheon always smiled brighter.
As soon as Okin had fully stepped in the room, and had more than a spare second to take in the exquisite air that the display created, he immeadiately joined the two guards in a line in front of a statue of the featured figure at the far edge of the room. At once, they all knelt on one knee.
"Nexon, God of Joy, God of Creativity, God of Peace, God of Care, God of Time, we permission ask that we be brought before your messenger on Opartha, the Mouth of the Gods," the two guards said. "We are returning his request for Athar Okin Santac."
For some moments, there was nothing, and the guards and Okin looked almost comical standing so reverently, almost hoping for a response from the statue, which was in a childish position, mid-jump. Then left of the statue, a man in light-armor stepped out from a line of four light-armored men in front of a narrow doorway.
"The Mouth has spoken. Permission is granted," his voice rumbled through the hall. He stepped back into the line, and then the line broke and folded so that pairs of men were facing each other. Okin and the two guards stood up from their position, and Okin noticed that on the right side was an identical line of guards, but unbroken, except these were heavily armored in the identical armors as the ones who were guarding Aldwin when he was attacked on the platform, except the white one was missing. Okin followed the guards through the left side, between the two pairs of men.
/How powerful must these four Heralds be? They could probably take down a whole army of their own.../
As they reached the top of the staircase, Okin's mind spun in a million directions. Here he was, about to meet the most powerful, holiest man in the Citadel, the direct leader of all Athars like him. Once they finally got through the doors, Okin's panic was only stopped by one fact: he expected the central chamber to be /bigger/. The room was nice, no doubt, not too cluttered or ostentatious; each priceless material was placed with intention; on the opposite side of which they came out elegant emeralds encapsulated a set of paintings, the largest and central being that of a dark-haired, angular woman with foreign eyes. There were two paintings on either side of her, one man and one woman on each side, of different builds and skintones; next to that entire set was another, this one surrounded by rainbow gems. The central figure in this one was another foreign-looking man with yellowish skin, jet-black hair, squinted eyes, a strong jawline, and a kind smile.
:comment:
Who is the women? Is it Intillia? I'm confused who the paintings next to the women are supposed to be
:END:
As he looked at each piece, Okin realized, as almost all men did when entering, that in fact his expectations were wrong, that the room was perfectly sized, that it had the symmetrical beauty both for form and function, and that every item within had itself the perfect amount of positive space it filled and negative space around it to shine itself and complement the items around it. That the closeness would remind the people within that they were sitting on top of an organized, holy order, where everything is already in its place and that they must act with total Wisdom to ensure its perfection.
:question:
who is saying the dialouge after this? I don't understand what it means 
:END:
"I'm gonna have to extend my nighttime prayers by two hours today. Being the plainest thing in the room for years has caused me some Envy," Okin's wandering eyes found a man sitting directly ahead of where they had entered, on a chair in the round red wood table in the centre of the room. He wore a hat shaped like a diamond, with one of the tips ending right above his nose bridge. His robes were puffy, and four lines of equal measure streamed down the sides, green, orange, purple, and multicolored. He had a variety of jewelry, including four brooches on top of his hat, and a large necklace with sixteen gems.
He gave Okin a bright smile. Okin knelt immeadiately, and only noticed after that the guards already were.
"We'll leave you to your privacy, Holy Mouth of the Gods," the guards said, before exiting back down the staircase in which they came.
The Mouth of the Gods nodded before standing. He stepped forward, still with a mischeivious smile, almost like a teen asking /Am I doing it right? Do I really belong here?/, before shaking Okin's hand. Okin locked in the shake for a long time, probably too long.
"Why so nervous, Athar Okin?" the Mouth asked.
"Well-- only handful of clergy even meet you, Holy Mouth of the Gods," Okin said. "And here I am, barely thirty, only having achieved Truth, and hearing that I am going to be inducted as an Impalias."
"Sometimes... a thing does not profit from immediately receiving what is already finished," The Mouth of the Gods smiled with his cheeks. "Sometimes, it is not the beginning nor the end state of a being that the situation needs, no, it requires the process, the effect created by the transformation itself. I believe that may be the relationship between the Citadel and you."
Okin's slow nods betrayed his confusion.
"It is good that we have someone so young, and going through the beautiful journey of pursuing the Virtues, among the High Council now," the Mouth of the Gods said.
"Well, it's due to tragedy that I am here, so I hope it's not too long."
"I assure you we will have our best on the case for the investigation of this terrible event. But enough of that Pessimism. It brings me Joy that you are here," the Mouth motioned for Okin to take a seat. "I always love to meet new people. I /see/ new faces, but to connect to someone new, to grow with someone, like I get with the other Impaliases... it is rare. It is quiet here in the central chamber."
"Well, I hope you can understand-- I hope I am more than a face, but as I said I still hope that it is Aldwin here growing with you soon, and not me," Okin gave a tight-lipped smile before siting down.
"Of course," the Mouth nodded, and took his original seat. He cleared his throat and brushed some dust off his robe. "Devinar Aktro! Please will you bring me Athar Okin's things now?" He shouted down one of the corridors.
:comment:
Maybe these guards should be Krusadar
:END:
Heavy footsteps echoed through the hallway in response. A massive man, armored in the same kind of white shiny armor as Previa had worn before, walked up to Okin and presented a set of jewelry ontop folded robes to him. Okin received the package with open palms.
"I apologize we don't have time for a formal ceremony, though if you really want one it can be arranged," the Mouth said.
Okin shook his head, "There's not a more respectable place I could be." He felt the warm touch of the linen filling his palms.
The Mouth smiled. "You have more Humility than many of the Athars of Nexon." He stood to his feet again and hobbled over to pick up a staff leant against the wall. The staff reflected a soft light from the chandelier above, its body satin and subtle. He rose the tip which formed from four arches that stretched out from the body and created a hollow center where a large orange Crystal shimmered.
"I'm always casual, but the Citadel requires that you kneel. And you've seen how tough its walls look," the Mouth chuckled.
Okin fell to his knees and placed the folded clothes in front of him. He raised his palms to the ceiling, in the same position that he always prayed in.
"Athar Okin Santac, do you recognize the Truth of the Versalist world, and claim yourself as part of it?"
"I do," Okin spoke with a measured voice.
"Do you recognize that the Citadel is the center of the Versalist world, and out from it the holiness and the authority of the Gods dissapates across Opartha?"
"I do."
"And do you recognize that I am the Mouth of the Gods, and from my Mouth the will of the Gods is given?"
"I do."
"And as a member of the clergy of the Citadel, have you dedicated your life to the Gods and the Versalist world, but heard the calling of one of the Four?"
"I have."
"And which of the Four is that?"
"Aredal."
"And do you understand that Impalias Aldwin of the Citadel, who receives his authority from the Mouth of the Gods, who recieves his authority from the Gods themselves, his called upon to be his replacement as one of the holy ten Impaliases of the Citadel in a time of need?"
Okin froze. His eyes travelled upwards to meet the Mouth of the Gods'. /I understand, but I don't agree. There's thousands of other Athars, older and holier than I, who should be taking this decision. Every night I will be up praying that by some miracle of Light Heraldry Aldwin instantly recovers. I shouldn't even be here, I was only planning to be here for a week to get reassigned./
The Mouth of the Gods looked at Okin expectedly, and lowered his staff until it brushed Okin's hair. The ocean of concerns almost flooded out of Okin's mouth.
/What an act of Cowardice it would be now to whine like a child about my fears./
Then, his voice shaky yet determined, he delivered.
"I do."
The Mouth smiled, "Then as the Mouth of the Gods, he who proclaims the will of the Four on Opartha, I declare you Impalias Okin Santac of Aredal."
* Chapter IV
** Notes
- Gendro Intro
- Intro other characters
- Istar roles explained
** Chapter
Aldwin's manor was in the Nexon quarter of the city, nestled between two townhouses. Okin had visted the home manor before, but it had a different air about it now that he was the Impalias-- he felt he actually had the permission to look around.
The manor was a two story house, surrounded by a well-kept garden. The manor had enough room to house the Impalias of Whenran, his family, and few select servants. The remainder of the staff would likely live in the same quarter, in the many town houses and low lying apartments of the Citadel.
Okin had been escorted from his meeting by the three guards: one in crimson red, one in golden yellow, and one in deep blue. Three of the guards who had failed to protect Aldwin. The only words the men had exchanged with Okin were to inform him that the last two guards were watching over Aldwin's body. Okin didn't blame the men for their silence.
Lights shone out of the window as Okin approached the manor. In the drive way up to the entrance, stood a man and a women. They each wore the uniform of an Athar and Istar respectively.
"Impalias Okin!" The woman said. She was a short middle aged woman with the blue eyes, almond brown hair and pale peach skin of a Nairfalkian. Her hair was cut in a straight bob that framed her round face. 
"I'm Othar Amesa, and that's Athar Gendro." She said pointing to the taller man behind her.
:comment:
is she othar or istar
:END:
"There is no need for that," Okin said, quickly trying to wave the pair off.
"We insist, Impalias," the man, Gendro, said. Okin couldn't place the man's ethnicity, but his curly black hair indicated he was from one of the central provinces. Based on his long face and plump cheeks, Gendro was young for an Athar, not much past Okin's age.
"Come, come, we have so much to catch up on." Amesa practically shoved Okin down the drive way and into the manor's two story entry hall.
"Wh- where are we going?" Okin asked.
"To Aldwin- I mean, to your study," Amesa led Okin down a hall on the first floor towards the back of the manor. They passed busts of the previous Whenran Impaliases and oil paintings of the Gods, till they reached the study at the back of the manor.
The study was obviously not designed as such. It was awkwardly large, and had a glass door that led to a conservatory. A huge oak desk set to Okin's left, and behind it a painting of Aldwin and a young Previa. The room was crowded with at least fifteen other staff members of all ranks. The collective turned to Okin as he entered, and silence fell over the room.
Okin could feel Gendro looking between the crowd and himself silently. Okin's heart skipped a beat under the weight of those eyes.
"This is Impalias Okin," Amesa said after a long pause. "Impalias, meet your aides."
"It is an honour to meet you all," Okin said.
There were murmurs of agreement amongst the crowd. Gendro motioned for Okin to take a seat at the head of the oak desk. The Impalias took the seat silently. Gendro, Amesa, and the three guards--- now without helmets ---filled in after.
His aides seemed to be from all over the Versalist World. He had heard most Impaliases recruited exclusively from their home province, but only half the assembled aides appeared to be from Whenran.
"The first order of business is ensuring the Impalias is prepared for tomorrow's meeting," Gendro took a place at the side of Aldwin's desk.
An Othar stepped up to slide a piece of paper across the desk. "I have this week's Registir here. I just updated it this morning, it's all the same topics as last week."
Gendro gave the Othar a solid nod as she handed a second copy to him, then another to Amesa.
"No, I have a more pressing issue," Okin said. All eyes in the room once again went to the new Impalias.
"Impalias Aldwin was attacked today." Okin paused. He hung the silence long enough for the assembled aides to begin to nervously shift. "We can not let this go unpunished. I want to assemble a task force to hunt down the two attackers."
Okin paused, wondering if he should reveal that he knew the attackers personally. He had already told the two Devinar about Cynin and Damin, if it would tarnish his image there was nothing Okin could do to stop it.
"It was an orchestrated by a man by the name of Cynin Gruissem. Aldwin knew him as a child, but some old grudge seems to have driven the man to his attack."
There were gasps amongst the crowd.
"The man is dangerous, and armed. I won't force anyone to go after him, but I need Brave men and women to pursue this assassin."
The crimson red anti-Herald guards stepped up. Okin put out a hand to stop the man.
"I have a task for you three already."
The guard's jaw visibly tensed as he bit back a retort.
"I want you to gather the White Knight and go after the escaped Dark Herald. They are the most pressing issue. We can not allow a rouge agent of Darkness to be free within the walls of our hallowed Citadel."
The guard still seemed annoyed, but nodded his head in understanding. "After you capture the Herald, you can transfer to lead the search for Cynin Gruissem."
The man gave a slow nod, "it will be done, Impalias."
"May the Four bless you."
"And you Impalias." 
The three anti-Heralds exited the room with their task as Okin read the Registir over. He had learned what the Registir was during his training as an Athar. It was a list of all the issues and disputes from over the Versalist world which the Impalises worked to resolve in their weekly meetings. The Mouth controlled the flow of issues. He had the power to decide which issues were discussed in each meeting, and the power to take any topics off the Registir.
The list had twelve items on it, some of which he recognised. /Troop allocation on the Western Front, Versalist presence in Marthia, Space Guild rate negotiations,/ and various requests by high Othars to fund their research projects. Some were ones that would be solved within a week. Others were debates that might've gone on past his life time, and would only change in name.
Two items caught Okin's eyes. /Funds for a new Terellian shipyard/, and /Wolstamm food shortage/, "Are these all real?" Okin asked.
Gendro nodded, still reading over the paper.
"There's a food shortage in Wolstamm? No one's said anything about it? How could they not?" Okin felt himself rise from his chair.
"With all due respect Impalias, you were on the front," Gendro replied.
Okin glanced at Gendro.
"How did you know?" Okin asked.
"Impalias Aldwin thought quite highly of you," Amesa said with a fond smile. "He made sure to keep tabs on you and young Previa."
Okin nodded, that made sense.
"But news that big, it must have travelled to the front. Wolstamm is less than a day by Portal, and only a week or two ride by horse. Plus this news of a new naval shipyard? How many ships do they plan on needing?" Okin said.
"Fifty ships," an Athar in the crowd said. Okin blinked. That would be doubling the size of the Navy.
"Fifty?" The room nodded in response. "How long would that take?"
"If they approve the new ship yard, a decade. If we invested all excess resources from the region into it and brought in wood from Whenran."
"So Aldwin... opposed this?" Okin asked. Aldwin had mostly supported the Army since it was inducted into the Versalist world.
Gendro and the aide both nodded.
"What about the food shortages?" In his lifetime, Okin had never heard of a food shortage in the province. Wolstamm was said to be one of the richest provinces. It had been the bread basket of the army since it was brought into the Versalist world, and contained a great wealth of minerals. It was said that the mills of Wolstamm never stopped spinning.
"It was a particularly bad harvest," a third, new aide, explained. "In addition, two brigades of Surkusch cavalry raided the country side for months before Impalias Volmunst could gather the troops to fight them off."
Okin looked at the aide, and his mouth widened.
"How did I not hear about this? I was on the front. If two brigades of cavalry had crossed into Wolstamm, we surely would have been mobilized."
Out of the corner of his eye, Okin saw Gendro biting his lip.
"We think you should avoid this topic tomorrow," Amesa said.
"Why?"
Amesa hand clutched the folds of her skirt. "There are... dynamics and alliances built on years of disagreements which we simply couldn't teach you by tomorrow's meeting, even if we tried. And this issue was a particularly sore point for many of the Impalises."
Okin took a deep breath. There were ten more issues on the Registir, and he was sure he had missed a hundred details. He was in so far over his head that he had no hope of breaking the water's surface, even with his great memory.
"What can you teach me by tomorrow?" Okin asked with a shaky breath.
"Enough," Gendro said.
Amesa waved an Infantis over, "get refreshments for the Athar. Tea or coffee, Impalias?"
"Tea please," Okin said with a smile. "And crackers if you have them."
The Infantis nodded and ran off.

The sun was beginning to rise over the Citadel's inner most wall by the time the briefing had concluded. There was doubtless details the briefing had missed, but Amesa had declared that Okin needed rest and had dismissed the staff of aides. Amesa herself had left not long after. Now only Okin and Gendro seemed to remain in the manor.
"Shall I have your lunch brought to you before you leave?" Gendro said as he followed Okin up the main hall's grand stairs to the second floor.
"No, no, I'll take it in the main dining room before I leave."
Gendro nodded, "the guest bedroom is at the end of the hall, on your right. I can have the Impalias' bedroom made up if you wish."
"The guest bedroom is fine. I am a guest after all." Okin paused pondering a question he had been holding since he had first arrived.
"So what are you and Amesa's roles?"
Gendro's eye brow raised, "I'm your personal aide, Impalias. Amesa is your head aide, and head of staff. I'm sorry Impalias Okin, I had assumed that you would be briefed on your staff prior to your arrival."
Okin shook his head, "it was a fair assumption."
Gendro made a small grunt of affirmation.
"Goodnight, Impalias Okin."
"Goodnight, Athar."
Okin pushed the door to the guest room open and collapsed against the door once it closed. He brought his knees up and began to cry. Alone in his mentor's home, the Impalias cried until he had no tears left.

:comment:
This could be a chapter break tbh
:END:

"Aredal, God of Truth, God of Compassion, God of Bravery, God of Temperance, we ask permission that we be brought before your messenger on Opartha, the Mouth of the Gods." Gendro and Okin knelt in front of the chiselled statue of Aredal. One of the guards at either side of the Okin signalled them through double doors at the end of Aredal's cathedral.
"I'll be waiting for you here," Gendro said as they passed through the doorway and onto the same spiralling staircase Okin had taken less than a day ago to see the Mouth of the Gods. "Aides and guards aren't allowed in the chamber. But it's customary for us to walk you up."
A hundred or so steps up a hall way split from the staircase into in to an antechamber. Even in a simple antechamber, there was overwhelming detail in the brick work. No face was unordained. A small window in the ante chamber looked down upon the interior of Aredal's Cathedral.
"I leave you here, Impalias Okin," Gendro tipped his head and Okin returned the gesture. As Gendro left, another party crested the staircase. The Impalias at their head was easily identifiable as Impalias Henard. The man stood tall despite the age apparent in his greying hair and wrinkled, square face.
"Impalias Henard," Okin nearly dropped to the ground in respect before catching himself. 
"I see the new Impalias is here," the man's baritone voice was tinged with a rough gravel edge.
"It's an honour to meet you."
Henard had been one of the men Okin most admired and most strived to base his own life on. A paragon of Truth and Virtue.
"And it is an honour to have you amongst us young Okin." Henard said. He had the same soft fatherly smile of Okin's own father. Okin understood why so many over the Versalist world has sought the man out for guidance. "A fresh set of eyes and ears have always done the Impaliases good. It takes many perspectives to fully reveal the Truth."
Okin nodded, focused, absorbing every word. The mention of Truth spurred his heart, as it always had-- it was the Virtue he felt most confident in.
Henard stared at Okin waiting for him to speak. The young Impalias dared say no words. Moments later, Henard let out a hearty laugh at Okin's silence.
"Come, I'm sure they're waiting for us already." Henard walked past Okin to the double doors at the antechambers far side. The chamber within was circular, and silent. Eight men sat around a large circular table. Behind the table was an ornate cushioned chair.
Okin let out a silent gasp at the sight. Before Okin had learned Temperance, he had dreamed of being an Impalias. He had dreamed of living in the manor and of making policy and directing the Versalist world.
Henard motioned to an empty seat between the Impaliases of Monasque and Golzen, and Okin took it.
"I am very sorry to hear about Aldwin. He spoke of you well," The Impalias of Golzen said. He was a fit man, even into his late sixties, and handsome. The Impalias sported a bald head and curling gray mustache.
"As am I," said the fat man at Okin's other side.
"I thank you, Impalias Mikeol," Okin said, turning to the bald man. "And you, Impaliases Vovaq. Your condolences mean a great deal."
The Impaliases around the table took turns offering their condolences and introducing themselves. It was only after all had gone that the Mouth of the Gods entered the chamber. He wore the same robes and pointed that Okin had seen yesterday. He gave subtle waves and nods of greeting to the Impaliases as he passed to sit on the ornate chair at the back of the chamber.
"Shall we begin?" The Impaliases around the table nodded in response.
"The first issue we shall discuss is..." The Mouth looked over the Registir squinting. "Let's begin with a light issue. I would say it's for our new recruit, but we know that it's really me that needs the easing in," the Mouth smiled, and a few of the Impaliases chuckled. "Othar Julesh has requested we approve a new sub-committee to research what she calls /flintlock/ muskets. She claims that they'll be a marked improvement on our current matchstick muskets. Impaliases?"
There was silence for a moment before Impalias Ovolo of Farsun, Grand Marshal of the Western Armies, spoke. "I believe the idea to be solid. We have reports of Sirkusch's calvary using such weapons to great effect."
Even in their chairs, the Grand Marshall cast a shadow over the room. He was not the most handsome, but there was not a stain on his broad shoulders, and his groom was cut short and perfect, giving his hawkish face two sharp peaks. He was one of the youngest Impaliases ever, elected when he was thirty-four. The old Grand Marshal had been ousted after the early years of failure in the most recent war against Farsun and Sirkusch.
"Why can the Council of Advancement not manage such a project with their own resources," an old man's voice croaked out opposite from Ovolo, Impalias Levinor. "We've given them more than enough to accomplish such a task."
"She claims that the best way to acquire them is to buy a shipment from Apathasaw. A deal she can't make without our approval," Mikeol said, leaning back in his chair. "I personally think we should allow her to negotiate with them. If she manages to find a way through the Kaihani pirates to get our shipment, then that solves us all some headache, and its buying a single product to possibly increase the effectiveness of our entire army."
There was a series of nods from around the table.
"The only solution to the Kaihani pirates is to increase our naval outreach," a shorter man on Okin's side of the table said. Groans came from a select few Impaliases.
"Not everything is about your damned Navy!" A high-pitched voice yelled.
"Maybe it should be," the shorter man replied.
Okin searched for the high-pitched voice and found it had come from a hulk of a man to Okin's right. Even sitting, he clearly towered above the other Impaliases, including Ovolo. He had a short mustache and beard, scattered with trimmed but thick, rough hairs, and a few greys showing a mix of vitality, experience, and roughness. A huge scar cut across his left cheek and nose, ending a hair away from the man's right eye.
The Mouth waved them to silence, "we will get to your proposal later, Impalias Mathelin. Please. Focus."
The shorter man barely bit back a word of protest at the Mouth's command, leaving the hulk of a man with a satisfied smile.
"I vote in favour of forming this subcommittee," a man with hair braided in two strands said. The braids began at the hair line and divided the scalp in thirds. The Impalias had smaller thin eyes and a pointed chin.
"I agree with Impalias Ricartotten," Mikeol said. The other Impaliases all gave their support until it was only Okin and Mathelin left.
"I, uh..." Okin's eyes darted between the other Impaliases. Their faces were relaxed, almost unreadable. "I support this motion. I see no reason to reject an earnest proposal made in Curiosity."
Mikeol patted Okin on the back, leaning in to whisper. "Well said, young Impalias. Be not intimidated, we are all equals here."
Okin nodded slowly. Those simple words were somehow comforting and nerve wracking all at once.
Mathelin gave an over-dramatic sigh, "Fine. I agree. Let this motion be passed."
"Let this motion be passed," the Mouth repeated as he made a mark on his copy of the Registir. "I suppose Mathelin would like to discuss his proposal?"
Mathelin stood without prompting. "Yes, I would like to propose that we commission an additional shipyard to prepare for the planned expansion of our navy."
Okin could see the hulk of a man roll his eyes, as did Levinor. The room was still aside from them, as if encased in amber.
"No protests? I suppose we shall move to approve it then?" Mathelin's face shifted as a smug grin came onto his face.
"How many ships are you building?" Okin blurted out. He hadn't meant to speak out of line, but still didn't believe the figure his aide had given him.
"He wants fifty, he's getting zero!" The hulking man's high pitched voice yelled out, causing a quiet chuckle from around the table.
Mathelin wheeled on the man, "you have such a strong opinion, do you, Volmunst?"
"You're putting the cart in front of the horse is all," Volmunst shrugged. A murmur of agreement came from the crowd.
"Impalias Volmunst makes a wise observation," Henard said. "How do we know if we truly need these ships and this ship yard?"
"Any man can see it," Mathelin scoffed. "Apathasaw is becoming a more and more important nation by the day. The Kaihani become more aggressive with each turn of the leaves. Our colonies are thriving in the South. How are we to protect our interests abroad and spread Versalism if we are limited to the land?"
Another wave of agreement.
:comment:
I am confused here. do you mean disagreement?
:END:
"You already got fifteen damned ships last month, and still decided to just repost this issue to the Registir. Shouldn't we at least see your grand plan for ourselves before we go dumping resource that could be used /elsewhere/ into your project."
:comment:
seems like something's missing here.
:END:
"What would you propose instead?" Mikeol said.
"I purpose we move to an issue that's actually pressing to our people. The food shortages in Wolstamm."
"Of course you wish for us to shield your own province from your mismanagement," Mathelin threw the comment into the crowd with a casual roll of his eyes.
"My mismanagement?" Volmunst said in a quiet tone. Okin instantly understood why he was to stay away from this topic in the meeting.
Volmunst rose to tower over Mathelin. Mikeol let out a small whistle from Okin's side. "Krusadars, what else can you expect," he said.
"Was it my mismanagement that allowed 6,000 mounted men and horses to cross the Strait and land in Wolstamm? Was it my mismanagement that allowed those two brigades to slip past the first and second army and into the heart of Versalist territory?" With that lat comment, Volmunst turned to Ovolo. "Was it my mismanagement that kept me here for weeks, discussing the budget for these new ships and rate hike contracts with the guilds? Weeks that prevented me from rallying my own men and riders to repel a force which should never have gotten so far in the first place!"
Volmunst slammed his fist on the table, causing the whole table jump.
"Impalias Volmunst, that is enough! Back to your seat," the Mouth roared. "We will maintain the sacred order of this meeting." 
"I will not yield!" Volmunst yelled. "My people are starving, /dying/! Wolstamm has given everything the Citadel has ever asked of it. We arm, house, and feed the righteous forces of Versalism. Two hundred years of the Citadel asking my people to turn their farms to mines. Wheat mills to steel mills. Bakeries to forges. My people have given all for the good of the war, for the good of the Citadel. Yet you ask us to invest in shipyards, missionaries, and more Devinars!?"
Okin shied away from the man's passionate speech.
"All I ask is a tax on your harvests, to be help feed the army and alleviate the pressure on my people," his voice shook this time, and Okin thought he saw wetness in the massive, rough man's eyes. "What Charity do we have if we let our people starve?"
There was silence in the room. Volmunst looked each Impalias over slowly till he made eye contact with Okin. There was a plea in his eyes clear as day. /What would Aldwin have done? Surely, he would have helped the people in need. Whenran could afford to sacrifice for the good of all Versalists./
"I support this motion," Okin was the first to say.
"As do I," Mikeol said with a grudging sigh.
Another round of silence before Henard spoke, "Volmunst speaks to Truth. We have asked much of the people of Wolstamm. If they can not support themselves, then we will fail to support our own Army. There is Wisdom in this decision. I agree."
The others slowly agreed until only Ovolo and Mathelin remained.
Ovolo ran a hand through his combed hair. The man chewed on his decision, slowly running it over. "It's true the army does need more food. I will agree if Impalias Mathelin does. As I hold no land, it is improper of me to make a decision on your behalfs."
Mathelin had cowered from Volmunst's rant. He had slipped silently back in his chair and had allowed his wavy hair to fall over his eyes. As he began to speak, Okin could see his hands visibly shake.
"I... I understand Impalias Volmunst's concern," Mathelin gripped his hands into fists. "But we have a careful balance--," He paused and glanced over everyone, except Volmunst. "Who's to say this food tax won't ruin us all?"
"Mathelin," Henard spoke with an even voice. "Do you not know Sacrifice? We all know the Truth of the matter. Terellia can afford to share it's bountiful harvests with it's brothers and sisters."
Okin could see a line forming between the two Impaliases as Mathelin glared at the older man. Henard's face held only a soft, nearly condescending smile. Mathelin bristled, but did not back down. There was an internal order to which the Impaliases seemed to all defer to, if not respect
"I. Approve. This. Motion." Mathelin practically spit each word out. Henard tipped his gray head with a satisfactory smile. Volmunst gave Okin and the others a respectful nod.
"A second issue, resolved," the Mouth said with a heavy sigh.
Okin could tell today's meeting would be a long one.
* Chapter V
** Chapter
Okin sat in Aldwin's study, reading over a stack of reports from his aides. His head still hurt from the meeting two days prior. Okin had expected Impaliases to be composed and formal, he had expected the decorum to be overwhelming. The meeting have been much more casual and adversarial than Okin could have ever imagined.
Had Aldwin somehow kept order amongst the Impaliases? Okin had gathered, from Amesa and Gendro, that Aldwin had been somewhat of a leader amongst them. /Of course he was a leader, anyone would know to respect Aldwin./ Okin did not feel similarly about himself. Previa and his Devinars had barely respected him when they were at the front, and those had been men that he worked closely with and advised: some had even come to him with their deepest spiritual fears. One that should have known the quality of Okin's character, yet they could did not respect Okin. And could he blame them? He was ten years younger than even Volmunst. And he only had two Virtues, the same as some Rothars and Devinars!
A knock came at the door and Okin bid the knocker to enter.
Gendro craned his neck through and gave a cheeky smile. He was holding a plate of food, and the smell made Okin's stomach grumble loudly.
"My apologies," Okin said. "It seems I let my hunger get the better of me."
Gendro smiled, "No apologies required Impalias. It's my job to do things like bring you food after all. Would you like to eat here or in the conservatory? I could also bring the plate back to the dining room if you would like."
"Which did Impalias Aldwin prefer?" Okin asked.
"He enjoyed his lunches in the conservatory. One of the many reasons he had this room converted from a sitting room to a study."
Okin waved Gendro towards the conservatory. "Outside it is, then."
Gendro held the glass door to the conservatory open for Okin. He drank in the sunlight as he sat down at the room's small table. The sunlight gave the room a pleasant, but not stuffy, warmth.
The Rothar set the plate plate of food down. It was a dish of spiced beef on a plate of roasted vegetables, with a dark red sauce that drenched the plate. "Aldwin picked a great cook, didn't he?"
"He did, Impalias. It is the way I show my Joy and Creativity the world," Gendro smiled.
Okin eagerly dug into the food, shoveling bites into his mouth. He was five bites in before he realized how Gluttonous his behaviour appeared. He set his fork down and wiped the sauce away from the corner of his chin with a mirthful smile.
"I guess Aldwin was more dignified, wasn't he?" Okin asked Gendro.
Gendro leaned against one of the glass walls, watching two birds hopping around each other in the garden outside. "Not at all, Impalias. I don't think I've ever seen a man eat faster than Impalias Aldwin did."
"Truly?"
Gendro nodded. "If he ate at all, that is. I remember when I first began, Amesa would often have to force Aldwin to make time for meals."
Okin could understand why. He had spent the better part of the night reading papers by candle light, but the stack of reports on his desk had only grown and grown. Most of the reports were meaningless numbers to Okin. A confirmation of shipments at a dock, reports on the elevation of this Othar or that Athar, a Krusadars' distinguished actions, a string of murders in one of the northern regions. He knew each of the reports meant everything to someone, but they meant nothing to him.
Okin wanted desperately to slow down and learn each and every person's story. He wanted to know the Othar's and Athar's under him, their wishes, their struggles, their families, and understand how exactly every resource of Whenran was used. But he didn't have time.
"Perhaps it's best if you do the same and remind me when to eat." Okin said as he forked another piece of vegetable.
"I already did, Impalias," a small smile tugged at the edges of Gendro's mouth.
Okin ate the next few bites in silence. He watched the two birds in the garden alongside Gendro, wondering what problems troubled their worlds.
Far off, Okin could hear rapid knocking at the main door. The two clergymen turned at the sound.
"Were we expecting anyone?" Okin asked.
"No, we were not," Gendro motioned for Okin to stay seated as he moved off towards the main hall. A moment later voices came from the hall; it was a voice Okin recognized.
"Previa?" Okin asked, standing. He made his way back to the study as his friend burst through the door, out of breath.
"He's here!" Previa's eyes popped wide with veins, and he looked almost manic.
"Who's here?" Okin looked to Gendro, but the aide was equally confused.
"The man, the one from the East that we've been hearing about. He's here, and he's claiming to be Aredal!"
Okin froze. If he had been holding his dinner plate, it would have shattered across the floor. He had heard the rumours, but they were just that. /Rumours/. Made by some trumped-up warlord in the East trying to spread their heretical religion.
"Y-you need to see him," Previa gasped. "I ran all the way here from the outer gates."
"He's attacking the Citadel?" Okin asked.
"No, he's in the walls," Previa replied.
"He's already breached the wall?"
"He comes in peace!" Previa yelled. "He wants to recruit us? He wants us to join him for something, I couldn't make it all out."
"Thank you for coming to get me," Okin said. He pushed past Previa before turning back. "Gendro, get a carriage and guards ready, and Previa something to drink."
Gendro nodded leaving the study at a run. "Sit, sit, catch your breath."
Previa waved Okin off, "My dad. Where is he?"
"They didn't tell you?" Okin blinked, dumbfounded.
"Just tell me where he is."
"He's in a hospital near here. Two rings in, and four streets clockwise."
"Thank you," Previa grabbed Okin into a tight, sweaty, hug.
The younger man ran off faster than Okin had ever seen him move. It reminded him of what had just happened at the front. Had he made a mistake? He couldn't think about what that boy was up to. He probably was just excited to see his father.
Okin clasped his cape on as he ran to the street. He was surprised to find Gendro ready with the carriage. The aide sat in the driver's position, one armoured Devinar beside him, and another in the carriage. Okin leaped in and yelled at Gendro to drive.
Gendro spurred the horses down Nexon boulevard. It seemed most people in the inner wall had yet to hear of the figures' arrival; along the avenue people milled about their daily tasks, unaware of the gravity of the moment. Okin felt like a fool-- there's no way Previa would be pulling a prank about something like this on Okin's first week as Impalias, would he?
The carriage passed through the gates of the inner wall at a worrying speed. It soon became clear that Previa was in fact not lying. Gendro shouted at pedestrians as they barrelled past shops and homes. Halfway through the outer ring, they began to run into a thicket of bystanders. From inside the carriage Okin could hear their shouts of amazements, but couldn't make out the exact event or words.
"What can you see?" Okin asked Gendro, leaning out the carriage window.
"I can't see anything."
"Get out, we're walking," Okin hopped out of the carriage. The two Devinars fell in behind him, allowing Gendro to take point.
"Impalias coming!" Gendro's voice bellowed over the crowd. The outer ranks turned to see him and parted. A whisper passed like a wave through the crowd at the sight of Okin.
"Impalias, it's truly him!" A man in the crowd shouted in esctacy. "Aredal, reborn!"
Enthusiastic nods followed through the crowd.
"He did it!" Another voice came. "Aredal's power, he has it!"
Okin wheeled on the voice, practically grabbing the man. "What did he do, what did he do exactly?"
"He made us all /powerful/," the man seemed to be vibrating with energy. His eyes had a faint glowing sheen behind the iris. The man claiming to be Aredal had obviously done something to the crowd, showed them something. Okin just needed a reliable source.
Okin pushed past Gendro, despite the Rothar's protest, and into the crowd.
As he neared the front the voice of the man claiming to be Aredal trickled in his ears.
"If you all join the pyramid, all our problems would be easily overcome. We believe this to be the optimal course for us all."
Okin pushed past the final ranks of the crowd and found himself face to face with /his/ God. The man had the correct look of Aredal. He looked slightly older than Aredal did in the paintings. But he had the correct silver eyes and hair. Okin wasn't sure if he felt more comfortable that he had seen this man as a giant statue in the center of the Citadel so many times. He froze like a frog as the man stared down at him with an expectant look.
:comment:
add Ty-Shou description here and double check with references
:END:
"Are you the one claiming to be Aredal?" The word left Okin's mouth in a frantic rush.
"We are," the man's voice had a calming, authoritative air.
"Why have you returned now, of all times," Okin asked.
"Yeah! Is Tregale coming back?" a voice from the crowd yelled. The rest of the crowd drew silent at the name.
"Tregale..." the man paused. "Tregale will one day return, and we will be there to fight alongside you all."
"But how?" Okin asked. If the man was truly Aredal reborn, he would know the Truth. The Truth of it all.
"He will return by his own will," the man said. "If you join me in my pyramid, we can prepare the world for Tregale's arrival."
The crowd seemed to accept that answer.
"Do you really hate Tregale?" Okin asked.
"We do. He is an evil that must be wiped out." The end of the reply tightened Okin's body. The Onorun said that Aredal was a compassionate man. That he hated no one, not even his greatest enemies. He understood his role in protecting, but took no great pleasure in combat.
A cheer went up from the crowd, and Okin felt his stomach drop at the response. The man looked the part, and maybe he had done some special Heraldry, but he had none of the Truth about him. The Impalias fell silent, allowing the questions of the crowd to drown him out. The shells of some questions drifted around his mind, but they were overshadowed by a monstrous, depressing weight.
"When will the others return?" he heard a faint echo in his ear, though the question had come from so close to him.
"Soon. Soon," the imposter said, sounding days away now.
A woman burst through the crowd, "Show it again, please. Show us your power."
Okin turned this time to see. The man smiled at the woman, and touched two fingers to her forehead. She began to glow, until she was a brilliant light in the crowd. She laughed and began to grow. Her laughter shifted to calm and she began to grow back to her normal size. It was as if the imposter had blessed the woman with the gifts of a Light Herald.
"We are Aredal reborn." The man said, his voice booming with Light Herald amplification.
From behind, a new commotion moved the crowd. Okin turned to see Impalias Henard and Impalias Ovolo parting the crowd.
"We are glad to more Impaliases have come to observe our majesty," the imposter said.
"I am Impalias Ovolo, and this is Impalias Henard." Ovolo stood two paces in front of Henard, his hand resting on his sword.
"Your reputations proceed you."
"You claim to be Areadal?" Henard asked, his eyes bounced up and down the imposter's face and body.
The imposter shook his head, "we make no claims. We simply are Aredal."
Ovolo raised a scarred eyebrow. "Why should we believe you?"
"Because your people do," he gestured to the crowd who gave a deafening cheer. "We only ask for your support in our quest to unify Central Marthia under our banner. The world will eventually be united, as your Onorun speaks."
A guard, dressed in a stark white uniform, motioned for the imposter's attention.
"Unfortunately, we do not have much time. The people in Central Marthia require my attention."
As the man turned away, a new shout rose on the wind. Okin recognized the desperate voice as Previa's instantly. He was more than a hundred paces away, trailing a cart with two Istar nurses in it, sprinting as fast as the horses that pulled it.
"Aredal! AREDAL!"
The imposter hadn't heard Previa. The guard opened a portal as Previa continued to barrel towards the Imposter. The portal grew, and Previa's cart seemed to grow further and further with each and every second.
A final cheer went up in the crowd as the imposter stepped through the portal. A moment later the portal collapsed. The sound of thundering hooves came to a halt as Previa drew up at the edge of the crowd. The Devinar hopped off the cart to run through the crowd at Okin.
"Where did he go? My dad, he needs to heal my dad!" Previa grabbed Okin by the shoulder, shaking his older friend.
"I- I think he left," Okin was in shock from the whole ordeal. The crowd erupted in cheering and chatter as Previa clasped his face in panic, but Okin's world shrunk to the little void in his mind.
Previa shook Okin once more, "what do you mean he left!? He just got here!"
The younger man's hair fell in front of his face, his eyes losing focus. Okin could feel Previa's finger digging into his shoulders till the pain surged through his upper body.
"How could he abandon us?" Faces in crowd turned towards Previa's ranting. "He's Aredal, isn't he? Aredal wouldn't abandon us, he wouldn't!"
A bronze skinned hand grabbed Previa by the shoulders, yanking the man off Okin. "Pull yourself together, young man. You are better than this. Do not shame your father."
Ovolo had one hand on Previa's shoulder-- it was he that trying to shake the sense back into the man.
"My dad needs to be healed he won't sur-" a slap cracked the air as Ovolo back-handed Previa.
"What would your father say seeing you like this? Ranting and raving like a mad heretic."
"Impalias Ovolo, there's no need for this..." Henard placed a hand on Okin's shoulder to silence the younger Impalias.
Previa's face fell slowly, "dad would be ashamed... you're right Impalias."
Ovolo let Previa go with a slight scoff. Okin was shocked by the Impalias' attitude, he had seemed a calm mediator in the meeting-- no hint of the domineering attitude Ovolo had just shown could be seen.
Ovolo turned to the crowd and shouted over the bodies, "all of you, disperse yourselves."
Before the crowd could react, the Grand Marshal turned to the two other Impaliases. "I will go inform the Mouth of these events. You two handle the crowd."
Ovolo whistled his horse over and flung himself into the saddle in one fluid motion, the same process would've taken Okin minutes, not seconds.
"What-- what do we do now?" Okin slowly turned to Henard. The older man gave a slight shrug.
"The people will leave soon enough, Ovolo worries too much about them."
"I mean, about the impostor!" Okin shouted. The words exploded from his lips, and by the time they left he tried to shut them. By Henard's look, he could tell he sounded almost as unhinged as Previa.
Henard raised a gray eyebrow, "why are you so quick to label him an imposter?"
"He's obviously not Aredal. He knew nothing about Tregale, and his attitude is all wrong."
"There is no Truth in that," Henard said. "How do we know whether he is or is not Aredal? Those who believe will see the signs. Skeptics like you will point only to inconsistencies and say all evidence is coincidence. To truly embody Truth, you must leave your mind open to all possibilities."
Okin saw the Wisdom in that reasoning. Okin had called the man an imposter based on a reaction, on one sentence and his knowledge of the Onorun. But there was doubtless countless arguments and passages in the Onorun that would justify this man as Aredal reborn.
"I'm sure this will be quiet the topic in the next meeting." Henard said with a smile.
* Chapter VI
** Chapter
It had been twelve days, three whole weeks since the man claiming to be Aredal had arrived at the Citadel. Okin had set a member of his staff to collect all the information they had on the imposter. They hadn't been able to turn up any new information, only growing rumours. People said he was a man controlled by Deionis to trick them all. Others said they had seen him give the man the ability to fly, or that he had healed the dying. None of those were the Truth. Okin still felt it was useful to keep track of and make note of.
Even without the rumours, Okin could feel the difference in energy as he walked towards the central Cathedral. Okin had spent the previous two weeks in Whenran, overseeing certain matters in person. He had returned the previous day via the Citadel's own portal network. Okin had never been able to afford to use the Guild's network of portals, nor had he been granted access to the Citadel's portal network as an Athar. Being able to get anywhere in the Versalist would in a matter of hours was a level of privilege that was hard to comprehend.
The Cathedral was overflowing with worshippers as Okin and Gendro approached. They had come down Nexon Boulevard, passing devotes leaving and making their way towards the Cathedral. In front of statue of Nexon, people had gathered in group prayer, the smell and haze of burning incense filling the street.
Aredal's entrance was even more extreme. People lined the boulevard, shoulder to shoulder, all the way past the statue. If Okin had been just an Athar there was no hope he would have been able to make it to the crowd. Even with his robes on and Gendro's bellowing voice, it took nearly half an hour to get from the statue of Aredal to the Cathedral's door.
Inside the Cathedral, people packed the pews in every one of the four quadrants. The constant song of prayer rose in one harmonious voice from the crowd that shook Okin's very soul. He had only ever seen a mass as large as this outside of the army's pre-battle prayer; those prayers contained thousand about thousands of ranks of Devinars and Krusadars but paled in comparison to the devotary before Okin. As Okin ascended the stairs to the meeting room, the prayers could still be heard in muted tones.
Okin was the first to arrive in the meeting room, alone he finally had the opportunity to explore the details of the room. Portraits of all the sixteen hung around the room. The portraits were evidently aged by their slightly faded colours and faint cracking. It seemed nothing, even in the heart of Versalism, was eternal.
The portrait of Aredal looked nearly exactly like the man who had claimed to be Aredal reborn. The same silver eyes and hair, the same hawkish nose and pointed chin. Upon closer investigation, it was clear the portrait had even included the folds around the man's small thin eyes. It was remarkable how closely the man's appearance mirrored the one in the portrait. As he stared at the portrait, Okin could easily understand how one could believe the man had in fact been Aredal.
"The resemblance is truly uncanny," Okin turned to see Henard enter the chamber. "These are the oldest paintings of the gods we have. They date back to only a hundred years after the Ascension."
The fact caused Okin to take a step back. He had thought these paintings to be a hundred, maybe two hundred years old. To know they were nearly nine hundred shocked Okin. They hadn't been preserved poorly, rather it was incredible they had been preserved so well.
"Do you believe these portraits to have Truth in them?" Okin asked.
Henard nodded in response.
"Then should we not believe the man is speaking to Truth with his claims?" Okin asked.
"It is a component," Henard said after a long moment. "But we must consider every component to arrive at Truth. Come, take a seat, the others should arrive soon."
Okin took the same seat as he had in the previous meeting, Henard sat three chairs down from him. As the first Impaliases arrived, Okin sat alone till Volmunst arrived.
"Impalias Okin," the hulk of a man said as he took the seat next to Okin. Okin gave a small nod in reply.
"I want you to know that I appreciate your support in the last meeting. I find it harder and harder to find sympathy for my people amongst this /council/."
"Of course, Impalias," Okin said.
"I liked your predecessor quite a bit. Very fair man that one." Volmunst gave a long, sad sigh with his words.
"He's not technically my predecessor. I'm only here temporarily." Okin said.
The older Impalias shook his head, "you're a shoe in to be the next Impalias now. As long as you don't completely ruin everything, which you seem smart enough to not do."
Volmunst flashed a quick chuckle and patted Okin on the back.
"Be nice, Volmunst," bald-headed Mikeol said as he swept into the room. "Our role is no easy task."
"I was being nice. Simply complimenting the young Impalias on how well he's performed. Don't you think?"
"We have seen worse," Mikeol sat down in the other chair at Okin's side as the final Impaliases filed in. The small din of conversation fell to silence as the tenth and final Impaliases sat, a man who hadn't been present at the prior meeting. Impalias Xohl'a of Neiexilee'i, the black sheep of the Versalist territories. Like the colonies that had recently been founded in the ruins of Vianarya, Neiexilee'i existed overseas in Caspo, but had full territory status. It was self-sufficient, and one of the more materially rich territories in the Versalist world, and didn't require support from the Wreathwardian territories like the colonial lands did.
Xohl'a was a tall wisp of a man, the Impalias robes fell off the his thin frame to swallow him in a swath of cloth. The man had dark obsidian skin, far darker than any of the Wreathwardian Impaliases, which stood out against the the golden jewlery he wore. Two large golden bands hung around his neck, and small golden hoop earrings threaded the lobe and cartilage of his left ear.
No one spoke as the group waited for the Mouth to descend from his room above the meeting chamber. The Mouth had not been seen or heard from since the man from Bei-San had come. When the Mouth finally descended into the chamber, all ten sets of eyes turned to watch him.
He looked like he had aged ten years in the last three weeks. The already old man now hunched as he walked, new wrinkles had set in across his forehead, and his walk was now shaky and hobbled. Volmunst and Ovolo rose from their seat offering to help the Mouth to his seat. The Mouth waved them off and went to collapse into his elevated chair.
"For the past weeks, I have prayed, fasted, and given all I can to the Gods in hope that they shine their Wisdom upon me. All so I may know if this man from the East is one spoken of in the Onorun. But this is not a question I can answer on my own. I am putting the topic of the man from the East onto the Registir and forcing its selection as the first topic for today's meeting. I'm sure everyone will agree."
Of course that would be the topic, Okin didn't need to see it on the Registir to know it was the only thing that would be discussed on this momentous day. Okin glanced to his side to see Mikeol sit up from his casual lounge. The bald laced his fingers together, leaning forward.
"No comments?
>>>>>>> 683afa9bed43e922e3de5a1bbca3913a6563674d
* Chapter VII
Okin's eyes popped open. The world was blurry, and felt upside down... hazy Light shone in from below. His arm was limp but also in pain, dragging him down to the center of Opartha, wherever that was...
"YEECH!" He felt a little stab at his eyelid-- and another at his chin. He jerked up, and nearly slid off table. Wiping his eyes, he saw the stack of papers he had cut himself on, and a ball of spittle mixed with the ink on the lone sheet below. His curtains were still open, letting a little bit of grayish light into the soft yellowish room.
He jiggled his head and bounced his shoulders until the blood flowed normally and his arms came back to life.
/Knock knock./ He turned to the door. /Knock knock./ That must've been what woke him up.
"Come in!" Okin shouted, his legs still to limp to move.
There was a /chk-- chk/ behind the door. Okin sighed and got up to get it.
He swung open the door and met Previa's bright smile.
"Devinar Previa," Okin's voice was still groggy. "Were you not greeted by Athar Gendro?"
"He told me you had a late night and I could get you myself. This was after I came here three times and he'd said you were busy. No matter which of the Four you are, the requirements for Athar should be to have a little more balls," Previa chuckled.
Okin groaned and his thick eyebrows narrowed at the young Devinar. "Previa, I'm an Impalias now. What are you here for?"
"I apologize, Impalias Okin," he spoke in a voice like a young teen pretending to speak like his father and saluted. "I won't busy your schedule with such non-urgent matters."
"Previa, if you came all this way, stop wasting both of our time and get to it," Okin said and rubbed his forehead.
"I just came to check on you. I know that all these guys are just running around with their agendas," Previa wrapped an arm around Okin's back. "It's just like when you went off to Oleda to study: there's none of the Dockmasters looking out for ya!"
Previa slapped Okin on the back. "'Cept me now!"
Okin squirmed away from Previa and sighed, but the boy inside him had to resist cracking a smile at the 'Dockmasters'. It was the place where all the rowdiness of the teenage boys of the south side of Metheno gathered-- Okin had been the 'mature' 'overseer' who both Tempered the gang, but also let them run wild. But the smile faded as his mind shuffled through the faces-- Previa, Donnin, Losoh, Paal-- /Cynin/.
Okin had forgotten about the man; over these several weeks, he hadn't even really been able to think about him-- it was crazy to think that his old friend returning and nearly /assassinating/ his former mentor had only been the /second/ craziest thing that had happened in the past two months-- scrunched between a possible /Aredal/ returning and Okin becoming an Impalias. Previa and Cynin were closer in age, and were close friends before.
Inside, Okin gasped. He stared at Previa's excitable, sharp eyes-- he hadn't even told the young Devinar that it was Cynin and Damin this whole time.
Previa didn't read Okin's concern-- he had already begun talking.
"So. What do you Impaliases think about-- you know, /him/?"
Okin cleared his throat. Even Previa was thinking more about the Aredal-or-not then what had happened to his father. "Our meetings are of the highest confidentiality. You know that, Previa."
"Oh come on, Okin! This is the biggest event since-- since the Ascension and Creation of the Citadel, for crying out loud! How is it in Truth that we don't know what the Mouth speaks on this issue?"
"That's Imp--"
"Sorry, /Impalias/ Okin," Previa rolled his eyes.
Okin sat down on the bed. His backside had been sore from all the paperwork and meetings. Even his short stint as a purely behind-the-desk logistics Rothar in Whenran didn't compare to how much time in the chair this was-- sheer amount of reading and writing had to be more than triple, even with his whole team of assistants.
Previa plopped down next to him, jiggling the entire wool mattress.
"I will say that there are differing opinions, as you could have surmised, and I have been surprised that so many are so ready to accept that this is without a doubt, Aredal, so immeadiately. But unless you'd like to engage with me in a theological debate-- which I don't have the time for, and I doubt you have the patience for-- there is not much more to say."
Previa nodded emphatically and threw his hands up. "I know! There's no way something isn't going on. Where are the other three?  Isn't there supposed to be an attack from the Five before the Return? "
Okin just stared at Previa. Even though he actually agreed with all the points, he knew that Previa didn't come up with them himself, he was just repeating talking points he heard. He hoped the Devinar at least understood what he was saying.
"I know that the attempt on dad's life was part of this, too. Whoever's behind this just knew that dad wouldn't be pushed around and would stand for the Truth!"
Previa turned and smiled to Okin.
"Thankfully, they didn't know that dad would be smart enough to recommend 'honest Okin' in his place. You're going to tell the world he's a
"But would the Aredal-- the Aredal WE WORSHIP-- really be callous enough to just show up to all his believers, and then leave them without healing one of their leaders in need?" Previa asked.
"I don't think he saw you, Previa," Okin said.
""
Okin looked out of the corner of his eye. There were a lot of debates about the nature of the Gods' perfection, that had moved from spiritual retreats for Athars and theological debates for retired Othars to conversations on the market street, to the dinner table, and to of course, the high table of the Impaliases. Even the minor Gods were seen as holy and perfect, but the Four were seen as /more/ perfect, but does that mean that in every way they could make no mistakes? If that was true, how did they let Tregale and Deionis bring in the Darkness and the other Devils? But of course, it wasn't their fault. But still, that had to be a mistake of some kind, right? The text said that though the Gods have prophesized and created their own destiny, and by that the destiny of all of Opartha, even they could not stop all the Darkness alone, which is why Versalism was required. If they had Returned, would they be perfect enough to hear the needs of
every person, or was that just not even possible as an incarnate being, regardless of perfection?
"Whoever the assassins were that day, I'm gonna find them, and I'm gonna unveil this whole conspiracy!"
This was a smooth opportunity for Okin to tell Previa about Cynin-- one he needed to take, even though it made his skin crawl. Truth was not just telling no lies when asked-- it was a duty to use one's voice to spread it as far as possible.
