#+title: Okin
* Chapter I
"...and instill your Bravery in each of these men's hearts, every one, especially those of your Light, so that none may be deterred either by fickle emotions or the Vices of the One and the Five."
The square-faced man took a pause from his whispers. The flame sung a rhythym under his breathe. He remained still, hunched over with his arms raised in a reverent kneel in the corner of the room.
"And if I may ask again, that you may instill that same Bravery into my heart, not for my achievement, nay, but for my Arising to you."
His golden draped silk sleeves lowered from their raised position until his arms were clasped against his chest. His left index finger traced an invisible line over the back of his right palm, connecting to a line of golden paint already there.
"Bravery", he said under his breathe.
He raised his finger and brought it back in place to repeat the motion.
"Bravery."
Again, and again.
*SLAM!* The door, feet from him, smashed against the wall. The square-faced man jumped. He swung around, arms raised in an awkward stance, barely intelligible that it was one of defense.
They lowered, along with his wide eyes, as he noticed his intruder. From a violent shake, his body gradually stilled.
"Devinar Previa!" he said. "What is the meaning of this?!"
"S-sorry, Okin," an adolescent, crooked smile and slight blush appeared on Previa's face.
Okin shook his head. "I know your father taught you not to disturb a man during his prayers. So I must conclude that this is just carelessness on your part. And that's ATHAR Okin to you."
Previa rolled his eyes. "Since Krusadar Caldro is gone, I was more focused on maintaining the chain of command," he said. "You know me, it's hard to focus on more than one thing to remember at a time... and there's something much more important to remember than that."
Okin raised an eyebrow.
"Maldin tracked the Farsunni who captured Islovol's squad. We're gonna get 'em back!" Previa's eyes lit up.
Okin's eyes narrowed on Previa. Something inside him was always poked by the young man's childish declarations.
"That is Caldro's decision to make," Okin replied. He turned back to the candlelit corner, even though he knew that it wouldn't be the end of the conversation.
Previa looked at the back of Okin's head with wide eyes. He stepped to the right so his shout was basically in Okin's ear. "They'll be killed by then!"
Okin's stare didn't flinch from the light in the corner. "As much as it pains both you and me, if they wanted to kill them, they'd be dead by now."
Previa shook his head. He turned away and opened the door again. "Every second we wait, is a second they're more likely to be killed by those monstrous heretics. What if you're saying that, and they're still alive, then their blood is on our hands!"
Previa turned back to Okin. "Isn't it in Bravery that we risk our lives to save those that need us?"
Okin's lips pursed. His harsh stare softened, and his shoulders shrunk. *Bravery.* He felt his finger against the back of his hand again. *Bravery. Bravery.*
"No." Okin's sternness returned to him. "It is in Temperance and Truth that remain patient, that we get more information about the Farsunni outpost, and most importantly that we follow the orders of Krusadar Caldro to remain on the defensive."
Previa turned and ran like a petulant child, the door sputtering shut on his way out.
"Previa!" Okin shouted after him. He strut through the doorway and turned into the hallway. Previa was quick, and Okin just made out the end of the young man's leather boots turning down one of the fortress' stone brick hallways ahead.
Okin looked down to his unathletic rounders. He grit his teeth and made off, his awkward, intense strides being made by the softness of his rounders and flowing Athar's robes made him look comedic, and he knew it, but he had to catch Previa.
As Okin turned down the hallway Previa had, the young man was nowhere in sight, his footsteps could be heard in the distance but the echo diminished. Still, Okin kept running, he knew where Previa was headed.
A load of heavy breathes and a forehead of sweat later, it was Okin's turn to burst through a wooden door. Before even shoulder-checking it open, he could hear the clank of iron boots being fastened and swords being sharpened.
*THUD.* He burst through, before instantly grasping his forearm in pain. However, he was given no attention, the few dozen soldiers scattered around the benches were focused on hastily equipping their armor, and clammoring with a mess of different chants.
He was shoved aside by an armed soldier already leaving the barracks.
His eyes urgently danced around the room for Previa. The young soldier had armor like an alien quartz statue, shimmering with an austere beauty. It was not painted steel, but a material of its own, like a glowing pearl.
The row of soldiers marching out past him, the clanging of the iron boots, made Okin and shrink. He snapped at himself for his Cowardice, and straightened his posture before marching up to Previa.
"Stop them!" Okin shouted. Even with the commotion, he knew Previa heard him, though it was easy for the young soldier to pretend that he didn't with his visor totally hiding his face, and towering armor supporting it a whole head over Okin.
"I thought you said you wished to maintain the chain of command! I command you to stop them!" Okin got up next to Previa's shoulder and shouted upwards.
Previa turned, his blue eyes just barely visible as he stared down at Okin between the white visor. "And you always tell me that all men are truly ruled by the Four, and should be guided by their Virtues. So I am doing just that."
Previa fully turned and hilted his long steel sword. He tilted his head up so his eyes were gone, and again he was like a magnificent white statue. He took a step forward that shook the ground. Technically, maybe, Okin could keep standing in his way; Previa was the one going against command, and it would be a true crime to attack Okin, and Okin knew that though the adolescent was brash. But he could not do it, his instincts took over to step aside and let the moving white tower thunder past him.
After Previa had noticeably left the room, the rest of the men who were still inside the barracks rushed themselves and each other to follw him, clumsily putting on boots or still having their helmets tucked under their arms. Okin should've stopped them, he had the authority to, but was frozen, and could only let out small utterances.
He followed them out, stuck in between two armored men; he knew, on paper, they knew who he was, his Athar's robes told them that, and he had even counseled them before, but now they were locked into war, and he was just an object to get past. The collosal raindrops of their pounding boots drowned out his thinking; he didn't really know what he was doing, just that he had to do SOMETHING.
After turning down another hall dimly lit by torches, the white stream of the world burst onto him. Three hallways met upon a masssive iron door which had been pulled open, through which the stream of soldiers marched out of.
As he ran through, the soldiers behind him swarming past, Okin scrunched his nose at the kiss of the hot air. The soldiers climbed atop their horses, those who were ahead circled or doubled back and forth to channel the energy they were amping up. Okin looked around for an empty horse, but it seemed that just as he thought one was unreserved, it was taken. Finally, he just ran up to the group of trotting mounting soldiers. As he approached, their walks became more ordered, until they were totally circling around one figure in the middle, and it felt like a defensive shell against Okin. The figure in the middle was that white obelisk glimmering under the bloody morning sun, the mounted Previa.
Previa raised his fist. Okin froze, and the circle opened on the opposite side of the Athar, and Previa's horse trotted out ahead before stopping, the rest of the circle curving to line up behind him. Once they had, he turned his horse back to the squadron. He opened his visor, revealing his thin but energetic face, and raised his armored fist again.
"The energy in the barracks has been morose. We came here to FIGHT Darkness in strength in the open promise we made to The Citadel as Devinars, not slowly watch our friends die and be captured and hear that they burned down another village of our faithful, and capture our brothers, many of who you have been mourning. But-- you have mourned falsely. They are not dead. Now, here, is our chance to fulfill our promise! Open your visors, brothers! Let me see your smiles, let me see your passion!"
The men howled, and most followed and opened their visors. Okin understood the passion. Many of them had been dissappointed by the brutal, yet slow pace of the war; instead of glorious battles, it was characterized by ugly raids, by strategically sound but dishonorable uses of attrition. And though the enemy teased them by setting camps a mere ride from their bases, the message from high command was always to hunker down, prepare, and play the long game. But here, standing with his sword raised, was an opportunity for these young men to earn the glory they came here for.
"When you draw your sword today, men of Nexon, let me see your Joy! Men of Olitheon, show me your Sacrifice! Men of Intillia, show me your Discipline! Men of Aredal, show me your Bravery!"
Their swords sprung from their hilts, and their passion sprung from their hearts. Even though Okin was trying, in vain, to stop this, the strong summoning of brotherhood gave him, as it would any man, the urge to support this valiant effort, even when Okin knew it came from an otherwise forgetful, foolish boy-- in that white armor, on that horse, that boy was gone. A soldier, a leader remained.
"This is not some dishonorable raid, some backhanded pillage like those animals did to the innocent towns on our front! It is snatching our loyal brothers from the venomous jaws of Darkness! And if you are here to fight for your brothers, then RIDE WITH ME!"
Previa raised his sword again. The rest of the men did in unison.
"VIR VERSALIS!" The men shouted. "VIR CITADEL! VIR VOUR!"
"CHARGE!" The men hilted their weapons, then screamed and whipped their horses into a sprint. Previa raised his sword even higher to the sky.
Okin was thrust out of the moment-- he was here to stop this. But it seemed his chances were charging away towards the enemy camp.
"Previa!" Okin shouted with his whole body just as the white-armored soldier had finally hilted his sword to join the rest of his charging army.
Previa stopped just as he was about to whip the reins of his horse. He turned around just as Okin ran up to his saddle-side.
"Okin?" Previa stopped and pulled up his visor. His face was mired with geniune concern and shock. "Get back in the bunker!"
"You have to stop them, Previa!"
Okin looked like a child next to the mounted Previa. Though Okin was almost a decade older than Previa, Previa stared down at him like a concern adult to a lost child.
"Even if I wanted to, it's too late. They would fight on even if the Mouth of the Gods showed up to stop them," Previa sighed. "But you do not want to be here when the enemies' riders and Portalers chase us to try to get their prisoners back."
"Previa--"
"Go inside, Okin. I'll see you later."
Okin stared at Previa. Part of him wanted to jump on the back of Previa's horse, or run back in and grab some gear. But then he looked down at what he was wearing, and his shivering body, and by the time he looked up again, Previa had already turned back to his charging army, and made off.


"Unacceptable!"
The mustached man's meaty hands slammed down on the stone table.
"But Krusadar, what I'm saying is right! We got Islovol's squad back, all alive! The mission was a success--"
"Did your mother make you out of dirt? That's the not the point! You disobeyed orders!"
"To save lives--"
"Do not speak over me, Devinar Previa!" The Krusadar rose to his feet. "You saved no lives. The Farsunni thought your attack was just the start of a proper raid, and sent out an entire company after you killed the original pursuit. To ensure that the entire front wasn't destroyed, the neighboring forts had to send out nearly half their men. We're now waiting on reinforcements as far back as Klivor, and there will be much more casualities than anticipated," the Krusadar's thick eyebrows stared down harshly at Previa, who looked down in embarassment. "You might've saved a handful of men, but you've doomed thousands."
Previa's hands clapsed the bottom of the wooden chair, and he rocked back in forth in it, his eyes glancing around to the drawn maps of the region on the walls, desperately avoiding the Krusadar's harsh, continuous stare.
"Now you, Athar," he turned to Okin. "I put you in charge of the men, despite your lack of military experience, as I wanted someone higher than a Devinar to be my substitute. I saw how the men respected your character. I hate to be wrong, but I was, wasn't I?"
Okin looked down. "You are right. I tried to bring order, but it was my lack of character that got in the way."
"Honest as ever, even when it hurts you," the Krusadar paused, his large hands clasped just under his wide chin. "But I cannot respect your lack of authority when I put you in charge."
"You are both hereby dismissed as acting service members of the Versalist military. Athar Okin, as we are equals, and as I assigned you to a post of which you would not normally be expected, you are merely released to go back to your regular town cycle or to return to The Citadel or another center for reassignment. Devinar Previa, as you were the instigator of this unauthorized assault, as your commanding officer I am issuing a discharge and a description of this incident will be added to your permanent record. Any questions?"
Previa's head hung low. Okin just shook his head.
"Good. Now get out of my sight."


Okin stared out over the horizon which stretched across over the sandy mountains, where a light breeze created a pleasant translucent curtain of sand, the red sun comfortably veiled by both the curtain and its seat between two mountains. He appreciated the natural beauty of all lands he came across, and always thought to how each of the Four contributed. All gave an equally necessary contribution, but some he had an easier time than others understanding; Intillia brought both the earth, and the waters, and the gasses and winds in the sky; Aredal brought the Light for all living things to see by, through which this view would otherwise be impossible, and by it the heat which allows all living things to survive, and according to some of the newer Istars apparently, also the sustenance for plants; Olitheon, he could somewhat understand, brought the actual area where all things are, even the stars, but not the actual objects itself, those were still Intillia and Aredal. Him and Nexon brought many other things that were quite confusing. Okin tried to comprehend it abstractly on his own time, and even ask Istars he met in the natural sciences, though it made him uncomfortable, but still, he could not really comprehend it. Still, he trusted it and felt it in his prayers, which was what was most important.
"I'm sorry Okin."
Previa interrupted Okin's tranquil observation, and brought him immeadiately back to his current air of disdain. Okin turned around and continued heading forward with Previa up the hill.
"That's Athar Okin to you."
Previa raised his hands, "Oh come on, Okin, we've known each other since we were kids--"
"That's Athar Okin to you," Okin's voice sunk like a swamp.
"Okay, okay, ATHAR Okin," Previa said. "So, uh, now that this all over, what's next for ATHAR Okin?"
Previa looked to Okin with the open eyes of a puppy. Okin ignored him.
"Come on, I know you have some plan in that big, meticulous brain of yours."
Okin's glare snapped onto Previa.
"This isn't nothing, Previa. I came here for a reason. To force myself to really JUMP into Bravery."
"You didn't come here to help the Citadel spread the holiness of the Four against the Corruption of the Farsunni heretics?"
Okin glared at Previa. Previa gave a sheepish smile, before sighing.
"This was important to me, too. This was a chance for me to grow in Bravery, and Temperance, too. I know how you feel."
Okin's glare softened. He waited for Previa to hoist himself upwards into the cart. Previa offered Okin a hand, but by then Okin was already himself getting into the cart, and he didn't take it.
Previa collapsed against the side of the cart, and rested his cheek on his arm which he rested on the side of the cart. The cart bumped up and down against the cobbly road, and the young Devinar just let his face slide into his hand like melting wood.
"Well, if you have to know, I'm going to the Citadel. Probably to see Impalias Aldwin."
Previa sighed again. He stretched his arms and readjusted so his arms provided a cushion for his back against the cart.
"Yeah, I think I'm gonna have to go see dad too."
Okin stared away from Previa, outside the cart. His eyes drifted, not on any of the dry yellow countryside, but past it. His mind was on what the future could hold, but it was just soft, meaningless impressions.
He raised the back of his hand into his gaze. The singular golden stroke shone in the Light. *Truth.*
He stretched his other index finger against it. He drew out an invisible stroke, coming out from the other golden stroke. *Bravery*, he said to himself.
He drew the stroke again, keeping his finger on it even as the cart jumped upwards and his whole body shook.
*Bravery.*
* Chapter II
** Notes
- maybe change the intro as Previa should be wearing the armor
- maybe they should have squire-like Infantis assistants
- unit of measurement mentioned, right now feet
- Neiman mentioned
** Chapter
"Impalias Aldwin," Previa said. He bit his lip till it formed like a parted wave, and his eyelids covered his irises in a bored expression. "You know, *Impalias.* There's only like ten of them."
"Yeah, exactly, I know, *Impalias*," the bearded man shot back. "But for what reason on Opartha would a kid like you need an Impalias for? Or better yet, why would an Impalias take their precious time to meet with a kid like you?"
"It's not for clerical duties, Virtues, or anything of the sort," Okin stepped in, already feeling enough embarrassment from Previa. "It's a personal matter. We know Impalias Aldwin personally."
"He's my father," Previa scratched the back of his neck and smiled sheepishly. The bearded man gave an unimpressed nod, and Okin scowled.
"Oh. Well, regardless, I don't really have anything to give you beside the common knowledge that the Impaliases spend most their time near the center of The Citadel," the mustached man grunted.
"Oh," Previa's smile faded. "Well, thank you anyway, and may the Four bless you."
"Four bless you too," the man said plainly before strutting away.
"Ugh," Previa shook his head. "Made myself look like an idiot, and I still have to have all this anxiety as we wait to find him. Of course some random Rothar wouldn't know where we dad is."
"Temperance, Previa, Temperance," Okin said.
"You know, it's not that I'm impatient, it's just that it's like-- it's basically like what's happening right now is the same as when I was a kid," Previa blushed, "...coming home to dad after getting in trouble."
Previa glanced to Okin, checking to see if his friend related, but Okin gave away nothing.
"Oh come on, don't tell me you never got into trouble as a kid? I mean come on, you weren't *that* stuck up and perfect, Okin," Previa raised an eyebrow at his own question, and then leaned closer to Okin. "You weren't, right?"
Okin just bit his lip.
"I coulda sworn I saw you got in trouble with one of the Istars," Previa rubbed his chin. "Yeah."
A slight smile appeared on Okin's face. "Your memory is better than I expected, Previa."
Previa matched Okin's smile with a tooth grin. "I knew it! I told Vashod you were one of us!"
Previa gave Okin a friendly slap on the shoulder, and Okin's smile faded. Previa chuckled a bit more, and Okin let it fade off into awkward silence between them, and the bustling of The Citadel to fill their ears. Okin and Previa both glanced around for a while. Though he was by no means a listless slacker, and Previa, though less conscientious, was definitely more filled with actual energy which caused a certain form of industriousness, Okin was surprised and with the Citadelian's defiteness of movement, in a sea of other men, inches away from them, all on their own path and mission, they just stared straight ahead as if they were the only ones in existence. It reminded Okin of the preoccupation of wild animals, and in that way, it made the people feel less human, and though definitely more alive in some senses, less in others.
Okin cleared his throat before turning back to Previa and continuing. "But I liked your attitude on our trip here more than this distracted nostalgia. Now is a time to learn from what happened and look ahead, regardless of your feelings of shame."
Previa's lips pursed, and then he nodded. Okin often debated with himself whether Previa really took his advice to heart as best as he could and mostly suffered due to his own undisciplined nature, or if the lad just wanted Okin to like him and thus just tried to appear as if he was processing things.
"Good advice, Okin," Previa said, but his focus was obviously on something else. Okin peeked over the young man's shoulder and saw what he was staring at-- a market stand where some young dough-faced boys were being handed a large, thick yellow pastry covered with thick sugars on the top.
"Well, you never said how far I should look ahead, and looking ahead about thirty feet, I see something very tasty--"
Okin sighed and shook his head. "Go ahead, Previa."
Previa smiled and ran forward a few steps, before turning back to Okin. "You want any?" he asked.
Okin shook his head no. "Temperance requires especially that times of personal dissappointment are not met with indulgence but with quiet, even uncomfortable, introspection."
Previa looked up in thought, and then took a step back. "You're right, I won't have any."
"No, no," Okin looked down. "I'm sorry, Previa. I'm probably coming off as a stickler. I didn't mean you shouldn't have one."
Previa's lips pursed. "Yeah, but, I feel bad having one if you don't. What about, I just get one, and we split it. It'll still cause me to do like, that introspection, 'cause normally I'd probably have-- well, two."
Okin laughed and shook his head again. "Oh, alright," he said.
Previa ran to the stand, excitedly exchanged some coins for the pastry, split it in half and handed it to Okin. The two enjoyed the snack as they kept along the large stone brick main road of The Citadel, towards the towering statue of Olitheon ahead.
"So, do you think," Previa said between bites, "that the Citadel will be able to beat Farsun and Surkusch without us?"
Okin bit into his snack. His eyelids lowered to say, *seriously*?
"I'm kidding. But I mean, in seriousness, do you think we'll win?"
"Well, the Onorun says we will encompass the world. And we beat them before, and they have less men then us, and they seem to be losing now," Okin said. "So of course we will win."
"Yeah, but I mean like, when? Like you know, do you think we're living in... like, the Advent?"
Okin's eyes narrowed, but his head was obviously spinning.
"Only a fool or a demagogue, will say, before the signs have come, that they are near, and therefore, change should be upon us."
"Neiman Seven, Eighteen Four," Previa finished with Okin in unison. Okin raised an eyebrow and smiled.
"But I mean... you've heard the rumors that there's a man in the East..."
"Enough," Okin said.
Previa nodded. Okin looked away to get his mind on something else. It was true that he did think of these things, but he trusted in that verse, and understood why it was there, not just to heed people against manipulative opportunists, but also for the sake of the ordinary Versalist's sanity. Though the Onorun ultimately foretold the events during and after the Advent as ultimately the lead up to paradise for all, Okin was still fearful that things would change too fast, that his lifetime would be derailed. But those were selfish, small-minded, unholy thoughts.
Okin looked forward as the already busy streets got more dense and noisy. Ahead, a large crowd had gathered, all within the shadow of the massive statue of Olitheon, which was being cast to the left. He and Previa stopped just at the edge of the crowd. Near the front of the crowd, low horns rumbled.
"Dad should be serving near here... but this is an awfully large crowd just to get into one of his services," Previa said. "Still it is Olithday, so..."
Okin tiptoed to get a better view, and could see a large wooden pole peeking above the crowd. His stomach twisted. "I-I don't think it's a service."
"Let's get closer," Previa said as he started manuevering through the crowd. Okin squeezed behind him, uttering constant "excuse me"s and "sorry"s.
As they reached a few rows from the front of the crowd, Okin's suspicions were confirmed. He stared up at the wooden platform, upon which the large wooden hanging post sat. His throat squeezed up.
"Oh," Previa said as he also looked upon the wooden post. The Devinar's eyes bounced away to group of men on the side, just next to the stairs where the post, coming out from the entrance of a large cathedral made of painted stone.
"There he is," Previa pointed to one of the men, in the middle, who wore robes similar to Okin's, but with purple stripes instead of golden ones, and with a large cape that also came out in an apron-like structure but split in the middle, outfitted with geometrical engravings. He was clearly the central figure of the group, being guarded by many heavily armed men. "I think he's the one hosting this."
The horns, which had been playing a low, ambient rumbling, suddenly erupted. The man in the ornate robes marched onto the stage, surrounded by five guards all in different, unusual colored armor-- one was the same as Previa's, glowing with a softer version of the sun's glare, one a goldish yellow, one a crimson red, one a deep blue, and one a mix of several colors in a swirl, all glazed over with the same glow, which was shiny, yet contained. They separated out onto different corners of the stage, except the one with the white armor, who grasped a thin, dirt-faced man, pushing him forward, just behind the central robed figure.
"I'm gonna move back just a bit," Previa whispered into Okin's ear. "I don't want dad to see me and get distracted."
Before Okin could protest, Previa snuck backwards and the crowd moved forward to fill the gap. Okin's eyes returned to the thin man, shivering under the massive shadow of the armored white man behind him.
The horns erupted again, even louder this time. The robed man raised one arm, and there was silence on the other side of the blast.
"Olitheon bless you on his day," the robed man smiled. "Let us all, and especially those moving towards his heaven, be filled with Curiosity, Humility, Wisdom, and Sacrifice. We are standing under him today in more ways then one." the robed man looked up at the massive statue above, and there was some chuckles.
"As we observe our world, and our language, without the enlightenment of Versalism, we often see the opposite of Darkness as Light. This, while intuitive, is a Deception from the Darkness itself. It is a misunderstanding that creates an imbalance in our worldview and priorities. The reality is, that it is all Four, in balance, that stand in opposition to the Darkness. And today, as every Olithday, we stand in recognition of how Space works in opposition to the Darkness. In fact, it was the Wisdom of Olitheon which first saw the evil of Tregale, as well as the Sacrifice of Olitheon which saw to his banishment."
The white-armored man threw the thin man against the post as the robed man continued his speech. The thin man groaned, and Okin could see that he was barely a man, moreso an adolescent.
"But even though Tregale's banishment prevented Darkness from taking over our world, the war against its evil was not finished, nay, the Gods desired that many things be spread to us, that we be a part of their mission so that we could join them in the Four heavens. That we all take part in the war against Darkness, and spread the Four rightfully across the Earth."
The thin man let out a moan like a pleading animal. He was silenced by a backhand from the white-armored man, which erupted in a squeal, and a pang in Okin's chest. Okin shielded his eyes.
/These are the Forces of Darkness... they seek to destroy Versalism, the Citadel, and the world... there should be no mercy for them, as they have no mercy.../
Okin looked back to the stage. The robed man pulled out a torch.
"Every destruction of the followers of the Darkness is one step closer to its total banishment, to the total arrival of the Four on Opartha."
The red-armored guard walked over to the robed man, lit his torch, and then stepped away. The robed man raised the torch high in the air.
"Vir Versalis!"
The robed man shouted, and the crowd erupted with him.
"Vir Citadel!"
Their shouts punched across the dense streets.
"Vir--"
FTSK! Several balls of fire sparked into large plumes of smoke near the stage. Screams tore through the streets, and Okin shielded his eyes.
* Chapter III
** Notes
- feet mentioned as measurement
** Chapter
Coughing ahd shouting surrounded Okin. The crowd moved like restless waves. Okin's eyes were on the central cloud of smoke, blocking where the robed man and the posted thin man were before. The colored armed guards moved in from the corner of the platform towards the smoke. Okin knew something was happening... that the robed man, his mentor and friend, and his friend's father, was under attack. But what would he do? He would just get in the way of those who could actually defend, the guards. And the screaming, the smoke, the fear he admittedly felt but hated at the prospect of the thin man being burned... it was too much. Okin was taken up by the waves of the crowd, surrendered himself into its waters.
But after running a few paces with the crowd, he had to turn his eyes back to the chaos of the central platform. He saw a man emerge from the smoke at the front of the platform. He was dressed as an ordinary urban peasant of the Citadel, in a long tunic of natural browns. But Okin knew the man was not just an ordinary peasant, he was the one who had created the smoke, and from the looks of it, this was an attack. Okin was some twenty paces past the man, with the crowd flowing in between them. The colored guards were preoccupied and stuck in the smoke, and it seemed that neither them nor the crowd noticed this man descending from the platform. Maybe this was his chance. His chance for Bravery.
Okin turned against the weight of the crowd. The shoulders moving against him bucked against his, but he stood his ground. Suddenly, Okin's gaze met the eyes of the man. His face was gaunt and scarred, more dark and weathered than most peasants in the eastern Versalist lands, though it was still obvious that this was a rather young man. But something in the man's eyes, a deep, fiery hatred, said that he knew Okin. And in that gaze, and some features of the man's face, and with the knowledge that that man had attacked today, and likely attacked the robed man, Previa's father, a thought coalesced in Okin's mind.
/Is that-- is it Cynin?/
And then, as it often does, Okin's mind exploded in panic. /Cynin-- he's a Herald. And he just killed Aldwin. And he's here to kill you too./
Okin turned back into the mass of the crowd and just ran with it. He crossed shoulders with many people, hoping to just lose Cynin in the sea of the crowd. He did not look back.
Finally, the crowd slowed their movement, but Okin was still stuck inside its mass. It became clear to them that they had dispersed far away enough from the conflict, which seemed to not have escalated further. Okin, along with many of the others, turned back to the scene. Okin searched for Cynin, but he couldn't find him. Okin pushed through the crowd, ignoring their murmurming. When he reached the edge, he ran back toward the platform. The smoke was still building, half covering the face of the cathedral behind it and half covering the bottom of the much taller statue of Olitheon to its right. However, the guards had all descended from the platform. They were running to surround someone who was knelt down-- it was Previa, with his father in his hands. Okin glanced around the entire intersection, and down the street him and Previa had come down before. Finally, he caught a man running to get on a horse. He wasn't certain, but was quite sure it was Cynin.
"It was him!" Okin shouted at the group of Devinars and colored armed guards, and pointed towards the man getting on the horse. "I saw him come out of the smoke!"
The guards took a second between them to decide if they trusted Okin, then nodded and ran towards the man on the horse. Okin watched them run towards Cynin. He could follow, but it was probably pointless for now, they would catch him or they wouldn't.
Instead, he turned back towards the knelt Previa, who was actually sitting on the floor. The young Devinar sobbed. Okin moved to the side to get a better view of the robed man, who was collapsed in his son's arms. Okin grimaced; Previa's father looked beyond old, like if a man kept growing after he was dead. The first thing Okin noticed were the offness of the man's colors, his hair was much longer than before but scraggly and twisted in many different directions, though it was gray before, now it was streamed in several uncomfortable shades of grey, his teeth were yellow, and his skin was also a whitish-gray. The man's gaunt hands lay motionless on the ground, his fingernails half as long as his fingers. His eyes were wide, as if they were being stretched open, and he had massive drooping bags which contrasted against his now ghoulish skin.
"Dad! No, no, no, no!" Previa shouted and kept shaking his father. Previa held his father's cold face against his cheek. "Please! Oh Aredal!" He screamed up, but past, the massive statue above. "Oh Aredal! Give your Compassion to my father! Oh Nexon! Give him your Care!"
He screamed directly at the statue just above them, with both its palms outstretched as if it was holding a large ball in front of its chest, "Oh, Olitheon, on your day, if it is my father's final hour, I know he will be blessed in your heaven, but please, give him some more time on Opartha, please!"
Okin's heart wrenched at Previa's sobs. He walked close enough that Previa could see it was him and leaned down and hugged his friend.
"I'm sorry," he said. "I'm sorry."
Previa kept hugging his father's cold body close to his chest, but he leaned into Okin's shoulder to wipe his tears.
"Who did this?" he said, his eyes red. "You said you saw who did this!"
Okin's throat froze as he pulled away from Previa and met the Devinar's teary eyes. "I-I'm not sure, but I think-- I think it was Cynin."
Previa's jaw tensed. "That's not-- he'd be dead, Okin."
"But, it would make sense, him coming to kill Aldwin. And he--," Okin said.
"How would you even know it was him?" Previa asked.
"I-- like I said, I don't. But it just, it looked enough like him," Okin said.
"I mean how far away were you?" Previa asked.
"I don't know. Twenty feet, or something."
Previa's fist clenched and he stared off in the direction of the street they came from.
"Devinar Previa," Both Okin and Previa looked up to see the red-armored guard standing over them. "I'm sorry, but we have to clear the streets and get your father to a hospital."
Previa nodded and wiped his eyes. Awkwardly, he slid held out his father's limp body to the red guard and another guard in plain armor who picked him up by supporting his back and legs respectively.
Previa immeadiately jumped to his feet like an angry teenager itching to get into a fight. "He went that way, right?" Previa said to Okin and pointed down the street.
"Y-yeah, "
