* Document Overview
* Ages of History Overview
** Pre-Gods Age
** Age of the Gods
** 
* Age of the Gods
1: Ascension, Revictus poses as a mortal and introduces the first cannon books of Classi Versalism

70: Revictus seeks out the snake to know if he is doing the right thing with establishing Versalism. Tregale is giong to come back from a Dark Herald child. Pushes the religion to make dark ontologicaly evil

80: Everyone is succesfully converted to Citadel Versalism

90: Kingdom 1 becomes Versalist

130: Kingdom 2 joins

175: Nairfalk joins Versalism, breaks alliance with Kingdom 9 preventing them from joining in wars against Delmia

180: Citadel construction begins

350: Kingdom 5 joins 

370: Tregale Five Guy gets enough of Region 10 to put him as a threat to Revictus

578: Revictus goes to the snake to find a vision about how to counter the Tregale Five Guy's rise. Sees how to kill the guy and things make him sus of Neiman.

580: Tregale Five Guy's empire reaches the height of its power

583: Intillia moves the Monastery to the bird and offically begins it's mission

590: Versalist Empire goes against the other Wreathward coalition

610: Neiman has doubts about the path and gets her own vision from the snake. Sees herself with Tregale and the Tregale Five, but without the Tregale Guy. Neiman kills the snake

650: Zombies overun the Versalist kingdom in the colonies. Intillia fails to save the colony and blames Revictus for not helping more. The Monastery becomes total isolationists

665: They kill the Tregale Guy. Neiman confesses her vision to Revictus. Revictus wants to kill her but isn't able to, lets her go and she leaves with the light weapon.

670: The Wreathward war ends, southern Farsun + Region 8 are conqured by the Citadel. Citadel joins Kingdom 9's war against Delmia

673: Region 6 joins the Versalist Empire

675: Farsun and the Empire break the peace with Wreathward. 9 officaly joins the Versalists

676: 

Revictus tried to fight the Zombies in the colonies, founds a civilzation that dies

Dead Tregale Five guy creates Kingdom A to rival the citadel

Revictus kills one of the Tregale Five

Revictus brings Jaralad into the fold in the fight against Tregale

Revictus eliminates much of the Gaoleian plant

Neiman gives the Light weapon to Farsun

Wreathward defeats the Delmian Empire, leading to the collapse of the Empire

960 AA: Gendro ere Unerio adventures deeper into Vianarya and discovers that the Aeroblaze has receded, as well as discovering massive Crysal deposits in Central Vianarya. The re-colonization of Caspo and Vianarya begins.

967 AA: The GaoLeian Empire (and Pirate regime) is officially disbanded, Apathasawians begin colonizing Caspo and Vianarya

1000 AA: Billy’s father is killed

1010 AA: Billy visits his father’s grave
