* To Do
* Part I
** Chapter I
Ty-Shou was three years old, but not a child. He had appeared fully formed in ball of light. The people of Bei-San claimed he was the reincarnation of a long dead god. Every step Ty-Shou took in the city was met with rapturous praise. People told him of all the legendary feats he had accomplished in his past life. They said that Ty-Shou built the city of Bei-San itself, that he had sheltered the people from the great turmoil of the Age of the Gods, that he had been able to transform people into the best versions of themselves. None of which he remembered.
"My Synodontis, please focus," the use of Ty-Shou's formal title cut through his introspection. The words had come from Wosa, his closeXst advisor and the man that guided him through his rise to fame. He had the silver hair— thinning at the temples —and silver eyes, typical of a Bei-Sanian. His wrinkled bronze skin was similarly typically of the city's populous. He was shorter than the average Bei-Sanian, and almost two heads shorter than Ty-Shou himself. Wosa carried himself with authority despite his stature. The old man easily filled the voluminous multi coloured robes favoured by the cities aristocrats. His own colours more muted than those worn by the two other servants in the room.  
"We've had this lesson a thousand times already. Can we at least go outside if we're going to be repeating lessons." Wosa insisted on conducting Ty-Shou's lessons in the same room every day, no matter the season or weather. The room was at the heart of the palace, with no windows. The room was lit in an iridescent glow from the Light Crystals around its perimeter. 
"If you stayed engaged throughout the lesson, perhaps I could rest assured that you understood the materials." Ty-shou hated the soft, suffering look Wosa so often had. "Now, what is this Crystal used for?"
In his hand Wosa held a perfectly black Crystal, one that appeared more as an absence of light than an actual object.
"It's a Dark Crystal. A full Dark Crystal," Wosa gestured with is fingers, urging Ty-Shou to go on. "This one is filled with a memory of a great battle. You're going to use your Heraldry to show me the memory so I understand how brutal the Vareeshi are."
"Good, but do not roll your eyes when you speak. The Synodontis does not roll their eyes."
Ty-Shou rolled his eyes again. The young god truly didn't understand this song and dance. From his first lessons in geopolitics, Wosa had emphasized how brutal the Vareeshi religion was. A religion built on might makes right and winner takes all, where people swore themselves to great men in the hope they would conquer all and lead them to eternal paradise. In Bei-San, the Vareeshi were a religious minority. But it was the only way of life for most of the neighbouring Central Marthian nations. Now that Ty-Shou was to leave the city for his first time, Wosa had been insistent on reviewing, and amplifying every lesson he had had on the Vareeshi. Still Wosa thought Ty-Shou didn't properly understand it, and had devised to show him a memory of Vareeshi brutality. Wosa helped seeing how they made their hierarchies, and how brutal the King Making fighting was would work better than lecturing Ty-Shou.
With a flourish of from the older man's hand the two servants covered the Light Crystals, plunging the room into darkness. Wosa's weathered fingers gripped Ty-Shou's forehead. The outline of the Crystal in the advisor's hand gave a false glow as Ty-Shou felt himself plunging into the false sleep of memory viewing.

Ty-Shou didn't know much about the man who's memories he now inhabited. The Synodontis knew instantly that his new body was shorter than his real one. Height was always one of easiest ways for Ty-Shou to spot an inserted memory.
He stood near the centre of a vast circular chamber. Pillars of painted red wood around the perimeter rose 50 feet up to hold up a wooden ceiling, intricately engraved with Vareeshi writing. On all sides of Ty-Shou a frantic mob pushed in, jockeying for position. The attention of everyone in the chamber was fixated on the structure at the very centre of the chamber. A towering triangle, nearly the height of the chamber itself. Ty-shou knew from his lessons that the triangle was made of a specific wood, found only in the Central Marthian valleys where the Vareeshi monks made their homes. The triangle was split into multiple tiers, each bigger than then the last, and filled with intricately designed wooden balls.
Ty-Shou held a similar wooden ball in his hand. Half his ball was plain wood, the other intricately carved and painted. He knew the ball was meant to represent the life journey of the person who's memory he inhabited, but Ty-Shou was unable to properly interpret it.
The ranks of the crowd slowly move forward, and Ty-Shou found himself at the head of the crowd before long. Near the base of the triangle, a monk in gray robes stood with his hand out for Ty-Shou. Ty-Shou watched his hand move as the memory played. He handed his ball over and the monk placed it at the bottom of the triangle, in last place. Once the ball in place another monk--- in the same gray robes ---handed him a circular tag with the number of his place in the pyramid on it. Ty-Shou placed the tag around his neck, like everyone else in the chamber had. That same monk called out his name with his number, and the crowd yelled it back in a chant. Suddenly, Ty-Shou felt the edges of his consciousness blurring as the memory skipped forward.

The memory rematerialized as Ty-Shou found himself in the middle of a battle. He was shoulder to shoulder with other men, all holding spears. Mere feet away, the enemy formation of spears thrust forward. All the men he could see wore simple leather armour. This memory was old, at least 400 years old.
A spear tip grazed Ty-Shou's cheek, and he felt searing pain shoot through his body. An equally intense freezing fear set into his bones. Ty-Shou couldn't tell if the fear was his own, or from the memory. Before he could decide he felt himself jolt forward in a lunge. His spear tip danced past an enemy spear and found purchase in their neck. Shoulders pressed up against Ty-Shou as his formation took a step forward. The man next to him dropped as the enemy thrust forward. Ty-Shou's spear frantically worked to parry incoming attacks, but the enemy formation pressed forward endlessly. Around pained moans from his allies filled the air. Men from the back ranks of the formation moved to fill the gaps as the injured were dragged to the back. A whistle blew and Ty-Shou was pulled back as a new front rank swapped in. He felt exhausted, more than he ever had in his short life. His body sagged with the effort, and leaning on his spear was all that kept Ty-Shou from slumping.
The yelling from the formation's head grew louder, and nearer. His grasp on Vareeshi was weak, but he was sure the yelling was in a dialect he hadn't been taught. Around him men snapped to attention. Ty-Shou's grip on his spear tightened. A sudden wave of motion knocked him on the ground as a group of the enemy burst through the ranks.
Two men led the charge of the enemy spearhead. The nearest had long black hair tied in a bun above his head, and a slender face. He wore light leather armour, like the other enemy soldiers. Three men charged him, and each was easily defeated. In his light armor, the man weaved through attacks perfectly parrying each with his straight edged blade. The other man was an obvious Space Herald. He had short cropped black hair, and a scar across his left eye. Three discs spun around him creating a protective radius around a foot wide.
The Space Herald's eye snapped to Ty-Shou and a disc came flying towards him. He rolled in the bloody dirt causing the disc to barely miss. The man must have been a powerful Herald to move the disc so fast. He scrambled to his feet barely dodging as the disc came back around. The Herald was keeping his distance well, his ally dispatching attacks before they could threaten the Herald. The long haired man moved with inhuman efficiency. He slipped between spears and parried attacks in perfect rhythm, with no wasted energy in each action. It was the same pattern of attack repeated. The long haired man would slip an opportunistic attack from behind, before lunging for the man in front of him. His blade thrust between his victims armour. Before the dying man could drop to the ground the inhuman swords man would reach out with is off hand to grab the number tag around his victim's neck.
Ty-Shou felt fear from the man who's memory he inhabited, but the god knew what the inhumane attack was. A Time Herald. One of the Subject Tree. It explained his superhuman reactions to attacks he shouldn't logically have time to react to, and how he always managed to perfect place himself and his blade. Judging by the number of number tags in his hand the man must have killed nearly three dozen men in his rampage. Two Heralds as skilled as these two could easily break route a hundred men undisciplined men. Ty-Shou saw it happening. The fear building in the soldiers around him, those near the back looking to flee and being pushed back by the elite rear guard. He let out  fierce roar and charged towards the Space Herald. A disc shot out from the Herald in response. Ty-Shou ducked his head and felt the disc graze the top of his hair. Two shouts rose from the crowd as two other soldiers joined Ty-Shou. He could feel his heart beat in his ears as he ran. In three years, his heart had never beat so strongly.
They were 15 paces off the Space Herald now, maybe 12 from his defensive radius. Two discs came at him now, one flying from around the Herald, the other coming in on the right flank. The soldier on his right caught the clean across the throat. The disc slowed to a brief crawl as the Space Herald pulled the soldiers number tag off and towards the Herald. Ty-Shou thrust out at the head on disc, managing to knock it enough to make the Space Herald loose control.
They were 10 paces off now, and the Space Herald had only one disc remaining. If Ty-Shou could close the gap before he brough the other two discs back on defense, he had a chance to kill the Herald.
A shoulder slammed into Ty-Shou. He stuck the butt of his spear in the ground, barely keeping upright. Before he could turn his head a punch clocked him clean across his face, and he was sent flying back to the bloody dirt. The final other soldier in Ty-Shou's desperate charge neared enough to thrust at the Time Herald. The Herald leaned his body perfectly enough to dodge the thrust. The soldier pulled his spear back and the Herald slipped down the shaft to within the weapons reach.
Ty-Shou jumped to his feet to defend his fellow soldier. He pulled a short dagger from his belt and jumped on the shoulders of the Time Herald. The Herald thrashed trying to throw Ty-Shou off. He locked his legs and elbow around the opponent and stabbed down with his dagger. The Herald jerked his hand up to catch Ty-Shou's forearm. The other soldier, discarding his spear, ran up to kick out the Heralds leg. The Herald rapidly twisted around the kick. In the same motion he jerked Ty-Shou's arm down and over, shifting his body weight into a throw.
For the third time in the fight Ty-Shou felt himself thrown onto the ground, this time he was on top of his ally. The whizzing of a Space disc cut the air as it embedded himself in the other nameless solider. Ty-Shou rolled off the body but was pressed to the ground by the Time Herald. He tried to stab the Herald's leg but he had lost the dagger in his fall. His unarmed punch barely phased the Herald as he plunged his sword down and between Ty-Shou's eyes.

Ty-Shou was panting and covered in cold sweats when he came out of the memory. The servants had uncovered the Light Crystals at some point.
"Do you understand now?" Wosa asked.
Ty-Shou felt sluggish coming out of the memory and could barely move his head to nod. "That was... What was that feeling? I- I've never felt it before."
"Fear," Wosa said solemnly. "I'm glad you understand that now."
Ty-Shou knew his heart wasn't racing, but he could still hear the drumming of a heartbeat in his ears. The lingering effects of the memory but have been evident, as Wosa knelt down to meet Ty-Shou's seated eye level.
"You are the most powerful Herald to have ever lived. Those Heralds in the vision have barely a fraction of your power my Synodontis." Wosa reached out to grab Ty-Shou's hand. "I've tried to instill in you how powerful you are, how much capacity for good you have. I hadn't intended for this lesson to reinforce that. Perhaps now you understand both how brutal the Vareeshi are, and how much power you hold."
Ty-Shou didn't reply, only nodded.
"Come, it's time to leave for Cong Lang. We must ensure we make all our appearances at the festivities before King Making begin in earnest. You would not want to experience the real memory now, would you?"
Ty-Shou rose from the chair with a shake of his head. "Of course not."

The streets of Bei-San was overcrowded for his procession out of the city. Ty-Shou rode in a two tiered carriage, pulled by six horses. The carriage had been originally commissioned by the Stewards of Bei-San. The noble family appointed to lead the councils of nobles and govern Bei-San in Ty-Shou's stead. The carriage was a reflection of the prestige and history of the city. It was made of black lacquered wood, with a polished gold trim along it's edges. The panels were engraved with art depicting the most famous of Ty-Shou's feats. The door panel had his favourite engraving. One of him standing against a dragon coiling around the world. The bottom tier was designed as a regular carriage for long distance travel. It was padded seats which could be made out into a full bed by his servants. Light curtains gave privacy, but allowed in a light breeze while on the move. The top level was a viewing platform. A waist hair railing ran around it's edge, allowing Ty-Shou to stand and wave out at the Bei-Sanian citizens as his carriage wound its way out from the palace at the city's heart.
Wosa had help back no level of splendor for the parade. The trip to Cong Lang had a stripped down escort, despite that every one of his mounted Royal Guards had on perfect dress uniforms. A long stark white tunic which flowed down to below the knees, cut in the middle to allow for comfortable riding.  A golden belt secured at their waist gave the top of the uniform a sharp triangular silhouette. The tunic was trimmed in the same shade of gold. In the centre of the chest the symbol of Bei-San was embroidered, a blazing 16 pointed sun held in the palm of Ty-Shou's hand. Their tall black hats provided minimal shade, with a thin rim.
The Imperial Guard were selected for their size strength. No man was shorter than Ty-Shou, all at least 12 hands tall. Each wore two weapons. A long sword for unmounted combat, and a curved cavalry blade.
At their head was Ji-Xing. The head of Ty-Shou's guard, and Field Marshall wore a white hat to match his white uniform. At 45 man was past his physical prime, but could easily beat five of the other Royal Guard at once. The man's face was nearly a perfect square with a jaw line that could cut glass. A scar across his eye gained during his youth only added to the Ji-Xing's fierce nature.
As they passed alleys, Ty-Shou could see people lining up 30, 50 ranks deeps to try and get a glimpse of their god. From the window of passing houses, and from the nearest ranks on the street, Ty-Shou could hear Bei-Sanians yelling for blessings. Some even prostrated themselves on the pavement in attempt to garner his favour. A yell to bless a sickly relative. One to aid a son on an examination. They were all cries Ty-Shou had heard before, and all aid Ty-Shou had no power to grant.
His powers allowed him to heal some of the sick and wounded, but only if he was in the correct mental state. But he couldn't bless people with better fortune, or perform any true miracles. He was a Herald, but they called him more. They called him God.
** Chapter 2
Cong Lang was the crowning jewel of the Central Marthian cities.
** Chapter 3 
Jakari's ball was as elegant as he had promised it would be. The city itself may have been poor in comparison to Bei-San but the palace at its heart
was an equal match. The palace's size and opulence had been clear from the moment Ty-Shou entered the city. Yet, he found himself in awe of the beauty as he approached.
The palace had been under construction for three generations--- commissioned as a sign of Cong Lang's post Delmian independence --- and had only been completed 50 years ago. The complex sat upon the city's name sake, Cong lang or the river hill . The hill around which the two life blood rivers of Central Marthia merged to create the river Keesh. The Yahl River, which flowed down the Nihdan mountains and through Delmian, and the Tacuk which from from the Northern Straight. The confluence of the two rivers had given the city influence, power, prestige, and wealth. Now they had built this palace to reflect all those things.
Ty-Shou's escort for the event was a compliment of only three. Ji-Xing, his protege Qi-An, and their carriage driver. The invitation had specified that only two servants would be allowed per guest, so Ty-Shou had taken a two man carriage tonight. Across from him, Qi-An sat with his attention out the window. The young guard sat straight backed and coiled for action. His internal anxiety was given away only by the rapid drumming of his fingers against his sword hilt.
Ty-Shou had been content to attend alone, he had in fact been looking forward to it. But, Wosa had lectured that it was improper for a man of his station to travel without a guard. Ji-Xing would have protested as equally strongly on the grounds of security. But he was God, should he not be able to go alone if he wanted?
The carriage came to a stop in a crowded stone square at the bottom of the hill. A guard dressed in Cong Lang indigo and teal conversed with the driver, pointing to an open spot at the edge of the square where he could park. Past the guard, Ty-Shou could see other dignitaries departing their carriages. Some wore the more traditional single piece Marthian tunics, while others wore the more modern Kaihanese suits and dresses.
The flowing, over sized, dresses of the women were unlike any that he had seen worn in Bei-San. Wide neck lines plunged to to reveal enough skin to make Ty-Shou blush. The colours were more intricate, yet more muted than the ones worn in traditional clothing, favouring detail over bright ostentation.
The modern suits of the men were tightly fitting. Their pants rose high on the waist and were paired buttoning tunics. Each man also wore a jacket with tails flowing down to their calfs.
Ty-Shou found their absence of head coverings most interesting. The Vareeshi minority in Bei-San wrapped their long hair in silk coverings above their head. He saw similar styling in some of the guests around the square, but many had their hair visible and intricate braids, flaunting the traditional covering of hair. Others wore hats, or shawls. 
A knock came at the door as Ji-Xing pulled the carriage door open. "We're to walk the rest of the path up to the palace, my Synodontis."
Ty-Shou nodded, "we have no complaints."
Ji-Xing took a step away from the carriage allowing Ty-Shou to descend himself. The square smelled of sweet tobacco. Coachmen awaiting their charges lounged smoking pipes or playing card games with the other servants which had been denied entry. Qi-An coughed at the smell as followed behind Ty-Shou.
At the gate, Ji-Xing gestured Qi-An forward and the younger man proffered their invite to the guard. The guard looked it over for a long moment. Did he not trust Ty-Shou? He scrutinized the Synodontis' invitation?
A flare of energy rushed through Ty-Shou's blood as he felt Indignation flare in him. The energy rushed to his finger tips, begging to be infused into an object.
He took a deep breath and let the emotion fade. The rush of power subsided.
The trio was let through the gate with a simple wave. No bow. Not even a note of gratitude for his presence. Only his escort spiriting him past the gate kept him for activating the full force of his power on the gate guard.

The path up to the palace was a beautiful walk. Light lamps lined the path, shimmering iridescent light over the cobbled path. Trees on either side arched over the path isolating the background chatter of the city,  only the occasional croak of a toad or buzz of a bug could be heard. 
"Bastards forced us to walk," Ji-Xing said in Bei-Sanian. The other parties were close enough to hear him, but none of them appeared to speak the language. "It's a power play, they want to tire us out."
"We do not think so,"" Ty-Shou said. Ji-Xing for all his wisdom was an army man. Every problem was military, every action one step towards winning an unseen battle. "It's a display of opulence, not power."
Ty-Shou heard Qi-An gasp as the trio stepped out from under the tree cover onto a carved stone outcropping. The city of Cong Lang and the royal grounds of the palace spread out beneath them. The hill and a large swath around it had been gated off for the royal grounds. Garden paths curved around water gardens and under huge drooping trees. There were no hard lines or symmetry in the layout. Everything had been arranged to flow naturally with the land. How much of the land was artificial was impossible to tell.
From his vantage point Ty-Shou could see the dense city within the walls and far beyond to the towns and farms surrounding it. Ships laden with cargo drifted lazy past each other as they went up the two rivers. From above, drifted the muted music of the ball. No map could have ever conveyed the scale of the city to Ty-Shou. Bei-san held it's majesty in its history, beauty, and its people. But Cong Lang's sheer scale was nearly enough to dwarf those all.
Ty-Shou felt eyes on him from the stragglers on the platform. He had no idea how long he had been staring out at the city. It couldn't have been longer than a handful of minutes. However long it was, was enough to cause a scene. Holding his head high, the god swept past the onlookers and up the final dozen or so steps to the palace itself.
At the top of the hill, a path lined with guards every 10 paces led them towards the open doors of the entry hall. The entry hall jutted out, rising as high as a six story building to a steep slanted tip. Like the rest of the palace was made of a variety of stone from all over Central Marthia, all neutral shades of white, grey, or black. Perpendicular to the flanks of the hall the west and east wings grew. The two wings were identical, defined by their curved glass roofs and huge glass windows. Each window was identical, five paces wide, 60 tall, and placed at 15 pace intervals. Between them, the same white stone as the hall served as the frame work. Ty-Shou had never seen windows so large before. However, it was the curved glass roof, which rose almost as dome, that was the true marvel of the palace.
Vang-Do glass blowers had been commissioned for the project. They were the best not just in the Marthia, but the world. Like all the artisans guild ins Vang Do, the glass blowers were a pretentious, pompous, egotistical institutions. One Ty-Shou was not eager to deal with any time soon.
"For such a violent people, you'd think they'd make more secure palaces. I could take this with two squads. Less if we had Heralds." Ji-Xing let out a small scoff as he looked over the Cong Lang guards.
A small smile of pride crept onto Ty-Shou's lips. He didn't doubt his Royal Guards could.
"I believe I could do it with a Dark, Space, and another Time  Herald," Qi-An said.
His mentor raised an eye brow in response. "Not very confident are you? You need two Time Heralds?"
"Quiet," Ty-Shou said. "we approach the steward."
Qi-An took two broad stride slipping infront of Ty-Shou. The older guard slipped back to guard the Synodontis' rear. Qi-An produced their invite once again and handed it to the man at the entrance.
"Synodontis Ty-Shou Xing of Bei-San and company," the steward voice was amplified by the architecture of the ante-chamber and a short call of horns followed. The hall was large enough that the stewards words seemingly hadn't reached the far end of the hall. At the far end of the hall, one massive throne sat in front of pyramid, filled with balls, large enough to stretch the full height of the hall.
Ty-Shou struggled to distinguish the figures crowded around the thrown at the far end of the hall. Jakari was easily identifiable by his place on this father's thrown. The two smaller chairs in front--- typically for Jakari and his sister ---were empty. Another silhouette stood by his the thrown, likely the advisor. In front of the three thrones a dance floor took up the majority of the hall.
The distinct twinge of disappointment flashed in Ty-Shou. It was a familiar emotion, but the cause this time was surprising. The palace and ball was all he could have imagined. Yet, his disappointment flashed none the less.
"What now my Synodontis?" Ji-Xing surveyed the crowd, his hand not touching, but never drifting from his short sword.
"We will enjoy the refreshments, and speak if spoken to." The two royal guards nodded.
The initial crowd of people, seemed to be mostly lower level dignitaries and business people. No face Wosa had taught. They congregated around small wait high tables, all nursing a drink proper to their gender. Conversations could hear the conversations as he passed. Most were in languages he couldn't understand, but could identify. Some were from Central Marthia, and some from farther beyond. He heard the sweet tonal rising and falling of the commonwealth, the hissing of Trentanian, and even the guttural clipped speech from Aparthasaw. 
"Synodontis!" A voice came from the edge of the crowds, where it gave way to the dance floor. The crowd parted as the voice approached.
It came from a man in his late 30s. He had cool bronze skin and soft, nearly feminine features. His long black hair was tied in two thin braids which fell to small of his back. His nose was scarred, and bent from being set in place more than once.
"King Ruit of Khua," Ty-Shou said in Delmian. The man was easy to recognize from the memories Wosa had given him. He wore a single piece tunic. A thin belt tied in a flowery knot cinched his belt at the waist. Over his shoulders he wore a cloakshawl of sheer black material. It was embroidered with the golden six petal flower of his house. Tassels of the same gold hung around the shawl's edge.
"Synodontis," the king tipped his head down in reverence. Ty-Shou waited for the man's gesture to deepen to a bow. Instead, Ruit rose to stand straight. "I'm glad to make your acquittance. Your reputation proceeds you."
"We have heard much of you as well," Ty-shou straightened his back fully.
"How did Jakari convince you to attend?" Ruit took a sip of his drink as he raised an eyebrow. "Bribery? That's how he got me."
Ty-Shou's eyes narrowed. "You accuse us of taking a /bribes?/"
"Bribes, yes," the king took a long moment finishing his drink. "Favours, a promise of audience with the boy's father, a meeting with the dockers guild, an opportunity to court his sister. Everybody who's anybody received something to attend."
Ty-Shou felt a slight tinge rise in his cheeks. He pushed the blush down with his disgust.
"What were you promised?" Money? Men? Weapons? Ruit was a brutal warlord, having made his claim when he could barely grow facial hair. Men like that wanted only money and power.
"Tickets to the opera," Ruit replied with a laugh. "I give the boy credit, he knows his guests well."
Ty-Shou blinked. "The opera?"
"Yes, in Cong Lang. Everyone knows the opera houses in Vang Do are superior of course," Ty-Shou nodded, though he did not know that. "But Cong Lang is one of the few cities with true artistic culture."
From just outside the conversation, Ji-Xing guard scoffed. Ruit whirled on the man, "was my statement humours?"
"Not precisely, I was just curious. Which cities do you believe have /true artistic culture/. Khua?" Ty-Shou levelled a glare at Ji-Xing. He did not want to reprimand the head of his guard publicly. But he would have to in order to appease Ruit.
The king burst out in a hearty laugh. "No, no. Not Khua," Ruit let out a long sigh. "Not yet. But by  the time of my death, it will be. My people have nearly completed construction on our new theatre. The largest in the coalition. In time we will build great statues, and galleries, and one day the sweet song of opera will fill my city's streets."
Ruit had the twinkle of a dreamer in his eyes as he spoke. It was true, every word he said. Or at least, he believed it be so.
"We have many great stone masons in our lands," Ty-Shou said.
Ruit leaned in, "is that truly so? Perhaps I will have to come during King Making to recruit some."
Indignation flared in Ty-Shou again. He had tried to relate to this interloper, and the king had mocked him. He wanted to reach out to grab Ruit's face. How funny would the joke seem when Ty-Shou infused his indignant rage onto the king's skin.
Ruit let out the same laugh he had only moments ago before his face fell to a frown.  "Ah, it appears I finished my drink."
A lady appeared from the crowd. She had the same skin tone as Ruit and worse a modern dress, one with a fashionable low cut neck line.
Ty-Shou averted his gaze as the woman hooked her arms around Ruit's. She whispered something in the king's ear and they shared a private laugh. Ruit looked between the new woman and Ty-Shou as a slight frown crept onto the king's face.
"It appears I am required else where," Ruit nodded his head once again to Ty-Shou, then to Ji-Xing. "Don't be stranger Synodontis."
The couple disappeared into the crowd and left Ty-Shou was a sharp pang in his heart. It wasn't physical pain, but it was an emotional pain Ty-Shou hadn't experienced before. The distress must have shown in Ty-Shou face. Ji-Xing leaned to whisper as hand went to his sword.
"My Synodontis?" Ji-Xing asked. "Are you well?" 
The older guard made a series of hand motions Ty-Shou couldn't understand. His two guards each held an arm, bolstering Ty-Shou. He shrugged them off instead. "Do not make a scene general."
The pang had dulled to a low ache but was still unidentifiable. Ty-Shou pushed the pain away focusing instead on the crowd of onlookers. A rough circle of onlookers formed around him, all whispering amongst themselves. After a long moment, one man stepped forward and bowed.
"Synodontis, I am lord Nuanaak..."

The next several hours of dragged on with introductions. Ty-Shou remembered maybe a quarter of their names, and cared about even less.
"Where is Qi-An?" Ty-Shou asked in a lull between introductions.
"I sent him to locate refreshments, my Synodontis."
Ty-Shou nodded at his general, "we value your initiative. Our mood would be greatly improved by proper nourishment."
Qi-An returned a handful of minutes and introductions later. He gave a waist deep bow as he drew up.
"Were you successful?" Ty-Shou asked in Bei-Sanian
"I did my Synodontis, the food and drink is set out in the West wing." Qi-An replied still in a bow.
"What of the East wing?" Ty-Shou cut in.
Qi-An paused for only a moment. "I apologize my Synodontis, I failed to acquire that information."
"Nonsense," the older guard said with a scoff. "I ordered you to find the food, not scout the whole damned palace."
"I will go now to find out. If that pleases my Synodontis."
Ji-Xing cut off his protege, "I will go. You need the refreshments more than I do. I've been sending you running around the whole damned night."
"Thank you sir," Qi-An gasped. Perhaps the general had been working the younger guard too hard.
"Go. Half the good food is already gone by now. That's how these parties always work."
Qi-An led Ty-Shou silently around the edge of the dance floor to the West wing. Ty-Shou wasn't sure if he would know that this man was Ji-Xing's protege. He shared none of his master's hot headed tendencies. He never slouched, spoke out of turn, nor swore. The other royal guards were in line with Ji-Xing, but all soldiers seemed to be.

The West wing's interior beauty easily matched its exterior architecture. The room off the great hall spanned the total height of the wing, allowing sweeping views through the towering windows. Art, lit be candles, adorned the space between windows. Two tables on either side of the room were filled with food. Plates were set out in a buffet style, organized from spicy to sweet. Stewards patrolled the room, cleaning away finished meals, organizing food, or bringing drinks. In the centre of the room, a large table was set for 50 guests, though less than 10 sat eating. He recognized two of the people at the table. Kitsai and the towering man that had been with her in the market.
Ty-Shou averted his eyes from the table to the food at the side. He made his way down the table, focusing on the rows of food. Most were unfamiliar to him, and smelled of strange spices.
Finally, the smell of one dish caught his attention. It appeared to be chicken. It's skin looked crisp, and was a deep red colour. They had plated it on a bed of long grained rice.
"It's good, you should try it," a feminine voice said in Delmian. Ty-Shou looked up to see Kitsai two dishes down, her body guard a further three paces back. She wore her hair in a single wide pleated braid. She wore a Kaihani dress, but didn't obey the fashion of the women at the ball. Her neckline was up in defiance of the plunging ones Ty-Shou had seen all night. It formed a tight collar, adding to the slimming effect from her comparatively straight skirts. The maroon colour and silver detailing of the dress complimented her pale skin.
"What is it?"
The woman shrugged as she picked up a baked pastry from a silver platter. "My brother handles the menu, I simply come to observe his work."
"How do you know if it is good?" Ty-Shou asked.
"Cause Jakari isn't very creative," a small smile tugged at Kitsai's lips. "Or perhaps our head chef isn't. But the menu always contains repeated favourites. That one has been on the menu for the last three years."
A steward patrol crept up from behind Kitsai. The princess waved the man off before he could open his mouth.
"I'll call you if I need something Vaitran," she seemed to pause before turning to look at Ty-Shou. "Do you want anything Synodontis?"
Ty-Shou was taken aback by the sudden usage of his title. She hadn't said it with emphasis, Kitsai had used it as if it were his name.
"We would be greatly pleased by tea, Yue tea," Ty-Shou turned to look at Qi-An. "My guard will have water."
The steward nodded and ran off through a servants door at the back of the room.
"Just tea?" Kitsai asked as she ripped the pastry in her hands apart. Ty-Shou could see it was stuffed with spiced meat.
"We do not drink alcohol." Ty-Shou said as he took a step towards the pastries.
"Many would call that a sad life."
"We pity those would rely on such vices."
Kitsai smirked, "don't let the ones out there hear you. Some of those /kings/ and /lords/ out there do not take kindly to pity."
"We care not."
"You might," Kitsai took a bite out of the pastry. Ty-Shou felt his mouth water. "Emperor Voto is one of those men."
Ty-Shou thought he had recognized the Emperor of Delrei in the crowd.
"The emperor is quite the reveller. He-"
Ty-Shou cut the woman off blurting out, "what is it that you are eating?"
Kitsai furrowed her bro holding up the half eaten pastry. "This? It's a meat pie. Do you not have meat pies in your land Synodontis?"
The two Bei-Sanians shook their head. "Our people prefer sweet pastries."
The meat pie Kitsai held was antithetical to Bei-Sanian baking. Not only was it savoury, but it had been baked in a thick dough. Totally unlike the airy, flaky pastries in Bei-San.
The woman took a step forward and handed Ty-Shou the unmolested half of her meat pie. He took the pie without hesitation. The meat smelled unlike any blend of spices he had tried before. The taste was exquisite and the texture unique.
Kitsai let out a small giggle as she finished her half of the pie. "Now I have to try a Bei-Sanian pastry. It's only fair Synodontis."
The rising sound of approaching foot falls came through the servants door. The door burst open and a man Ty-Shou recognized as the king's advisor rushed out.
"Anut?" Kitsai called out as the man rushed through the dinning room. She called out again in a language Ty-Shou couldn't understand. She seemed to curse as she motioned her body guard forward.
"I apologize Synodontis. I'm afraid I must take my leave."
Kitsai took chasing the Anut. Ty-Shou imagined all the things that could make Wosa rush like that. None of them were good.
In a split second Ty-Shou was following Kitsai. Qi-An kept up well as the pair carved their way through an increasingly concerned crowd. They only made it half way up the dance floor before the press of bodies was too great to push past.
Over the heads of the other guests Ty-Shou saw Anut mount the stairs the throne. Jakari was engaged in conversation with a women he recognized as Maleesh. Seeing the urgency in Anut's steps, the prince motioned Maleesh off. The advisor leant down to whisper in Jakari's ear. Even from this distance, Ty-Shou could see the younger man pale.
Jakari stood and clapped to draw his guest's attention. "Excuse me, I have an urgent matter to attend to. Please, enjoy my sister's company in the interim."
Kitsai was at the foot of the steps up the throne now. She rushed up to her brother's side, but was waved off by the advisor. She attempted to grab hold of her brother, but was shaken off. Her yell of protest was loud enough to carry to Ty-Shou.
That was when it began.
Jakari stumbled, missing a step, then began to cough. Before Ty-Shou could process it the prince had fallen down the stairs and was on the ground. Guards around the throne began to cough as well. Then a woman in the crowd, dressed in Cong Lang indigo. A man in the crowd next to Ty-Shou collapsed and began to convulse. Near the throne more of Jakari's staff began to suffer similarly.
Panic spread like a spark in dried grass.
Yelling in a dozen different languages as the throng of the crowd scrambled to push out. If Ty-Shou and Qi-An had been the height of an average Bei-Sanian, they were sure to have been trampled. The younger guard braced himself against the flood, diverting the flow around his charge.
On the stairs Kitsai stood frozen. She hadn't suffered any of the symptoms those on the ground. She covered her face in horror as she looked down at her brother.
"We must provide assistance," Ty-Shou proclaimed.
"Yes my Synodontis," Qi-An held out his hand and froze a man in place with his Heraldry. The man provided a break for the crowd, giving the pair a small gap to slip forward. A moment later, the man skipped forward in time, appearing two paces forward and tumbling into the back of an unsuspecting woman. They repeated the process till they spotted the prince's body.
Jakari lay on the ground convulsing. Blood from his coughs painted the ground around him. Where were his staff? Where was Anut, the advisor? That didn't matter right now. Ty-Shou had a chance to save the prince and he had to use it.
Qi-An did his best to form a cordon, pushing fleeing guests away from Jakari's body. Getting on his knees, Ty-Shou drew in the light from the Crystals embroidered in his gown. Every piece of clothing he wore had Light Crystals sewn in instead of regular gemstones. It wasn't enough. The prince was too badly injured, he would require a great amount of Light. Ty-Shou reach out and felt light in the Crystals in the throne. He drew that Light in and felt himself surge with power as the throne lost it's ethereal glow. 
Ty-Shou knew Empathy would be able to heal him. Empathy was one of a select few Light Emotions that allowed the Herald to heal. Caring could make a man's body heal faster. But Empathy, if done by a healthy Herald, could bring a man back from the brink of death. The prince was too far gone for any power except for Empathy to work.
/Pain/
/Doubt/
/Anxiety/
/Fear/
Not any fear, /fear of death/.
Ty-Shou knew /pain/, knew /doubt/, knew /anxiety/. But those weren't enough. Jakari's mind was so flooded with fear that Ty-Shou need to feel it deeply in his being for the power to work.
A body running past pushed into Ty-Shou breaking his focus. He wanted to feel Rage. He did feel Rage. Everybody fled, and he was the only one trying to help, and they couldn't even make enough space for him to do that?
Empathy. He ha to emphasise with the /fear of death/ itself. He had rarely felt Fear. But his life had never been truly threatened. The fear and adrenaline of sparring was a poor facsimile of the emotion.
Someone let out a cry, and Ty-Shou looked up to see Kitsai's body guard grab her. The woman pounded on her servants back. She held at the man in but her body guard took her what had been a hidden door behind the throne.
Another body bumped into Ty-Shou, this time hard enough to send him fully to the ground. Qi-An threw the body off Ty-Shou and back into the crowd.
"My Synodontis, we need to go." Ty-Shou shook his head and resumed his position over Jakari's body. The princes' coughing was getting shallower, the coughing less frequent.
He needed more time. Ty-Shou was burning with Light, but had no outlet. His body was an imperfect container. Every second, light leaked from him. What would Ty-Shou think about when he was on death's door step. He had no answer, no idea.
Ji-Xing burst through the crowd. "What the hell are you doing!"
"The prince, I have to save him." Ty-Shou's voice shook as he spoke.
The general took one look at the dying prince. "If you could have done it you would have by now. He's too far gone for even you."
"No he's not!" Ty-Shou felt all his power shift into Indignation. "I am a god! I can heal what no other can!"
Light surged from his hands onto the tiled floor as he poured his Indignation out. 
"Get down!" Ji-Xing pulled Ty-Shou up and put his body between the god and glowing spot on the floor. The older man's skin shifted to stone. Qi-An dove over the body of Jakari.
An explosion tore through the tiles up, shooting debris into the crowd and air.
The panic in the crowd grew to a fevered pitch.
"We're under attack!" A man yelled in Vareeshi
"The Dragon Riders!"
"It's the Versalists!"
Panic over took the crowd as they began to brandish weapons. Plates from around the room began to fly up as Space Heralds took control.
"Qi-An, to me!" Ty-Shou was frozen by shock. Each of his arms was grabbed by a guard as the two drew daggers.
"Out of the way!" Ji-Xing yelled. No one moved.
"Out! Out of the way!" Qi-An yelled in Delmian. The crowd began to part slightly as they pushed through.
The cold outside air brought Ty-Shou slightly out of his shocked stage. Bells of alarm rang out from the city below. Servants from the square below poured up the hill side, all armed for a fight.
"Did you spot another path down?" Ji-Xing swapped his dagger for the short sword at his side.
The younger guard pointed to a break in the tree line near the West wing. "I spotted the path on our way up."
"Good lad, come on! We've got a long run ahead of us!"
