* To Do
* Part I
** Chapter I
Ty-Shou was three years old, but not a child. He had appeared fully formed in ball of light. The people of Bei-San claimed he was the reincarnation of a long dead god. Every step Ty-Shou took in the city was met with rapturous praise. People told him of all the legendary feats he had accomplished in his past life. They said that Ty-Shou built the city of Bei-San itself, that he had sheltered the people from the great turmoil of the Age of the Gods, that had been able to transform people into the best versions of themselves. None of which he remembered.
"My Synodontis, please focus," the use of Ty-Shou's formal title cut through his introspection. The words had come from Wosa, his closest advisor and the man that guided him through his rise to fame. He had the silver hair— thinning at the temples —and silver eyes, typical of a Bei-Sanian. His wrinkled bronze skin was similarly typically of the city's populous. He was shorter than the average Bei-Sanian, and almost two heads shorter than Ty-Shou himself. Wosa carried himself with authority despite his stature. The old man easily filled the voluminous multi coloured robes favoured by the cities aristocrats. His own colours more muted than those worn by the two other servants in the room.  
"We've had this lesson a thousand times already. Can we at least go outside if we're going to be repeating lessons." Wosa insisted on conducting Ty-Shou's lessons in the same room every day, no matter the season or weather. The room was at the heart of the palace, with no windows. The room was lit in an iridescent glow from the Light Crystals around its perimeter. 
"If you stayed engaged throughout the lesson, perhaps I could rest assured that you understood the materials." Ty-shou hated the soft, suffering look Wosa so often had. "Now, what is this Crystal used for?"
In his hand Wosa held a perfectly black Crystal, one that appeared more as an absence of light than an actual object.
"It's a Dark Crystal. A full Dark Crystal," Wosa gestured with is fingers, urging Ty-Shou to go on. "This one is filled with a memory of a great battle. You're going to use your Heraldry to show me the memory so I understand how brutal the Vareeshi are."
"Good, but do not roll your eyes when you speak. The Synodontis does not roll their eyes."
Ty-Shou rolled his eyes again. The young god truly didn't understand this song and dance. From his first lessons in geopolitics, Wosa had emphasized how brutal the Vareeshi religion was. A religion built on might makes right and winner takes all, where people swore themselves to great men in the hope they would conquer all and lead them to eternal paradise. In Bei-San, the Vareeshi were a religious minority. But it was the only way of life for most of the neighbouring Central Marthian nations. Now that Ty-Shou was to leave the city for his first time, Wosa had been insistent on reviewing, and amplifying every lesson he had had on the Vareeshi. Still Wosa thought Ty-Shou didn't properly understand it, and had devised to show him a memory of Vareeshi brutality.
With a flourish of from the older man's hand the two servants covered the Light Crystals, plunging the room into darkness. Wosa's weathered fingers gripped Ty-Shou's forehead. The outline of the Crystal in the advisor's hand gave a false glow as Ty-Shou felt himself plunging into the false sleep of memory viewing.

Ty-Shou didn't know much about the man who's memories he now inhabited. The Synodontis knew instantly that his new body was shorter than his real one. Height was always one of easiest ways for Ty-Shou to spot an inserted memory.
He stood near the centre of a vast circular chamber. Pillars of painted red wood around the perimeter rose 50 feet up to hold up a wooden ceiling, intricately engraved with Vareeshi writing. On all sides of Ty-Shou a frantic mob pushed in, jockeying for position. The attention of everyone in the chamber was fixated on the structure at the very centre of the chamber. A towering triangle, nearly the height of the chamber itself. Ty-shou knew from his lessons that the triangle was made of a specific wood, found only in the Central Marthian valleys where the Vareeshi monks made their homes. The triangle was split into multiple tiers, each bigger than then the last, and filled with intricately designed wooden balls.
Ty-Shou held a similar wooden ball in his hand. Half his ball was plain wood, 
