* To Do
* General Style Notes
:generaleditonenotes:
- The details and visualization is good and inspiring.
- Be more careful with the grammar, there were many incomplete or improper sentences.
- in general, sentences can sometimes be two abrupt, especially the description ones. While of course run on sentences are bad, it is kind of a waste of words and awkward to have to identical description sentences that just repeat the subject and verb again, or  at least substituties of them, e.g: "Nick had shimmering green eyes. He had long brown hair. His skin was pale. He wore a crimson red jacket that always looked too loose." can easily be 1-2 sentences instead of 4.
- use words instead of numbers for numbers
:END:

* Part I
** Chapter I
:chapteroneeditonenotes:
- I like the events that happen here and introduction as a god, and a lot of the details which give a feel for a rich world.
- Maybe the second memory should show how much they value killing higher spot people. Maybe they are but it isn't clear.
:END:

Ty-Shou was three years old, but not a child. He had appeared fully formed in a ball of Light. The people of Bei-San claimed he was the reincarnation of a long dead god. Every step Ty-Shou took in the city was met with rapturous praise. People told him of all the legendary feats he had accomplished in his past life. They said that Ty-Shou built the city of Bei-San itself, that he had sheltered the people from the great turmoil of the Age of the Gods, that he had been able to transform people into the best versions of themselves.
He didn't remember any of it.
"My Synodontis, please focus," the use of Ty-Shou's formal title cut through his introspection. The words came from Wosa, his closest advisor and the man that guided him through his return, and the rise of fame that had come with it. Wosa had the silver hair— thinning at the temples— and silver eyes typical of a Bei-Sanian. His wrinkled bronze skin was similarly typically of the city's populous. He was shorter than the average Bei-Sanian, and almost two heads shorter than Ty-Shou, but he carried himself with authority regardless. The old man easily filled the voluminous multi-coloured robes favoured by the cities' aristocrats. His own colours were more muted than those worn by the two other servants in the room.
"We've had this lesson a thousand times already. Can we at least go outside if we're going to be repeating lessons?" Wosa insisted on conducting Ty-Shou's lessons in the same room every day, no matter the season or weather. The room was at the heart of the palace and had no windows. It was lit in an iridescent glow from the Light Crystals around its perimeter.
"If you stayed engaged throughout the lesson, perhaps I could rest assured that you understood the material." Ty-Shou hated the soft, suffering look Wosa so often had. "Now, what is this Crystal used for?"
Wosa proffered a perfectly black Crystal, one that appeared more as an absence of light than an actual object.
"It's a Dark Crystal. A full Dark Crystal," Wosa gestured with his fingers, urging Ty-Shou to go on. "This one is filled with a memory of a great battle. You're going to use your Heraldry to show me the memory so I understand how brutal the Vareeshi are."
"Good, but do not roll your eyes when you speak. The Synodontis does not roll their eyes."
Ty-Shou rolled his eyes again. The young god truly didn't understand this song and dance. From his first lessons in geopolitics, Wosa had emphasized how brutal the Vareeshi religion was. It assumed no morals beside might makes right and winner takes all, where people swore themselves to great men in the hope they would conquer all and lead them to eternal paradise. In Bei-San, the Vareeshi were a religious minority. But it was the only way of life for most of the neighbouring Central Marthian nations. Now that Ty-Shou was to leave the city for the first time, Wosa had been insistent on reviewing and amplifying every lesson he had had on the Vareeshi. Wosa still thought Ty-Shou didn't properly understand it, and had devised to show him a memory of Vareeshi brutality. Wosa helped seeing how they made their hierarchies, and how brutal the King Making fighting was would work better than lecturing Ty-Shou.
With a flourish of from the older man's hand the two servants covered the Light Crystals, plunging the room into darkness. Wosa's weathered fingers gripped Ty-Shou's forehead. The outline of the Crystal in the advisor's hand gave a false glow as Ty-Shou felt himself plunging into the false sleep of memory viewing.

Ty-Shou didn't know much about the man who's memories he now inhabited. The Synodontis knew instantly that his new body was shorter than his real one. Height was always one of easiest ways for Ty-Shou to spot an inserted memory.
He stood near the centre of a vast circular chamber. Pillars of painted red wood around the perimeter rose 50 feet up to hold up a wooden ceiling, intricately engraved with Vareeshi writing. On all sides of Ty-Shou a frantic mob pushed in, jockeying for position. Everyone in the chamber fixated on a towering triangle in the very centre, nearly the height of the chamber itself. Ty-Shou knew from his lessons that the triangle was made of a specific wood, found only in the Central Marthian valleys where the Vareeshi monks made their homes. The triangle was split into multiple tiers, each bigger than then the last, and filled with intricately designed wooden balls.
Ty-Shou held a similar wooden ball in his hand. Half his ball was plain wood, the other intricately carved and painted. He knew the ball was meant to represent the life journey of the person who's memory he inhabited, but Ty-Shou was unable to properly interpret the precise, dense writing and images on it.
The ranks of the crowd inched forward, and Ty-Shou found himself at the head of the crowd before long. Near the base of the triangle, a monk in grey robes stood with his hand out for Ty-Shou. Ty-Shou watched his hand move and place the ball in the monk's palm. The monk placed it at the bottom of the triangle, in last place. Once the ball was in place, another monk--- in the same gray robes ---handed Ty-Shou a circular tag with a number on it. Ty-Shou knew it was a very large number, the same number as the amount of balls now in the pyramid. Ty-Shou placed the tag around his neck, like everyone else in the chamber had. That same monk called out his name with his number, and the crowd yelled it back in a chant. Suddenly, Ty-Shou felt the edges of his consciousness blurring as the memory skipped forward.

The memory rematerialized as Ty-Shou found himself in the middle of a battle. He was shoulder to shoulder with other men, all holding spears. Mere feet away, the enemy formation of spears thrust forward. All the men he could see wore simple leather armour. This memory was old, at least 400 years old.
:style:
Not sure if I like that he knows this specific
:END:

A spear tip grazed Ty-Shou's cheek, and he felt searing pain shoot through his body. An equally intense freezing fear set into his bones. Ty-Shou couldn't tell if the fear was his own, or from the memory. Before he could decide, he felt himself jolt forward in a lunge. His spear tip danced past an enemy spear and found purchase in their neck. Shoulders pressed up against Ty-Shou as his formation took a step forward. The man next to him dropped as the enemy thrust forward. Ty-Shou's spear frantically worked to parry incoming attacks, but the enemy formation pressed forward endlessly. Pained moans from his allies filled the air. Men from the back ranks of the formation moved to fill the gaps as the injured were dragged to the back. A whistle blew and Ty-Shou was pulled back as a new front rank swapped in. He felt exhausted, more than he ever had in his short life. His body sagged with the effort, and leaning on his spear was all that kept Ty-Shou from slumping.
The yelling from the formation's head grew louder and nearer. His grasp on Vareeshi was weak, but he was sure the yelling was in a dialect he hadn't been taught. Around him men snapped to attention. Ty-Shou's grip on his spear tightened. A sudden wave of motion knocked him on the ground as a group of the enemy burst through the ranks.
Two men led the charge of the enemy spearhead. The nearest had long black hair tied in a bun above his head and a slender face. He wore light leather armour, like the other enemy soldiers. Three men charged him, and each was easily defeated. The man weaved through attacks perfectly, parrying each with his straight-edged blade. The second man had short, cropped black hair, and a scar across his left eye. Three discs spun around him creating a protective radius around a foot wide. Ty-Shou knew this was obviously Space Heraldry.
The Space Herald's eyes snapped to Ty-Shou and a disc came flying towards him. He rolled in the bloody dirt, causing the disc to barely miss. The second man must have been a powerful Herald to move the disc so fast. He scrambled to his feet, barely dodging as the disc came back around. The Herald was keeping his distance well, his ally dispatching attacks before they could threaten the Herald. The long-haired man moved with inhuman efficiency. He slipped between spears and parried attacks in perfect rhythm, with no wasted energy in each action. It was the same pattern of attack, repeated. The long-haired man would slip an opportunistic attack from behind, before lunging for the man in front of him. His blade thrust between his victim's armour. Before the dying man could drop to the ground, the lightning-quick swordsman would reach out with his off-hand to grab the number tag around his victim's neck.
Ty-Shou felt fear from the man who's memory he inhabited, but the god knew what the inhumane attack was. A Time Herald. One of the Subject Tree. It explained his superhuman reactions to attacks he shouldn't logically have time to react to, and how he always managed to perfect place himself and his blade. Judging by the number of number tags in his hand the man must have killed nearly three dozen men in his rampage. Two Heralds as skilled as these two could easily break route a hundred men undisciplined men. Ty-Shou saw it happening. The fear building in the soldiers around him, those near the back looking to flee and being pushed back by the elite rear guard. He let out  fierce roar and charged towards the Space Herald. A disc shot out from the Herald in response. Ty-Shou ducked his head and felt the disc graze the top of his hair. Two shouts rose from the crowd as two other soldiers joined Ty-Shou. He could feel his heart beat in his ears as he ran. In three years, his heart had never beat so strongly.
They were fifteen paces off the Space Herald now, maybe twelve from his defensive radius. Two discs came at him now, one flying from around the Herald, the other coming in on the right flank. The soldier on his right caught the clean across the throat. The disc slowed to a brief crawl as the Space Herald pulled the soldiers number tag off and towards the Herald. Ty-Shou thrust out at the head on disc, managing to knock it enough to make the Space Herald loose control.
They were ten paces off now, and the Space Herald had only one disc remaining. If Ty-Shou could close the gap before he brough the other two discs back on defense, he had a chance to kill the Herald.
A shoulder slammed into Ty-Shou. He stuck the butt of his spear in the ground, barely keeping upright. Before he could turn his head a punch clocked him clean across his face, and he was sent flying back to the bloody dirt. The final other soldier in Ty-Shou's desperate charge neared enough to thrust at the Time Herald. The Herald leaned his body perfectly enough to dodge the thrust. The soldier pulled his spear back and the Herald slipped down the shaft to within the weapons reach.
Ty-Shou jumped to his feet to defend his fellow soldier. He pulled a short dagger from his belt and jumped on the shoulders of the Time Herald. The Herald thrashed trying to throw Ty-Shou off. He locked his legs and elbow around the opponent and stabbed down with his dagger. The Herald jerked his hand up to catch Ty-Shou's forearm. The other soldier, discarding his spear, ran up to kick out the Heralds leg. The Herald rapidly twisted around the kick. In the same motion he jerked Ty-Shou's arm down and over, shifting his body weight into a throw.
For the third time in the fight Ty-Shou felt himself thrown onto the ground, this time he was on top of his ally. The whizzing of a Space disc cut the air as it embedded himself in the other nameless solider. Ty-Shou rolled off the body but was pressed to the ground by the Time Herald. He tried to stab the Herald's leg but he had lost the dagger in his fall. His unarmed punch barely phased the Herald as he plunged his sword down and between Ty-Shou's eyes.

Ty-Shou was panting and covered in cold sweats when he came out of the memory. The servants had uncovered the Light Crystals at some point.
"Do you understand now?" Wosa asked.
Ty-Shou felt sluggish coming out of the memory and could barely move his head to nod. "That was... What was that feeling? I- I've never felt it before."
"Fear," Wosa said solemnly.
:comment:
it feels like we can expand this moment a bit.
:END:
"I'm glad you understand that now."
Ty-Shou knew his heart wasn't racing, but he could still hear the drumming of a heartbeat in his ears. The lingering effects of the memory but have been evident, as Wosa knelt down to meet Ty-Shou's seated eye level.
"You are the most powerful Herald to have ever lived. Those Heralds in the vision have barely a fraction of your power, my Synodontis." Wosa reached out to grab Ty-Shou's hand. "I've tried to instill in you how powerful you are, how much capacity for good you have. I hadn't intended for this lesson to reinforce that. Perhaps now you understand both how brutal the Vareeshi are, and how much power you hold."
:comment:
he hadn't intended for this lesson to reinforce that? or he had?
:END:
Ty-Shou didn't reply, only nodded.
"Come, it's time to leave for Cong Lang. We must ensure we make all our appearances at the festivities before King Making begin in earnest. You would not want to experience the real memory now, would you?"
Ty-Shou rose from the chair with a shake of his head. "Of course not."
:comment:
I think I know what he is saying but it is a bit confusing and not the most smoothly phrased.  (You wouldn't want to experience death for real like in the memory, right?) i feel like this transition can be a bit less abrupt, and maybe Ty-Shou can have more questions about the King Making and Vareeshi.
:END:


The streets of Bei-San was overcrowded for his procession out of the city. Ty-Shou rode in a two-tiered carriage, pulled by six horses. The carriage had been originally commissioned by the Stewards of Bei-San, the noble family appointed to lead the councils of nobles and govern Bei-San in Ty-Shou's stead. The carriage was a reflection of the prestige and history of the city: it was made of black lacquered wood, with a polished gold trim along it's edges, and the panels were engraved with art depicting the most famous of Ty-Shou's feats. The door panel had his favourite engraving; it pictured him standing against a dragon coiling around the world.
:suggestion:
I really like this. This is also a spot you can show some of Ty-Shou's backstory and legend more naturally and maybe even eliminate the intro. A possible flow could be, "it showed Ty-Shou's feats, some past: him fighting off six other figures, some present: him coming down from the sky in a ball of Light", and some future; "Him standing against a dragon coiling around the world."
:END:
The bottom tier was designed as a regular carriage for long distance travel. It had padded seats, which could be made out into a full bed by his servants. Light curtains gave privacy, but allowed in a light breeze while on the move. The top level was a viewing platform. A waist hair railing ran around it's edge, allowing Ty-Shou to stand and wave out at the Bei-Sanian citizens as his carriage wound its way out from the palace at the city's heart.
Wosa had held back no level of splendor for the parade. The trip to Cong Lang had a stripped-down escort, despite that every one of his mounted Royal Guards had on perfect dress uniforms. A long stark white tunic which flowed down to below the knees, cut in the middle to allow for comfortable riding. A golden belt secured at their waist gave the top of the uniform a sharp triangular silhouette, and the tunic was trimmed in the same shade of gold. The symbol of Bei-San was embroidered in the centre of the chest: a blazing sixteen-pointed sun held in the palm of Ty-Shou's hand.
:question:
is it like, you see him? or is it like a sun in the palm of a hand?
:END:
Their tall black hats provided minimal shade, with a thin rim.
The Imperial Guard were selected for their size and strength. No man was shorter than Ty-Shou; all were at least twelve hands tall. Each wore two weapons. A long sword for unmounted combat, and a curved cavalry blade.
At their head was Ji-Xing. The head of Ty-Shou's guard, and Field Marshall, wore a white hat to match his white uniform. At forty-five man was past his physical prime, but could easily beat five of the other Royal Guard at once. fhis face was nearly a perfect square with a jawline that could cut glass. A scar across his eye gained during his youth only added to the his fierce appearance.
As they passed alleys, Ty-Shou could see people lining up thirty, even fifty ranks deep to try and get a glimpse of their god. From the window of passing houses, and from the nearest ranks on the street, Ty-Shou could hear Bei-Sanians yelling for blessings. Some even prostrated themselves on the pavement in attempt to garner his favour. A yell to bless a sickly relative. A cry to aid a son on an examination. They were all cries Ty-Shou had heard before, and all aid Ty-Shou had no power to grant.
His powers allowed him to heal some of the sick and wounded, but only if he was in the correct mental state. But he couldn't bless people with better fortune, or perform any true miracles. He was a Herald, but they called him more. They called him God.
** Chapter 2
Cong Lang was the crowning jewel of the Central Marthian cities.
** Chapter 3
*** Notes
- mention coalition. this party is for the coalition
- someone didn't come because it's so close to king making
*** Chapter
Jakari's ball was as elegant as he had promised it would be. The city itself may have been poor in comparison to Bei-San, but the palace at its heart was an equal match. It's size and opulence had been clear from the moment Ty-Shou entered the city. Yet, he found himself in awe of the beauty as he approached.
The palace had been under construction for three generations--- commissioned as a sign of Cong Lang's post-Delmian independence --- and had only been completed 50fifty years ago. The complex sat upon the city's name sake, Cong Lang or the river hill. The hill around which the two life blood rivers of Central Marthia merged to create the river Keesh. The Yahl River, which shot down the Nihdan mountains and through Delmia, and the Tacuk which weaved from the Northern Strait. The confluence of the two rivers had given the city influence, power, prestige, and wealth. Now they had built this palace to reflect all of it.
Ty-Shou's escort for the event was a compliment of only three. Ji-Xing, his protege Qi-An, and their carriage driver. The invitation had specified that only two servants would be allowed per guest, so Ty-Shou had taken a two man carriage tonight. Across from him, Qi-An sat with his attention out the window. The young guard sat straight-backed and coiled for action. His internal anxiety was given away only by the rapid drumming of his fingers against his sword hilt.
Ty-Shou had been content to attend alone, he had in fact been looking forward to it. But Wosa had lectured that it was improper for a man of his station to travel without a guard. Ji-Xing would have protested just as strongly on the grounds of security. But he was God, should he not be able to go alone if he wanted?
The carriage came to a stop in a crowded stone square at the bottom of the hill. A guard dressed in Cong Lang indigo and teal conversed with the driver, pointing to an open spot at the edge of the square where he could park. Past the guard, Ty-Shou could see other dignitaries departing their carriages. Some wore the more traditional single piece Marthian tunics, while others wore the more modern Kaihanese suits and dresses.
The flowing oversized dresses of the women were unlike any that he had seen worn in Bei-San. Wide neck lines plunged to to reveal enough skin to make Ty-Shou blush. The colours were more intricate, yet more muted than the ones worn in traditional clothing, favouring detail over bright ostentation. The modern suits of the men were tightly fitting. Their pants rose high on the waist and were paired buttoning tunics. Each man also wore a jacket with tails flowing down to their calfs.
Ty-Shou found their absence of head coverings most interesting. The Vareeshi minority in Bei-San wrapped their long hair in silk coverings above their head. He saw similar styling in some of the guests around the square, but many had their hair visible in intricate braids, flaunting the traditional covering of hair. Others wore hats, or shawls.
:comment:
"flaunting the traditional covering of hair" is a bit confusing here cause they aren't really covering their hair, and 'visible' and 'covering' are such antonyms. I only know what you mean cause we discussed and created this
:END:
A knock came at the door as Ji-Xing pulled the carriage door open. "We're to walk the rest of the path up to the palace, my Synodontis."
Ty-Shou nodded, "We have no complaints."
Ji-Xing took a step away from the carriage, allowing Ty-Shou to descend himself. The square smelled of sweet tobacco. Coachmen awaiting their charges lounged smoking pipes or playing card games with the other servants which had been denied entry. Qi-An coughed at the smell and followed behind Ty-Shou.
At the gate, Ji-Xing gestured Qi-An forward and the younger man proffered their invite to the guard. The guard looked it over for a long moment. Did he not trust Ty-Shou? Why was he scrutinizing the Synodontis' invitation?
A flare of energy rushed through Ty-Shou's blood as he felt Indignation flare in him. The energy rushed to his finger tips, begging to be infused into an object.
He took a deep breath and let the emotion fade. The rush of power subsided.
The trio was let through the gate with a simple wave. No bow. Not even a note of gratitude for his presence. Only his escort spiriting him past the gate kept him for activating the full force of his power on the gate guard.
:comment:
maybe this is too unsubtle and extreme
:END:
The path up to the palace was a beautiful walk. Light lamps lined the path, shimmering iridescent light over the cobbled path. Trees on either side arched over the path isolating the background chatter of the city. As they walked the path only the occasional croak of a toad or buzz of a bug could be heard. The path wound its way around the hill at a steady incline.
The path up to the palace was a beautiful walk. Light lamps lined the path, shimmering iridescent light over the cobbled path. Trees on either side arched over the path isolating the background chatter of the city,  only the occasional croak of a toad or buzz of a bug could be heard.
"Bastards forced us to walk," Ji-Xing said in Bei-Sanian. The other parties were close enough to hear him, but none of them appeared to speak the language. "It's a power play, they want to tire us out."
"We do not think so," Ty-Shou said. Ji-Xing for all his wisdom was an army man. Every problem was military, every action one step towards winning an unseen battle. "It's a display of opulence, not power."
Ty-Shou heard Qi-An gasp as the trio stepped out from under the tree cover onto a carved stone outcropping. The city of Cong Lang and the royal grounds of the palace spread out beneath them. The hill and a large swath around it had been gated off for the royal grounds. Garden paths curved around water gardens and under huge drooping trees. There were no hard lines or symmetry in the layout. Everything had been arranged to flow naturally with the land. How much of the land was artificial was impossible to tell.
From his vantage point Ty-Shou could see the dense city within the walls and far beyond to the towns and farms surrounding it. Ships laden with cargo drifted lazy past each other as they went up the two rivers. From above, drifted the muted music of the ball. No map could have ever conveyed the scale of the city to Ty-Shou. Bei-San held it's majesty in its history, beauty, and its people. But Cong Lang's sheer scale was nearly enough to dwarf those all.
Ty-Shou felt eyes on him from the stragglers on the platform. He had no idea how long he had been staring out at the city. It couldn't have been longer than a handful of minutes. However long it was, was enough to cause a scene. Holding his head high, the god swept past the onlookers and up the final dozen or so steps to the palace itself.
At the top of the hill, a path lined with guards every ten paces led them towards the open doors of the entry hall. The entry hall jutted out, rising as high as a six story building to a steep slanted tip. Like the rest of the palace was made of a variety of stone from all over Central Marthia, all neutral shades of white, grey, or black. Perpendicular to the flanks of the hall the west and east wings grew. The two wings were identical, defined by their curved glass roofs and huge glass windows. Each window was identical, five paces wide, sixty tall, and placed at fifteen pace intervals. Between them, the same white stone as the hall served as the frame work. Ty-Shou had never seen windows so large before. However, it was the curved glass roof, which rose almost as dome, that was the true marvel of the palace.
Vang-Do glass blowers had been commissioned for the project. They were the best not just in the Marthia, but the world. Like all the artisans guild in Vang Do, the glass blowers were a pretentious, pompous, egotistical institutions. One Ty-Shou was not eager to deal with any time soon.
"For such a violent people, you'd think they'd make more secure palaces. I could take this with two squads. Less if we had Heralds." Ji-Xing let out a small scoff as he looked over the Cong Lang guards.
A small smile of pride crept onto Ty-Shou's lips. He didn't doubt his Royal Guards could.
"I believe I could do it with a Dark, Space, and another Time Herald," Qi-An said.
His mentor raised an eye brow in response. "Not very confident are you? You need two Time Heralds?"
"Well they'd all be single Schools! Illusion, Teleporation--"
"Quiet," Ty-Shou said. "We approach the steward."
Qi-An took two broad stride slipping infront of Ty-Shou. The older guard slipped back to guard the Synodontis' rear. Qi-An produced their invite once again and handed it to the man at the entrance.
"Synodontis Ty-Shou Xing of Bei-San and company," the steward's voice was amplified by the architecture of the ante-chamber and a short call of horns followed. The hall was large enough that the stewards words seemingly hadn't reached the far end of the hall. At the far end of the hall, one massive throne sat in front of pyramid, filled with balls, large enough to stretch the full height of the hall.
Ty-Shou struggled to distinguish the figures crowded around the thrown at the far end of the hall. Jakari was easily identifiable by his place on his father's throne. The two smaller chairs in front--- typically for Jakari and his sister ---were empty. Another silhouette stood by the throne, likely the advisor. In front of the three thrones was a dance floor which took up the majority of the hall.
Despite the palace and ball being all he could have imagined, a distinct twinge of disappointment flashed in Ty-Shou. It was a familiar emotion, but the cause this time was surprising.
"What now my Synodontis?" Ji-Xing surveyed the crowd, his hand not touching, but never drifting from his short sword.
"We will enjoy the refreshments, and speak if spoken to." The two royal guards nodded.
The initial crowd of people seemed to be mostly lower level dignitaries and business people. No face Wosa had told him about. They congregated around small but high tables, all nursing a drink proper to their gender. Conversations could hear the conversations as he passed. Most were in languages he couldn't understand, but could identify. Some were from Central Marthia, and some from farther beyond. He heard the sweet tonal rising and falling of the commonwealth, the hissing of Trentanian, and even the guttural clipped speech from Apathasaw.
"Synodontis!" A voice came from the edge of the crowds, where it gave way to the dance floor. The crowd parted as the voice approached.
It came from a man in his late thirties. He had cool bronze skin and soft, nearly feminine features. His long black hair was tied in two thin braids which fell to small of his back. His nose was scarred, and bent from being set in place more than once.
"King Ruit of Khua," Ty-Shou said in Delmian. The man was easy to recognize from the memories Wosa had given him. He wore a single piece tunic, and a thin belt tied in a flowery knot cinched his belt at the waist.  Over his shoulders he wore a cloakshawl of sheer black material. It was embroidered with the golden six petal flower of his house. Tassels of the same gold hung around the shawl's edge.
"Synodontis," the king tipped his head down in reverence. Ty-Shou waited for the man's gesture to deepen to a bow. Instead, Ruit rose to stand straight. "I'm glad to make your acquittance. Your reputation proceeds you."
"We have heard much of you as well," Ty-shou straightened his back fully.
"How did Jakari convince you to attend?" Ruit took a sip of his drink as he raised an eyebrow. "Bribery? That's how he got me."
Ty-Shou's eyes narrowed. "You accuse us of taking a /bribe?/"
"Bribes, yes," the king took a long moment finishing his drink. "Favours, a promise of audience with the boy's father, a meeting with the dockers' guild, an opportunity to court his sister. Everybody who's anybody received something to attend."
Ty-Shou felt a slight tinge rise in his cheeks. He pushed the blush down with his disgust.
:question:
is this a Light heraldry use?
:END:
"What were you promised?" /Money? Men? Weapons?/ Ruit was a brutal warlord, having made his claim when he could barely grow facial hair. Men like that wanted only money and power.
"Tickets to the opera," Ruit replied with a laugh. "I give the boy credit, he knows his guests well."
Ty-Shou blinked. "The opera?"
"Yes, in Cong Lang. Everyone knows the opera houses in Vang Do are superior of course," Ty-Shou nodded, though he did not know that, and even though he knew rather little, felt like not 'everyone' did either. "But Cong Lang is one of the few cities with true artistic culture."
From just outside the conversation, Ji-Xing scoffed. Ruit whirled on the man, "Was my statement humourous?"
"Not precisely, I was just curious. Which cities do you believe have /true artistic culture/? Khua?" Ty-Shou levelled a glare at Ji-Xing. He did not want to reprimand the head of his guard publicly. But he would have to in order to appease Ruit.
The king burst out in a hearty laugh. "No, no. Not Khua," Ruit let out a long sigh. "Not yet. But by the time of my death, it will. My people have nearly completed construction on our new theatre. The largest in the coalition. In time we will build great statues, and galleries, and one day the sweet song of opera will fill my city's streets."
Ruit had the twinkle of a dreamer in his eyes as he spoke. It was true, every word he said. Or at least, he believed it be so.
"We have many great stone masons in our lands," Ty-Shou said.
Ruit leaned in, "is that truly so? Perhaps I will have to come during King Making to recruit some."
Indignation flared in Ty-Shou again. He had tried to relate to this interloper, and the king had mocked him. He wanted to reach out to grab Ruit's face. How funny would the joke seem when Ty-Shou infused his indignant rage onto the king's skin.
Ruit let out the same laugh he had only moments ago before his face fell to a frown.  "Ah, it appears I finished my drink."
A lady appeared from the crowd. She had the same skin tone as Ruit and worse, a modern dress, one with a fashionable low cut neck line.
Ty-Shou averted his gaze as the woman hooked her arms around Ruit's. She whispered something in the king's ear and they shared a private laugh. Ruit looked between the new woman and Ty-Shou as a slight frown crept onto the king's face.
"It appears I am required elsewhere," Ruit nodded his head once again to Ty-Shou, then to Ji-Xing. "Don't be a stranger, Synodontis."
The couple disappeared into the crowd and left Ty-Shou was a sharp pang in his heart. It wasn't physical pain, but it was an emotional pain Ty-Shou hadn't experienced before. The distress must have shown in Ty-Shou face. Ji-Xing leaned in to whisper as hand went to his sword.
"My Synodontis?" Ji-Xing asked. "Are you well?"
The older guard made a series of hand motions Ty-Shou couldn't understand. His two guards each held an arm, bolstering Ty-Shou. He shrugged them off instead. "Do not make a scene general."
The pang had dulled to a low ache but was still unidentifiable. Ty-Shou pushed the pain away focusing instead on the crowd of onlookers. A rough circle of onlookers formed around him, all whispering amongst themselves. After a long moment, one man stepped forward and bowed.
"Synodontis, I am lord Nuanaak..."


The next several hours of dragged on with introductions. Ty-Shou remembered maybe a quarter of their names, and cared about even less.
"Where is Qi-An?" Ty-Shou asked in a lull between introductions.
"I sent him to locate refreshments, my Synodontis."
Ty-Shou nodded at his general, "we value your initiative. Our mood would be greatly improved by proper nourishment."
Qi-An returned a handful of minutes and introductions later. He gave a waist deep bow as he drew up.
"Were you successful?" Ty-Shou asked in Bei-Sanian.
"I did my Synodontis, the food and drink is set out in the West wing." Qi-An replied still in a bow.
"What of the East wing?" Ty-Shou cut in.
Qi-An paused for only a moment. "I apologize my Synodontis, I failed to acquire that information."
"Nonsense," the older guard said with a scoff. "I ordered you to find the food, not scout the whole damned palace."
"I will go now to find out. If that pleases my Synodontis."
Ji-Xing cut off his protege, "I will go. You need the refreshments more than I do. I've been sending you running around the whole damned night."
"Thank you sir," Qi-An gasped. Perhaps the general had been working the younger guard too hard.
"Go. Half the good food is already gone by now. That's how these parties always work."
Qi-An led Ty-Shou silently around the edge of the dance floor to the West wing. Ty-Shou wasn't sure if he would know that this man was Ji-Xing's protege. He shared none of his master's hot headed tendencies. He never slouched, spoke out of turn, nor swore. The other royal guards were in line with Ji-Xing, but all soldiers seemed to be.


The banquet was held in the palace's great hall, a vaunted stone hall who's ceiling seemed to reach up into the clouds. Carved stone pillars ribbed the hall, rising to support the dauntingly tall hall. A mezzanine ran the length of the hall on either side, giving dignitaries a more private place to talk.
The Bei-Sanian party entered from the wooden double doors at the front of the hall. The vast room was long enough that Ty-Shou struggled to make out the figure of Jakari and his sister atop of their thrones at the far end of the hall. At their feet was a dance floor--- where men and women engaged in the traditional mixed gender dances ---past that was a sea of
:fix:
you didn't end this sentence
:END:
Such a vast hall was required to accommodate the 2000 or so members in attendance, as anyone who had a shred of influence or prestige in the Vareeshi world would be here. The laughs and casual but energetic dancing told Ty-Shou everyone was having a good time. It flabbergasted him that with only a slight movement of the moon, all of them would be trying to kill each other.
Ji-Xing entered ahead of Ty-Shou, his prodigy Qi-An taking up the rear, both in Royal Guard white. All guests in attendance had been limited to two servants. Some of the more haughty guests had tried to force their way into the hall with full coteries of servants. Ty-Shou barely had need for servants, body guard even less so. But Wosa had always insisted that it would be improper for such an important figure to travel without a guard.



The West wing's interior beauty easily matched its exterior architecture. The room off the great hall spanned the total height of the wing, allowing sweeping views through the towering windows. Art, lit be candles, adorned the space between windows. Two tables on either side of the room were filled with food. Plates were set out in a buffet style, organized from spicy to sweet. Stewards patrolled the room, cleaning away finished meals, organizing food, or bringing drinks. In the centre of the room, a large table was set for fifty guests, though less than then sat eating. He recognized two of the people at the table. Kitsai and the towering man that had been with her in the market.
Ty-Shou averted his eyes from the table to the food at the side. He made his way down the table, focusing on the rows of food. Most were unfamiliar to him, and smelled of strange spices.
Finally, the smell of one dish caught his attention. It appeared to be chicken. It's skin looked crisp, and was a deep red colour. They had plated it on a bed of long grained rice.
"It's good, you should try it," a feminine voice said in Delmian. Ty-Shou looked up to see Kitsai two dishes down, her body guard a further three paces back. She wore her hair in a single wide pleated braid. She wore a Kaihani dress, but didn't obey the fashion of the women at the ball. Her neckline was up in defiance of the plunging ones Ty-Shou had seen all night. It formed a tight collar, adding to the slimming effect from her comparatively straight skirts. The maroon colour and silver detailing of the dress complimented her pale skin.
"What is it?"
The woman shrugged as she picked up a baked pastry from a silver platter. "My brother handles the menu, I simply come to observe his work."
"How do you know if it is good?" Ty-Shou asked.
"Cause Jakari isn't very creative," a small smile tugged at Kitsai's lips. "Or perhaps our head chef isn't. But the menu always contains repeated favourites. That one has been on the menu for the last three years."
A steward patrol crept up from behind Kitsai. The princess waved the man off before he could open his mouth.
"I'll call you if I need something, Vaitran," she seemed to pause before turning to look at Ty-Shou. "Do you want anything Synodontis?"
Ty-Shou was taken aback by the sudden usage of his title. She hadn't said it with emphasis like everyone else, instead she had used it as if it were his name.
"We would be greatly pleased by tea, Yue tea," Ty-Shou turned to look at Qi-An. "My guard will have water."
The steward nodded and ran off through a servants door at the back of the room.
"Just tea?" Kitsai asked as she ripped the pastry in her hands apart. Ty-Shou could see it was stuffed with spiced meat.
"We do not drink alcohol." Ty-Shou said as he took a step towards the pastries.
"Many would call that a sad life."
"We pity those who rely on such vices."
Kitsai smirked, "don't let the ones out there hear you. Some of those /kings/ and /lords/ out there do not take kindly to pity."
"We care not."
"You might," Kitsai took a bite out of the pastry. Ty-Shou felt his mouth water. "Emperor Voto is one of those men."
Ty-Shou thought he had recognized the Emperor of Delrei in the crowd.
"The emperor is quite the reveller. He-"
Ty-Shou cut the woman off, blurting out, "what is it that you are eating?"
Kitsai furrowed her brow, holding up the half eaten pastry. "This? It's a meat pie. Do you not have meat pies in your land Synodontis?"
The two Bei-Sanians shook their head. "Our people prefer sweet pastries."
The meat pie Kitsai held was antithetical to Bei-Sanian baking. Not only was it savoury, but it had been baked in a thick dough. Totally unlike the airy, flaky pastries in Bei-San.
The woman took a step forward and handed Ty-Shou the unmolested half of her meat pie. He took the pie without hesitation. The meat smelled unlike any blend of spices he had tried before. The taste was exquisite and the texture unique.
Kitsai let out a small giggle as she finished her half of the pie. "Now I have to try a Bei-Sanian pastry. It's only fair Synodontis."
The rising sound of approaching foot falls came through the servants door. The door burst open and a man Ty-Shou recognized as the king's advisor rushed out.
"Anut?" Kitsai called out as the man rushed through the dinning room. She called out again in a language Ty-Shou couldn't understand. She seemed to curse as she motioned her body guard forward.
"I apologize Synodontis. I'm afraid I must take my leave," she said.
Kitsai took to chasing Anut. Ty-Shou imagined all the things that could make Wosa rush like that. None of them were good.
In a split second Ty-Shou was following Kitsai. Qi-An kept up well as the pair carved their way through an increasingly concerned crowd. They only made it half way up the dance floor before the press of bodies was too great to push past.
Over the heads of the other guests Ty-Shou saw Anut mount the stairs the throne. Jakari was engaged in conversation with a women he recognized as Maleesh. Seeing the urgency in Anut's steps, the prince motioned Maleesh off. The advisor leant down to whisper in Jakari's ear. Even from this distance, Ty-Shou could see the younger man pale.
Jakari stood and clapped to draw his guest's attention. "Excuse me, I have an urgent matter to attend to. Please, enjoy my sister's company in the interim."
Kitsai was at the foot of the steps up the throne now. She rushed up to her brother's side, but was waved off by the advisor. She attempted to grab hold of her brother, but was shaken off. Her yell of protest was loud enough to carry to Ty-Shou.
That was when it began.
Jakari stumbled, missing a step. He began to cough. Before Ty-Shou could process it, the prince had fallen down the stairs and was on the ground. Guards around the throne began to cough as well. Then a woman in the crowd, dressed in Cong Lang indigo. A man in the crowd next to Ty-Shou collapsed and convulsed on the ground. Near the throne, more of Jakari's staff began to suffer similarly.
Panic spread like a spark in dried grass.
Yelling in a dozen different languages as the throng of the crowd scrambled to push out. If Ty-Shou and Qi-An had been the height of an average Bei-Sanian, they were sure to have been trampled. The younger guard braced himself against the flood, diverting the flow around his charge.
On the stairs Kitsai stood frozen. She hadn't suffered any of the symptoms as those on the ground. She covered her face in horror as she looked down at her brother.
"We must provide assistance!" Ty-Shou proclaimed.
"Yes, my Synodontis," Qi-An held out his hand and froze a man in place with his Heraldry. The man provided a break for the crowd, giving the pair a small gap to slip forward. A moment later, the man skipped forward in time, appearing two paces forward and tumbling into the back of an unsuspecting woman. They repeated the process till they spotted the prince's body.
Jakari lay on the ground convulsing. Blood from his coughs painted the ground around him. Where were his staff? Where was Anut, the advisor? That didn't matter right now. Ty-Shou had a chance to save the prince and he had to use it.
Qi-An did his best to form a cordon, pushing fleeing guests away from Jakari's body. Getting on his knees, Ty-Shou drew in the light from the Crystals embroidered in his gown. Every piece of clothing he wore had Light Crystals sewn in instead of regular gemstones. It wasn't enough. The prince was too badly injured, he would require a great amount of Light. Ty-Shou reach out and felt light in the Crystals in the throne. He drew that Light in and felt himself surge with power as the throne lost it's ethereal glow.
Ty-Shou knew Empathy would be able to heal him. Empathy was one of a select few Light Emotions that allowed the Herald to heal. Caring could make a man's body heal faster. But Empathy, if done by a healthy Herald, could bring a man back from the brink of death. The prince was too far gone for any power except for Empathy to work.
/Pain/
/Doubt/
/Anxiety/
/Fear/
Not any fear, /fear of death/.
Ty-Shou knew /Pain/, knew /Doubt/, knew /Anxiety/. But those weren't enough. Jakari's mind was so flooded with fear that Ty-Shou needed to feel it deeply in his being for the power to work.
A body running past pushed into Ty-Shou, breaking his focus. He wanted to feel Rage. He did feel Rage. Everybody fled, and he was the only one trying to help, and they couldn't even make enough space for him to do that?
Empathy. He ha to emphasise with the /fear of death/ itself. He had rarely felt Fear. But his life had never been truly threatened. The fear and adrenaline of sparring was a poor facsimile of the emotion.
Someone let out a cry, and Ty-Shou looked up to see Kitsai's bodyguard grab her. The woman pounded on her servants back. She held at the man in but her body guard took her what had been a hidden door behind the throne.
Another body bumped into Ty-Shou, this time hard enough to send him fully to the ground. Qi-An threw the body off Ty-Shou and back into the crowd.
"My Synodontis, we need to go." Ty-Shou shook his head and resumed his position over Jakari's body. The princes' coughing was getting shallower, the coughing less frequent.
He needed more time. Ty-Shou was burning with Light, but had no outlet. His body was an imperfect container. Every second, Light leaked from him. What would Ty-Shou think about when he was on death's door step? He had no answer, no idea.
Ji-Xing burst through the crowd. "What the hell are you doing!"
"The prince, I have to save him." Ty-Shou's voice shook as he spoke.
The general took one look at the dying prince. "If you could have done it you would have by now. He's too far gone, even for you."
"No he's not!" Ty-Shou felt all his power shift into Indignation. "I am a god! I can heal what no other can!"
Light surged from his hands onto the tiled floor as he poured his Indignation out.
"Get down!" Ji-Xing pulled Ty-Shou up and put his body between the god and glowing spot on the floor. The older man's skin shifted to stone. Qi-An dove over the body of Jakari.
An explosion tore through the tiles up, shooting debris into the crowd and air.
The panic in the crowd grew to a fevered pitch.
A man screamed in Vareeshi. "We're under attack!"
* Chapter 4
"The Dragon Riders!"
"It's the Versalists!"
Panic over took the crowd as they began to brandish weapons. Plates from around the room began to fly up as Space Heralds took control.
"Qi-An, to me!" Ty-Shou was frozen by shock. Each of his arms was grabbed by a guard as the two drew daggers.
"Out of the way!" Ji-Xing yelled. No one moved.
"Out! Out of the way!" Qi-An yelled in Delmian. The crowd began to part slightly as they pushed through.
The cold outside air brought Ty-Shou slightly out of his shocked stage. Bells of alarm rang out from the city below. Servants from the square below poured up the hill side, all armed for a fight.
"Did you spot another path down?" Ji-Xing swapped his dagger for the short sword at his side.
The younger guard pointed to a break in the tree line near the West wing. "I spotted it on our way up."
"Good lad, come on! We've got a long run ahead of us! My Synodontis, come on!" Ji-Xing burst forward and motioned for Ty-Shou and Qi-An to follow. The crowd, pouring out from the palace, invaded behind them. Ty-Shou was about to protest when--
"ATTENTION!" The massive shout erupted over the crowd. It was so loud, inhumanely loud, that many clasped their hands over their ears, and many that were running stopped in their tracks.
"THERE HAS BEEN AN ATTACK. THE CITY IS UNDER LOCKDOWN," the shout came from ahead of Ty-Shou and his security, at the square below, and they clasped their ears.
"What!? Are you trying to get us killed!?" someone in the crowd shouted from behind. Ty-Shou supressed the Indignation rising up in his chest-- how dare they restrict the other leaders after inviting them here?
"FOR YOUR SAFETY, STAY CALM AND STILL. DISRUPTIVE ACTS WILL BE INTERPRETED AS AN ASSAULT ON THE CITY AND THE GUESTS."
The crowd boiled with anger and confusion. As a mass, they stayed more still than before, but little parties spread in different directions.
"Come on," Ji-Xing said. "We're still going to the compound!"
Ty-Shou tightened his lips. He didn't like being pushed around by Ji-Xing, but when the man commanded, it was instinct for even the likes of Synodontis to follow him. Which just made his feelings more complicated.
"Do they even have the right to do this? We are not their subjects, how can they restrict our right of travel?" Synodontis asked as the three of them ran.
"To be fair, it's what I would do if something similar happened in Bei-San," Ji-Xing said, his breath measured. "It's good security practice to contain the zone. But that doesn't mean we're going to follow their orders."
"I hate to be a bother, my Synodontis," Qi-An interjected. "But that shout, that was Light Heraldry, was it not? Do you know what emotion that was?"
Ty-Shou bit his lip. He knew it was Light Heraldry, as it wasn't any of the others. And he had channeled many more emotions than most were ever able to in their lifetimes, but he didn't even know which that was.
"Exasperation," Ji-Xing said. "It's one that works out quite nicely in the military-- the angrier the officer gets at his troops' incompetence, the louder and more deadly the shout. Of course it can backfire, if you actually use it against your own men."
"Deadly?" Qi-An raised en eyebrow.
Ji-Xing nodded. "You heard how loud that messenger was. If someone like Ty-Shou used it, who knows? It could shake a mountain."
Ty-Shou's insecurity at Ji-Xing knowing the answer faded. The head of security was hard, no-nonsense, and independent, but he was a true believer, and loyal, as much as an Bei-Sanian.
"Back to the topic," the Synodontis said. "Who do you think is attacking? Almost all the kings of large pyramids are here, and I didn't see any armies with them."
"It might be a set up by Cong Lang themselves, to trap all the important leaders here when king making begins," Ji-Xing said. "A bit more opportunistic than I would expect from King, but they have the most troops here, and are the most likely to win from this situation."
Ty-Shou caught his breathe before speaking again. Even though he was the eldest, Ji-Xing ran like a horse, and even the lithe Qi-An struggled to keep up.
"But it was Jakari and the other Cong Langans who got poisoned," Ty-Shou said. "You think it's just a trick?"
"If you are to underestimate anything in this world, don't let it be how far the Vareeshi will go to win king making," Ji-Xing said.
The three got back on one of the main roads from the hill that had taken as a short cut. Ty-Shou glanced around-- some of the guests were still pouring out from the general direction of the temple, and all the servants and natives, though less panicked, were generally in a rush and confused. It was a shame that such a desperate panic was coming out of such a luxurious palace. Ty-Shou turned his eyes back down the hill; Cong Lang once again amazed Ty-Shou by how it seemed to go on forever.
"What about Ruit of Khua?" Ty-Shou turned his attention back to the conversation. "He seemed ambitious and a bit... eccentric. Like someone who would have a trick up his sleeve."
Ji-Xing shook his head. "It may not be obvious from Ruit's flamboyance, but Khua is far too traditional to do something like this."
Ty-Shou's head tilted. "You just said that the Vareeshi would do anything to win in king making?"
"It's not so simple," Ji-Xing said. "Khuans are traditional Vareeshi. Though they are perhaps /the/ most cutthroat on the battlefield, nothing outmatches their sense of honor and pride. They don't believe in warfare when it's not king making, and they see dirty tricks like this as especially dishonorable. Go to Khua any time of the year, and it will be much more like Ruit, just less artistic: a cheerful people obsessed with wine. That is, unless you visit a military camp."
"And they have a lot of them," Qi-An said. "Khua's armies last king making were estimated to be over one thirthieth their total population. That's more than five times the size of our army."
Ji-Xing gave Qi-An a harsh stare. Ty-Shou knew he should've felt offended on behalf of the nation, but to him, the numbers weren't that important, and even knowing him for such a short time, he could already tell that Qi-An wasn't the most socially adept, or at least the most socially normal.
"Bei-San is always growing," Ty-Shou said. "Now that I've returned."
Ji-Xing and Qi-An just nodded. /It must be especially awkward, talking to your god/, Ty-Shou realized. /Maybe I should be a little lighter around them. But-- Wosa said I must always stay respectable.../
"It could be Hysho," Qi-An said. "They're one of the only large enough pyramids to have a chance at becoming truly dominant, yet the smallest of that top class, and one of the only very large pyramids that didn't show up.  It could be that they're making a desperate power play."
"That is a possibility, Qi-An," Ji-Xing said. "Your analysis is shrewd."
Ty-Shou felt a bit ashamed for knowing so little, but he brushed it off. He had only been incarnated for three years, and they still saw him as a god. Right?
"No matter who it is, even with this order, we should try to leave the city," Ji-Xing said. "We do not want to be here when king making begins."
"I don't know," Ty-Shou said. "It's unbefitting of a hero, much less a god, to run from danger. And plus, Wosa told me not to upset any of the major pyramids-- I would think he would be especially mad if I upset our hosts."
Ji-Xing just gave Ty-Shou a nod, but Ty-Shou knew that that just meant this conversation would continue when they returned to the compound.
Qi-An finally caught his breath as the tiled road curved up to the grassy hill where the flat stone walls of the compound sat. It was a decent run, and Ty-Shou had used a bit of Passion to keep his endurance up.
Ahead, a quartet of armored men in teal and indigo approached. They eyed the three before lowering their spears. Cong Lang guards.
"Halt. The city is in lockdown. State your name and destination," the tallest guard stepped forward and said.
"I am Synodontis Ty-Shou Xing of Bei-San. The Great God of Light," Ty-Shou stepped forward.
"You have carriages within these walls. As mentioned, the city is in lockdown," the tall guard said.
"So you are intent on arresting a foreign leader that you invited as an honored guest?"
The guards looked between each other. It was unclear if they were preparing for an attack, or communicating something else.
"We made no such statement," one finally said.
"Then let us pass," Ty-Shou said.
The guards looked between each other again. Using his right hand, Ji-Xing clutched something in his back pocket. Inch by inch, his right arm shifted to steel.
In unison, the guards divided into two pairs to let the three pass. Ji-Xing bowed in respect as Ty-Shou and Qi-An approached the compound.
But just as Ji-Xing was about to pull the loose rope that would ring the entrance bell on the black compound gate, the clop-clop and whinny of a running horse pulled the attention of the three. The horses' stark white body glared against the inoffensive green hills, and its pitch black mane demanded the eye's focus. It had come from the hillside, also from the direction of the palace, but running a roadless, hilly path. Ty-Shou gasped in surprise-- its rider was Kitsai, but she wore open wounds and was nearly slouched over, a harsh contrast to her usual regal posture. The horse slowed its roll as it approached the three.
"Kitsai!" Ty-Shou ran up to her.
"Ty-Shou!" Ji-Xing shouted and ran to grabbed the Synodontis by the shoulders.
The Synodontis shoved his security back. He understood why the Solid Herald had used his powers to contain his Indignation at the palace, though the whole thing was a blur. But he was getting a bit too comfortable with restraining, or even touching his god.
"Do not put your hands on me, Ji-Xing!" Ty-Shou shouted.
Ji-Xing nodded and backed off, but still stood confidently concerned. "My Synodontis, we do not know if she is responsible for this attack!"
"Look at her!" Ty-Shou pointed.
"It's true, she was one of the only Cong Lang in the area to not be targeted in the initial attack, and the whereabouts of her father are still unknown," Qi-An said. "Perhaps this is a grab for power, such things are not unheard of among the Vareeshi."
"She looks like she's suffered an attack to me," Ty-Shou growled.
"Timing is important," Qi-An said, but he just stood still as Ty-Shou rushed up to Kitsai's side, and Ji-Xing turned his hand to steel again.
The horse came to a complete halt once it reached flat ground. Kitsai's hands went limp, and she fell off the horse. Ty-Shou caught her in his arms.
"I-I saw you," she said. "Y-you t-tried..."
Ty-Shou grasped her wounded arms. He searched for her emotions.
/Fear/.
He tried again. He tried to think about what he felt in the vision Wosa showed him of the Vareeshi in battle. Something more specific.
/Threatened./
Still, nothing. He looked at her face-- it was more peaceful. She was in pain, but any Fear, if it was there, had subsided.
/Satisfaction?/ /Relaxation?/
He kept searching. His emotional depth was wearing thin.
"Y-you h-helped h-him..."
She was here. While her nation was being attacked, falling apart, her brother murdered, she came here. She saw Ty-Shou's efforts, even though they were in vain. He heard of this before-- how he felt when the servants brought him his favorite food. When Wosa took a break from the more serious or bookish lessons to teach him something like fishing.
/Gratitude./
Bright soft curves of Light flowed from Ty-Shou's fingertips and divided into thinner tendrils which mended Kitsai's wounds. Her smile widended, and her eyes fluttered to life.
"Synodontis," she said. She looked down at her arms, which were now as clean and smooth as newly sanded piece of wood. "You saved me."
"He did. Now back on your horse, Lady Kitsai", Ji-Xing said, as Kitsai straightened her long indigo dress.
Ty-Shou politely set Kitsai on her feet before turning over his shoulder and squinting at Ji-Xing. "Does it look like she came as a threat?"
"Scouts are always sent in the lowest number, and as inconspiciuously as possible," Qi-An said.
"I understand your suspiscion," Kitsai said as she gripped her horses' lead and pet his long, dark mane. "But I am not here to threaten you. I hoped for your healing, but had come to tell you that it was Anut who attacked my brother, attacked me, and have heard reports that my father is also dead, which he no doubt arranged. He has tried to take over, and trap the kings here until king making begins. He hopes to win everything in one fell swoop."
Ty-Shou felt a trust for Kitsai, but this time he looked to his two followers for their reaction.
"What proof do we have that the king is dead?" Ji-Xing asked.
"From your eyes, no proof. But would you not think he would be here by now? Is it not an unusual coincidence that the king's son and daughter, two and three on the pyramid, are attacked when the king is away and under threat?" Kitsai returned.
"And your logic doesn't seem to follow. If all you saw was Synodontis Ty-Shou fail to help your brother, why would you assume that he could heal you?"
Ji-Xing side-eyed Qi-An again. Qi-An didn't seem to get the message. Ty-Shou didn't feel any Indigination, perhaps it was the recent warmth of saving Kitsai.
"It was a panicked situation. What mattered is that he tried to help," Kitsai said. "And if my logic is so flawed, why am I healed and standing right now?"
Ji-Xing nodded. The tough, square-bodied head of security turned back to Ty-Shou, his eyes soft in thought.
"I realize our incessant analysis may have come off as rude to your authority, my Synodontis," Ji-Xing said. "You know the facts. The decision is yours, my Synodontis."
Ty-Shou had mixed feelings about what Ji-Xing said-- being so young, Ty-Shou did feel it natural to listen to people's opinions and knowledge of the world and absorb like a child-- to have any authority to act on at all, he had to be informed enough to know what to do. However, he did find it unusual that Ji-Xing and Qi-An had been so talkative on this trip, especially since their official position was that of security guards. But this was an unprecedented situation-- Wosa had told him about how to conduct himself if everything went right, not if everything turned to chaos. He looked to Kitsai for more.
"You should leave while you are able to Synodontis. Before king making begins," Kitsai stared into Ty-Shou's eyes. "You don't deserve to be caught up in a conflict you are not a part of."
Ironically, this brought up some emotion in Ty-Shou, and now he knew how to respond. "I am a part of every conflict. I introduce myself here as the Synodontis of Beisan to avoid confusion, but the Truth is, all people are my people. The Vareeshi will soon see the truth."
Kitsai laughed. Ty-Shou raised an eyebrow in confusion. "Well, I will take advice from your right hand and get on my horse and flee then. I don't want Anut's men catching me."
With a swift jump, Kitsai pulled herself upon her horse. "Thank you, Synodontis. May we meet again, if I am still around after king making."
"Wait." Ty-Shou commanded. "We are leaving the city as well. Perhaps you will be safer with our protection."
Kitsai turned. Her lips scrunched to one side of her face in consideration.
Ty-Shou took that as a yes. "Ji-Xing! Get the rest of the men ready and tell them only to pack necessities. We are leaving in secret after a short discussion in the compound."
Ji-Xing nodded. He, Ty-Shou, Ji-Xing, and Kitsai approached the gate and rung the bell. In a matter of seconds, the black wood gate was pulled open by a thin servant.
Kitsai gave an impressed smirk. "So what is your plan?"
Some of the Bei-Sanian men, dressed in their typical deep yellow thick tunics, were already running out of the buildings on the edges of the closed compound walls to join Ty-Shou's party. They made a straight line just as Ty-Shou stepped forward.
"My Light will guide me," the Synodontis said.

* Chapter 5
"My Synodontis, your sword," a thin squire clad in slightly oversized armor held out a sheathed sword, scurrying sideways in an awkward manner to hold it out as Synodontis walked alongside the garden squares in the courtyard of the compound. Ty-Shou took the sword-- it had a long, twisted black leather handle, with beautiful dark red wood peeking through the leather's snake-like wrap. The sheath was carved in the same wood as the base of the handle, with a long snake with detailed scales on it. At each quarter interval of the handle was an indent, wherein a brilliant rainbow crystal glowed. "I left it out the day so it could fill." The squire did a deep bow, and handed Synodontis the sword along with a cover for the handle, and Synodontis returned a gracious nod.
"Uhm, Synodontis," Kitsai walked alongside him. "Maybe your Light might guide you to listening to the educated daughter of the king of this city, who does have a plan?"
Synodontis rubbed the wooden sheathe of his sword and covered the handle before hilting it on his belt. "Go on."
"There's a secret passage to the old underground city, upon which Cong Lang was built," Kitsai motioned over the hills. "It's abandoned and difficult to access, and difficult to navigate in the dark, but that might be an advantage for us if we are patient."
Synodontis' eyes darted around as Qi-An pulled open the red engraved wood doors with a mighty tug of the large bronze ring doorknobs. He waited until the party entered under the central building's curved black clay tiled roof before continuing.
"I was inclined to try to end this peacefully. Even if what you say is true, and Anut has betrayed you, the other leaders are discontent and will join our side against his order. And with you on our side, we don't need to worry about the locals either."
"You might be right about the other leaders, but in terms of sheer number they are a minority here, and with Jakari dead, Anut has control of my father's pyramid now. And the monks have been saying king making could start any night now," Kitsai said. "The fact is, if we do not leave in secret, violence is likely unavoidable."
"I am not a coward. I can handle anything from the Vareeshi," Ty-Shou said. The main doors opened again, and a trio of servants bowed deeply before entering. Ty-Shou just gave a friendly nod.
"I do not mean to intrude nor correct you, My Synodontis," Ji-Xing said as the servants swarmed in and began gathering items. "But I thought you wanted this to end peacefully?"
Ty-Shou's lips pursed. "Well, I am equally surprised that you are suggesting we hear out her plan, as I thought you did not trust her."
"That is a good point, my Synodontis," Ji-Xing said.
"All ready," a short, bald servant reported to Ji-Xing and Ty-Shou as the other servants, holding small leather sacks over their shoulders, ran to hold open the door for the party.
"We need some time to discuss," Ty-Shou said to the servant. The servant nodded and left the compound.
"Ji-Xing is right," Ty-Shou said as he sat down on one of the square, detailed stools. "If we are leaving-- then our goal is to leave with the least conflict possible. But I believe we can do that by negotiating with the other leaders and the people of Cong Lang. They will see through Anut's lies, and you can reclaim your rightful place on the pyramid."
"It is too far gone. Anut has control now, and he is higher than me in the pyramid anyway," there was disdain in her voice. "I will start my own pyramid, and will be leaving tonight," Kitsai said. "If you do not wish to join me, that is your perogative." Synodontis harshly eyed Kitsai. Should he listen to her as an ally? His masculine instincts said, yes-- her face and posture were strong, but not too offensive to seem a threat; her prominent yet rounded cheeks and chin created a perfect mix of regality and trustworthiness. But reason wasn't as sure about what her true intentions was-- on the surface, her story was a possibility, but her long term goals? ""
"Men!" Ty-Shou turned to the group of a dozen men who had lined up between the small square gardens and ponds. A majority of them, like him, had the same striking silver hair, and less of them piercing silver eyes. "We are leaving the city when the sun fully sets. The mission is to stay quiet and protect and follow Lady Kitsai. Got it?"
The men-- some armored, some dressed in the yellow imperial servant tunics-- did the affirmtive Bei-Sanian salute in response: a clasping of the palms together and an aggressive thrust forward. Ji-Xing nodded to Ty-Shou. Ty-Shou looked up at the sky-- it was a swirled pastel of dark crimson and violet; the wispy clouds slithered like the snake on his sword.
"It should only be a matter of time."


The men mounted their horses as the carriage rolled up in front of the rooftop-spotted compound. Things were just getting too dark to see more than a few paces in front of oneself.
Ty-Shou stepped onto the carriages' step bar just as a cosmo of bright red stars lit up the town below the hill-- the Cong Langans were on alert.
Kitsai got on her horse and walked it off the road towards the hill which she had come from-- she was already ahead of the problems that Ty-Shou was just spotting.
"We need to ride off the main roads, and without light," she said. "It's the only way to not be spotted."
The carriage driver turned to Ty-Shou for orders. Ty-Shou sighed.
"We will commission a greater one once we return to Bei-San," Ji-Xing said.
Synodontis looked again at the golden outline of him wrangling the dragon on the side of the carriage door. "Yes. We must," he said.
The carriage driver placed a small stone in front of the front wheel of the carriage and then unhitched the two horses. He lead them both forward for Ty-Shou and Ji-Xing to get on before returning. Ty-Shou mounted the silver-maned horse.
Qi-An stood still, the only one not mounted, like a confused child staring up at a group of adults. "Come on, Qi-An," Ji-Xing slapped the back of his horses' saddle."Are you too insecure to ride lady-style?"
Without a word, Qi-An awkwardly lifted himself onto the back of the saddle with Ji-Xing's help.
Kitsai rode ahead, but still saying close enough that even in the utter darkness the rest of the group could see the back of her horse, and definitely could hear its hoofsteps. "Stay together," she whispered to the group. "A light will attract attention. I'll move slowly, but follow my footsteps."
Ty-Shou was simultaneously impressed, offended, and though he also had auxillary negative feelings to the fact he felt this feeling-- a bit attracted-- to the fact that Kitsai had so quickly taken charge so soon after coming to him in desperation. But now was not the time to squabble about these things or work out complex feelings.
The shape of the hill now was hardly visible, and the little bumps and dips felt like jumps and drops when Ty-Shou didn't expect them. /Maybe it's time to become a better rider/.
"How do you know we're going the right direction?" Ty-Shou hissed towards the back of a horse he thought was Kitsai.
It took a little longer than expected for Kitsai to respond, and Ty-Shou almost opened his mouth again to ask the same question towards the sound of another horse.
"Growing up as a little girl who had everything scheduled for her, but always wanted to play outside, I learned how these hills felt in the dark. Well, not perfectly, I usually didn't go out when it was this late. But I can tell where everything is by where the other torches are."
Ty-Shou looked around. Off in the distance, little balls of light moved like overgrown fireflies that could only move right or left.
They kept on quite the same for a bit. Though the ride was rather slow and quiet, it felt a bit nerve-wracking, constantly listening in the darkness for the group of hoofsteps. As they got closer to a line where the bright balls would cross, Kitsai said, "Stop."
One by one, the soft patter of the horses' hooves on grass united into silence, until all that could be heard were crickets and a frog.
"We don't want to get spotted. On my mark, take off," Kitsai said. "Go a bit faster when crossing the line of torches, but follow the pace of the sounds ahead of you. It'd be a disaster if we bump into each other."
Around eighty paces ahead, five torches walked from left to right. Four torches was coming the other direction. After the five crossed the four, there was an opening behind each of them.
"Go!"
One by one, the patter of the horses started up again. Ty-Shou was fourth in line, behind Kitsai, Ji-Xing, and two other guards. Kitsai's horse crossed the line just as the two crossing torches were about thirty paces from the crossing point. However, on the side where the group of four torches was on, a couple of torches emerged from the darkness-- likely from behind a building, and started walking the opposite direction-- towards the crossing point.
The couple of torches and the four torches both stopped when they intersected, just as Ty-Shou's horse crossed the road. He could hear muttering from their direction.
The four torches started moving again in the same direction. Soon after, the couple of torches continued on.
The last horses in Ty-Shou's party sprinted across the road. After they had completely escaped back into the hilly darkness, Kitsai and the rest of the group had begun to slow their roll.
"Shit! We've been spotted!" Ji-Xing said.
Ty-Shou turned his head. The couple of torches had turned to follow them.
"Just stay calm. And stay still," Kitsai said. "We don't want to attract any more attention."
"Hey!" Someone shouted in the distance, still only visible as the torches, which kept approaching.
They got closer until the party could hear the footsteps of their horses, as well as see the group-- it was a group of only four horses.
"We aren't Bei-Sanians. We're from Vang Do, and we mean no harm," a matronly, somewhat chubby yet quite beautiful middle-aged woman spoke from under the light of the torch.
Still, nobody moved. The torch kept coming closer until their horses were touching noses.
"My name is Maleesh. We know you're trying to get out of here, and we want in," the woman spoke again.
"We would we help you when you're just drawing more attention? Do you think we're riding in the dark for no reason?" Kitsai hissed.
"Because if you don't I'm just going to draw even more," Maleesh said.
"Fine, we'll help you! Just snuff out that light already!" Kitsai hissed.
Maleesh looked to the other torch bearer before they both complied. Once again, the party was talking in darkness.
Ty-Shou squirmed in his saddle as Kitsai again speaking as leader of the group. It was time for him to take charge.
"How did you spot us?" he asked. "And let's get moving again. They might come to invesetigate why two torches went out on the middle of the hillside. Men! We're moving out!"
"We saw you leaving your compound earlier," Maleesh turned to Ty-Shou as he moved his horse into a trot. "When we saw that you left your carriage behind, we knew something was up. We tried to follow, but got lost, I hate to admit it but it was luck that you were crossing this main road when we were on it. We are not trackers or hunters by trade," Maleesh laughed. "Any how, what is your plan?"
Ty-Shou spoke quickly before Kitsai could interject. "There's an abandoned underground city that Cong Lang was built over, which connects to the outer plains."
"And how far is it?" Maleesh asked.
This time, Ty-Shou couldn't comment. "We're actually almost there," Kitsai replied. "Now just stay quiet until I give the word."
Even though he knew that Kitsai was talking to Maleesh, this time he felt her tone really get on his nerves. His fist clenched and felt rage pump through his veins. But he only had a bit of Light left-- the Light stored in his sword-- not to mention that it would be an embarrasment to erupt in front of his men, or harm his ally. He pushed it down.
They moved on for what felt like a long time as the focus required to move in the dark and push down the fear was quite draining, especially as the hill became a steep downhill. Finally, Kitsai spoke.
"It should be around here," Kitsai lit a torch, illuminating a less lush and trimmed area then their previous surroundings, full of sickly trees and yellowish grass. Ty-Shou jumped in his saddle. Frankly, they had been riding in the dark so long that the spark was a shock.
Kitsai waved the torch around the area while turning with her horse. They trotted in zig-zags for a bit until Kitsai found a natural rocky wall that intersected with the hilly terrain. She led the group down its steps. Ty-Shou guarded his eyes preemptively at the squeaking bats which seemed to shoot out of the rocks.
"Yes!" Kitsai shouted. Ty-Shou followed the ball of light which faded in between the rock face ahead. The group squeezed into the cave entrance. Two of Ty-Shou's guards lit torches of their own.
The cave immeadiately widened. As they went a bit deeper, Kitsai's light shined on two smooth stone pillars three times as wide as tree trunks.
"Rivers! There's guards," Kitsai said. She tried to hide her light behind one of he pillars, but it was too late.
"We can't leave now," Ty-Shou hissed. "We'll have to get past them eventually."
"Maybe they're like us?" Maleesh said.
"Why are they coming this direction, then?" Kitsai rebutted. "There's not too many of them. This is the only shot we got. I'll lead and try to negotiate," she whipped her horse back into a trot and turned around the pillar.
"Come on," Ty-Shou said back to the rest of the party. He rode five paces behind Kitsai. Ji-Xing and Qi-An rode next to him, and the rest rode in a blob behind them. As they passed the pillars, the
"Who goes there?" one of the group shouted. He held a torch himself. As they got closer, it was clear that they were Cong Lang guards, outfitted in the thick indigo with teal outlines.
"Kitsai, Third in Pyramid of Cong Lang, after the tragic death of my brother," Kitsai stood up straight and raised her torch to her face.
"Lady Kitsai. You know that there's a city-wide lockdown. What are you doing down here with these--" the guard leaned his head to look at the rest of the party, "foreigners."
"Well, as a High Superior, I command you to let us pass," Kitsai said.
The guards two guards holding torches looked to each other. Ty-Shou glanced between them, pulling the cloth cover off his sword's handle. Ji-Xing gripped the steel ingot in his back pocket. One guard nodded to the other.
"Of course, as per your command, Lady Kitsai," the first torchbearer said. The two guards, and the sixteen or so behind them, split to let the party passs through.
Kitsai gave the guards a small nod. She whipped her horse into a slow trot through the hall. The rest of the party manuevered to form a straight line. But as Kitsai crossed the two torchbearers, she spotted something among the men behind them that made her jump.
:comment:
maybe Kitsai is too stupid for even passing through without making the guards move more. (I originally wrote this scene like it's one big hallway.)
:END:
"It's a trap!"
Before she could even finish the sentence, one of the torch bearers charged his horse right at the party. Ji-Xing dodged the thrust. Kib-Si wasn't so lucky. The spear impaled the carriage driver like a knife through a tomato, splattering innards out the new opening.
"Kib-Si!" Ty-Shou shouted. His heart squeezed and shrank. Ty-Shou was fond of all his people, and had enjoyed talking to the driver on the ride here.
Ty-Shou unsheathed his sword and sliced right at the guard. The guard blocked with an armored gauntlet. Sparks flew. Ty-Shou's sword richocheted back. The guard yelled.
Two guards stabbed at Kitsai. Kitsai soumersaulted off her horse as the spears crossed over her saddle. Her horse squealed and ran through the guards in panic.
Kitsai stood determined like a small coyote against a pack of wolves. The much taller mounted guards closed the hall through which her horse ran through. One guard, a woman unexpectedly old and frail, rotated both her hands and flexed her fingers at the ground. Directly where her hands were pointing, a swirling, violet form the height of one of the mounted men but with crab-like legs and a praying mantis body raised itself out from the ground. Its arms started thick and pointed outwards, and divided into four sharp tendrils each, which were themselves about the length of a normal human arm. A threatening Creation.
The Creation swept its tendrils at Kitsai. Each finger spread to maximize the time and reach of the sweep attack. Kitsai backflipped back to avoid the attack. The Creation closed in. A large Bei-Sanian guard shielded Kitsai.
:comment:
creation used here
:END:
The Creation's left tendrils spread and lurched at the lumbering Bei-Sanian guard. He confidently smashed away two of them with his shield, and slashed one with his spear. The tendrils flashed white when hit, but didn't seem to be misshapen from the attack.
Ji-Xing fled with Qi-An in an opposite direction, into the darkness, to put more distance between him and the attackers. "Give me time to harden!" he told Qi-An.
From the stone ring on Ji-Xing's hand grew a layer of stone that covered his skin, moving from his arm to his torso. An enemy rider noticed this and charged at the mounted pair. Qi-An threw a quill the size of a pencil. It /flew/ like a geyser. Faster than the eye could track, it pierced the arm brace of the charging man. He howled and dropped his sword.
Maleesh and her three guards, already in the back of the caravan, retreated further from the battle, leaving the rest of the Beisanians in darkness. However, the guards and servants alike charged in anyway against the greater numbers.
The large Bei-Sanian guard threw his shoulder to stab at the Creation. The Creation's front leg flashed white, and its form noticeably collapsed to one side.
"Low!" the old woman shouted at her Creation. The Creation lowered its arms and swept at the horses' chest. The horse whinnied in pain, and raised its front legs in defense. The rider's back smashed against the rock wall. A Cong Lang rider moved in and stabbed a spear through his eye.
Ty-Shou saw the killing out the corner of his eye and grit his teeth. Indignation flared in his chest-- he pressed it down. The enemy guard thrust his spear. Ty-Shou dodged and sliced off its head.
He caught the tip of the spear in his off hand. Indignation moved from his chest to consume the spear tip with a hot glow. The enemy guard's shocked face twisted from his cut spear to the glowing red tip. Ty-Shou chucked it over the Creation to the back line of guards. It landed on a guards' chest. His neck and jaw blew to pieces.
Ty-Shou didn't waste a second to stab his flabbergasted opponent right through the neck. The guard's body and decapitated spear slumped off his horse. Ty-Shou moved back into the Light provided by his guards' torches-- he had used all the Light in his sword.
Another trio, unmounted, focused on Qi-An and Ji-Xing. Two large shields stood in front converged to shield the third. Two discs floated from his hand into the air-- A Space Herald. The discs spun at Qi-An and Ji-Xing. Qi-An squinted and aimed a quill at the disc. It shot right at it, but the Space Herald piloted it away. Qi-An panicked and grabbed another quill from his off-hand. He chucked it. It missed. He scrambled for another.
Ty-Shou saw the disc fly towards his friends. He jumped off his horse. Enough people had died today-- enough Bei-Sanians, his people, his responsiblity to protect. Another emotion flared in his body-- Determination mixing with responsibility, and even a hint of Love-- Passion.
His muscles pulsed with power. He lept forward like a cheetah, faster and farther than what was humanly possible. His guards' torch blew out-- he sucked the power from it-- and mid-jump he was cast in Darkness-- but so was the Space Herald.
Ty-Shou slashed his sword right through one of the discs. A half-moon of each fell to the ground. He swiped back for the other disc, but in the Darkness, he missed.
Qi-An could barely make out the area with the Light from Maleesh's party's torches far behind him, and the enemy's torches ahead. The disc came out of the Dark, paces away from him. In desperation, he threw all the quills in his hand at it-- it dodged. An arms length away, it shot right for his neck--
*CRUNCH!* The disk smashed into pieces. Ji-Xing drew his fist back from the successful punch.
"Good lad," Ji-Xing smirked at Qi-An. All his skin was stone except his forehead now. "Next time remind me to stone up earlier."
Qi-An nodded and breated a sigh of relief.
Kitsai's chest pumped up and down. She ran. The rocks crunched behind her. Her knee smashed against something hard, and she nearly screamed in agony. She felt ahead-- it was a wall of some sort.
She had blundered coming into the Darkness-- the Creation didn't need Light to see her, but she needed Light to see it. She spun her head in the Darkness, searching desperately for a Light source. The crunching came closer. The Light was now a smaller ball, making a sillhouette out of a few men on horses.
She pushed her back against the wall she had run into, sliding herself away from the crunching at a fast speed, and towards the Light. She gritted through the pain in her knee. The crunching sped up, and she took a chance and ran for the Light.
Three more mounted soldiers rushed at Ty-Shou and the guards.
"AAA!!" Out from the Dark, a stone-skinned Ji-Xing leaped onto a soldier's horse. He knocked him off. The horse wailed. The man screamed as he was trampled by his neighbor's horse, who also shrieked, and tripped, sliding onto the rock floor.
The other riders turned to Ji-Xing. One stabbed at him, but his spear cracked against the warrior's skin. Ji-Xing pulled the broken spear, and sent the man flying off his horse. He *smashed* the man in the face, decimating it.
The floating daggers came at Ty-Shou. They threatened to stab at his neck, he held his sword just in front of his nose, preparing to slice them. One whipped left-- Ty-Shou swung, and it dodged, avoiding his attack but moving away from his body. It slid past him and focused on his servants. Ty-Shou charged at the shieldbearers protecting the Space Herald. He sliced at the bearer's arm, but the bearer parried with his shield. The daggers moved with less grace and speed than the discs, but it was enough to fly past the servant's arms-- and cut their throats.
Ty-Shou felt fear, and rage, building in his sweat. He tried to turn it into something that could help him-- Suspiscion would let him see in the dark but leave his attackers blinded-- but he couldn't, the emotion was too volatile, too desperate, and he wasn't used enough to channeling Suspiscion. He screamed and threw his weight behind his sword, but it was no use.
Ji-Xing saw the knives move from the servant's neck's to Ty-Shou's guards. He knew Ty-Shou would be in trouble soon. He whipped the horse into a sprint, but was blocked by the last rider.
The rider raised his shield at Ji-Xing. Ji-Xing slammed his horse into the rider's', and tackled the rider to the ground. He smashed the screaming man's skull in and used his body as a cushion against the rocks.
"Get him! Only Oskavi can kill him, we need to stall!" One of the guards pointed to Ji-Xing. A group of four guards advanced and formed a defensive diamond between Ji-Xing and Ty-Shou.
"You really don't learn from your eyes," Ji-Xing said. He slammed his rock-hard knuckles against his palm.
The Beisanian guards made themselves small and held their shields close to their necks. The dagger tried to loop around the guards-- one hit it with his shield. The Space Herald lost control, and it fell to the ground. The other guard ended up with a bloody throat. The guard raised his shield and Ty-Shou stepped in to slash his sword at the dagger.
"SYNODONTIS!" the guard shouted.
Ty-Shou turned to see the fallen dagger rising from the ground. He slapped it with his sword, sending it clattering into the Dark.
He spun back around again-- to hear the broken throat clears of a guard with a dagger in his neck. The second the guard had taken a second he needed to defend himself to warn his god.
Ty-Shou screamed.
:missing:
ty-shou uses powerlessness or some other sadness to escape here. don't know what it is yet.
:END:
Ji-Xing saw the knife turn in the air, dressed with dripping blood spin back towards Ty-Shou. He was still several paces away and blocked by four guards. Spears aimed for his eyes. He swatted them away. The horses tried to move backward. He jumped and smashed one of the guards in the kneecap. He pulled another down from the leg and uppercutted his stomach, puncturing his inner organs and reaching past the other side of his back. He pushed the disemboweled guard off his arm.
Even against one floating dagger, Ty-Shou's sword was far too thin to effectively block it. He tried to lunge for the fallen guards' shield, but the Herald was too smart, and used the dagger to dominate the space. With one dagger, he played a lot slower, biding his time to wait for the perfect opportunity to slice Ty-Shou's neck.
The last guard realized his fate and retreated to just place himself between Ji-Xing and his Ji-Xing ran after him, but he just created space-- until a rock came /flying/ at the guard so hard, he fell off his mount. Ji-Xing didn't have time to look back and thank Qi-An. He just kicked the guard in the stomach and moved on.
Ty-Shou stumbled backwards. His heart shook his whole being. There was no light large or close enough for him to grab. He only make out a tiny speck of orange light on the dagger. The knife moved in on him.
Xi-Jing ran towards Ty-Shou, entering the darkness. However, his eyes found a shape-- something was there-- something dark, but massive...
The Creation. For the first time, it opened its mouth, with a row of teeth so long that it made a shark look like a squirrel, and ROARED.
If his stone skin could still make goosebumps, it would. The literally hardened warrior felt fear for the first time in decades.
He tried to move to the left. The monster blocked him. It slashed at him-- and unlike the spears and swords, he FELT this one. He grasped his stone arm in pain.
But though people thought he was muscle, it was Ji-Xing's memory that never failed him.  He remembered what his first drill sergeant had screamed in his face the first time he froze up.
/You feel the FEAR. CHARGE THROUGH IT!/
With a war cry, Ji-Xing raised his shoulder and TACKLED the monster. Its whole front lit up white. It scurried backwards on its hind legs, trying to maintain balance, getting pushed back farther and farther by Ji-Xing. In vain, it stabbed at Ji-Xing, but it's arms weren't able to reach right in front of its chest.
Ji-Xing remembered something else that drill sergeant told him when he was put on archery as a punishment.
/ALWAYS AIM FOR THE BIGGER TARGET./
He twisted his elbow and turned his charge towards the Space Herald and his shieldbearers. The shield bearers positioned to defend the Space Herald.
The back of the Creation broke through the shield bearers. Its crab legs trampled them. The Space Herald dodged and whipped his wrist--
The dagger THRUST at Ty-Shou. Ty-Shou ducked. He could only feel the emotions, and the true fear of having no way to channel them into power. Of being turned from a god into a helpless child.
Ji-Xing uppercutted the Creation, sending it flying on its back. The Space Herald motioned with his wrist, but turned his focus to Ji-Xing.
The dagger slammed down. Ty-Shou scrambled onto his back. The Vareeshi fighter's memory of death he experienced felt like a joke now-- it was as real as any day, but that little part of the brain that knows something is fake goes a long way. Here, in the Darkness, there was no Hope. There was nothing but void waiting for him.
The Space Herald ran. Ji-Xing lunged forward.
The dagger sped for his neck. Ty-Shou didn't move in time, and only thrust backwards.
Ji-Xing gripped the Space Herald by the back of the neck.
The dagger's tip hit Ty-Shou's neck.
Ji-Xing SQUEEZED.
The dagger fell. The flat long side landed onto Ty-Shou's belly.
A demonic swallow came from the Space Herald's mouth. His body collapsed. His head still stayed on the spine, but tilted, with an hourglass-like dent in his neck.
A blood red line came to life on Ty-Shou's neck.
Ty-Shou sat up.
No blood dripped from it. A superficial scratch.
All the guards were dead, except the elderly Creation Herald, who Kitsai pointed a sharp sword at. The woman raised her hands in surrender.
With a shaky hand, Ty-Shou picked up the dagger off his belly, and blew out a huge exhale.
Ji-Xing picked up one of the fallen guards' torches. His skin gradually faded from stone grey to brownish yellow. The group regrouped around Kitsai and the Creation Herald.
"I surrender to you, Lady Kitsai," the old woman knelt. "I am not high in your pyramid, nor have I ever been high in any pyramid, and neither has my family. Please let me live for this king making."
"Today is your lucky day," Kitsai said and lifted the woman's chin. "I have just founded my new pyramid, today. You can be my Second."
The woman gave a creased smile and a nod.
"You should fix your Creation, to make it's arms able to reach directly in front of it," Qi-An said as he knelt down to check the pulse of one of the guards. "So someone as bold as Ji-Xing can't just beat it by charging like that."
Ji-Xing smiled and patted his prodigy on the back. "It's scary enough already," he said.
"Mal-EESH!" Kitsai shouted, cupping her hands on her lips. The shout echoed through the entire cave. "We won!"
There was a pause, and then the clapping of hooves slowly got closer as the torches approached, their echoes doubling and tripling through the expanding cave.
As they got close enough so their torches' light met with Ji-Xing's, Maleesh gave a kind smile, but it came off as forced.
"You didn't fight at all," Qi-An said, but his tone was not accusatory.
"Of course," Kitsai said as she picked up the shield of a fallen guard. "You Vang Doans are degenerates."
"It's not king making yet," Maleesh raised her chin defensively. "Not only are we not obliged, isn't it dishonorable to attack an opposing pyramid beforehand?"
Kitsai spit toward Maleesh. "We were fighting for our lives. And like you cowards plan to do anything this king making."
"We are still Vareeshi," Maleesh said, her words ignoring the spit but her expression clearly acknowledging in. "Strict fundamentalists like Khua and backwards animals like Hysho will get nowhere in the coming world. I thought you Cong Langans were smarter."
"You choose not to fight and to work with the rest of the world because it is easy," Kitsai said. "That is the definition of dishonor, and against all Vareeshi."
"Vareeshi or not, even the simplest barbarians would consider what you did a slimy act of cowardice," Ty-Shou said. "You owe us your life, and especially the innocent Bei-Sanians who were slain due to your cowardice."
Ty-Shou's heart was still pounding, and he poured the energy into his words. Now he feared truly death-- but could a god like him even die?  Perhaps that was the very reason he feared it-- the fear that if he did die, it would prove he was not one. That all the legends he was told about himself was a big lie.
:comment:
is this too obvious foreshadowing?
:END:
"We did not kill them. But the rest-- is fair," Maleesh's lips tightened. "And you will see that Vang Doans DO have honor and repay quite generously."
"Cowardice and actions not meeting words are too traits that go hand in hand," Ty-Shou returned. "I hope you defy the norms."
Maleesh just smiled awkwardly again.
"You mean, dishonesty?" Kitsai raised an eyebrow. Ty-Shou said nothing, but inside, he facepalmed. Though his grasp of language had been quite good, sometimes, he said phrases that sounded odd to everyone.
"The battle is over," Ji-Xing said. "What's important is that we get out of here as fast as possible, before reinforcements arrive."
"Agreed," Kitsai said. She turned to face deeper into the cave.
"Or worse, before king making begins."

* Chapter VI
Ty-Shou weaved like an excited child from the Vang Doan guards' side to the middle of the party, where Kitsai huddled with her new recruits. Ty-Shou remembered Wosa's voice. /I know you're excited, but you must always maintain a regal posture./ He slowed his roll and straightened his face as he approached a group of tall armored men.
Kitsai had picked up quite a mass of followers along the littering rural towns of Cong Lang past the other side of the abandoned underground town, and they had taken a detour to a small temple just outside the city where Kitsai had received a chest full of the same circular, numbered necklaces that Ty-Shou had seen in his vision. Everyone in the group wore their new ones. The old Dark Herald had moved down pretty far from second, but she was happy all the same.
It was getting late, and the former daughter of Cong Lang was scanning the sky again. The sun was setting, and the large moon was hidden behind the clouds. She still stared at it, as always.
"It's getting closer," she said, same as the past few nights since they had left the city. "The monks said it would start this week."
Ty-Shou shivered. The area was not dense enough to give that protection forest roof and that powerful feeling of a breathe of dense nature, nor open and dry enough to give the feeling of serenity away from danger. Rather, they trudged through a bog speckled with trees and reeds, many merely corpsed foliage being consumed by the sinking swamp. Dark, cold, wet, thick.
Their clothes embodied the environment now, too. Delicate patterns woven over wispy white dresses, meant to create a semi-transparent effect to evoke an ethereal beauty, had been ruined by a stain of thick mud. Colorful cultural threads that had been layered and relayered to pop more than anything in the natural world had been sucked dry by the rain. Everyone had regretted bringing their best to the palace.
The couple Ty-Shou had come up next to noticed him and smiled. Ty-Shou bowed his head.
"Hello," he said. "I did not get a chance to meet you yet since you joined us. My name is Synodontis Ty-Shou Xing of Bei-San." Though he wasn't confident about his vocubulary in Vareeshi, Ty-Shou spoke the words proudly.
"We are Caman and Jusill of...," they looked to each other, and then at Kitsai. "Kitsai? Now, I guess so."
Ty-Shou chuckled and they did as well. "Yes, new startings are exciting. But I am more excited by everyone's whole story. Where did you come from? Even before Cong Lang."
"We actually used to be from around this area," the plump woman said. "We were part of Tesaak pyramid before last king making."
"I do not want to try to find a place to sleep here again," Maleesh interrupted, speaking at Kitsai. She had come up behind the group, still on horseback. "You said you could negotiate with a local lord to let us stay."
Both Kitsai and Ty-Shou turned to glare at Maleesh. "Your impatience is coincedental," Kitsai said. "My new eighteenth was just speaking of it-- we've just entered Tesaak's territory, and he might offer us a place to stay in exchange for an alliance in king making."
"Before I was interrupted," Ty-Shou grumbled, "Who is this Teesak?"
"Tesaak was my father's prime enemy in the region before last king making-- we really cut him down to size," Kitsai said. "Probably a good two-fifths of all Cong Lang is made up of former Tesaak."
Ty-Shou knew, but didn't understand, the ever-changing loyalties of the Vareeshi. Ever since he was reincarnated, Ty-Shou had been told one truth about his origin, his people, his land, and who he was. The Bei-Sanian people had problems, but they were one people together, who did not change: if there was a problem about his people, it would be that they were not ready for the realiziation of his destiny to rule over all people and not just them.
Ty-Shou's stomach grumbled. They hadn't eaten since yesterday, when one of Kitsai's new recruits hosted them. They kept struggling through the swamp, the only comfort being their group and the chirping of frogs, crickets, and owls.


They crossed a river and reached a drier clearing that intersected with a dusty path. Kitsai took some time to figure out where they were before leading them down the path. It had grown darker and now they could only make out the faint shapes of animals rustling in the bushes, but they noticed black sloped roofs between the trees-- a town. As they approached, some figures moving at the end of the town came closer.
"HALT!" One of them shouted. "STATE YOUR PYRAMID AND BUSINESS!"
Kitsai pushed through her lowers and ran up by herself to shout. "KITSAI PYRAMID LEADER HERE WITH VANG DO PYRAMID LEADER AND SYNODONTIS TY-SHOU XING OF NO PYRAMID! WE ARE SEEKING TO NEGOTIATE AND BE HOSTED BY LORD TESAAK!"
There was only crickets for some time. Then: "APPROACH! WE WILL ESCORT YOU TO LORD TESAAK'S MANOR."
The party rushed into the town. There was no thought to Suspiscion, only sanctuary. The torchbearers, armored in a dusty brown, led the . Though it was dark, Ty-Shou could see the similarity between Tesaak's houses' and the Cong Langs; they also featured the steep clay tile roofs except they were at an even steeper, though their designs, as did the whole town, blended into the forest; they were made with the same sharp shapes, but as natural in pallete as tree houses. Both the houses and the paths were shaded by trees and foliage, unlike the Cong Lang who seemed to clear the entire area to appear like just palaces on a hill under the sun. Ty-Shou wasn't used to so much green; he had spent the last three years on the rocky coastal hill of the Bei-San palace.
The road turned into an outdoor gate, and the guards had anyone with a horse mount them to the fence before they proceeded inside.  The party plodded through a field filled with sheep and goats. Here they looked much more docile and domestic than the crazy mountain goat Ty-Shou occassionally saw when training on the rocky coast. A massive hay mat, covered with mud, lay on the front steps before a stone staircase that led up to a square palace with a pyramidal black roof with several wood pillars stretching the horizontal length beneath it. The guards brushed their feet off in an obviously illustrative manner before walking up the steps and knocking on the large stone door. A bald man answered the door with a candle in hand as the party wiped their shoes and trickled up the steps. The bald man whispered to the guards, left, and closed the door before returning shortly after. Ty-Shou couldn't make out what they were saying, but he knew the master of the house wouldn't speak like that. Before the servant could speak again, heavy footsteps banged from within.
"What is it at this hour!?" A man with a different accent than the Cong Langers said. He opened the door, and his expression took a second to go from irritable to a smile. "Oh, guests!"
The man had a thick, black, straight, hair, eyebrows, and mustache. His frame filled the door and gave the room a serious, but not scary, air.
Lady Kitsai bowed, and the rest of her pyramid bowed after her, though some were delayed. "Lord Tesaak. I, Lady Kitsai, request to discuss some important matters and to stay with you for a night."
"Lady Kitsai. I am pleased to meet you face to face, but I must admit this is quite unusual timing," Tesaak smiled.
"I apologize for the disruption," Kitsai said. "If you can't tell from our condition, we would not have come if we had any other option."
Tesaak laughed as he used his hand to sweep some dust and food into his hand. "Your stay might not be as luxurious as you expected. I had to permanently move to a smaller manor after my former one was destroyed near the end of king making by Cong Lang," there was a hint of disdain in Tesaak's voice.
"Then you'll be happy to know I am no longer a part of Cong Lang," Kitsai said. "I hate to inconvenience you, but do you possibly have some room for the rest of my party?"
"We'll get you all settled. My pyramidmen are very hospitable. There should be several houses able to host a guest or two," Tesaak turned to the servants and the guards. "Get them "
"Lord Tesaak was always a gracious leader," Caman said to Ty-Shou. Jusill nodded.
The guards and servants lead some most of the party back outside the manor and into the town. Tesaak himself welcomed Ty-Shou, Ji-Xing, Qi-An, Kitsai, Maleesh and one of her guards into his home.
"As I said, the manor not quite as hospitable as before. Unfortunately you'll have to share rooms. You look hungry, I can have the servants prepare you something when they get back," Tesaak said as he led them into the living room. Not much was visible beside the planks illuminated by Tesaak's candle, but the smell of warm, raw wood reminded Ty-Shou of spring, even though it was closer to fall.
"Thank you, Lord Tesaak," Kitsai and Ty-Shou said in unison. "Your hospitality is greatly appreciated," Maleesh said.
"The rooms are upstairs. I'll lead you to them. If you don't mind, let's save the negotiations for tomorrow. We are all exhausted," Tesaak said.
Kitsai looked to Ty-Shou and nodded. "Agreed."
Tesaak did just that. He strode around his own house, up the stairs, down the stairs, holding his candle with one hand like it was an explorer's torch. He was determined, but high-strung, almost anxious, in his voice and movements. In the end many had a small rice bowl and mushroom soup delivered to their rooms. Part of Ty-Shou's heart wanted to share a room with Kitsai, but he decided against it and bunked with Ji-Xing and Qi-An. He had never shared a room with a woman-- well, he had never shared a room with anybody, but he had never even shared a /building/ with a woman-- and this felt like an awkward time to start. Both Ji-Xing and Qi-An had collapsed with a wool blanket tucked over them into a heavy snore. Ty-Shou's eyes stayed wide in the dark room, his feet hitting the bamboo frame of the bed. His mind bounced between the unanswered questions-- /Was Kitsai to be trusted? Did she like him? Was it really Anut who did this attack? What would Wosa say about these events? Would Bei-San survive this king making?/ Eventually, the whirlwind of thoughts drifted into mindless, broken ones, softened and suppressed by the Darkness.


Many slept an ample time, almost double a normal day's rest, as they had pusehd through the night days before and exhausted themselves to gain a lead on Anut's pursuing forces. Ty-Shou was one of the last to wake up.
After taking a cold bath, he made his way downstairs. Kitsai had already taken a seat at the circular table under a glass


"Perhaps. Some Vareeshi legends say that at the end of time, all humanity will be under a singular pyramid, and the ruler of that pyramid will be like a god. It is called the Last Heaven."
"Perhaps you are not as far from the truth as I thought," Ty-Shou said, his eyes fixed on a caramel dresser and the porcelain vase atop it.
"And you think that is you?" Kitsai said with a smile of disbelief.
"Yes. And it is not some empty megalomania. Nearly a thousand years of Bei-Sanian history and prophecy predict my arrival and my salvation of both the Bei-Sanians and all peoples. And even the Versalists concur, though they call me by a different name."
:style:
Maybe use a different word not as long as "megalomania"
:END:
"And what is that? That you are the god of all people? And you think everyone, even the Vareeshi, are your worshippers?" Kitsai asked.
"As I said, you are already one, you just don't know it," Ty-Shou said without a drop of humor. Kitsai gave a wide-eyed, flabbergasted expression, but Ty-Shou wasn't looking.

"Perhaps an alliance would not be a terrible idea," Tesaak said. "I need all the help I can get."
"I will be a king! Cong Lang will be no more! It will by mine! Khua will bow! It will be mine! Xirin, Iletta-- no one will speak their names! It will all be mine! There will only be Ding Wao!"
The thin man laughed maniacally.

"It's been so long since I tasted blood," the old man said. "This may be it-- the last stand for me to determine my eternal life. Whatever pains, whatever hardship-- it never compares to the rewards of eternity."
The old man's mandible raised like a tiger, as did his arms, the katanas in his hands like the canines in his mouth.
His fingernails /tore/ at his nose-- deep lines tore, like a cat's paw ripping a blanket.
THEY TRY TO DROWN JI-XING
SOMEONE LOSES AN ARM (maybe kitsai

"Let's be honest, Kitsai. My pyramid has no hope of surviving this king making. And Anut was always a conniving bastard-- an offering is the only hope I have of getting a good invitation into Cong Lang. And just like that, the prettiest little letter just slid right into my hand," Tesaak grinned.
"That's not your only option, Tesaak," Kitsai's eyes were wet with desperation. "You could be my second-- I could use your experience."
Tesaak sputtered. "What a joke. Starting a new pyramid a day before king making? I thought you were smarter than to get new tip delusions, Kitsai."
"MENNN!!" Tesaak shouted down the hall.
"If you want a fucking damn good heaven--"
He paused and snapped his arm at Kitsai.kxs
"KILLLLL THEMMMMM!!!! KILLL THEMMMM ALLLLLL!!!"
