* To Do
* Part I
** Chapter I
Ty-Shou was three years old, but not a child. He had appeared fully formed in ball of light. The people of Bei-San claimed he was the reincarnation of a long dead god. Every step Ty-Shou took in the city was met with rapturous praise. People told him of all the legendary feats he had accomplished in his past life. They said that Ty-Shou built the city of Bei-San itself, that he had sheltered the people from the great turmoil of the Age of the Gods, that he had been able to transform people into the best versions of themselves. None of which he remembered.
"My Synodontis, please focus," the use of Ty-Shou's formal title cut through his introspection. The words had come from Wosa, his closeXst advisor and the man that guided him through his rise to fame. He had the silver hair— thinning at the temples —and silver eyes, typical of a Bei-Sanian. His wrinkled bronze skin was similarly typically of the city's populous. He was shorter than the average Bei-Sanian, and almost two heads shorter than Ty-Shou himself. Wosa carried himself with authority despite his stature. The old man easily filled the voluminous multi coloured robes favoured by the cities aristocrats. His own colours more muted than those worn by the two other servants in the room.  
"We've had this lesson a thousand times already. Can we at least go outside if we're going to be repeating lessons." Wosa insisted on conducting Ty-Shou's lessons in the same room every day, no matter the season or weather. The room was at the heart of the palace, with no windows. The room was lit in an iridescent glow from the Light Crystals around its perimeter. 
"If you stayed engaged throughout the lesson, perhaps I could rest assured that you understood the materials." Ty-shou hated the soft, suffering look Wosa so often had. "Now, what is this Crystal used for?"
In his hand Wosa held a perfectly black Crystal, one that appeared more as an absence of light than an actual object.
"It's a Dark Crystal. A full Dark Crystal," Wosa gestured with is fingers, urging Ty-Shou to go on. "This one is filled with a memory of a great battle. You're going to use your Heraldry to show me the memory so I understand how brutal the Vareeshi are."
"Good, but do not roll your eyes when you speak. The Synodontis does not roll their eyes."
Ty-Shou rolled his eyes again. The young god truly didn't understand this song and dance. From his first lessons in geopolitics, Wosa had emphasized how brutal the Vareeshi religion was. A religion built on might makes right and winner takes all, where people swore themselves to great men in the hope they would conquer all and lead them to eternal paradise. In Bei-San, the Vareeshi were a religious minority. But it was the only way of life for most of the neighbouring Central Marthian nations. Now that Ty-Shou was to leave the city for his first time, Wosa had been insistent on reviewing, and amplifying every lesson he had had on the Vareeshi. Still Wosa thought Ty-Shou didn't properly understand it, and had devised to show him a memory of Vareeshi brutality. Wosa helped seeing how they made their hierarchies, and how brutal the King Making fighting was would work better than lecturing Ty-Shou.
With a flourish of from the older man's hand the two servants covered the Light Crystals, plunging the room into darkness. Wosa's weathered fingers gripped Ty-Shou's forehead. The outline of the Crystal in the advisor's hand gave a false glow as Ty-Shou felt himself plunging into the false sleep of memory viewing.

Ty-Shou didn't know much about the man who's memories he now inhabited. The Synodontis knew instantly that his new body was shorter than his real one. Height was always one of easiest ways for Ty-Shou to spot an inserted memory.
He stood near the centre of a vast circular chamber. Pillars of painted red wood around the perimeter rose 50 feet up to hold up a wooden ceiling, intricately engraved with Vareeshi writing. On all sides of Ty-Shou a frantic mob pushed in, jockeying for position. The attention of everyone in the chamber was fixated on the structure at the very centre of the chamber. A towering triangle, nearly the height of the chamber itself. Ty-shou knew from his lessons that the triangle was made of a specific wood, found only in the Central Marthian valleys where the Vareeshi monks made their homes. The triangle was split into multiple tiers, each bigger than then the last, and filled with intricately designed wooden balls.
Ty-Shou held a similar wooden ball in his hand. Half his ball was plain wood, the other intricately carved and painted. He knew the ball was meant to represent the life journey of the person who's memory he inhabited, but Ty-Shou was unable to properly interpret it.
The ranks of the crowd slowly move forward, and Ty-Shou found himself at the head of the crowd before long. Near the base of the triangle, a monk in gray robes stood with his hand out for Ty-Shou. Ty-Shou watched his hand move as the memory played. He handed his ball over and the monk placed it at the bottom of the triangle, in last place. Once the ball in place another monk--- in the same gray robes ---handed him a circular tag with the number of his place in the pyramid on it. Ty-Shou placed the tag around his neck, like everyone else in the chamber had. That same monk called out his name with his number, and the crowd yelled it back in a chant. Suddenly, Ty-Shou felt the edges of his consciousness blurring as the memory skipped forward.

The memory rematerialized as Ty-Shou found himself in the middle of a battle. He was shoulder to shoulder with other men, all holding spears. Mere feet away, the enemy formation of spears thrust forward. All the men he could see wore simple leather armour. This memory was old, at least 400 years old.
A spear tip grazed Ty-Shou's cheek, and he felt searing pain shoot through his body. An equally intense freezing fear set into his bones. Ty-Shou couldn't tell if the fear was his own, or from the memory. Before he could decide he felt himself jolt forward in a lunge. His spear tip danced past an enemy spear and found purchase in their neck. Shoulders pressed up against Ty-Shou as his formation took a step forward. The man next to him dropped as the enemy thrust forward. Ty-Shou's spear frantically worked to parry incoming attacks, but the enemy formation pressed forward endlessly. Around pained moans from his allies filled the air. Men from the back ranks of the formation moved to fill the gaps as the injured were dragged to the back. A whistle blew and Ty-Shou was pulled back as a new front rank swapped in. He felt exhausted, more than he ever had in his short life. His body sagged with the effort, and leaning on his spear was all that kept Ty-Shou from slumping.
The yelling from the formation's head grew louder, and nearer. His grasp on Vareeshi was weak, but he was sure the yelling was in a dialect he hadn't been taught. Around him men snapped to attention. Ty-Shou's grip on his spear tightened. A sudden wave of motion knocked him on the ground as a group of the enemy burst through the ranks.
Two men led the charge of the enemy spearhead. The nearest had long black hair tied in a bun above his head, and a slender face. He wore light leather armour, like the other enemy soldiers. Three men charged him, and each was easily defeated. In his light armor, the man weaved through attacks perfectly parrying each with his straight edged blade. The other man was an obvious Space Herald. He had short cropped black hair, and a scar across his left eye. Three discs spun around him creating a protective radius around a foot wide.
The Space Herald's eye snapped to Ty-Shou and a disc came flying towards him. He rolled in the bloody dirt causing the disc to barely miss. The man must have been a powerful Herald to move the disc so fast. He scrambled to his feet barely dodging as the disc came back around. The Herald was keeping his distance well, his ally dispatching attacks before they could threaten the Herald. The long haired man moved with inhuman efficiency. He slipped between spears and parried attacks in perfect rhythm, with no wasted energy in each action. It was the same pattern of attack repeated. The long haired man would slip an opportunistic attack from behind, before lunging for the man in front of him. His blade thrust between his victims armour. Before the dying man could drop to the ground the inhuman swords man would reach out with is off hand to grab the number tag around his victim's neck.
Ty-Shou felt fear from the man who's memory he inhabited, but the god knew what the inhumane attack was. A Time Herald. One of the Subject Tree. It explained his superhuman reactions to attacks he shouldn't logically have time to react to, and how he always managed to perfect place himself and his blade. Judging by the number of number tags in his hand the man must have killed nearly three dozen men in his rampage. Two Heralds as skilled as these two could easily break route a hundred men undisciplined men. Ty-Shou saw it happening. The fear building in the soldiers around him, those near the back looking to flee and being pushed back by the elite rear guard. He let out  fierce roar and charged towards the Space Herald. A disc shot out from the Herald in response. Ty-Shou ducked his head and felt the disc graze the top of his hair. Two shouts rose from the crowd as two other soldiers joined Ty-Shou. He could feel his heart beat in his ears as he ran. In three years, his heart had never beat so strongly.
They were 15 paces off the Space Herald now, maybe 12 from his defensive radius. Two discs came at him now, one flying from around the Herald, the other coming in on the right flank. The soldier on his right caught the clean across the throat. The disc slowed to a brief crawl as the Space Herald pulled the soldiers number tag off and towards the Herald. Ty-Shou thrust out at the head on disc, managing to knock it enough to make the Space Herald loose control.
They were 10 paces off now, and the Space Herald had only one disc remaining. If Ty-Shou could close the gap before he brough the other two discs back on defense, he had a chance to kill the Herald.
A shoulder slammed into Ty-Shou. He stuck the butt of his spear in the ground, barely keeping upright. Before he could turn his head a punch clocked him clean across his face, and he was sent flying back to the bloody dirt. The final other soldier in Ty-Shou's desperate charge neared enough to thrust at the Time Herald. The Herald leaned his body perfectly enough to dodge the thrust. The soldier pulled his spear back and the Herald slipped down the shaft to within the weapons reach.
Ty-Shou jumped to his feet to defend his fellow soldier. He pulled a short dagger from his belt and jumped on the shoulders of the Time Herald. The Herald thrashed trying to throw Ty-Shou off. He locked his legs and elbow around the opponent and stabbed down with his dagger. The Herald jerked his hand up to catch Ty-Shou's forearm. The other soldier, discarding his spear, ran up to kick out the Heralds leg. The Herald rapidly twisted around the kick. In the same motion he jerked Ty-Shou's arm down and over, shifting his body weight into a throw.
For the third time in the fight Ty-Shou felt himself thrown onto the ground, this time he was on top of his ally. The whizzing of a Space disc cut the air as it embedded himself in the other nameless solider. Ty-Shou rolled off the body but was pressed to the ground by the Time Herald. He tried to stab the Herald's leg but he had lost the dagger in his fall. His unarmed punch barely phased the Herald as he plunged his sword down and between Ty-Shou's eyes.

Ty-Shou was panting and covered in cold sweats when he came out of the memory. The servants had uncovered the Light Crystals at some point.
"Do you understand now?" Wosa asked.
Ty-Shou felt sluggish coming out of the memory and could barely move his head to nod. "That was... What was that feeling? I- I've never felt it before."
"Fear," Wosa said solemnly. "I'm glad you understand that now."
Ty-Shou knew his heart wasn't racing, but he could still hear the drumming of a heartbeat in his ears. The lingering effects of the memory but have been evident, as Wosa knelt down to meet Ty-Shou's seated eye level.
"You are the most powerful Herald to have ever lived. Those Heralds in the vision have barely a fraction of your power my Synodontis." Wosa reached out to grab Ty-Shou's hand. "I've tried to instill in you how powerful you are, how much capacity for good you have. I hadn't intended for this lesson to reinforce that. Perhaps now you understand both how brutal the Vareeshi are, and how much power you hold."
Ty-Shou didn't reply, only nodded.
"Come, it's time to leave for Cong Lang. We must ensure we make all our appearances at the festivities before King Making begin in earnest. You would not want to experience the real memory now, would you?"
Ty-Shou rose from the chair with a shake of his head. "Of course not."

The streets of Bei-San was overcrowded for his procession out of the city. Ty-Shou rode in a two tiered carriage, pulled by six horses. The carriage had been originally commissioned by the Stewards of Bei-San. The noble family appointed to lead the councils of nobles and govern Bei-San in Ty-Shou's stead. The carriage was a reflection of the prestige and history of the city. It was made of black lacquered wood, with a polished gold trim along it's edges. The panels were engraved with art depicting the most famous of Ty-Shou's feats. The door panel had his favourite engraving. One of him standing against a dragon coiling around the world. The bottom tier was designed as a regular carriage for long distance travel. It was padded seats which could be made out into a full bed by his servants. Light curtains gave privacy, but allowed in a light breeze while on the move. The top level was a viewing platform. A waist hair railing ran around it's edge, allowing Ty-Shou to stand and wave out at the Bei-Sanian citizens as his carriage wound its way out from the palace at the city's heart.
Wosa had help back no level of splendor for the parade. The trip to Cong Lang had a stripped down escort, despite that every one of his mounted Royal Guards had on perfect dress uniforms. A long stark white tunic which flowed down to below the knees, cut in the middle to allow for comfortable riding.  A golden belt secured at their waist gave the top of the uniform a sharp triangular silhouette. The tunic was trimmed in the same shade of gold. In the centre of the chest the symbol of Bei-San was embroidered, a blazing 16 pointed sun held in the palm of Ty-Shou's hand. Their tall black hats provided minimal shade, with a thin rim.
The Imperial Guard were selected for their size strength. No man was shorter than Ty-Shou, all at least 12 hands tall. Each wore two weapons. A long sword for unmounted combat, and a curved cavalry blade.
At their head was Ji-Xing. The head of Ty-Shou's guard, and Field Marshall wore a white hat to match his white uniform. At 45 man was past his physical prime, but could easily beat five of the other Royal Guard at once. The man's face was nearly a perfect square with a jaw line that could cut glass. A scar across his eye gained during his youth only added to the Ji-Xing's fierce nature.
As they passed alleys, Ty-Shou could see people lining up 30, 50 ranks deeps to try and get a glimpse of their god. From the window of passing houses, and from the nearest ranks on the street, Ty-Shou could hear Bei-Sanians yelling for blessings. Some even prostrated themselves on the pavement in attempt to garner his favour. A yell to bless a sickly relative. One to aid a son on an examination. They were all cries Ty-Shou had heard before, and all aid Ty-Shou had no power to grant.
His powers allowed him to heal some of the sick and wounded, but only if he was in the correct mental state. But he couldn't bless people with better fortune, or perform any true miracles. He was a Herald, but they called him more. They called him God.
** Chapter 2
Cong Lang was the crowning jewel of the Central Marthian cities.
** Chapter 3 
Jakari's ball was as elegant as he had promised it would be. The city itself may have been poor in comparison to Bei-San but the palace at its heart
was an equal match. The palace's size and opulence had been clear from the moment Ty-Shou entered the city. Yet, he found himself in awe of the beauty as he approached.
The palace had been under construction for three generations--- commissioned as a sign of Cong Lang's post Delmian independence --- and had only been completed 50 years ago. The complex sat upon the city's name sake, Cong lang or the river hill . The hill around which the two life blood rivers of Central Marthia merged to create the river Keesh. The Yahl River, which flowed down the Nihdan mountains and through Delmian, and the Tacuk which from from the Northern Straight. The confluence of the two rivers had given the city influence, power, prestige, and wealth. Now they had built this palace to reflect all those things.
Ty-Shou's escort for the event was a compliment of only three. Ji-Xing, his protege Qi-An, and their carriage driver. The invitation had specified that only two servants would be allowed per guest, so Ty-Shou had taken a two man carriage tonight. Across from him, Qi-An sat with his attention out the window. The young guard sat straight backed and coiled for action. His internal anxiety was given away only by the rapid drumming of his fingers against his sword hilt.
Ty-Shou had been content to attend alone, he had in fact been looking forward to it. But, Wosa had lectured that it was improper for a man of his station to travel without a guard. Ji-Xing would have protested as equally strongly on the grounds of security. But he was God, should he not be able to go alone if he wanted?
The carriage came to a stop in a crowded stone square at the bottom of the hill. A guard dressed in Cong Lang indigo and teal conversed with the driver, pointing to an open spot at the edge of the square where he could park. Past the guard, Ty-Shou could see other dignitaries departing their carriages. Some wore the more traditional single piece Marthian tunics, while others wore the more modern Kaihanese suits and dresses.
The flowing, over sized, dresses of the women were unlike any that he had seen worn in Bei-San. Wide neck lines plunged to to reveal enough skin to make Ty-Shou blush. The colours were more intricate, yet more muted than the ones worn in traditional clothing, favouring detail over bright ostentation.
The modern suits of the men were tightly fitting. Their pants rose high on the waist and were paired buttoning tunics. Each man also wore a jacket with tails flowing down to their calfs.
Ty-Shou found their absence of head coverings most interesting. The Vareeshi minority in Bei-San wrapped their long hair in silk coverings above their head. He saw similar styling in some of the guests around the square, but many had their hair visible and intricate braids, flaunting the traditional covering of hair. Others wore hats, or shawls. 
A knock came at the door as Ji-Xing pulled the carriage door open. "We're to walk the rest of the path up to the palace, my Synodontis."
Ty-Shou nodded, "we have no complaints."
Ji-Xing took a step away from the carriage allowing Ty-Shou to descend himself. The square smelled of sweet tobacco. Coachmen awaiting their charges lounged smoking pipes or playing card games with the other servants which had been denied entry. Qi-An coughed at the smell as followed behind Ty-Shou.
At the gate, Ji-Xing gestured Qi-An forward and the younger man proffered their invite to the guard. The guard looked it over for a long moment. Did he not trust Ty-Shou? He scrutinized the Synodontis' invitation?
A flare of energy rushed through Ty-Shou's blood as he felt Indignation flare in him. The energy rushed to his finger tips, begging to be infused into an object.
He took a deep breath and let the emotion fade. The rush of power subsided.
The trio was let through the gate with a simple wave. No bow. Not even a note of gratitude for his presence. Only his escort spiriting him past the gate kept him for activating the full force of his power on the gate guard.

The path up to the palace was a beautiful walk. Light lamps lined the path, shimmering iridescent light over the cobbled path. Trees on either side arched over the path isolating the background chatter of the city. As they walked the path only the occasional croak of a toad or buzz of a bug could be heard. The path wound its way around the hill at a steady incline.
"Bastards forced us to walk," Ji-Xing said in Bei-Sanian. The other parties were close enough to hear him, but none of them appeared to speak the language. "It's a power play, they just want to tire us out."
"We do not think so,"" Ty-Shou said. Ji-Xing for all his wisdom was an army man. Every problem was military, every action one step towards winning an unseen battle. "It's a display of opulence, not power."
Ty-Shou heard Qi-An gasp as the trio stepped out from under the tree cover onto a carved stone outcropping. The city of Cong Lang and the royal grounds of the palace spread out beneath them. The hill and a large swath around it had been gated off for the royal grounds. Garden paths curved around water gardens and under huge drooping trees. There were no hard lines or symmetry in the layout. Everything had been arranged to flow naturally with the land. How much of the land was artificial was impossible to tell.
From his vantage point Ty-Shou could see the dense city within the walls and far beyond to the towns and farms surrounding it. Ships laden with cargo drifted lazy past each other as they went up the two rivers. From above, drifted the muted music of the ball. No map could have ever conveyed the scale of the city to Ty-Shou. Bei-san held it's majesty in its history, beauty, and its people. But Cong Lang's sheer scale was nearly enough to dwarf those all.
Ty-Shou felt eyes on him from the stragglers on the platform. He had no idea how long he had been staring out at the city. It couldn't have been longer than a handful of minutes. However long it was, was enough to cause a scene. Holding his head high, the god swept past the onlookers and up the final dozen or so steps to the palace itself.
At the top of the hill, a path lined with guards every 10 paces led them towards open doors of the entry hall. The entry hall jutted out towards them and rose up five or six stories to a slanted tip. Like the rest of the palace, it was made of large smooth white bricks, with smaller grey bricks filling in detail. On perpendicular to the flanks of the hall the west and east wing grew. The two wings were identical, defined by their curved glass roofs and huge glass windows. Each window was identical, five paces wide, 60 tall, and placed at 15 pace intervals. Between them, the same white stone as the hall served as the frame work. Ty-Shou had never seen windows so large before. However, it was the curved glass roof, which rose almost as dome, that was the true marvel of the palace.
"For such a violent people, you'd think they'd make more secure palaces. I could 


The banquet was held in the palace's great hall, a
vaunted stone hall who's ceiling seemed to reach up into the clouds. Carved stone pillars ribbed the hall, rising to support the dauntingly tall hall. A mezzanine ran the length of the hall on either side, giving dignitaries a more private place to talk.
The Bei-Sanian party entered from the wooden double doors at the front of the hall. The vast room was long enough that Ty-Shou struggled to make out the figure of Jakari and his sister atop of their thrones at the far end of the hall. At their feet was a dance floor--- where men and women engaged in the traditional mixed gender dances ---past that was a sea of  Such a vast hall was required to accommodate the 2000 or so memembers in attendance. Any who had a shred of influence or prestige in the Vareeshi world would be in attendance.
Ji-Xing entered ahead of Ty-Shou, his prodigy Qi-An taking up the rear, both in Royal Guard white. All guests in attendance had been limited to two servants. Some of the more haughty guests had tried to force their way into the hall with full coteries of servants. Ty-Shou barely had need for servants, body guard even less so. But Wosa had always insisted that it would be improper for such an important figure to travel without a guard.
