** chapter
The Monastery was more comfortable than Billy had expected. Where he had expected stone beds and fasting diets, he had found plush beds and full dining halls.  Damin and himself had been assigned comfortable accommodations, a large living room and two bedrooms. Like all the rooms of the Monastery, they were carved into spines of the great Beast. A window had even been carved in the living room, a luxury according to Voshri.
The girl had come twice in the week since their arrival. Once on the first day, with her taller brother, to guide them on a tour of the spine. The second time to deliver a book for Damin to study. She had lingered. Longer than she should.
Everyday was the same. Training begun in the morning, and stretched well into the afternoon. When they did break for lunch, the food would always be over-spiced. A mess of spices that nearly made him wish for the bland gruel of the mines. After training, each Herald was given a set of tasks to attend to. Some helped with the farms on the Beast's back, others took a shift operating the elevators, and others maintaining the delicate environment of the Monastery. All duties Billy had been excused from so far. As a newcomer he'd been looked down upon, too incompetent to help with the tasks at hand. He wasn't sure he was more glad to finaly have a day off or angry at how they obviously thought of him as a stupid child.
Cold leached into him as Billy sat on the floor of the training ground. Around him, and on the various padded mats, Heralds of all types fought hand-to-hand. They were all supervised by the brown haired man from the Council, Torin. Torin watched the students closely, before bringing them to attention with a shout and a raised fist. Now was the most entertaining part of the day-- where the 'master' would spar a large group of students at once. The students formed a circle around him, with some of them dragging the padded mats to form a larger area that stretched from wall to wall, where the walls were also padded.
Billy scooched back to lean against the wall. Torin eyed Billy, but gave him no response. He turned to the circle of eight students who surrounded him, 

He was a Light Herald, like Billy, perhaps the most powerful one Billy had ever encountered. Billy could not deny that his abilities were anything short of /impressive/; blasts of white Light exploded from his arms and legs as he slammed back kicks and hits from several students at once, sending them flying and crashing down. These students each could fight several trained men at once-- one threw This was a Light power Billy had never seen before, which while unusual was not unexpected, there were probably few men in the world traveled enough to have witnessed every Light power.
A little voice in his head clamored with excitement-- maybe he could be one of those few men to witness them all here? Maybe he would even /himself/ be able to unlock a new Light power here?
/Nonsense./ Billy crossed his arms. These people may have had impressive skills, but ultimately they were hiding out on this big bird in the sky; it was just combat as a gimmick; they were like the circus he worked for in Apathasaw, but at least the circus /performed/ for actual people.
Still, it was undeniably amazing to watch. Billy tried to get a good look at Torin's face to see what emotion was being channeled for this power. The middle-aged man made a face that was somewhat terrifying with each deflecting hit, like a growling bear. Though he kept it obviously controlled it, it seemed like it there was an undercurrent of anger. Torin could obviously swat the students off like flies with this sole power if he desired, but this mastery was not one-note. He turned around to all the sweaty, out of breathe students pick themselves up from the floor, and looked at them all as a group. Then, he sighed, and the corners of his lips fell-- the ferocious snarling teeth were gone in a second. He was feeling something much more internal.
A bald, muscled student grit his teeth and charged at Torin. His fist and upper arm reflected a steel glare-- an existential threat to most men.
And when the fist was a few feet from Torin's face, the master /dissappeared/.
Billy lurched forward from the wall. Torin was nowhere to be seen.
The student swung wildly with his steel fist, at a speed that would crush the bones of the average man. But the only effect was the /woosh/ of the air, and the scream of the student. 
"YAH!" The student yelped, as his feet flew forward. /SLAM!/ He fell on his back. The other seven quickly closed in, as Torin reappeared, leaping up from the mat like a frog after successfully sweeping the student's legs.
A red-haired student was fast-- faster that even the most well-trained athlete could move. /Jerkwad Subject,/ Billy thought. Billy could already tell this guy didn't like him-- they had been having a stink-eye contest over the past week.
However, he was one of the best students at using his Heraldry. Before, he was the only one who was able to get off successful hits on Torin, though he was still slammed back by Torin's reflective power. He dodged to the side as Torin jumped and kicked two students down, one with each leg. Torin flipped back onto his feet, springing back up in an instant and jump-kicking a third-- but he flew farther that expected as the student vanished, immeadiately appearing on the other side of the matter where Torin had come from. The Subject Herald, being able to see this in slow motion, was able to react first and sent a push kick right for Torin's chest-- his feet tapped and slid, barely providing enough friction to prevent him from falling and losing.
Torin quickly reganined his fighting stance-- he swung to block just as the student who had teleported behind him tried to kick him in the back, and though his back was turned he was able to thrust a kick backwards just as the Subject Herald tried to grapple him. The Subject lowered into a grappling stance, as did the others who circled Torin. If they could all surround him at once, it wouldn't matter how many of them had to wrestle him down, the game would be theirs.
The others glanced at each other, subtly forming a plan of attack. Torin turned, an arm raised in each direction.
The students turned back to Torin. Now they circled, and he stopped in place, his head facing the wall that Billy was leaning against.
Billy thought he saw Torin wink in his direction, before the man's face turned into a totally neutral stare.
"NOW!"
The Subject screamed. Billy sat up-- the room went WHITE with blinding Light, Billy barely covering his eyes.
"FUCK!" Billy wasn't the only one who cursed. Bodies crashed into each other and plopped onto the mat.
Billy knew what emotion Torin had used the second it came out-- Apathy, poetically expressed as an unfiltered blast of Light. But even he wasn't fast enough to cover his eyes in time.
By the time Billy had regained his vision, the students were untangling themselves from the pile of bodies on the floor. Torin had knocked down all those who hadn't ran into each other while they were blinded. He stood with his hands clasped, giving a little cheeky smile, before reaching out to help an olive-skinned student off the ground.
"Another loss," the Subject Herald sighed.
"On the contrary, that was a good reaction Draxuun, and good teamwork, Hafabi," Torin gave a nod to the red-headed Subject Herald and the round-faced Teleportation Herald. 
Billy's grasp of their language using Suspiscion had gotten a lot better; It was the only thing worth putting effort in so far. He had to get a better idea of who these people were, what they were trying to indoctrinate him, and more importantly Damin with. So far, he hadn't caught anything too strange in Torin's classes. The Light Herald seemed the most affable on the Council.
"Yeah, Draxuun, you're being too negative. Of course we would lose fighting master Torin. It's not something to worry about, focus on the lesson," the bald Solid Herald barked. 
"You never know, you might meet a more powerful Light master than me one day," Torin stepped back as the students gathered in a line. They bowed to him in unison, and he returned a much slower, lingering bow.
"The chances of that are so unlikely," a student with a nasally voice resumed speaking as they sat down criss-crossed on the mat. "We have the most powerful Heralds in the world, and you have ... the most Light powers here."
"You don't know who the most powerful Light Herald in the world is. Maybe it's that young man over there," Torin smiled and pointed his chin at Billy.
The student's all looked over their shoulders at Billy. For a second, he felt like one of the circus animals in Apathasaw being ogled by dumb kids after the show was over. He glared back at them.
"I don't think so," the nasally-voiced student replied.
"Maybe not," Torin said. "But the real lesson here was not about power, or even victory. It was about how to engage with someone who has multiple means of escape, who you can't seem to get at."
Billy raised an eyebrow. /Is this really all they do? Get beat up by one guy way more powerful than they are, and then listen to a huge lecture by him afterward, even though they were screwed the whole time?/
"So what were we supposed to do?" The student took the words out of Billy's mouth; for once someone here had some sense.
"Perhaps you already learned part of the lesson here," Torin smiled. "A fight is like an exploration, though it is hard to notice, since it so intense and quick. If I am hard to catch, it is not wise to throw your neck out trying, for you will stumble before I will. I do not beat you until I do, so make me come for you, especially if there are more of you. Keep it slow and watch, and you will find an opening."
Some of the students nodded along and rubbed their chins. Billy had enough, he couldn't just sit here and watch all day.
"You might not be the most powerful, but you're way more powerful than they are. They were fucking screwed, whether they follow your advice or not." Billy got up from the mat, and the whole class turned to him. "Now you're gonna tell them it was their fault they got screwed, when the game was rigged from the start. That's how it always works, whether Heraldry or not."
"Why is this guy even here?" Draxuun whined.
Torin gently lowered his hands to hush the Subject Herald. "It is nice to hear your input Billy. As I said, today's lesson was not about winning. Though--"
"Then what is the fucking point?" Billy shrugged. "I thought you guys trained to fight? If this was real, they would all be dead!"
"Can we just kick this guy out of here so we can do our lesson?" Draxuun glared at Billy. 
"Yeah! I don't like him here!" Hafabi shouted, and a few others nodded in unison. The students, as far as he knew, didn't understand the Trentanian Billy and Torin were speaking, but nevertheless had despised Billy since he arrived.
Torin shook his head to the class. "No. And in fact the most important lesson I could teach you today is to go to your quarters and think about why it's important we have people like Billy here. Class dismissed."
"What?" Draxuun exclaimed. There were a few groans but most just packed up their mats and placed them against the plank walls.
That left Billy standing awkwardly in front of Torin, seated criss-cross. Torin gently lifted his chin to peer up at Billy.
"Why did you do that?" Billy broke the silence.
"A plant needs some guidance to grow, but in most cases, the only real necessary step is to plant the seed."
Billy rolled his eyes. "So what? You already got them all as loyal followers, even if you treat 'em like shit, so its smarter to focus on new recruits to indoctrinate?"
Torin laughed. "One could say so."
Billy pursed his lips. "Finally, some honesty."
"Do you not like it here at all? How did you end up here, then?" Torin asked.
Billy felt his guard let down for a moment. It made him feel ridiculous to think that someone with such a casual demeanor as Torin would have some malicious intent.
"It's not my choice to be here. Those girls Mei-Li and Voshri rescued us when were in a bind," Billy said. "And while I am thankful, that doesn't mean we're staying here long. If you expect repayment, which I understand... I'm sure there's a way I can find you once I've gotten some cash."
Torin laughed again. "We expect no such thing. That is how we are different, and why I think you might appreciate joining us. We believe in using our power to help others, as we did you, not take advantage, as you know most do."
Then again... what if that casual attitude was just his strategy? 
Billy shook his head. "That's what the fucking Citadel says."
"I grew up in the Versalist Realm too," Torin said. "Whenran, to be precise, as I bet you would know by my name."
Billy nodded. "It must be why your Trentanian isn't so damn awful like everyone else here."
Torin laughed again. "Yes. Misun has mostly old, old books to teach the language. Luckily I still had enough experience from my childhood."
Torin's face darkened. "But I know how the Citadel is. And your brother... he's Dark Herald, is he not?"
Billy bit his lip and gave a slight nod.
"Then they had finally discovered him and you were fleeing when Mei-Li found you?"
Billy looked down. Was there any point in lying about this? Either way, he knew that they were vulnerable to the Citadel. He decided against it, and shook his head.
Torin scowled. His eyes searched Billy's face, and Billy held his glare-- he wouldn't let this guy find anything.
"So you must have been on the run a long time," Torin said. "Not in the Citadel-- that would be too dangerous. Billy... that's an... is that an Apathasawian name? Ah. So why did you come back?"
Billy clenched his fists at his sides. He regretted telling him the Truth. Whether Torin was personally innocent or not, it was a liability for him to know too much.
"Ah. I see you are not comfortable with this topic. No matter. I only wish to know to perhaps remind you of a reason why you would want to train here," Torin said.
"I don't need more power to do what I need to do. I got my powers, and my weapon."
"Is 'what you need to do' here, in Wreathward?" jtorin raised an eyebrow.
Billy had already made the mistake of revealing too much once. Not again.
"That's none of your business."
"Mmm. So yes, then," Torin smiled.
Billy grit his teeth. He couldn't blame Torin for being able to piece that together.
"So if it is here, isn't it very likely that history will repeat itself and you will end up on the run, having to defend yourself again?" Torin asked. 
"That is.... actually very likely," Billy sighed. How did he let this guy convince him like this? He might as well just train if they were gonna stay here another weak or too. After all, sitting against the wall had gotten a bit boring and made him rather twitchy.
"So..."
"Yeah fine, I'll train," Billy said. "But actually teach me some stuff instead of just saying bullshit."
"I understand," Torin smiled and finally stood up from his criss-cross position to meet Billy at eye level. "Let's start with the basics. You said you are Light. Good. It's easiest for me to teach what I am. So what are the emotions you channel? Don't worry, I don't judge what emotions people channel. All are necessary. Is it Powerlessness? Insecurity?"
Billy scoffed. "It's not that. Just not everyone wants to join your gay little troop."
Torin smiled. "They are not here now. You have no reason to be defensive. Unless, of course, is your emotion."
Billy rolled his eyes. 
"I use.... Suspiscion, Indignation... and Resentment."
"Three for an untrained man. Decently impressive," Torin said. "And not a bad combination. In fact, very deadly."
"Yeah," Billy said. "I don't see much of a way for me to practice it here, unless you want to be cleaning students' guts off the walls."
"Indeed. Unless I explicitly say so, you cannot use Indignation or Resentment during group training. However, I will end group training early to train you privately, and at any time when both of us are free, if you wish," Torin said.
"What's the point of me showing up for group training, then?" Billy said.
"Well, as you know, it is mandatory for all those in the Monastery," Torin said. "But beside that... Indignation and Resentment are such explosive powers, I bet you need to be able to fight without putting yourself at such risk. And with Light, you never know, you may even develop new powers."
"I'm surprised I even conformed to the first level of your bullshit. I guess staying in the room is more boring than watching you guys wrestle."
In one sense, Torin was right. Now, especially since the Citadel was on alert, and since unlike Aldwin, Billy had no idea what Okin's whearabouts would be, he would need to be more powerful to get through the guaranteed fights that would meet him head on as he tracked Okin down, and afterwards. And he was also right that Billy's greatest advantage was his Heraldry.
Billy smirked. "So, what will you teach me first, master?"


The first thing Torin taught Billy had nothing to do with Heraldry. Torin claimed Billy first needed to learn how to fight without it. Billy knew there was going to be some bullshit like that, and would have quit if there was anything else to do. He knew how to fight-- he had won plenty of drunk scuffles and had even temporarily worked for a security company in Apathasaw. He didn't need some guy twice his age with Light Heraldry twenty times as strong as his to tell him how to win a regular old fistfight-- or so he thought. After hearing a couple dismissive remarks Torin went right into the examples, and as much as Billy hated to admit it, absolutely kicked his ass without using a single ray's worth of Light Heraldry.
The challenge made their private sessions somewhat enjoyable, and much more so after Billy had been finally allowed to use Heraldry. The first week was rather quiet for Billy's tastes-- Torin solely focused on Suspiscion, which mostly built off the purely martial training they had done previously. Billy was taught to sense opponents moves before they came, and Torin had brought in a Subject Herald (thankfully, not the one from Billy's group class), as a challenge for Billy to react to, as even with Suspiscion he would be at a disadvantage when it came to raw reaction speed and a sense of prescience. Billy felt a huge rush of achievement when he finally bested the Herald at the end of a long traning session, both in hand-to-hand and ranged combat.
However, the rest of the day, while still as rote as usual, had gotten more infuriating. The group sessions were still loathsome, as the others obviously had contempt for him, and he was just running around in sweat barely using his actual powers. Damin had brought back books, and from the little phrases he was exchanging with Voshri and a few other teens that came by Billy's Suspiscion that they were indoctrinating him was confirmed. When Billy tried to remind Damin just how strange these people were, and how they couldn't be trusted especially considering there were no other authorities on this weird Beast-- Damin would just bring up how Mei-Li and Voshri saved them, and even repeat their bullshit about developing their Heraldry to keep peace in the world. It got to the point where Billy knew pushing Damin further would just make him more stubborn. Sharp nails cut through his mind-- /what if they separate him from you?/
That made Billy determined to understand what exactly these people were up too. Reason told him there was no way even with the level of strictness they practiced that their head honchos could control everyone here to decieve Billy and Damin, no, if there was something fishy going on it was either something only the higher-ups knew. But even without some sort of conspiracy, the Citadel taking Damin for their upfront purposes was unacceptable. He couldn't push Damin directly, he had to find some crack in what they were doing.
So he pushed down his gut and started talking to anyone who spoke his language. He started with the person who seemed the least irked by his presence in the group sessions-- a charcoal-skinned woman named Wailana. Woman with that cool dark skin were common in Apathasaw, as was the fact that she spoke Trentanian like him, but her ancestors could have originally come from either Apathasaw, Vianarya, or Caspo, and even if he prodded he might never find out as he suspected that they she was born on this Beast.
Wailana seemed like one of those dolled-up secretaries working for some sleazy Apathasawian company Billy would run into when he worked as the assistant dock foreman-- she wasn't overly pushy or baity, but she would say exactly what you wanted to hear, in a voice just a bit more responsive than normal, but not too much that you could call her out for it. And like them, she would answer all his questions, though he was careful not to go too far as they would mostly talk during or right after class.
"How many people are on the Beast?"
"About a thousand two-hundred ten."
"And are all of them Heralds?"
"Just about. Probably about one-tenth aren't."
That made Billy think.
"But that's way more Heralds then must be born. What do you do with.... the other non-Heralds?"
"They are still part of us. They just don't live on the /Tehwa Kanura/."
The /Tehwa Kanura./ That was what they called the Beast. Surely, these pompous jerks must've thought being "part of us" was an honor, and being on the /Tehwa/ was just the best version of that honor. Honestly, 
Today, Torin had set up pairs of rock statues which were scattered among the open grassy field, probably with the assistance of some Solid Heralds. One statue was had a red stone head, that was the enemy, but it was placed quite close to another statue, which Torin told Billy to imagine as Damin. 

"Revenge. Injustice. All from one moment. In one moment I went from seeing the world the Citadel laid out to the rotten world that really is. It's fueled me since that day, fueled my Indignation, fueled my Resentment."
"You are lucky, Billy. Not everyone has something that powerful, that consistent to drive them," Torin said. For a second, Billy's eyelids popped up-- he usually expected the first thing out of these peoples' mouth to be some vague nonsense-- but then he flared his teeth in anger. 
"You think ANYTHING about that is fucking lucky!? Do you know what fucking happened!?"
"Calm, Billy," Torin had that usual sly smirk on. "Our training is over. This is not the time for Indignation."
Billy spun around. The Indignation simmering from realizing all the power and potential the Monastery had, that they kept hidden up here in the clouds had boiled over.  "What? This is all some game to you people?"
Torin shook his head. "On the contrary, we aim to be more serious about Heraldry than anyone else in the world. If you've failed to see that, then maybe we have failed."
Torin, despite sometimes being a bit too spritely for Billy's taste, ultimately seemed quite innocent. But he still had all this power-- and for what? Billy looked to the ground. 
"You might be serious about training. That's all good, but what good does it do if you do no good with it? If you guys just stay on this cloud jerking yourselves off?"
"You do not understand, Billy," Torin had a dark twinkle in his eye, the first spark of real intensity Billy had seen in the man. "I thought someone like you would know firsthand how dangerous the world is. There are powers that cannot be stopped by a reckless village hero."
"So what? You're gonna take down the Citadel?"



- Billy fights with Damin's bullies.
  - Damin's instructor yells at Billy.
    - Torin arrives in time, knowing Billy would be there, to deescalate.
