** chapter
The Monastery was more comfortable than Billy had expected. Where he had expected stone beds and fasting diets, he had found plush beds and full dining halls.  Damin and himself had been assigned comfortable accommodations, a large living room and two bedrooms. Like all the rooms of the Monastery, they were carved into spines of the great Beast. A window had even been carved in the living room, a luxury according to Voshri.
The girl had come twice in the week since their arrival. Once on the first day, with her taller brother, to guide them on a tour of the spine. The second time to deliver a book for Damin to study. She had lingered. Longer than she should.
Everyday was the same. Training begun in the morning, and stretched well into the afternoon. When they did break for lunch, the food would always be over-spiced. A mess of spices that nearly made him wish for the bland gruel of the mines. After training, each Herald was given a set of tasks to attend to. Some helped with the farms on the Beast's back, others took a shift operating the elevators, and others maintaining the delicate environment of the Monastery. All duties Billy had been excused from so far. As a newcomer he'd been looked down upon, too incompetent to help with the tasks at hand. He wasn't sure he was more glad to finaly have a day off or angry at how they obviously thought of him as a stupid child.
Cold leached into him as Billy sat on the floor of the training ground. Around him, and on the various padded mats, Heralds of all types fought hand-to-hand. They were all supervised by the brown haired man from the Council, Torin. Torin watched the students closely, before bringing them to attention with a shout and a raised fist. Now was the most entertaining part of the day-- where the 'master' would spar a large group of students at once. The students formed a circle around him, with some of them dragging the padded mats to form a larger area that stretched from wall to wall, where the walls were also padded.
Billy scooched back to lean against the wall. Torin eyed Billy, but gave him no response. He turned to the circle of eight students who surrounded him, 

He was a Light Herald, like Billy, perhaps the most powerful one Billy had ever encountered. Billy could not deny that his abilities were anything short of /impressive/; blasts of white Light exploded from his arms and legs as he slammed back kicks and hits from several students at once, sending them flying and crashing down. These students each could fight several trained men at once-- one threw This was a Light power Billy had never seen before, which while unusual was not unexpected, there were probably few men in the world traveled enough to have witnessed every Light power.
A little voice in his head clamored with excitement-- maybe he could be one of those few men to witness them all here? Maybe he would even /himself/ be able to unlock a new Light power here?
/Nonsense./ Billy crossed his arms. These people may have had impressive skills, but ultimately they were hiding out on this big bird in the sky; it was just combat as a gimmick; they were like the circus he worked for in Apathasaw, but at least the circus /performed/ for actual people.
Still, it was undeniably amazing to watch. Billy tried to get a good look at Torin's face to see what emotion was being channeled for this power. The middle-aged man made a face that was somewhat terrifying with each deflecting hit, like a growling bear. Though he kept it obviously controlled it, it seemed like it there was an undercurrent of anger. Torin could obviously swat the students off like flies with this sole power if he desired, but this mastery was not one-note. He turned around to all the sweaty, out of breathe students pick themselves up from the floor, and looked at them all as a group. Then, he sighed, and the corners of his lips fell-- the ferocious snarling teeth were gone in a second. He was feeling something much more internal.
A bald, muscled student grit his teeth and charged at Torin. His fist and upper arm reflected a steel glare-- an existential threat to most men.
And when the fist was a few feet from Torin's face, the master /dissappeared/.
Billy lurched forward from the wall. Torin was nowhere to be seen.
The student swung wildly with his steel fist, at a speed that would crush the bones of the average man. But the only effect was the /woosh/ of the air, and the scream of the student. 
"YAH!" The student yelped, as his feet flew forward. /SLAM!/ He fell on his back. The other seven quickly closed in, as Torin reappeared, leaping up from the mat like a frog after successfully sweeping the student's legs.
A red-haired student was fast-- faster that even the most well-trained athlete could move. /Jerkwad Subject,/ Billy thought. Billy could already tell this guy didn't like him-- they had been having a stink-eye contest over the past week.
However, he was one of the best students at using his Heraldry. Before, he was the only one who was able to get off successful hits on Torin, though he was still slammed back by Torin's reflective power. He dodged to the side as Torin jumped and kicked two students down, one with each leg. Torin flipped back onto his feet, springing back up in an instant and jump-kicking a third-- but he flew farther that expected as the student vanished, immeadiately appearing on the other side of the matter where Torin had come from. The Subject Herald, being able to see this in slow motion, was able to react first and sent a push kick right for Torin's chest-- his feet tapped and slid, barely providing enough friction to prevent him from falling and losing.
Torin quickly reganined his fighting stance-- he swung to block just as the student who had teleported behind him tried to kick him in the back, and though his back was turned he was able to thrust a kick backwards just as the Subject Herald tried to grapple him. The Subject lowered into a grappling stance, as did the others who circled Torin. If they could all surround him at once, it wouldn't matter how many of them had to wrestle him down, the game would be theirs.
The others glanced at each other, subtly forming a plan of attack. Torin turned, an arm raised in each direction.
The students turned back to Torin. Now they circled, and he stopped in place, his head facing the wall that Billy was leaning against.
Billy thought he saw Torin wink in his direction, before the man's face turned into a totally neutral stare.
"NOW!"
The Subject screamed. Billy sat up-- the room went WHITE with blinding Light, Billy barely covering his eyes.
"FUCK!" Billy wasn't the only one who cursed. Bodies crashed into each other and plopped onto the mat.
By the time Billy had regained his vision, the students were untangling themselves from the pile of bodies on the floor. Torin had knocked down all those who hadn't ran into each other while they were blinded. He stood with his hands clasped, giving a little cheeky smile, before reaching out to help an olive-skinned student off the ground.
"Another loss," the Subject Herald sighed.
"On the contrary, that was a good reaction Draxuun, and good teamwork, Hafabi," Torin gave a nod to the red-headed Subject Herald and the round-faced Teleportation Herald. 
Billy's grasp of their language using Suspiscion had gotten a lot better; It was the only thing worth putting effort in so far. He had to get a better idea of who these people were, what they were trying to indoctrinate him, and more importantly Damin with. So far, he hadn't caught anything too strange in Torin's classes. The Light Herald seemed the most affable on the Council.
"Yeah, Draxuun, you're being too negative. Of course we would lose fighting master Torin. It's not something to worry about, focus on the lesson," the bald Solid Herald barked. 
"You never know, you might meet a more powerful Light master than me one day," Torin stepped back as the students gathered in a line. They bowed to him in unison, and he returned a much slower, lingering bow.
"The chances of that are so unlikely," a student with a nasally voice resumed speaking as they sat down criss-crossed on the mat. "We have the most powerful Heralds in the world, and you have ... the most Light powers here."
"You don't know who the most powerful Light Herald in the world is. Maybe it's that young man over there," Torin smiled and pointed his chin at Billy.
The student's all looked over their shoulders at Billy. For a second, he felt like one of the circus animals in Apathasaw being ogled by dumb kids after the show was over. He glared back at them.
"I don't think so," the nasally-voiced student replied.
"Maybe not," Torin said. "But the real lesson here was not about power, or even victory. It was about how to engage with someone who has multiple means of escape, who you can't seem to get at."
Billy raised an eyebrow. /Is this really all they do? Get beat up by one guy way more powerful than they are, and then listen to a huge lecture by him afterward, even though they were screwed the whole time?/
"So what were we supposed to do?" The student took the words out of Billy's mouth; for once someone here had some sense.
"Perhaps you already learned part of the lesson here," Torin smiled. "A fight is like an exploration, though it is hard to notice, since it so intense and quick. If I am hard to catch, it is not wise to throw your neck out trying, for you will stumble before I will. I do not beat you until I do, so make me come for you, especially if there are more of you. Keep it slow and watch, and you will find an opening."
Some of the students nodded along and rubbed their chins. Billy had enough, he couldn't just sit here and watch all day.
"You might not be the most powerful, but you're way more powerful than they are. They were fucking screwed, whether they follow your advice or not." Billy got up from the mat, and the whole class turned to him. "Now you're gonna tell them it was their fault they got screwed, when the game was rigged from the start. That's how it always works, whether Heraldry or not."
"Why is this guy even here?" Draxuun whined.
Torin gently lowered his hands to hush the Subject Herald. "It is nice to hear your input Billy. As I said, today's lesson was not about winning. Though--"
"Then what is the fucking point?" Billy shrugged. "I thought you guys trained to fight? If this was real, they would all be dead!"
"Can we just kick this guy out of here so we can do our lesson?" Draxuun glared at Billy. 
"Yeah! I don't like him here!" Hafabi shouted, and a few others nodded in unison. The students, as far as he knew, didn't understand the Trentanian Billy and Torin were speaking, but nevertheless had despised Billy since he arrived.
Torin shook his head to the class. "No. And in fact the most important lesson I could teach you today is to go to your quarters and think about why it's important we have people like Billy here. Class dismissed."
"What?" Draxuun exclaimed. There were a few groans but most just packed up their mats and placed them against the plank walls.
That left Billy standing awkwardly in front of Torin, seated criss-cross. Torin gently lifted his chin to peer up at Billy.
"Why did you do that?" Billy broke the silence.
"A plant needs some guidance to grow, but in most cases, the only real necessary step is to plant the seed."
Billy rolled his eyes. "So what? You already got them all as loyal followers, even if you treat 'em like shit, so its smarter to focus on new recruits to indoctrinate?"
Torin laughed. "One could say so."
Billy pursed his lips. "Finally, some honesty."
"Do you not like it here at all? How did you end up here, then?" Torin asked.
Billy felt his guard let down for a moment. It made him feel ridiculous to think that someone with such a casual demeanor as Torin would have some malicious intent.
"It's not my choice to be here. Those girls Mei-Li and Voshri rescued us when were in a bind," Billy said. "And while I am thankful, that doesn't mean we're staying here long. If you expect repayment, which I understand... I'm sure there's a way I can find you once I've gotten some cash."
Torin laughed again. "We expect no such thing. That is how we are different, and why I think you might appreciate joining us. We believe in using our power to help others, as we did you, not take advantage, as you know most do."
Then again... what if that casual attitude was just his strategy? 
Billy shook his head. "That's what the fucking Citadel says."
"I grew up in the Versalist Realm too," Torin said. "Whenran, to be precise, as I bet you would know by my name."
Billy nodded. "It must be why your Trentanian isn't so damn awful like everyone else here."
Torin laughed again. "Yes. Misun has mostly old, old books to teach the language. Luckily I still had enough experience from my childhood."
Torin's face darkened. "But I know how the Citadel is. And your brother... he's Dark Herald, is he not?"
Billy bit his lip and gave a slight nod.
"Then they had finally discovered him and you were fleeing when Mei-Li found you?"
Billy looked down. Was there any point in lying about this? Either way, he knew that they were vulnerable to the Citadel. He decided against it, and shook his head.
Torin scowled. His eyes searched Billy's face, and Billy held his glare-- he wouldn't let this guy find anything.
"So you must have been on the run a long time," Torin said. "Not in the Citadel-- that would be too dangerous. Billy... that's an... is that an Apathasawian name? Ah. So why did you come back?"
Billy clenched his fists at his sides. He regretted telling him the Truth. Whether Torin was personally innocent or not, it was a liability for him to know too much.
"Ah. I see you are not comfortable with this topic. No matter. I only wish to know to perhaps remind you of a reason why you would want to train here," Torin said.
"I don't need more power to do what I need to do. I got my powers, and my weapon."
"Is 'what you need to do' here, in Wreathward?" jtorin raised an eyebrow.
Billy had already made the mistake of revealing too much once. Not again.
"That's none of your business."
"Mmm. So yes, then," Torin smiled.
Billy grit his teeth. He couldn't blame Torin for being able to piece that together.
"So if it is here, isn't it very likely that history will repeat itself and you will end up on the run, having to defend yourself again?" Torin asked. 
"That is.... actually very likely," Billy said. 


"Let's start with the basics. You said you are Light. Good. It's easiest for me to teach what I am. So what are the emotions you channel? Don't worry, I don't judge what emotions people channel. All are necessary. Is it Powerlessness? Insecurity?"
Billy scoffed. "It's not that. Just not everyone wants to join your gay little troop."
Torin smiled. "They are not here now. You have no reason to be defensive. Unless, of course, is your emotion."
Billy rolled his eyes. He might as well do this if they were gonna stay here another weak or too. After all, sitting against the wall had gotten a bit boring and made him rather twitchy.
"I use.... Suspiscion, Indignation... and Resentment."
"Three for an untrained man. Decently impressive," Torin said. "And not a bad combination. In fact, very deadly."
"Yeah," Billy said. "I don't see much of a way for me to practice it here, unless you want to be cleaning students' guts off the walls."



