* Guidelines for this doc format
- For **, this means that this key beat occurs, and then
  everything grouped after it is all the beats/scenes that occur after it until the next beat begins. e.g: ** Midpoint will start with the first crucial beat (the midpoint itself), which are additionally marked with ! as a prefix, and then scenes which follow after. This is why Break into X is in Act X.

* ACT I (APATHASAW, METHENO, CITADEL)
** Opening Image 
*** ! Billy doesn't have enough money for Wreathward, but he can make enough in a duel >
- [x] Billy complains he doesn't have enough money for the duel and is alcoholic.
- [x] Damin steals gun for Billy for the duel
- [x] Billy joins the duel
*** - Billy wins the duel
- [ ] Billy faces off. It's close, but the revolver is potent.
*** - Billy and Damin go to Metheno
- [ ] Billy negotiates with Benjamin for the trip.
- [ ] Billy on the boat. It's cheap and uncomfortable. The crew members take advantage of Damin and steal his food, and we see Damin's nihilism and roll-overness here, as well as Billy's anger and determination for justice.
** Goal Stated
*** ! Billy visits his father's grave [goal: taking revenge]
- [ ] Billy and Damin arrive in Metheno and reflect on its changes. Billy deals with negative emotions regarding the place, Damin doesn't remember much.
- [ ] Billy and Damin visit the grave. Billy reflects in private. Brief flashbacks to the day, we learn why they left. Billy swears revenge.
*** - Billy gets info of Aldwin and Okin's whereabouts [+]
- [ ] Billy goes to Aldwin's old house, but someone else lives there.
- [ ] Billy goes to the chapel, and learns from the fill-in Ather that Aldwin is now an Impalias at The Citadel, and Okin is the Ather for this town, but is fighting on the Farsunni front.
*** - Billy travels to the Citadel with Damin [+]
- [ ] Billy and Damin enter the Citadel
- [ ] Billy fakes being a wide-eyed Versalist who wants Aldwin to hear his testimony to get his first Point.
- [ ] Billy and Damin find Aldwin in a Cathedral.
** Inciting Incident
*** ! Billy shoots Aldwin, but sees Okin [+]
- [ ] Billy shoots Aldwin, but sees Okin
*** - Billy is hunted by Rothars and he escapes the Citadel [-]
- [ ] Billy and Damin chase sequence from Rothars.
- [ ] Billy and Damin escape the Citadel.
*** - Billy goes back in to try to kill Okin
- [ ] Damin doesn't want to do it. Damin says that Okin wasn't responsible. Billy convinces Damin as Damin fears being alone. 
- [ ] Billy gets him and Damin disguised as an armored Rothar and a squire.
- [ ] Damin uses his summons to find Okin in the middle of the night.
- [ ] Billy and Damin sneak into Okin's quarters, but Gendro catches them.
- [ ] Another fight commences between Gendro, the awoken Rothars, and Billy and Damin. Billy and Damin lose and are cornered.
* ACT II (THE MONASTERY)
** Break into Two
*** ! Allia and Voshri eliminate the Rothars and rescue Billy and Damin [+]
- [ ] Allia and Voshri fight off the Rothars, and then teleport the four of them out of the Citadel.
*** - Allia and Voshri take Billy to the Monastery [-]
- [ ] Allia and Voshri take Billy and Damin to their airship.
- [ ] Allia and Voshri explain how they found Billy and Damin; they spotted Damin's Summon and knew that someone illegal was doing something, and then tracked Billy and Damin. Billy will not tell Allia what they were doing at the Citadel.
- [ ] 
*** - Avador discovers Damin's nightmares {b-plot goal: find the Dark Weapon}
*** - Billy tries to escape with Damin [+]
** First Pinch Point
*** ! Billy and Damin are caught [-] {+}
- Billy and Damin fight, but are outnumbered and surrender to the  Monastery.
- Upon this development and the unsuccessful hunt for Intillia's killer, the Monastery Council makes leaving the Tneranatos prohibited, infuriating the minority factions, especially the Revenants, within the Monastery.
*** - Billy meets the Revenants, Damin meets the Sentinels [+] {+}
- Billy is introduced to the Revenants by meeting Calkesh, a radical Mind Herald in the Monastery who is very anti-Citadel and seeks Intillia's killer [+]
*** - Billy tricks Revenants into planning a secret mission to track and kill Okin [+]
- Billy sneakily gets information from Allia and Voshri about Intillia.
- Billy crafts some lies to make Calkesh believe that Okin was Intillia's
  murderer.
*** - Damin discovers a map to the Forge {+}
- Damin's visions lead him to Intillia's secret records where he finds
  a book about the locations of the weapons, which gives him new
  visions
* ACT III (THE SKIES, THE LEVIATHI STRAIT)
** Midpoint
*** ! Billy's rebel scheme is found out and he faces execution. [-] {-}
*** - The Party escapes the Monastery. [+] {+}
*** - Calkesh has found Okin, the Party squabbles [+] {+}
- Billy tries to convince the party to go drop him and Damin back at the Citadel, but fails. However, Allia thinks Billy does owe them a ticket back in the Citadel, and thinks Intillia's killer would suffice, while Voshri and Damin think its fruitless and rather follow Damin's vision {+} [-]
- Billy convinces Damin to connect him with Calkesh, who has found
  Okin [+]
- Calkesh wants to kill Okin himself, but Billy wants the kill for
      himself. [-] 
- Damin decides to tell Voshri and Allia what's going on. Allia tries to subdue Billy, and the two fight, disrupting the ship. [-] {+}
** Second Pinch Point
*** ! Nexon's Pirates capture the Party [-] {-}
- The Party fighting makes the Ship nearly fall out of the sky and
  come within Nexon's view. Nexon shoots it down, and they are
  captured. 
*** - Billy befriends Nexon, The Party plan their escape [+] {+}
    - Nexon befriends Billy, and returns him the Dark Crystal [+]
    - Allia and the other three plan to escape [-] {+}
    - Billy convinces Nexon to help him go kill Okin if Billy comes
      with him to hunt the Leviathi [+]
    - Allia and the other three get Voshri's Space Crystal [-] {+}
*** - Billy ruins their escape plan [+] {-}
    - Damin wants to go with Allia, and Billy and Damin 
      fight. Billy thinks Damin will go if he doesn't do something
      drastic, and will die in Krinosas.
    - In fear of losing his brother to Krinosas, Billy tells Nexon
      about their escape plan. Nexon stops their plan and locks up
      Allia and Voshri.
    - Damin is more distant then ever from Billy, even though Damin is
      not punished by Nexon.
      
*** - The Leviathi Hunt [-] {+}
** All is Lost
*** ! Allia destroys the ship's engine, the Leviathi destroys the fleet, Billy loses contact with Calkesh [-] {-}
- In a desperate, angry attempt to escape, Allia overloads her powers to explode the ship's engine. The explosion sinks Nexon's lead crusier, and shocks the Leviathi, which attacks the fleet in a
  frenzy. [-] {-}
- Billy is knocked unconscious. He loses his Dark Crystal, and with it, his connection to Calkesh.
*** - Billy and Damin crash on Krinosas [-] {+}
- Billy wakes up, surprised he is alive.
-
*** - Billy and Damin try to find the Forge [+] {+}
* ACT IV (KRINOSAS, THE FORGE)
** Break into Four
*** ! Billy and Damin find the Forge [+] {+}
*** - Billy bonds with the Dark Children and Architor 
*** - Billy and Damin go to find Allia {+}
*** % Architor-Revictus is born 
** Final Confrontation
*** ! Billy and Damin fight Allia and Voshri for the weapon [+] {+}
*** ! Architor-Revictus challenges Billy for the weapon [concluded] {concluded}
** Closing Image
*** ! The Party escapes with Dark Children from Krinosas

