add Okin visit to synodontis

Concerns:
-Plot is too boring/not compelling, Okin is not a good character for this plot
-Considering:
  - Add more beats between Okin and the Mouth of the Gods (main antagonist)
    - Backuh and/or Revictus use the mind-wiping powers on Okin after Okin discovers a big secret (if Backuh, that Okin is a Dark Herald)
      -


* ACT I
** Opening Image
*** ! Okin will not lie, even to help his men on the Farsunni front.
- [ ] Previa sees a chance for a glorious raid of the enemy. Okin thinks it's a good idea but wants to wait on the Krusadars' orders. Previa decides to do it anyway.
- [ ] Okin follows Previa and gets a backup squad because he is worried for Previa's safety.
- [ ] Previa's squad is threatened but Okin is there to save the day.
- [ ] They are tried, and Okin tells the truth despite Previa's insistence otherwise which gets them sent back to the Citadel.
** Inciting Incident
*** ! Billy puts Aldwin into a coma, and Okin is his impromptu replacement
- [ ] Okin is traumatized, the doctors are unsure whether they are alive. Previa tries to hide his feelings but later breaks down.
- [ ] Okin is named as Aldwin's replacement.
- [ ] Okin leads the hunt for Billy.
- [ ] Okin hears the Mouth of the Gods.
- [ ] Okin meets the other Impaliases.
* ACT II
** Break Into 2
*** ! The Synodontis debate begins
- [ ] Okin is introduced to the Synodontis debate and is astonished.
- [ ] Okin feels like he can't make the decision without first meeting Synodontis. He requests a meeting which is quickly approved.
- [ ] Okin and a few other Impaliases visit Synodontis. Okin is wowed by Synodontis' power but also is suspicious of him.
- [ ] Okin keeps track of the vote, which will need a majority (6/9) to pass or fail. Right now he knows that 4 are strongly for, 1 is against, and the rest are up in the air.
- [ ] Another Impalias tries to subtly buy off Okin to pass the vote, Okin is astonished by this. He brings it to the Mouth of the Gods, who gives Okin an empty promise that he will do something.
- [ ] Okin brings up the other Impaliases' corruption before the Council and the Council pretends to be flabbergasted.
- [ ] Another anti-Synodontis Impalias visits Okin and tells him that the Mouth will not advance the vote until he is sure that everyone will vote in favor of Synodontis. Okin doesn't exactly believe him. The Anti-Synodontis Impalias introduces Okin to Backuh, an eccentric who believes that the current Mouth of the Gods is an unholy usurper who murdered the former Mouth.
- [ ] Okin is attacked in the street. Luckily Gendro is there to defend him.
* ACT III
** Midpoint


** Second Pinch Point
*** !  Okin's allies are found and murdered. Okin's life is barely saved by his own accidental activation of Illusion Heraldry.
- [ ] The meeting is attacked.
*** - Okin
- [ ] Okin is in denial about himself being an Illusion Herald.
- [ ] Okin is insecure and still in denial about whether he should tell the truth about being an Illusion Herald and gets guidance from Gendro at a Dark Herald execution without getting into details. Gendro stands by his Versalist values.
  - This time, Okin looks away.
- [ ] Having given up, Okin attends the council, and agrees to vote for Synodontis, which moves the vote to the "next stage".
- [ ] Okin finally can't take it and tests his Illusion Heraldry.
- [ ] Okin is about to kill himself, but Backuh presents Okin with someone who has testimonies of Synodontis' non-godliness (who knows him from Marthia.) Okin is convinced by Backuh's "greater truth" narrative.
- [ ] Okin confronts the most cowardly Impalias directly about why all the other Impaliases are so gung-ho about Synodontis, and also about who attacked the meet. The cowardly Impalias reveals that this was all planned out ahead of time.
- [ ] Okin agrees to go with Backuh on a secret portal trip to meet Synodontis in person again.
- [ ] Aldwin has awoken, but Okin thinks he is the only one who is aware.
** Second Act Turn
- [ ] Knowing that Aldwin will vote for Synodontis, Okin decides to kidnap Aldwin and maintain his role as an Impalias.
** Post 2A
- [ ] Okin kidnaps Aldwin with Backuh's help.
- [ ] Okin tries to convince Aldwin not to vote for Synodontis, but Aldwin vaguely alludes to Revictus' control. Okin takes this as a sign that Aldwin is also corrupt.
- [ ] Previa tries to visit his father, but finds he is missing. He goes to the Council with the medical professionals to report Aldwin's missing status as the top priority.
- [ ]
** Break Into 3

** Final Confrontation
- Revictus knows Aldwin's been murdered and in desperation meets Okin. Okin meets Revictus, then you hear information in Billy's plot from Architor, then cut back to Okin from high-tension information.
- Deionis frames
- Okin lies in court about Previa's testimony that Okin is a Dark Herald, and that it was Okin that killed Aldwin. Previa is sentenced to death. (B plot close).
** Denouement
- Previa is broken out of prison by DEionis
- Okin acts as a McCarthy-esque demagogue, making false promises to the people to gain power, saying that he has been ordained by Aredal/Olitheon to fight against the modern Citadel.
