add Okin visit to synodontis
* ACT I
** Opening Image
- Okin will not lie, even to help his men on the Farsunni front.
** Inciting Incident
- Billy puts Aldwin into a coma, and Okin is his impromptu replacement.
* ACT II
** Break Into 2
- The Synodontis debate begins.
** Pre-Mid

- Okin is attacked in the street. Luckily Gendro is there to defend him.
- Okin and a few other Impaliases visit Synodontis under orders from the Mouth.
  - [] Okin doesn't want to believe that Synodontis is 
- Okin tells the truth about
* ACT III
** Midpoint
- The other anti-Synodontis Impalias is murdered by Revictus, and Okin's life is barely saved by his own accidental activation of Illusion Heraldry.
** Post-Mid
- As an Illusion Herald, Okin panics, but Backuh convinces him that perhaps the Gods had just saved him for a more important mission.
- Okin is insecure about whether he should tell the truth about being an Illusion Herald and gets guidance from Gendro at a Dark Herald execution without getting into details. Gendro stands by his Versalist values.
- Okin speaks with an unconcious Aldwin for guidance.
- Okin attends the council, and agrees to vote for Synodontis, which moves the vote to the "next stage".
- Okin is about to kill himself, but Backuh presents Okin with someone who has testimonies of Synodontis' non-godliness (who knows him from Marthia.) Okin is convinced by Backuh's "greater truth" narrative.
- Okin confronts the most cowardly Impalias directly about why all the other Impaliases are so gung-ho about Synodontis, and also about who attacked the meet.
- Aldwin has awoken, but Okin thinks he is the only one who is aware.
** Second Act Turn
- Okin learns that Aldwin plans to vote for Synodontis. Okin decides to kidnap Aldwin and maintain his role as an Impalias.
** Post 2A
- Okin kidnaps Aldwin with Backuh's help. Okin tries to convince Aldwin not to vote for Synodontis, but Aldwin vaguely alludes to Revictus' control. Okin takes this as a sign that Aldwin is also corrupt.
- Previa tries to visit his father, but finds he is missing. He goes to the Council with the medical professionals to report Aldwin's missing status as the top priority.
** Break Into 3

** Final Confrontation
- Revictus knows Aldwin's been murdered and in desperation meets Okin. Okin meets Revictus, then you hear information in Billy's plot from Architor, then cut back to Okin from high-tension information.
-
- Okin lies in court about Previa's testimony that Okin is a Dark Herald, and that it was Okin that killed Aldwin, and Previa is sentenced to death. (B plot close)
** Denouement
- Previa is broken out of prison by DEionis
- Okin acts as a McCarthy-esque demagogue, making false promises to the people to gain power, saying that he has been ordained by Aredal/Olitheon to fight against the modern Citadel.
