* Guidelines for this doc format
- For **, this means that this key beat occurs, and then
  everything grouped after it is all the beats/scenes that occur
  after it until the next beat begins. e.g: ** Midpoint will start
  with the first crucial beat (the midpoint itself), which are
  additionally marked with ! as a prefix, and then scenes which
  follow after. This is why Break into X is in Act X. The ! points
  of the last beat of the act are duplicated as the first beat of
  the next act to show continuity.

Ty-shou's main power comes from his genuine love for humanity. Wosa tries to force it but it doesn't work because it is not genuine love. Aredal's version of the power was to amplify the aspects of a person, but Ty-Shou has a twisted version based on his own ego and self image that makes everyone a reflection of himself and super soldiers.

* ACT I :centralMarthia:
** Opening Image
*** All the leaders are in Cong Lang for the start of king making, Dragon Lord crosses the mountains
- [] There is a large formal gathering of high level officals
- [] Ty-Shou does not see the point in attending, Wosa has to remind him of the importance
- [] Ty-Shou sees Kaleesh and her brother and Anut
- [] Laatsi preaches about how this is a new king making season, where not all disputes will be of blood
- [] Messenger arrives delivering news of the Dragon Lord crossing into Hai Xin
- [] Coalition head commits to protecting all central Marthians 
*** Ty-Shou meets with Malesh
- [] Ty-Shou watches the Cong Lang army, and some contigents of other nations leave through portals to Hai Xin
- [] Malesh meets him there, Wosa introduces the two
- [] Wosa does much of the talking with Malesh, Ty-Shou is more interested in the army than economics
- [] Malesh calls Ty-Shou out direcetly
*** The brother hosts a formal banquet to welcome the start of king making
- [] Ty-Shou observes the differing fashion of the multiple nations
- [] Meets Kitsai, she asks if he is a god like his people say he is
- [] Laatsi introduces himself, he asks how Ty-Shou intends to govern Bei-san
** Inciting Incident
*** ! The banquet is interrupted by the King's death
- [] Anut arrives late and rushes to the brother, and everyone eventually comes to the conclusion the king is dead
- [] The two begin to leave the room, when the brother collapses and so do other members of his train and those around the hall
- [] Wosa wants to leave, Ty-Shou and Ji-Xing push through to try and help the brother. He is unable to heal the poison (no poison healing/ani-gem)
- [] Ji-Xing has to drag Ty-Shou out
*** The Bei-sanian party flees to their compound
- [] Wosa and Ty-Shou theorize about assination as they try to make their way out of the palace
- [] Stand offs against other parties, but no direct confrontation
- [] They manage to make their way out and as they do, they see portals opening up to return the army
- [] The army is small and looks badly beaten. The coalation head isn't there
- [] Wosa realizes he is dead, and they make it into carriages and back towards the compound
*** The city goes into lockdown
- [] The Bei-sanian compound is guarded by guards with guns
- [] Ji-Xing informs the party that the city is locked down
- [] Wosa, insits on leaving anyways, Ty-Shou thinks it is unbefitting of a hero to run from danger
- [] They talk about how far away their nearest armmy is
- [] A carriage arrives with Kitsai, she is injured, Ty-Shou is able to heal her
- [] She informs them of the death of her father, and that Anut has seized support in the city and attempted to kill her
- [] Wosa considers turning her over to Anut for their own safety, and to not interfere in Vareeshi politics as a non-believer
- [] Ty-Shou insits this is the type of thing Wosa has been training him for and agrees to smuggle her out of the city
- [] They agree to leave the next day
*** Chaos in the city breaks out
- [] Civilian population attacks the Hai Xing delegation, blaming them for getting their leader killed during non-kingmaking season
- [] The civilian population begins to riot and attack all the foreign leaders
- [] The Bei-Sanian's have to leave in the night, and sooner than planned
- [] They try carriages and they get stuck in the crowd
- [] Kitsai brings them down into the underground old city, from the era of the Gods
*** The group runs into the Vang Do contigent in the old city
- [] Malesh sees Kitsai and asks what Ty-Shou's plan is once he leaves the city, she realizes he doesn't have one
- [] She bargins for their help escaping the city
- [] The party is ambushed by Anut's men, they nearly kill Ty-Shou who is low on light in the underground city (establish fear of death and obsessive controlling)
- [] They manage to leave the city, but have to walk on foot to the nearest friendly town
* ACT II
** Break Into Two
*** The group crosses a friendly Cong Lang village
- [] See how the triangles work
- [] The villages are hostile at first, but are talked down by Kitsai
- [] The town adds their circles to Kitsai's triangle, she offically becomes a Candidate
- [] Ty-Shou tells Wosa to summon the nobles ahead of their arrival
*** They arrive back in Bei-San
- [] Lai-Ren greets them
- [] Kitsai marvels at the wonder of the city, maintaned since the time of the Gods
- [] Lai-ren informs Ty-Shou many of the nobles have yet to heed his call
- [] Ji-Xing subtly accuses Lai-ren of not summoning them
- [] Lai-ren asserts he has always been loyal, even before Ty-Shou's arrival, and that he only ever ruled in the name of Ty-Shou
- [] Ty-Shou reissues his decree, feeling like he is loosing his grip on control he tells Lai-ren to threaten any nobles not on their
*** Okin Visit
- [] A Versalist delegation arrives admist preperations to march
- [] Leave at the end of the chapter?
*** Arrival at the capital
- [] The group arrives at
<<<<<<< HEAD

** First Pinch Point
* ACT III
** Midpoint

** Second Pinch Point
=======
** Break into Two
 
** First Pinch Point
* ACT III
** Midpoint
** Second Pinch Point2
>>>>>>> 320277a4abb4296a5546b131d16330e991d92f04
** All is Lost
* ACT IV
** Break into Four
** Final Confrontation
** Closing Image

* Characters
** Bei-San
*** Ty-Shou
*** Wo-Sa
*** Lai-Ren
*** Ji-Xing
*** Kazon (Liu)
** Vareeshi
*** Kitsai
*** Anut
*** Laatsi
*** Maalesh



