* Dark
All branches have access to and utilise the dark dimension in order to create their powers. But Mind herald's power do not allow them to enter the dark dimension.
** School of Creation (Summons)
- Store both Summons/Creations, which are made up of different Modules in the Dark Dimension, which also resides in their memory.
- Modules are created by Creation Heralds, and are a modular 'piece' which can then applied to any Summons a Creation Herald stores in their memory.
- All Summons are made up of different Modules, and are 'compilied' in the Dark Herald's memory beforehand. The Summon takes up 30% of the amount of storage all their Modules use.
- Modules are created and Summons are compilied by experimenting with Dark Matter in the Dark Dimension. A Creation Herald will enter the Dark Dimension by entering a meditative state in which they cannot interact with reality.
  
*** Modules
Every conceivable property is a Module. While Modules end up taking defined forms, how they are created is somewhat arcane and the experience can only really be known by a Dark Herald, and many Modules that are functionally the same were created in vastly different ways; there are also more efficient ways, or more modular ways, to create the same Modules.

Examples of Common Modules:
- Floating
- Hard

*** Storage
- A hypothetical storage unit called Doltars (abbreviated D) exists, which describes how much memory capacity a Dark Herald has, but the numerical exacts of this unit are not currently known, and Dark Heralds do not know exactly how many Doltars their Modules and Creations take up, though many develop the intuition over time, and it is correlated with how difficult a Module is to create. If a Creation Herald is over capacity, they will not be able to Summon their most recently created Summon.
- The compilied Summon takes up 30% of the amount of storage that all their Modules uses. A small module will take about 10 Doltars, while a large can take up to 100.
*** Strength levels
**** S-Tier
- Storage of 10000D

In practice:
- Can hold 10-12 different creations in their own memory
- Can maintian up to 5 different creations at once
- Can often create some basic creations from scratch, if well-trained
- Can create beings with human-level intelligence
- Can create creations much larger than any natural animal
- Creations can last up to 5 minutes in direct sunlight, up to an hour in candle light, unlimited in anything darker

**** C-Tier
- Storage of 1000D

- Can hold 6-8 different creations in their own memory
- Can maintain up to 3 different creations at once
- Can create beings with poodle-level intelligence
- Can create creations about the size of a rotweiller
- Creations can last up till 10 seconds in direct sunlight, up to 5 minutes in candlelight, about a day in anything darker

**** F-Tier
- Storage of 100D

- Can hold 2-3 different creations in their own memory
- Can maintain up to 1 creation
- Can create beings with rat-level intelligencekxs
- Can create creations about the size of a large rat
** School of the Consciousness (Mind)
Consciousness Heralds can read, "write", and at the upper end, control the conscious thoughts and memories of any living being. There is an art to Consciousness Heraldry, and many Consciousness Heralds are very powerful at reading while some are not, and the same for 'writing' (putting memories or thoughts into others' brains), and controlling. Humans are the hardest beings to control, and humans' wild conscious can be very draining on the mental state of a weak Consciousness Herald, even causing them to collapse or die if they attempt to control one who does not wished to be controlled for too long. Every being varies in how hard it is to control, read, and write, though the actual information a Consciousness Herald gains from an animal are only vague feelings, as opposed to humans.

Memories that are "written" are experienced as if they were the person's own memory. But discrepncies in experience, like height, skin colour, voice, can indicate a false memory.

Consciousness Heralds require a path of darkness to enact their powers, or a crystal transmission. The less light intercepting the path, the better: though the best is always by touch, where a there is just direct shadow from person to person. Touch can even work in plain sunlight. 
*** In society
They are mostly auxiliary jobs to the upper class. Lots of them are tutors, or do mind wiping as therapy, communicating at fast speeds and storing videos of important events, influencing key players.

** School of Illusion 
Illusion Heralds create "bubbles" in Dark areas. The bubbles can be of any shape, and have an inside and outside which projects a certain image of the Illusion Herald's choice. Illusion Heralds have an easier time displaying things they have seen before, but can craft a good illusion, where their memory will fill in logical gaps without them needing to go over every detail. Illusions are impossible to maintain in high light levels, but strong Heralds can maintain illusions for some time in medium light levels, however, a bright flash of Light will interrupt that area of the illusion.

Illusion Heralds have the easiest time affecting the natural bubble around their own body.

Illusions can be visual, sound, or even taste, touch and smell for very well-trained ones, though Illusions do NOT actually affect physical reality, only perception: for example, an illusory knife cannot actually cut someone, nor an illusory hand actually push someone. However, illusions CAN conceal real objects which can affect physical reality: a skilled Illusion Herald can make it appear that they are not really there, and even deafen sounds outside a bubble of their Creation, and then attack a person.
* Time
Time Heralds accumulate Zeltics by the natural passing of them spending time at the fixed pace in the central timeline. There is a fixed rate at which one accumulates Zeltics, though Subject Heralds can also adjust their perception of Time in a positive direction and accumulate Zeltics more quickly, though it is overall less efficient (Zeltics/sec), then accumulating naturally due to the initial Zeltic cost of changing Time Perception. 
** Subject
Subject heralds can experience time at a different rate than the main timeline.
** Object 
Object heralds have two types. They can make an object experience the next X amount of time in a single moment, condensing the most likely forces that object experiences into one large force. The second freezes and object in place. Actions done to this object will have no visual effects, but will effect the outcome. After a X  amount of time the object will "teleport" to the state it would have been after X amount of time, taking into account all the things that have happened to it during its feezing and most probable outcomes.
* Light
Light is a Heraldry of Energy and Emotions. Because there are so many emotions there is a huge amount of Light powers, and a Light Herald can change their powerset over time. Most Light Heralds can only tap into 1-3 powers. Channeling the emotion and also having Light absorbed by your body is required to use a power.
** general scheme:
fear, sadness: defense myself
anger: offensive energy
love: buff others
selfish: buff myself/debuff others
powerful: buff myself
negative others (hate contempt etc): debuff others
happy: buff myself
** Joy (physical buffs)
*** Excitement
Get bigger and bigger and stronger
*** Euphoric
*** Asthonished
*** Hope
** Anger (energy)
*** Resentment
Suck out life force, leaving someone metaphysically dead.
*** Indignation
He can store more energy in his body when he gets hit, and it shines with light, and he can transfer that energy and it explodes.
*** Irritable
Punching harder
*** Exasperated
Shout
*** Annoyed
*** Combative
Deflect kinetic energy back where it came from, body becomes a kinetic energy return, can block attacks and send the energy back
*** Fury
** Negative-Others
*** Revolsion
*** Contempt
- see and target others weaknesses, create new weakness
*** Hate
*** Pity
- shrink others
*** Othering?
** Sadness
*** Depressed
*** Sorrow
*** Hurt
*** Guilty
*** Lonely
Invisibility
*** Grief
** Powerful
*** Passionate
physical superhuman, speed, agility, strength
*** Confidence
Higher defense
*** Determination
** Selfish
*** Greed
*** Pride
light grows more, shining brighter from body, can incinerate foes
*** Desire
*** Envy
- neutralize others' powers, make people weak?
** Love
*** Lust
*** Compassion
*** Passion
*** Sentimental
*** Romance
*** Empathy
Healing to my state
*** Forgiveness
General healing
*** Mercy
** Fear (defense, debuff others)
*** Terrified

*** Anxious
*** Threatened
*** Overwhelmed
*** Insecure
*** Insignificant
*** Excluded
*** Suspiscion
Spider Sense
*** Powerlessness

** Old
Absorb visible light, and covert it to other forms of energy. The conversations are harder and harder as they move away from EM energy.

STAYING WITHIN ELECTROMAGNETIC IS EASIEST:

1. light to other UV, xrays, or Infrared (gives them all types of vision assist)
2. light to radar, fm, tv, short wave, am (can be used to detect things and send messages with technology. right now pretty useless.)
3. gamma rays (can poison a person. Takes around 1 minute of light absorption to hit poison someone immediately @ contact distance)

EASY CONVERSIONS, in order of ease

1. light to heat (heat wave, self-feeding (caloric))
2. light to sound (sound wave, blow out people's eardrums)
3. light to kinetic (shock wave, blow people back)
4. light to healing (self healing in radiation / other healing in conduction)
5. light to "electricity" (combination of the three above; electric wave)

HARD CONVERSIONS, in order of ease

1. light to potential (hit harder)
2. light to gravitational (gravity well)

----

Energy emitted is in wave form, and follows inverse square law

Light has two modes, *conduction* and *radial* that are toggled between

​	Conduction is more efficient, the energy will try to find a path to the ground. Energy is released from the user at all points touching 	the ground

​	Radial is less efficient. Energy is released at all points along a person. Energy used in the radiation is equally distributed at all 	points

Healing is based on the anti-bodies or how the body is normally.
* Space
** Transportation
In both Manipulation and Force mode:
The more surface area the easier it is to grip
If something they grip is hit by another object, they lose grip
The less mass, the faster you can move it
Separating things that are fused is very difficult. It's mostly based on sight, and "the feel" of the invisible hand.
They see the things the same and find the objects in.
The more parts a thing has the harder it is to move

- Manipulation mode: can move things accurately, at a set, not very fast maximum speed
- Force mode: push quickly at a constant force, in one direction

*** S-Tier
- Move objects in manipulation mode so they're blurry to the average person
- Has 8 additional "Hands", play an instrument well with their "Hands", Can saw
- 600N Force
*** C-Tier
- Move object in manipulation mode at a speed you can catch
- Has 3 additional "Hands", 5 year old's dexterity
- 200N Force
*** F-Tier
- Move object very slowly
- 1 additional hand, dropping their object often, Parkinsons
- 30N Force

** Teleportation
Portals

Purple portal as an outline, circular, bridge between two points, you can see through the portal from one side to the other.

Portal cost is in the transportation of items, it scales linearly with mass, but exponentially with distance

Space realm is non-euclidian 4D-ish space that is made of the same material as the space artifact. When searching through the realm objects occur in order but no linearly, the user gets impressions of the area and uses them to place the portal in the real world. When someone enters a portal they are transported as data-ish entities to the poral exit. 

Blinks
* Elements
(The Heraldry of Atomic Interaction)

All Elemental Heralds can change their body to a different substance. But they must keep the replacement together. If they loose parts of the transmuted body part, then they can not recover the lost mass

** Solids
Can move and reshape solid objects. Very slow

Breaks all bonds when moving a substance, reforms all bonds in the lowest entropy state after manipulation is finished. 

Does not matter how many "discrete" objects there are, moves on an atomic level, but for the user "by feel".

Can transform non-organs and non-bones into solids.

Can crush and move all solids with the same difficulty, but if they are close to their melting point, it becomes more difficult.

## Worse vs Better Heralds
Worse Heralds move solids slower, they cannot transform solids to other solids that are two chemically or properterly distant from each other, also they expend more crystal (which can also be improved with technique) when transforming solids, but transformation will always be perfect.

## S Tier
- Can easily separate "pure solids" from materials, can separate even small amounts of specific solids from homogenous or heterogenous mix.
- They can manuever thier body, no matter the material, as it was their real body, quicker activation time
- Can make solids more "solid"
- Can manipulate shape of solids at the same speed as Earth benders, can crush solids
- Can engrave words on stone
- Can transform any element into any other element, and any isotope.

## C Tier
- Struggles at separating non-common solids, can separate only obviously visible portions; or heterogenous mixes. Can learn how to separate specific homogenous mixes by first mixing them.
- Feels like they are wearing titanium armor, when they transform their skin and bones into titanium. A little less dexterity. Lots of training to be able to do this well.
- Can make small shapes, can make sure bricks are aligned.
- Can only subtract or add thirty or so protons, and cannot if they do not know the substance.

## F Tier
- Cannot separate solids
- Needs a mould to make good shapes. Even then struggles.
- They are weighed down, and have no control over anything they transform themselves into.
- Can transform any substance into something they commonly know and use, and not if they are by more than 10 protons apart.

** Liquid


** Gas

* Physiology
A(Gland which
everyone has) -->B(Herald Hormone)
    B --> C(Hormone activates the Virus to attack)
    C -->|if able| D(Virus attacks the gene, if they succeed you become a Herald)
```

* The virus

The alien probes spread the virus when they scanned all the living things around it

The longer your body fights the virus before forming anti-bodies determine how strong a Herald is

The first Heralds are hit by the virus, they have no anti-bodies passed from food or parents so they fight the virus for longer making them stronger heralds.

Humans first get the virus from animals and it is spread slowly that way

* Materials
** Bonds
Bonds are the core of the gem deposit which appear in deep mineral deposits on Opartha. In their processed form they appear like clear Crystals with a touch of a certain color, and glow brightly in that color when filled with the Zeltics of that type.
*** Colors

** Breakers
Breakers are bonds which have been purposefully processed metallurgically to instead have Heraldry-interrupting rather than Heraldry-conducting/storing properties.
*** Colors
** Shell
Shell is a much weaker version of Breakers and appear as a brownish-grey material with the texture of mixed concrete and soil. They appear around the gem deposit where Bonds are formed, around Bonds. They can only interrupt Heraldry activation through contact, and as a much weaker source of interruption may still be overriden by some powerful Heralds. 
** The Five

