* Purpose of this document
This organizes political units and factions in the contemporary world. So if two factions were previosuly aligned it will be noted but it will not be categorized that way.
* The Monastery
** Environment
** Population
*** Ethnic Groups
*** Heraldry

** Culture
People are encouraged to engage in their ethnic cultures, but not mandatory
*** Apparel
*** Music
*** Trades
Liquid Heralds serve to filter water, and as pumps to get water around
*** Language

*** Taboos and Customs
*** Subcultures
**** Divergent
**** Accepted
**** Unaccepted

** Society
*** Government Type
**** Factions
***** Isolationists
- Think Intillia is a divinely inspired prophet, but not an actual god.
- Believe the world is morally corrupt, and that they will be corrupted by contact with it
- 
***** Sentinel
- See Intillia as just a perosn
***** Revenants
*** Religion and Philosophy
*** Class Structure
*** Technology
*** Economics
*** Military
* Versalist Realms
57 million
(from to East to West, then North to South)
** Military Organization
Total Soldiers: 450k
18k Heralds

Krusadar's typically have an Athar or Rothar attached as their quartermaster. If a Rothar or Athar is unavailable,
*** Non-Herald
**** Squad (6-12) - High Devinar
Squads with Heralds are all a single School, led by a Krusadar lieutenant.
Non-herald squads, are led by a Devinar Sergent
**** Company (6 squads, 4 Krusadar, 70-80 men) - Krusadar
Captain - Krusadar
Quartermaster - Rothar
Messenger - Rothar
Three Lietuenants - Krusadar
**** Battalion - Krusadar
**** Regiment - 
**** Brigade -
**** Army - 
*** Herald
**** Squad (6-12)
**** Company (4 Squads, 50 men)
**** Brigade - (1000 men

** Political structure
Revictus uses religous overtones and administrative tricks to control the populous
** Societal Roles
*** Clergy
All Lords have a compliment of clergy men.
Infantii are taught to read to increase literacy amongst the populous
**** Impalias
Elections every 10 years, ideally one election for each of the states a year
In a close race, the Mouth appoints one of the front runners

**** Rothar/Athar
Mostly do educated/adminstrative roles
*** Gender
Only Males can be Clergy
** Nairfalk
- Citadel
- -ro M names
** Ottencollen
- most recently joined, enemies of Delmia
** Trenta
- Old Trentanian = Middle English
- Trentanian = New English, Lingua Franca
- -un M names
** Monasque
- Monask in Trentanian
** Whenran
- where Okin, (Cynin) Billy etc is from
- -in, -ia M names
- -an F names
** Golzen
- -esh, -ol M names
- former Sürkusch empire
** Wolstamm
- former Sürkusch empire
** Terillié
- former Sürkusch empire
12 million
* Empire of Sürkusch
- Sirkush in Trentanian
- Sarttlmisch's empire
* Farsun
* Bei-San
* Central Marthia/Vareeshi
19.7 million
** Delrai
    United by strong cultural beliefs in their version of Delmian culture
    Good development and general level of education

    4 million

    - Inheritors of the Delmian legacy, the first Eastern Delmian Emperor was from the province of Delrei
- Well developed nation with a relatively highly educated populous
- Structured similarly to Delmia
- Head of state is referred to as Emperor

** Xi-Rin
  1.5 million
    Mediator amongst other major powers
    Good relations with other powers
    Land trade up, all western flowing trade flows through Xi-Rin

    - In the center of the region
- Mediator and negotiators
- Dense metropolitan city state
- Over land trade hub
- Last Eastern Delmian Emperor was from the city
** Hysho
    1.5 million
    
    Came to the defence of Delrai
    Strong military traditions
    Believes in central marthian identity and wants to uphold it, started the Coalition

    - Follow a more chaotic version of Vaaresh that allows infighting within Triangles
- The strongest Herald in the nation is the leader
- Strong military and naval traditions
- Saved Delmia with it's navy during war with 
** Khua
    4 million
    
    Highest population
    Large agricultural power
    Strict hierarchical religious beliefs

    - Most traditional Vaareshi nation
- Founded the coalition
- High population
- Food exporting economy
- Wants to centralize power in the coalition
** Cong Lang
     2.5 million
       
    Natural resource harvesting based economy
    Harvested resources not utilized in nation
    Current Coalition leader as of Enemy of the Gods

    - Low development nation with large natural resource reserves
- One of the larger nations by land mass
** Bei-san
    Small population
    High religous fevour and belief in their small religion

    1 million
** Vang Do
    1 million

    - Technologically advanced nation
- Naval and air trading hub
** Others
    4.2 million
* Delmia
13 million

At the height of the conquest of the Delmian Empire, the Delmian Emperor @ suggested 

After the First Delmian-Wreathward war, Delmia started to let go of its vassals. It first released the vassals of Khua and Vang Do.

The last vassals it released were Delrai and Hysho.

* Confederacy of Apathasaw
Apathasaw is both a continent and regional confederacy. (Technically, the proper political title is *The Confederacy of Apathasawian Designatories*, but almost everyone commonly refers to the political/geographical entity as just Apathasaw.)

The Confederacy is made up of Regional Designatories, which are most commonly a combination of corporate and private-owned lands  which themselves have confederated. There are several Regional Designatories that are part of the Confederacy, and usually support the Confederacy on the global stage. However, Designatories are not *required* to agree on foreign actions, and therefore foreign nations often find themselves negotiating with a couple of Designatories instead of the whole Confederacy, and sometimes in negotiations the “Confederacy” will actually only really be a couple of designatories.

*** Marshton
*** Saggadaway
*** Crantona
*** North Palano
*** South Palano
*** Triton's Isle
*** Goshtar
*** Lesway
*** Kehousee
*** Lanodan
* GaoLeian Gestalt
10 million
* GaoLei
* Republic of Kaihan
4.5 million

# Kaihan Da Sheen (Republic of Kaihan)

# Environment
## Terrain

The Republic of Kaihan is based primarily in lake Sikan (home lake). The name stems from a misunderstanding between the original Trentanian explores and the locals, as those in the republic call it simply Ti Si. A deep water bay, surrounded by lagoons it provides a good bay for ships to moor. 

## Climate
## Fauna
### Heraldic Animals
## Flora
## Legendary Beasts and Landmarks

# Population
## Ethnic Groups

The republic contains citizens of all nations around the word. But there are three primary ethnic groups native to the lake. The *Tillhan* in the north, the *Hansi* in the island lakes and the costal *Disi*. There are little notable exceptions in the appearance between them. They all share hazel toned hair, light brown skin, and dull blue eyes. Though the Tillhan tend to have more grey eyes. 

## Heraldry

# Culture
## Apparel
## Music
## Trades
## Language

The Kaihan speak *Ree Da Sai* more commonly known as simply *Sai*. Sai is a creole of the languages from around lake Kaisi. Originally used to communicate amongst crews from disparate towns, it has now developed into its own language. Many now grow up speaking primarily Ree Da Sai.

Subject --> adjectives --> verbs --> adverbs --> Object

As Hansi and Tillhan share similar grammatical structures Sai has taken mostly from those two. However, words such as Sheen take trace their roots back to Disi. There are other notable borrowed words in Sai, such as the their words for Heralds. Elemental Heralds were catergorized early and are called by their native names. Due to the lower frequency of all other Heraldry it was not until contact with the early Delmian traders that the words for all other schools of Heraldry entered into the Sai vocabulary. 

The writing system used is comprised of half drawn blocks and dots. Each column of a word represents a sound. They are connected by both context and the placements of dots. 

## Taboos and Customs

The most important moment in a person's life is the moment they commit to their Sheehan or crew. These pledges are expected to be for life. Breaking from this pledge to join another Sheehan marks one as an outcast and untrust worthy. Most Sheehan will not take one marked as such, leaving them to work menial labour on land. 

A perspective member must meet the requirements set out by the Sheehan and be accepted by each ship's captain specifically. The requirements differ from group to group but typically consist of a minimum number of voyages or year of services, and a set of feats.  

## Subcultures
### Divergent
### Accepted
### Unaccepted

# Society

All citizens in the republic belong to Sheehan. Most Sheehan operate between 1-3 ships, with only one being a deep water galleon. Some Sheehan operate exclusively within the republic and make a majority of their profits from on shore business and transactions. These logistical Sheehan have mostly been bought out or integrated into larger Sheehan. Those select few Sheehan that operate multiple long range, deep water ships, typically operate upwards of 15 of these larger vessels. 

## Government Type

Any captain of a ship is permitted entry into the Helhan or Assembly of Captains. Each captain gets one vote, though some Sheehan have multiple captains. This largest body is used to elect a smaller body of 60 senators. Each senator serves for a term of 10 years, staggered so six are newly elected per cycle. The senate holds nominal power, though multiple smaller subcommittees are created and dissolved as needed. Above them is the Kailev, a single elected figure who serves as a tie breaker and foreign dignitary. In times of crisis the Kailev can be granted emergency powers. 

The Helhan is held four times per year. The first session is primarily for senatorial elections. Any members of the Helhan may speak up to nominate themselves or any others. A captain may only be nominated every other year. Once all nominations are heard, each captain casts a single vote. The most popular name is passed, and the process repeats till six senate members are confirmed. If subcommittee members are required to be assigned, the Senate presents a list of ranked candidates. A subcommittee nomination is confirmed if less than 30% of present captain object. 

#### Special Subcommittees

**The Council of Tides**: (This is a reference so maybe we need to change it) Members of this council govern the direction and strength of the current produced by the Water Heralds in the bay. They are also in charge of approving and arranging the docking of all ships entering Kaihan.

Council of Foreign Affairs: Council of Piracy

## Religion and Philosophy

The primary religion is that of Levtav. They worship the Leviathi and read the current it creates in the straight as a form of divination.

* Feixiang-Nihdan Commonwealth
12 million
* General Military Strategy
## Usage of Heralds in Army Composition

#### Light

Whole units of Light Heralds. Cavalry mounted, using whips in conduction to electrocute.

Can't use Radiation mode

All metal weapons for conduction

Kamikaze bombers

#### Dark

Used for communication between COs

Squads of summon Heralds to create flanking manoeuvres

#### Space

**Transportation**

​	Increase force and range of arrows

​	Fire small metal and bullets without the need for guns

​	Squads of Transportation Heralds acting as cannons to speed sieges along

**Teleportation**

​	Portals to extend supply lines and create perfect logistics

<200b> Space Crystals at the bottom of war balloons that can drop big bombs from allied camp without needing to carry the bombs, bombs do not even need to be explosive, as well mass amounts of flammable liquid.

## Time

Time can be mixed with regular units, wouldn't provide utility or need to be its own unit. The benefits are mostly in 1v1 combat

## Elements

**Solids**

​	Build forts and camps

​	Dig trenches and other fortifications, or alter the battle field before a battle to create a perfect environment

**Liquid**

​	Reverse the currents in naval combat

​	Drain blood from opponents bleeding out

​	A unit specialised to spread oil during combat

**Gas**

​	Heralds with lanterns in small squads as flame throwers. They can control the flow of battle and are effective against clumped 	enemies

​	Squads of Gas Heralds with sealed poison glass. Throwing them like Grenades



## Tactics

Raiding would be more common to disrupt the better supply lines afforded by Heraldry

Large castles are not common. Forts with more pointed edges like star forts more common
