* Impalias Xohl'a (Pro)
* Impalias Levinor (Revictus) (Pro)
** Age
64
** Appearance
old, skinny, gray hair
** Location/Type
Nairfalk (Aredeal) ad  a
** Background
A traveling Athar up until his elevation. He was born to wealthy parents in Nairfalk, gave up their wealth to join the clergy. Extremely humble, austere. Doesn't own a mansion, sleeps in a room in his cathedral. Spends most of his time doing charity work with the civilians of the Citadel 
** Personality
Levinor is the truest of believers in the text. He is a man of few words.  
** Powers/Abilities/Skills

** Goals

* Impalias Ricartotten (Pro)
** Age
49
** Location
Ottencollen / Intillia
** Background
Krusadar
** Personality
True Krusadar. War hawk who wants to go to war with Delmia and convert people to Veralists
** Powers/Abilities/Skills

** Goals

* Impalias Henard (Revictus) (Anti)
** Age
66
** Appearance
Gray hair, wrinkled square face. Okin's height
** Location
Trenta / Aredal
** Background
traveling Author
** Personality
Truth focused. Intellectual. Objective truth guy. True believer
** Powers/Abilities/Skills

** Goals
Turn Okin to vote for the resolution, while pretending to be a friend
* Impalias Vovaq (Revictus) (Pro)
** Age
58
** AppearanFat
** Location
Monasque / Olitheon
** Background

** Personality
He loves being an impalias. Enjoys the finer things in life
** Powers/Abilities/Skills

** Goals
* Impalias Mikeol (Anti)
** Age
66
** Appearance
Fit handsome man. Bald head, curling (french style) gray mustache
** Location
Golzen / Olitheon
** Background
** Personality
Gorbachev type. Very personal able, but no one has good or bad things to say. Just neutrally liked
** Powers/Abilities/Skills

** Goals
* Impalias Volmunst (Pro)
** Age
50
Vo** Location
Wolstamm / Nexon
** Background
Krusadar. Calvary rider, has a special mount. Doesn't have Humility
** Personality
Boisterous and foul mouthed. 
** Powers/Abilities/Skills

** Goals
* Impalias Mathelin (Anti)
** Age
57
** Appearance 
Shorter man, a bit shorter than okin. 
** Location
Terillia / Olitheon
** Background
A Krusadar, he is now Grand Admiral of the Citadel's Navy. He came up as a ship commander
** Personality
More classic sailor type. Loud mouth, short tempered.
** Powers/Abilities/Skills

** Goals
Strengthen the Citadel's Nav
* Impalias Ovolo (Revictus) (Pro)
** Age
48
** Appearance
Taller man, normal build not overly buff or skinny." ** Location
Farsun (Intillia)
** Background
Grand Marshal of the Western Armies. He is two years into his term, he took over a few months into the new war. Ovolo was Strategy General of the 6th Brigade before his elevation to Impalias. He became known for his reliance on field artillery and innovative combined arms tactics. He was originally an artillery company commander.

He became known in the Versalist world after liberating the city of Tuchal from Surkush hands. He held the city with two brigades for a year before he was reinforced by the rest of the army.
** Personality
Ovolo highly practical. He has a good control on his temper and is an accelerationist. He believe in pushing the Citadel to advance technologically. 
** Powers/Abilities/Skills

** Goals
Retake Farsun
* Impalias Beirst
* Name/Aliases
** Location
** Background

** Personality

** Powers/Abilities/Skills

** Goals
