* BACKUH/DEIONIS :gods:main:antagonists:

* Identification
** Aliases
Deionis is an alias, his real name is actually Backuh.
Deionis has several other Illusion personas which he adopts aliases for. Some of the noticeable ones are:
- Uboad, a loving @ father and blacksmith. Deionis also occassionally projects Ofoid, the son.
- Marin, a Trentanian fisherman who's a rough houser, but knows how to get down with other working class men.
- Wai, a Delmian administrator who is foolish, hard-headed, dogmatic and arrogant. Wai reflects Backuh's idea of Delmians.
** Background
*** Motivation
Deionis is unhappy with his legacy and the way he is viewed in history and by Delmian culture. He doesn't want to believe the Elements idea of what makes a person. He hates his cultural identity but feels like he can not escape it and his entwined with it. 
*** Childhood
Backuh is the son of the Legendary Beast @, who has Summon and Elemental Herald properties who used his unique powers to form Backuh and his three sisters, Isana, @, @, giving them human forms, as he desired to experience humanity. Backuh and his sisters were born
** Appearance	
*** Ethnicity
*** Build
*** Face
** Social Status
*** Class/Allegiances
*** Wealth
*** Clothing
* Character
** Personality
** Goals
** Needs
** Fears
** Ideals
* Abilities
** Heraldry
** Profession
** Stats
** Skills
* Relationships
** Family
** Romantic
** Friendships
** Enemies
