* Document Overview
* Ages of History Overview
** Pre-Gods Age
** Age of the Gods
** 
* Age of the Gods
1: Ascension, Revictus poses as a mortal and introduces the first cannon books of Classi Versalism

70: Revictus seeks out the snake to know if he is doing the right thing with establishing Versalism. Tregale is giong to come back from a Dark Herald child. Pushes the religion to make dark ontologicaly evil

80: Everyone is succesfully converted to Citadel Versalism

90: Kingdom 1 becomes Versalist

130: Kingdom 2 joins

175: Nairfalk joins Versalism, breaks alliance with Kingdom 9 preventing them from joining in wars against Delmia

180: Citadel construction begins

350: Kingdom 5 joins 

370: Tregale Five Guy gets enough of Region 10 to put him as a threat to Revictus

578: Revictus goes to the snake to find a vision about how to counter the Tregale Five Guy's rise. Sees how to kill the guy and things make him sus of Neiman.

580: Tregale Five Guy's empire reaches the height of its power

583: Intillia moves the Monastery to the bird and offically begins it's mission

590: Versalist Empire goes against the other Wreathward coalition

610: Neiman has doubts about the path and gets her own vision from the snake. Sees herself with Tregale and the Tregale Five, but without the Tregale Guy. Neiman kills the snake

650: Zombies overun the Versalist kingdom in the colonies. Intillia fails to save the colony and blames Revictus for not helping more. The Monastery becomes total isolationists

665: They kill the Tregale Guy. Neiman confesses her vision to Revictus. Revictus wants to kill her but isn't able to, lets her go and she leaves with the light weapon.

670: The Wreathward war ends, southern Farsun + Region 8 are conqured by the Citadel. Citadel joins Kingdom 9's war against Delmia

673: Region 6 joins the Versalist Empire

675: Farsun and the Empire break the peace with Wreathward. 9 officaly joins the Versalists

676: 

Revictus tried to fight the Zombies in the colonies, founds a civilzation that dies

Dead Tregale Five guy creates Kingdom A to rival the citadel

Revictus kills one of the Tregale Five

Revictus brings Jaralad into the fold in the fight against Tregale

Revictus eliminates much of the Gaoleian plant

Neiman gives the Light weapon to Farsun

Wreathward defeats the Delmian Empire, leading to the collapse of the Empire

960 AA: Gendro ere Unerio adventures deeper into Vianarya and discovers that the Aeroblaze has receded, as well as discovering massive Crysal deposits in Central Vianarya. The re-colonization of Caspo and Vianarya begins.

967 AA: The GaoLeian Empire (and Pirate regime) is officially disbanded, Apathasawians begin colonizing Caspo and Vianarya

1000 AA: Billy’s father is killed

1010 AA: Billy visits his father’s grave
* Notes about the war of the gods
# 50 BP - Tregales' Exodus
Knowing that Aredal, Nexon, Olitheon and most the other gods will not agree to his plan, Tregale begins a rival faction with Intillia, Deionis, Revictus, and Rentar on his side. Their goals are to kill all the legendary beasts and create a united humanist government, with heralds on top.

# 47 BP - Tregale begins the war
The other gods try to reunite with and reintegrate Tregale's faction. However, at the meeting, things just escalate further. Deionis convinces Tregale to start the war. Tregale agrees, and secretly mind controls Olitheon, giving him three weapons. Nexon becomes suspsicious, and then Tregale uses Olitheon to mass escape him and all his allies.

# 47-46 BP - Tregale's civilization
Tregale and Intillia begin to create new civilizations based on their values, after killing legendary beasts. However, they are only allowed so much time, as Nexon soon finds the region. However, Aredal and Nexon's conscience keep them from killing the citizens. Tregale soon realizes even with Olitheon it is untenable as Nexon will find and defeat Tregale.

# 45-38 BP - Tregale underground
Tregale realizes he can make a secret civilization underground. He tries to create his own heralds, but without Time and Light, he does not have the energy required to create living organic beings, who have conception in time and are created when he wants. Little doees he know, he spawns the Spirit Chasms in around 500 years, and his civilization does survive, though very different to his original plan, in modern times. He then moves on to kidnapping civilizations to create his own underground one, which will be a supreme race which will conquer Opartha's surface, defeat the gods, and establish his civilization.

# 38-34 BP - Skirmish wars
Rentar and Revictus find Tregale's current strategy to be not interacting with the real world enough, a bit delusional. They try to negotiate with the other gods, but the other gods want both Olitheon back as well as the other weapons. Tregale will not accept these terms, and some skirmish wars are fought, with many gods on Aredal's side dying.

# 34-2 BP - Tyrant Tregale
Tregale creates Creations which can alert him of any Space Heralds or Nexon who are within 100 mile radius. With Aredals' numbers also down, Tregale feels safe enough to return to the surface, and he establishes himself as a tyrant in Nairfalk, after defeating their legendary beast. Intillia starts to somewhat disagree with Tregale, and Tregale secretly with Deionis' help begins to manipulate her mind with Dark Heraldry, and eventually gets control of her weapon permanently, which he uses to create massive fortresses and weapons for his new civ.

# 2 BP - Battle of Nairfalk
Nexon and the other gods finally convince Aredal to assault Tregale's civilization. In the massive battle, Tregale and his civilization kill most of the gods, but his civilization is brought to ruin.  Nexon surprisingly kills Olitheon, reclaiming the Space Weapon, but Deionis steals Aredals' weapon, after Aredal is reluctant to join the battle and kill his old friends.

# 2 BP - Aftermath of Battle of Nairfalk and Revictus' betrayal
After the immense brutality, Intillia realizes what Tregale's been doing to her and turns on him. Tregale also mind controls her, wanting to temporarily subdue her until 'she comes around'. Revictus realizes Tregale has become a mad tyrant, and catches him offguard, stealing back Aredal's weapon before escaping. Revictus' reveals Tregale's secrets to Aredal's side.

# 2 BP - The pre-birth of Damian



# 2 BP - Aredal fails to kill Deionis


# 1 BP - Aftermath of Battle of Trenta

# 0 BP - Revictus and Neiman begin 'The Citadel'
